### ISSUE TITLE
Display waypoints in imported GPX files

### ISSUE THREAD

**Issue by TheFive** [bryceco/GoMap#100]
When I am hiking I typically use pocket earth for my routes and add missing objects as favorite POI to the app. It is possibe to send this POI to other Apps, but not to GoMap!!

That would be a nice feature, especially for handling all my notes done this way after my hike with Internet Access (i use pocket earth offline).

Of course supporting sending a gpx track to GoMap!! and upload that to Openstreetmap would be helpfull too.

A higher integration in my ipad environment would be very helpfull, see #98.

**Comment by fntagit** [comment]
This may be another way to express the same idea...
When importing a GPX file, the <trk> elements are imported. It would be useful to also import the <wpt> elements, and to display them as small circles labelled with their <name>, like in ID.
It would even be better than ID if a file containing <wpt> elements, but no <trk> elements, could be imported!

**Comment by bryceco** [comment]
It would be great to have a sample GPX file containing markers to use for prototyping.

**Comment by patricks** [comment]
Here is a GPX file with a single waypoint. Sometimes it also would be nice to import such file.


[Herbert_Zand.zip](https://github.com/bryceco/GoMap/files/10147476/Herbert_Zand.zip)

**Comment by bryceco** [comment]
One snag: Waypoints are commingled with notes/fixmes, so that option needs to be toggled on to see them.

**Comment by tordans** [comment]
@bryceco I saw the new testflight. I cannot find a way to upload a GPX file from the iOS app. There is nothing in the GPX Section of the settings. How does this "waypoint"-feature work?

Context: I hope to repurpose it to upload custom files that will guide me to places that I want to re-survey.

**Comment by bryceco** [comment]
Go to where your GPX is saved (e.g. Files) and share it to Go Map!!
