### ISSUE TITLE
geo: uri seems not to work on ipad

### ISSUE THREAD

**Issue by TheFive** [bryceco/GoMap#102]
i just retract the uri issue from https://github.com/bryceco/GoMap/issues/98.

calling a geo uri from osm.org does not open Gomap!!

with maps.me it worked. i have deinstalled maps.me and removed and reinstalled gomap after deinstallation.

But a click on the uri does not do open GoMap!!

GoMap Version 1.4 iOS 9.3.2 on an ipad.

**Comment by bryceco** [comment]
I agree. It works on my iPhone okay but it's not working on my iPad Pro.

**Comment by bryceco** [comment]
After installing iOS 11 this seems to magically be working again.
