### ISSUE TITLE
show direction of ways

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#104]
at least optionally it would be nice to show the direction of ways (either with particular arrow heads, not confusable with those for oneways, e.g. in a different colour and only at the end) or by optionally displaying node numbers for nodes in ways.
This is relevant for the direction dependent tags (currently only oneway and waterways seem to be implemented), some reference can be found here (I was searching for a better one but didn't find it): 
http://wiki.openstreetmap.org/wiki/Category:Way_Direction_Dependent
Examples: left/right/forward/backward (as part of keys), incline=up/down

**Comment by geowOSM** [comment]
Yes, indication of way direction would be a useful addition. As a workaround you might temporarely add oneway=yes to any line to display the direction. Further examples: natural=cliff, man_made=embankment

**Comment by bryceco** [comment]
It seems that arrows should always display for whatever ways they are useful. Or possibly show them whenever a way is selected?

**Comment by geowOSM** [comment]
Thanks, I would prefer displaying arrows only if a way is selected, like in JOSM.

**Comment by dieterdreist** [comment]
you have to distinguish between the way direction and the direction of certain tags, e.g. oneway or incline.

**Comment by morgant** [comment]
Maybe selecting the head/tail node could show the direction arrow inside the node circle?

**Comment by bryceco** [comment]
Arrows will now be drawn on ways while they are selected.

**Comment by dieterdreist** [comment]
it would be very useful to see the direction (of the way, not of properties
like oneway) because there are many direction dependent tags (everything
with keys like *:"right"= and "left", "up" and "down", and those words in
values, coastlines, some barriers, etc., so there is an infinite list of
properties that require knowing the way direction while editing.

**Comment by zlavergne** [comment]
@bryceco I changed the color of the highlighted way's arrow to red and I also changed it to show them offset if the object is oneway and highlighted so that you can tell if the object you have selected is one-way. Would you want it merged into your repo? Here's the [commit](https://github.com/KaartGroup/GoKaart/commit/6eadbc5535074ee1beae3644c909942dbd0bbb49)
