### ISSUE TITLE
Provide link to tag info from wiki.osm.org

### ISSUE THREAD

**Issue by mikix** [bryceco/GoMap#106]
It would be nice to have a quick way to read the wiki for its usage advice. When dealing with an unfamiliar tag, I have to manually browse to the wiki and search for the key. An integrated link would make that common process a tad quicker.

And if the wiki loaded in an integrated browser view, it would also help avoid the frequent app switches as I review advice and come back to Go Map.

(Thanks for your work on Go Map, btw! It's far and away my favorite OSM editor.)

**Comment by bryceco** [comment]
I'm having a hard time imagining where such a link would be located. The tag fields are already pretty crowded.

**Comment by morgant** [comment]
I mostly use Go Map on an iPad, so don’t have the tag field space limitations that an iPhone would, but that’s a fair point. Thoughts on where/how this might be integrated:

* For the “Common Tags” view, the type could be linked to the wiki
* For the “All Tags” view, the auto-complete suggestions could also have a small button linking to the wiki
* Alternatively, maybe a small ‘info’ (i) button could be fit in next to the fields on both the “Common Tags” & “All Tags” views

Not sure if any of those would be easily implemented or fit into iPhone sized views.

**Comment by bryceco** [comment]
Fixed in 6f50111e4134aa918a7ea994e7864017cfba1a62
