### ISSUE TITLE
Support for custom Imagery in TMS format (flipped y coordinate)

### ISSUE THREAD

**Issue by vramirez122000** [bryceco/GoMap#107]
Go Map!! has supported custom imagery for a while. I create a tile server with high resolution orthophotos for my hometown that are unavailable anywhere else. Unfortunately, I created the tiles using Mapbox Tilemill in TMS format, which uses a flipped "y" coordinate. Both iD and JOSM support TMS format by using the {-y} syntax in the custom URL. I tried the same URL syntax in Go Map!! but it does not work. I really hope you could add this functionality, as Bing imagery is misaligned and blurry in my hometown of San Juan, Puerto Rico. 

[Explanation of how the flipped y coordinate works](https://gist.github.com/tmcw/4954720)

**Comment by vramirez122000** [comment]
Link to my image server: http://imagery-pr-usace-2013.s3-website-us-east-1.amazonaws.com/

**Comment by grischard** [comment]
In the meanwhile, you can set up mapproxy to serve them in a format GoMap supports.

**Comment by bryceco** [comment]
Fixed!
