### ISSUE TITLE
impossible to add tags to node where the way is part of a multipolygon

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#109]
It happened in several occassions and places to me: when I add a node to a way which is also part of a multipolygon and select the node and go to "tags" it will select the multipolygon (it will change the selection at the moment I hit the "tags" button, an instant before the tags view is loaded), so I can't apply the tags to just the node.
At first (before I noticed) this also led to the tags, that were intended for the node, end up at the relation. After I became aware of the bug I undid the unwanted tag additions.

**Comment by bryceco** [comment]
This behavior was by design, the idea being that if you try to tag a node that belongs to a way that has no tags, you probably intended to tag the way instead. For example you can trace a building, and press "Tags" while the final node is still selected, and have the tags apply to the new building instead of the final node in it. 
This heuristic doesn't work when the way is part of a relation though, so I've added an additional check for that scenario.

**Comment by dieterdreist** [comment]
thank you, this is great news, I finally had time to test it and it seems to work. This one was really bugging me, because in Italy housenumbers are referring to entrances, and this bug made it impossible to add housenumbers to building entrances where the buildings were part of a relation. Thank you!

**Comment by dieterdreist** [comment]
It happened again yesterday.
What I did:
select existing node (with tags) that is part of a way which is part of a multipolygon relation
tap on "tags"

what happens:
whole way gets selected

How can I modify the tags of an existing node in this scenario?

**Comment by tordans** [comment]
@dieterdreist I believe there is a misunderstanding about the timeline here: @bryceco closes an issue around the time he fixes it in his code (I guess), but that is not the same a an app release. 

The last release (version 1.4) was published at 30. Okt. 2015 – see https://itunes.apple.com/de/app/go-map/id592990211?mt=8.

We still have to wait for the next release to get all the new stuff that was closed during the last few weeks. There is no public timeline as far as I am aware.

**Comment by Skippern** [comment]
Current beta is on testflight for those with invite, the rest will have to wait for it to be pushed through iTunes Appstore, which is a process taking a few weeks. Don’t know if @bryceco have pushed it yet, or if there are other issues he will test in testflight before pushing

**Comment by tordans** [comment]
@bryceco happy to help with beta testing if you like (t@tobiasjordans.de). I have the Testflight app installed.
