### ISSUE TITLE
Add Preset / Type for Playground

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#111]
The Playground key allows to tag the playground equipment of a playground.
It would be great to have a preset "Playground Equipment" with the list of values based on https://wiki.openstreetmap.org/wiki/Key:playground.

Also some custom Icons for those elements would be great. – Can we help with researching those icons? What format is needed (SVG?)?

**Comment by bryceco** [comment]
Since we use the presets defined by iD then you'll have to lobby the iD maintainers to add those presets. 
All icons are in PNG format.

**Comment by tordans** [comment]
@bryceco but there are presets for playground in https://github.com/openstreetmap/iD, see https://github.com/openstreetmap/iD/search?utf8=%E2%9C%93&q=Playground&type=

Also, there are Icons.

**Comment by bryceco** [comment]
Okay, great. They should be picked up the next time I sync with iD.

**Comment by bryceco** [comment]
Resynced with iD and confirmed that playground presets are present.
