### ISSUE TITLE
GoMap creates a high amount of Changesets with zero map changes

### ISSUE THREAD

**Issue by pa5cal** [bryceco/GoMap#113]
Sometimes GoMap creates a high amount of Changesets with zero map changes.

See for example:
https://www.openstreetmap.org/changeset/56433095
https://www.openstreetmap.org/changeset/55792851
https://www.openstreetmap.org/changeset/55305458
https://www.openstreetmap.org/changeset/54757628
https://www.openstreetmap.org/changeset/54343085
https://www.openstreetmap.org/changeset/53295361

**Comment by pa5cal** [comment]
And again, a GoMap user created almost 2,100 changesets with zero map edits within 25min.

See https://www.openstreetmap.org/changeset/56970879

**Comment by pa5cal** [comment]
Aaand 300 new changesets w/ zero map changes: 
https://www.openstreetmap.org/changeset/57025798

**Comment by bryceco** [comment]
I have a fix in place for this, it just needs to be pushed out to the App Store.

This bug occurs if there is an edit conflict during upload, and the automatic conflict resolution algorithm doesn’t work properly.

**Comment by pa5cal** [comment]
And more changesets with zero map changes: https://www.openstreetmap.org/changeset/57196214

**Comment by tordans** [comment]
@bryceco its great to see you active again. Could you maybe talk to us over at https://github.com/bryceco/GoMap/issues/78 about OpenSourcing the App? This app is the best there is for iOS but it could be sooo much better!

(Sorry, for being off topic here)

**Comment by pa5cal** [comment]
thx

**Comment by pa5cal** [comment]
And still changesets w/ zero map edits:
https://www.openstreetmap.org/changeset/58267350

**Comment by pa5cal** [comment]
And again: https://www.openstreetmap.org/changeset/58420706
