### ISSUE TITLE
For unknown (way)s and (node)s, show a key-value-pair

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#114]
Whenever the app does not know the "display name" of a node/way, it just says `(way)` or `(node)`.
It would be a lot more helpful, if the app could show (one of the) key-value-pairs instead.

# Wireframe
![img_6747](https://user-images.githubusercontent.com/111561/38079672-cc9e3aa8-333f-11e8-957e-62a2ceb7c7af.png)
![img_6745](https://user-images.githubusercontent.com/111561/38079673-ccb58f64-333f-11e8-8d52-ceab75cbaf2e.png)

**The edit view for those two elements looks like this**
![img_6748](https://user-images.githubusercontent.com/111561/38079791-0bfeeea4-3340-11e8-9747-fa8c38afe551.png)
![img_6746](https://user-images.githubusercontent.com/111561/38079792-0c333cc2-3340-11e8-98f9-dbb8d5f46cc0.png)

The question probably is, what key-value-pair to show when there are multiple pairs. But IMO just any (the first pair) is better than nothing(?).

**Comment by bryceco** [comment]
Fixed.
