### ISSUE TITLE
Add ability to add relations under “All Tags” view?

### ISSUE THREAD

**Issue by morgant** [bryceco/GoMap#115]
I understand that relations are complicated and would be a lot of work to implement cleanly, but it might be nice to be able to manually add relations tags on the “All Tags” view.

**Comment by bryceco** [comment]
Turn restrictions will be in the next version. Some kind of multipolygon support will be in the one after that. If there are other specific relation types you're interested in let me know.

**Comment by morgant** [comment]
@bryceco Perfect! Turn restrictions will cover me for a while, but I’m sure I’d use sites on occasion too.

Many thanks for your time & effort in building this tool! Since I’m iOS-only at this point (call me crazy), it’s really the only way I can reasonably contribute to OSM, and it makes doing so quite easy.

**Comment by morgant** [comment]
@Skippern Agreed. Municipalities seem to experiment with them the most.
