### ISSUE TITLE
Introduce `check_date`-Button

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#116]
There is the concept of a `check_date=YYYY-MM-DD`-Tag in OSM
> The tag is intended to document the last date, when an object as a whole or specific tags of the object were checked and verified. 

Source https://wiki.openstreetmap.org/wiki/Key:check_date

It would be awesome to have a check_date-Button in the tags-screen.

**Possible workflow:**

- I walk the street and click on an item, go to the tags
- Review the tags
- Click a link at the end of the tag-list that says "All tags checked and correct"
- Clicking the link add the current date to the check_date-tag, then saves and closes the tags-panel

The use case would be to check a lot of notes right after another, so add-save-and-close is important to make this go really easy and fast.

**Where to place the button:**

On the "Common Tags" panel, the Link/Button could be above the "Customize Presets"-Button.
On the "All Tags" panel, the Link/Button could be above the "Relations" Area, below the "Add New" Element.

**Help**
Ideally, there is a `(i)` next to the link that could show a Dialoge, eg
> This will add the tag `check_date={{currentDateHere}}` to this {{note|way|…}} to indicate that you checked and reviewed the tags.
- Button 1: "Learn more" which opens https://wiki.openstreetmap.org/wiki/Key:check_date)
- Button 2: "OK" which closes the dialogue.

**Comment by dieterdreist** [comment]
sent from a phone

> On 7. Apr 2018, at 10:27, Tobias <notifications@github.com> wrote:
> 
> There is the concept of a check_date=YYYY-MM-DD-Tag in OSM


looking at the stats, there is also a key “survey:date” with much higher usage and the same meaning: https://taginfo.openstreetmap.org/keys/survey:date
or can there be other checks than surveys?

**Comment by tordans** [comment]
@dieterdreist yes, as is stated on the wiki page under "Other tags in use" with the additional information "note that usage is inflated by using it in Antarctica import and is not indicating real usage by humans".

However, this feature request was less about the exact tag-naem and more about the feature idea itself. IMO the question of what tag to use should be answered by the wiki (which recommends check_date ATM IMO) and maybe discussed on the talk page over there.

**Comment by dieterdreist** [comment]
sent from a phone

> On 7. Apr 2018, at 16:33, Tobias <notifications@github.com> wrote:
> 
> "note that usage is inflated by using it in Antarctica import and is not indicating real usage by humans".


have a look at it in taginfo history, there are 2 peaks, but there is also continuous growth over years and still an order of magnitude more than check:date. That wiki claim about the antarctica import distorting the picture completely is not telling the actual story.

I agree supporting a tag/value button for something=current date would be useful

**Comment by tohaklim** [comment]
In an ideal world, you'd be able to get this sort of info from "last modified" fields, since people editing a feature must/should be aware if it changed. 
Still, I feel like this is overcomplicating the workflow and can be easily achieved with the already present "Note" field. IMHO

**Comment by tordans** [comment]
@tohaklim the "last modified" does not answer the same question. This is already addressed on the wiki page unter "Issues" https://wiki.openstreetmap.org/wiki/Key:check_date#Issues.

The main difference with `last_checked` or `survey:date` are:
- I confirm that I checked the data data and that the data has not been changed / is still correct. To confirm correctness I need to update the element. Thats what the tag is for.
- The motified-date does not talk about the quality of the check. It might be a mass-update or just someone moving a node based on satellite images. That is something different than checking stuff locally.

> Still, I feel like this is overcomplicating the workflow 

I don't get that. My idea will not touch anyones workflow … except for people who like to walk and check existing stuff. Image a city that is mapped 80 % and most stuff just needs to be updated / checked.

> and can be easily achieved with the already present "Note" field. IMHO

IMO those feature have no overlap in usecases.

Best, Tobias

**Comment by tordans** [comment]
Just as a side note to this: There is a new Android App "OSMfocus" that addresses a similar issue: Walking down the street and understanding the tags on the map.
Details at https://lists.openstreetmap.org/pipermail/dev/2018-July/030311.html and https://github.com/MichaelVL/osm-focus.

However, the part that is missing – as far as I can tell – is to actually mark something as "checked"/correct or allow an edit.

**Comment by bryceco** [comment]
While I think this is an interesting and occasionally useful idea, I think in general its going to be too confusing for users and applies to too small an audience.
