### ISSUE TITLE
allow merging of 2 nodes (if both are part of a way)

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#120]
Offer to merge nodes when you move a node into the snap radius of another node (also for intermediate nodes, like gates in the middle of service ways that "meet" a fence.)

Ideally, the tags should be combined if at most one node has tags.

If both nodes have tags, a question to merge should be issued (and tell in the callout which tags (up to the first 3) there are on the objects).
yes -> combine tags
no -> do not merge

A "merge" means deleting the node with the higher iD and replace it by the other one in the ways.

**Comment by dieterdreist** [comment]
I could not get them to merge if the node I move is not an end point. 
If you allow merging for any nodes there are plenty of situations where you do not want to merge, but have moved a node into the snapping radius of another node.

**Comment by bryceco** [comment]
The forthcoming version allows arbitrary nodes to merge. If you want them very close without merging then you have to zoom in more (just like with end nodes currently).
