### ISSUE TITLE
Latest version for iPhone 4s

### ISSUE THREAD

**Issue by clavisound** [bryceco/GoMap#121]
Hello, the latest version although requires iOS 9.0 and greater does not install in iPhone-4s.

If it's AppStore restriction maybe I can install an .ipa?

**Comment by bryceco** [comment]
iOS 9 is necessary in order to aid compatibility with iPhone X. Didn’t mean to drop iPhone 4s (32-bit support), and a fix is in progress.

**Comment by bryceco** [comment]
If you send me a message through the in-app feedback I'll add you as a beta tester so you can verify the fix works for you.

**Comment by clavisound** [comment]
You rock! Closing this bug. Thank you for the invitation.
