### ISSUE TITLE
wrong tags added: "payment:payment:cash" and many more

### ISSUE THREAD

**Issue by mueschel** [bryceco/GoMap#122]
Since a few days mappers using GoMap add wrong payment keys. 
For example `payment:payment:cash` instead of `payment:cash`
https://www.openstreetmap.org/way/374689759

The same is the case with `currency:currency:...`
https://www.openstreetmap.org/node/5599271228

These tags are added by various mappers all using GoMap - this seems to be a bug in the software.

Edit:
The same with service tags:
service:bicycle:service:bicycle:pump
service:bicycle:service:bicycle:rental
service:bicycle:service:bicycle:repair
service:bicycle:service:bicycle:retail
service:bicycle:service:bicycle:second_hand

**Comment by bryceco** [comment]
Thanks! I'll push out a fix today.
