### ISSUE TITLE
Cache clearing removes custom tag values

### ISSUE THREAD

**Issue by tohaklim** [bryceco/GoMap#123]
Another point on caching behavior:
Not sure if intended, but clearing the cache appears to clear user-input values for custom tags (I.e. tags with no presets put in manually).
If this is by design, would be great to see some more cache granularity.
(Thanks for the update Bryce, keeping iOS osm editing alive)

**Comment by bryceco** [comment]
Can you provide steps to reproduce?

**Comment by tohaklim** [comment]
Absolutely.
1) User makes an edit by inputting a custom tag not in the presets (e.g. _man_made=street_cabinet_) manually;
2) This input is cached and offered the next time a user goes to input a _man_made=*_ tag;
3) User clears the OSM data cache;

Expected result:
4) Custom tag pairs are kept and survive the cache purge
Actual result:
4) App no longer offers the previously cached _man_made=street_cabinet_ tag pair, until re-input

As initially mentioned, not sure if this is intended and then I am missing the point

**Comment by bryceco** [comment]
The autocomplete suggestions are based on the currently downloaded data, so if you downloaded an object with a man_made=street_cabinet tag then it would suggest it. There isn’t a separate list of tags you’ve entered yourself.

**Comment by dieterdreist** [comment]
maybe it could be a feature to keep a permanent list of individually used tags to merge with the current autocompletion list based on tags in the area. It could be explicitly amendable by the user or automatically (e.g. if you used the same “new” tag at least twice (to reduce the probability that there is simply a typo)).

**Comment by bryceco** [comment]
I see the utility of having a persistent list, but once you start having a persistent list then people want a way to manage it (e.g. remove unwanted items, etc) and the UI gets large and messy. 

I also notice that for the case at hand (man_made=street_cabinet) it's now covered by presets, and IMO the best path forward is to have such things added to https://github.com/openstreetmap/id-tagging-schema (or organically added to TagInfo through repeated use) so we get support automatically.

Won't Fix.
