### ISSUE TITLE
Show `ref` number next to node/way

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#124]
The iD Editor has a neat feature that shows the `ref` content right next to a node.

The ref-attribute is used for public reference-numbers like tree-numbers and such (https://wiki.openstreetmap.org/wiki/Key:ref).

It would be great to have something similar in GoMap. It would make it easier to check existing data.

This could also be an optional feature (settings with opt-in), but I don't see a case where it would be a problem for anyone, so it could just be visible all the time – like iD-Editor does it as well.

## Example:

https://www.openstreetmap.org/edit#map=20/52.47361/13.44781
<img width="306" alt="bildschirmfoto 2018-05-08 um 22 38 27" src="https://user-images.githubusercontent.com/111561/39781863-ab7f7f12-5310-11e8-9e95-8585df72025d.png">

**Comment by bryceco** [comment]
Fixed in 1a21fd624c7f8209ad2aec76f438d3658c390d9f
