### ISSUE TITLE
Broken areas are created (when connecting areas?)

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#126]
I noticed the awesome new feature that allows to snap area-points to an existing area.

I tried it on an iPad and iPhone but the form that was submitted was broken.

## It looked like this:

GoMap: 
![img_0005](https://user-images.githubusercontent.com/111561/39782710-4b596d70-5313-11e8-864e-3e2e4730580b.JPG)

GoMap:
![img_0006](https://user-images.githubusercontent.com/111561/39782802-92e80fb6-5313-11e8-962e-d7e8081d3515.jpg)

iD Editor:
<img width="340" alt="bildschirmfoto 2018-05-08 um 22 55 24" src="https://user-images.githubusercontent.com/111561/39782813-9b5cde38-5313-11e8-9587-efe7fc54c1ae.png">

## It should look like this:

<img width="374" alt="bildschirmfoto 2018-05-08 um 23 00 55" src="https://user-images.githubusercontent.com/111561/39782858-b63a4eac-5313-11e8-9b9a-d81f2dde1753.png">

## Example:

https://www.openstreetmap.org/way/585105578/history
- the last edit is my fix in iD Editor
- the second to last edit is the broken one https://www.openstreetmap.org/changeset/58800577#map=19/52.47367/13.44698

**Comment by bryceco** [comment]
Fixed
