### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by tohaklim** [bryceco/GoMap#127]
Just started happening today: app crashes on launch, sometimes immediately, often it still manages to draw some of the area.
Reboots didn’t help, neither did a reinstall.
Here’s a log excerpt:

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  10

Application Specific Information:
abort() called

Filtered syslog:
None found


Last Exception Backtrace:
(0x181cda364 0x180f20528 0x181ce7828 0x181cdfd10 0x181bc4ecc 0x100fa8524 0x100fa8d7c 0x18226538c 0x18227dce0 0x1826b1ba0 0x1825f1894 0x1825e14c4 0x181656a14 0x18165e200 0x181656a14 0x18165e200 0x18165e0ac 0x1826b3878 0x181656a14 0x18165ef08 0x18165d80c 0x181663cf4 0x181663a38 0x1818ff06c 0x1818feb6c)

```
Crashed thread excerpt
`Thread 7 name:  Dispatch queue: NSOperationQueue 0x1c002cb20 (QOS: UNSPECIFIED)
Thread 7 Crashed:
0   libsystem_kernel.dylib        	0x00000001860d82e8 0x1860b6000 + 140008
1   libsystem_pthread.dylib       	0x00000001861ed2f8 0x1861ea000 + 13048
2   libsystem_c.dylib             	0x0000000186046fbc 0x185fe4000 + 405436
3   libc++abi.dylib               	0x00000001857e4068 0x1857e2000 + 8296
4   libc++abi.dylib               	0x00000001857e4210 0x1857e2000 + 8720
5   libobjc.A.dylib               	0x000000018580c810 0x185804000 + 34832
6   libc++abi.dylib               	0x00000001857fc54c 0x1857e2000 + 107852
7   libc++abi.dylib               	0x00000001857fc5b8 0x1857e2000 + 107960
8   libdispatch.dylib             	0x0000000185f42a28 0x185f41000 + 6696
9   libdispatch.dylib             	0x0000000185f4a200 0x185f41000 + 37376
10  libdispatch.dylib             	0x0000000185f42a14 0x185f41000 + 6676
11  libdispatch.dylib             	0x0000000185f4a200 0x185f41000 + 37376
12  libdispatch.dylib             	0x0000000185f4a0ac 0x185f41000 + 37036
13  Foundation                    	0x0000000186f9f878 0x186eb5000 + 960632
14  libdispatch.dylib             	0x0000000185f42a14 0x185f41000 + 6676
15  libdispatch.dylib             	0x0000000185f4af08 0x185f41000 + 40712
16  libdispatch.dylib             	0x0000000185f4980c 0x185f41000 + 34828
17  libdispatch.dylib             	0x0000000185f4fcf4 0x185f41000 + 60660
18  libdispatch.dylib             	0x0000000185f4fa38 0x185f41000 + 59960
19  libsystem_pthread.dylib       	0x00000001861eb06c 0x1861ea000 + 4204
20  libsystem_pthread.dylib       	0x00000001861eab6c 0x1861ea000 + 2924`

**Comment by jketcham** [comment]
I don't have much to add except that I'm also experiencing this, on an iPhone 6S running 11.3.

**Comment by bryceco** [comment]
This is caused by a malformed JSON file that is being downloaded to update the list of aerial imagery providers. I've contacted the host of the file, and also submitted a revised version of Go Map!! to the App Store that tolerates the bug. Hopefully one or both will get released soon.

In the meantime as a workaround you can enable airplane mode, launch Go Map!!, and then reenable internet and things will work correctly.

**Comment by bryceco** [comment]
New version is released, and editor-layer-index has been fixed, so we shouldn't see this again
