### ISSUE TITLE
wikipedia= field should be free text not a URL

### ISSUE THREAD

**Issue by mikix** [bryceco/GoMap#128]
The wikipedia= key field in Go Map!! is set as a URL field so that the OSK only shows URL keys. However, that key’s data  is supposed to be something like “en:Title of Page” not a URL.

Right now, the OSK doesn’t show a space bar which makes it tough to enter titles.

https://wiki.openstreetmap.org/wiki/Key:wikipedia

**Comment by bryceco** [comment]
Good to know. Fixed and thanks!
