### ISSUE TITLE
Nodes with long name are hard to move

### ISSUE THREAD

**Issue by nickel715** [bryceco/GoMap#129]
I'm very happy to see the german translation in GoMap! now. But unfortunately some type's has very long names like charging_stations. But also if the tag `name` is filled with a very long name you see the same result on the map.

## Steps to reproduce - name tag
* Add new node
* Set for the tag `name` a value with 70 chars
* Save the node to go back to the map
* Try to move that node to the right

## Steps to reproduce - preset name
* Find a preset with a very long name like [charging_station in german](https://github.com/openstreetmap/iD/blob/dc8e8eb933c74af58431b0f0ec236438a8879533/dist/locales/de.json#L3005):
```json
"amenity/charging_station": {
    "name": "Ladestation für Elektroautos, Plug-in Hybridfahrzeuge, Pedelecs und E-Bikes.",
    "terms": "Ladestation, E-Tankstelle, Stromtankstelle"
},
```
* Create a new node without any additional tags
* Select the preset you found

## Actual result
Sometimes if you try to move the node the map will jump and the node will not really move or even worse it will move in the opposite direction.
If you lucky you can move the node a little bit, then you have to reposition the map and move it again a small step.

## Expected result
It's easy to move the node in every direction, even if the name in the preset or the tag name is extremely long.

## Additional details

* iPhone X
* iOS 11.3.1
* Language and region: German/Germany
* Go Map! v1.5.2

![screenshot](https://user-images.githubusercontent.com/148483/40108961-a035433e-58fc-11e8-9aa7-736fb7c7698e.PNG)

**Comment by bryceco** [comment]
I'm not sure why, but when using very long names or the German language charging station preset I'm not able to reproduce this behavior. Everything is very smooth. I'm testing with iPhone X and OS 11.3.1 as well.

**Comment by dieterdreist** [comment]
I confirm very smooth on iphone 6. For very long names you have to move the screen though to reach the move-icon, maybe the labels could be multiline if very long.

**Comment by nickel715** [comment]
maybe this video can help to clarify that
[ScreenRecording_05-18-2018 11-53-00.MP4.zip](https://github.com/bryceco/GoMap/files/2016351/ScreenRecording_05-18-2018.11-53-00.MP4.zip)

My suggestion would be to cut off the title on the map, imho it's not important to see the entire title on the map. But multiline sounds good too

**Comment by bryceco** [comment]
Oh I see. It is a problem when the pin center is off-screen to the left. This activates the code that is responsible for scrolling the window to try to keep the pin on-screen. You shouldn't see this behavior if the pin/node is in view when you try to move it.

**Comment by nickel715** [comment]
OK guys I tell you something funny: I always try to move the node with the move symbol on the right and I didn’t figure it out that I can also move the node by simply tapping on the label some there else :facepalm:

**Comment by bryceco** [comment]
I went ahead and added a maximum size to the pushpin label for good measure.
