### ISSUE TITLE
„Set commit message to blank“ Button

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#130]
Feature request:

Its great to have the last commit message in the field on a new commit b/c often I can re-use this. But also often I need to write something new. 
An (x) somewhere in the UI that deletes the previous commit message from the field would be very helpful. 
Could also be a very small „Clear message“ Link below the Textarea.

**Comment by tordans** [comment]
@bryceco I might be looking at the wrong place … :-)
So: Where do I find this "Clear commit message"-Icon/Link?

I was expecting it next to the "Changeset comment"-Text.

![IMG_7628](https://user-images.githubusercontent.com/111561/83964718-1b5c5300-a8af-11ea-9819-1e97f44a48c5.jpg)

**Comment by bryceco** [comment]
It appears once you’ve clicked on the text field, but’s it’s really hard to see in dark mode.

**Comment by bryceco** [comment]
Fixed in ec426008dba7515bb8a50fa8f285dd2b33051b50
