### ISSUE TITLE
The links in the (i) Infowindow are not clickable

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#131]
There are two links in the info window that can be opened via the (i) at the top right of the screen.
On my iPad both links seem to do nothing.

**Comment by Mxdanger** [comment]
Yep I’m still having this problem too.

**Comment by wtimme** [comment]
Hey guys, I've made a few changes and created a pull request (#176). Could you have a look and report back if the problem still persists? Thanks in advance!
