### ISSUE TITLE
What imagery URL are you using?

### ISSUE THREAD

**Issue by grischard** [bryceco/GoMap#132]
Hi! I'm reaching out from https://github.com/osmlab/editor-layer-index since the latest version of Go Map!! seems to use our index. Just so we don't break it accidentally, what's the URL or method that you use to load the imagery? If it's not https://osmlab.github.io/editor-layer-index/imagery.geojson, could you use that in a future version? Thanks!

**Comment by bryceco** [comment]
I've been using https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/imagery.geojson, which is what the download button links to. I didn't realize I could reference the file directly.

**Comment by grischard** [comment]
Ah, that would break if we ever revisit https://github.com/osmlab/editor-layer-index/issues/506 then.

**Comment by bryceco** [comment]
It looks like https://osmlab.github.io/editor-layer-index/imagery.geojson uses a different, incompatible format from what I'm using. Is that change in format going to affect  https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/imagery.geojson imminently
 or do I have some time to fix my code?

**Comment by grischard** [comment]
Hah, it should be the same file! Are you using imagery.json maybe?

You have time, for once we're trying not to break other people's software :)

**Comment by bryceco** [comment]
Yes, sorry, I was using .json, not .geojson. I've updated my app to handle both formats and the next version will point at the .geojson version.
