### ISSUE TITLE
Always show "delete row" in "Node tags" view

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#133]
A suggestion for an improvement for the UI.

Use Case: When I change an existing tag I often need to remove additional tags from it. Example: A tree is now a tree_stump. So I need to remove the foliage-tags and ref-tag.

Right now those are multiple clicks when it could be just one UI for both actions (deleting and adding / editing)

## Current UI: Normal view  – Edit view

| Normal | Edit |
| --- | --- |
| ![img_7822](https://user-images.githubusercontent.com/111561/41509010-61c866d4-724d-11e8-9d63-831d5bca7ffd.png) | ![img_7823](https://user-images.githubusercontent.com/111561/41509009-61ab5576-724d-11e8-822f-b6cb56e3f3a6.png) | 

## Improved UI
- show the delete-icon on the right next to the input all the time
- remove the 'edit' link for the normal view

**Comment by dieterdreist** [comment]
sent from a phone

> On 17. Jun 2018, at 16:43, Tobias <notifications@github.com> wrote:
> 
> A suggestion for an improvement for the UI.
> 
> Use Case: When I change an existing tag I often need to remove additional tags from it. Example: A tree is now a tree_stump. So I need to remove the foliage-tags and ref-tag.
> 


in this case it is not clear whether you should remove the ref tag 


> Right now those are multiple clicks when it could be just one UI for both actions (deleting and adding / editing)
> 


do you know you can delete by swiping the tag?
FWIW, I think tag deletions are a sensitive topic and requiring to delete them individually makes sense to me.

**Comment by bryceco** [comment]
I also feel this change would make accidental deletions too easy.
(The real bug here is that content isn't being inset to make room for the delete button when in Edit mode.)

**Comment by tordans** [comment]
> do you know you can delete by swiping the tag?

Thanks, @dieterdreist I didnt know; that makes it easier. :-)

I never tested this interaction since there was a dedicated button to delete. It makes me wonder if the "edit-link + delete-buttons"-interaction is needed at all, since there is the swipe gesture already.
