### ISSUE TITLE
Place duplicated pin below the yellow cross

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#134]
I think the behavior of the duplicate feature could be slightly smoother:

1. I select a tree-node
1. I click 'more' => 'Duplicate'
3. the node is duplicated…
   * CURRENTLY: the new tree-node is placed somewhere below right to the mother-node
   * IMPROVED: the new tree node is place below my yellow cross at the center of my scree

Advantage: When duplicating, I look forward and have the cross at the place of the new node. So the cross is the more correct position (\* see screenshot). Also it is easier to spot / select at the center of the screen.

The improved behavior would also be similar to the copy-feature of iD-editor which places the pasted node below the mouse cursor.

\* The cross marks the spot of the new/next trash bin:
![img_8074](https://user-images.githubusercontent.com/111561/42073826-19c47678-7b69-11e8-8377-20243a66b238.png)

**Comment by bryceco** [comment]
That's a fine idea, but what is the behavior when the cross is on top of the original item, or the duplicated item is a way?

**Comment by tordans** [comment]
**As for the type of item:**

IMO this works for all kind of items. It basically is the same logic as right now, just with a different placement-lat/lng. I duplicated a few items for testing right now and don't see any problems.

**Some quasi-code:**

- user clicks on node/way/area
  - for way/area: interface saves the exact click point (which is the same place where that shows the popover/tooltip ATM)
- user clicks duplicate
- if new "cursor"-position 
  - … is somewhere else => then above the selected object: duplicate object
  - … is inside the yellow cross => use the previous duplication code that places the item a few "pixel" away
    - maybe everything inside this circle is "on top of the original item"? ![bildschirmfoto 2018-10-02 um 19 15 51](https://user-images.githubusercontent.com/111561/46365190-3907fc80-c678-11e8-9190-ba0b138a660b.png)

- interface selects duplicated element (same as before)

**Comment by tordans** [comment]
🤗
