### ISSUE TITLE
Clicktarget for button "upload gpx track" to small

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#135]
The click target for this button seems to be tiny. I miss-click 7 out of 10 times. 

This is especially time consuming, since a miss-click leads back to the map view, so I need to navigate back with a few clicks and then re-find my track in the list.

**Bugfix**
- Make the clicktarget of the button bigger and remove the overlap of the "show track on map"-action with the "upload" action

**Suggestions**
For privacy reasons, I dont want to upload every track. So I want to see what track I upload before I do so. The UI doesnt make that easy ATM. The UI could make it easier by
- Showing a preview of the track inside the list view (even a tiny preview would help)
-or-
- Adding a details-link to each track. On the details view, there could be a preview and a big upload-button. It would also eliminate the need for a "show track on map"-action since that is the preview already.
-or-
- Use the existing "show track on map" feature, but then hide all other tracks to I can see which I am looking at right away and also provide a direkt link back to the previous list, eg by changing the click-target of the settings button (it could then lead back to the list an skip the screen in between). Or maybe adding a "upload" and "delete" button to the map once I preview a track, so I can cleanup the list from right there.

**Its this button:**

![img_8147](https://user-images.githubusercontent.com/111561/42221264-cdc272d6-7ed1-11e8-91ba-31876c0db682.jpg)

**Comment by bryceco** [comment]
I made the button larger with more space, and when you select a GPX track it now highlights it in red. There should probably be a checkmark or some indication of the currently selected track, but that's future work.
