### ISSUE TITLE
Filter "Show Objects" not "Building Level -1" does not work

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#136]
Version: 1.6, iOS 11.4

I activated the filter. And I thing the building from the screenshot should be hidden now, right? – It is not.

Am I doing it wrong or is this a bug?

Does this feature "show objects" have anything todo with my object cache?

|Image|Image|Image|
|---|---|---|
|  ![img_8340](https://user-images.githubusercontent.com/111561/42868167-e9ecf7a0-8a71-11e8-870e-3362338cf639.png) |![img_8342](https://user-images.githubusercontent.com/111561/42868165-e9b27846-8a71-11e8-87c1-1ef34cdfc44f.png) | ![img_8341](https://user-images.githubusercontent.com/111561/42868166-e9ce945e-8a71-11e8-8528-4067888bcd1f.png) |

**Comment by bryceco** [comment]
Buildings are enabled, and the level= filter is disabled, so I believe the building should be shown.

**Comment by tordans** [comment]
Hi @bryceco, I retested it just now:
- Toggling the "Building level" on/off does not show/hide the selected element
- Toggling the "Buildings on/off" does show/hide all buildings
- I read the UI like this: "Show Object … Building Level -1…3,7 … no/false". So all buildings with this level should be hidden, right?

I might be miss-understanding the UI. And the use case for this building level filter.

My goal is to show all buildings except for those that are underground.

This is the place from the screenshot: https://www.openstreetmap.org/#map=18/52.49971/13.39413
To jump there within GoMap search for `Brandesstrasse` > first result > pan a bit north and east.

**Comment by bryceco** [comment]
The building level determines what is displayed, so level=1 shows objects on level 1. If it’s turned off then it doesn’t mean hide them, it means that filter isn’t used. I guess that isn’t obvious but I don’t know how to make it more clear.

**Comment by tordans** [comment]
Oooh, now I figured it out.

This is what I need to do:
- "Enable filter": on/green
In "Show Objects"
- "Building level": "1" in the input and on/green
- Everything else on/green

I was stuck in a usability loop :-).

I will think about how the UI could look to make it easier for me to understand. I will post those ideas here and keep the issue open until then, if thats OK with you. 

I understand its not a bug. But there should be a way to make it a bit more self explaining :).

**Comment by bryceco** [comment]
Closing due to lack of actionable feedback :)
