### ISSUE TITLE
GPX track: save upload status

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#138]
This is related to https://github.com/bryceco/GoMap/issues/135

My use case:

With the awesome new "collect in background" feature, I collect quite a few good tracks.
But I still want to select what I upload for privacy reasons.
Also, after I upload them, I want to keep them in the app for a bit for reference in the app.

**What I am looking for:** A way to see what tracks I uploaded already. Especially in the list view.

Right now I have to [check the file names of each of my tracks](https://www.openstreetmap.org/user/tordans/traces) to compare if I uploaded it already.

Sometimes I just delete them right after upload (which could be made easier by adding a prompt after the upload "delete now? >delete >keep"). But whenever I know that I stay at a region a while I want to keep the tracks and upload some every other day.

**Comment by bryceco** [comment]
I agree there should be an indicator once uploaded

**Comment by bryceco** [comment]
Fixed in e90ed12e44a9d0a437c2836522fb4036c592c12c

**Comment by tordans** [comment]
Thanks for this; this feature improved a lot!
