### ISSUE TITLE
Add quick toggle for fields with two values

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#140]
UseCase/Excample: I add a bench (example) and want to select the preset for "has backrest yes/no". 

Right now I need to click quite a few times.

This is the current views that I am referring to:

|  overview | details view |
|---|---|
|  ![img_9221](https://user-images.githubusercontent.com/111561/43703560-5c2ffe9e-995d-11e8-95d7-275f72a1b4d0.PNG)  |  ![img_9222](https://user-images.githubusercontent.com/111561/43703567-63331bcc-995d-11e8-868e-ac765bb192bc.PNG)  |

The iD Editor makes it easier by allowing to toggle between the options. Each click on the radio button toggles to the next of the 3 options:

| default | yes | no |
|---|---|---|
|  <img width="371" alt="bildschirmfoto 2018-08-06 um 09 54 58" src="https://user-images.githubusercontent.com/111561/43704097-f24b8582-995e-11e8-9081-8b0f62561c9e.png">  |  <img width="379" alt="bildschirmfoto 2018-08-06 um 09 55 03" src="https://user-images.githubusercontent.com/111561/43704105-f74e8566-995e-11e8-8aeb-742b0921acda.png">  |  <img width="371" alt="bildschirmfoto 2018-08-06 um 09 55 08" src="https://user-images.githubusercontent.com/111561/43704118-fdfa7a1e-995e-11e8-8304-fa1c57f8459d.png">   |  

To test it out: [Open iD](https://www.openstreetmap.org/edit#map=18/52.47241/13.44790), Add a node, select Bench, toggle…

This UI would be perfect for all defaults that have only 2 options + the "not defined" option.

**Comment by dieterdreist** [comment]
sent from a phone

> On 6. Aug 2018, at 09:59, Tobias <notifications@github.com> wrote:
> 
> This UI would be perfect for all defaults that have only 2 options + the "not defined" option.


there are no keys where you can enter only 2 values. Strictly speaking, all values can be anything. It often happens that keys that start with yes/no later become more detailed (e.g. bridge=yes became bridge=viaduct, building=yes becomes building types, etc.). This said, I‘d support a „yes/no one tap solution“, as long as it also allows to enter different values.

**Comment by tordans** [comment]
@dieterdreist I agree, the non-preset-input-option is still needed. However in my suggestion there would still be both UIs, the "common tags" UI (which I refer to) and  the "node tags" UI which allows editing all data raw.

**Comment by bryceco** [comment]
It’s two taps to select yes/no in the current implementation, and the iD implementation requires on average 1.5, right? It doesn’t seem like enough improvement to justify introducing a new UI behavior.
