### ISSUE TITLE
"Readonly" mode for certain elements

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#142]
Similar to the Filter-Feature (in the coming 1.6), a readonly-Mode for certain elements would be helpful.

**UseCase**

When editing, I like to see all the data, but only interact with some of it. For example borders (or postal code lines). Its very helpful to see them, but I would never edit them.

Recently I did some wrong editing by adding a gate to a border because while zoomed in I miss-read the line as a bike-lane. Luckily someone fixed that soon after :).

**Filter vs readonly**

Why not filter them: For example in a recent editing there was a fence that I mapped which looked like it followed a district border; which made sense; so I used the border line form as a strong guideline in addition to what I saw in the field. I can only see such relations when the border is visible (not filtered).

**Interface**

The admin interface could look very similar to the filter view where one selects elements that should be readonly.

Alternatively, the UI could just allow for one or more key-value pair input(s) that are then interpreted as readonly elements.

**Comment by bryceco** [comment]
This seems really confusing. I already have strong doubts about filtering, but added it because I needed it for indoor mapping. I'm unclear about whether read-only elements are supposed to throw an error dialog or something else? And adding another screen of read-only filters seems really complex.

**Comment by bryceco** [comment]
Closing this until some other people ask for it.
