### ISSUE TITLE
How to select multipolygon relations if there is more than one

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#143]
I did not manage to choose which multipolygon relation to select in a case where the same way was part of 2 multipolygon relations.
E.g.
* https://www.openstreetmap.org/relation/3080558
* https://www.openstreetmap.org/relation/3080559

It would be nice if you could choose which relation to select (or maybe I simply didn't find the way to do it?)

**Comment by fntagit** [comment]
It seems possible:
- select the object;
- “Tags”;
- “All Tags”.
After the tags, the relations containing the object are listed, and one can make a choice.
But maybe this was not what you were meaning.

**Comment by dieterdreist** [comment]
sent from a phone

> On 23. Aug 2018, at 14:08, fntagit <notifications@github.com> wrote:
> 
> It seems possible:
> 
> select the object;
> “Tags”;
> “All Tags”.
> After the tags, the relations containing the object are listed, and one can make a choice.
> But maybe this was not what you were meaning.


when I tap on tags all tags the view says “Multipolygon tags”, it doesn’t select the way on the map, it selects the multipolygon relation (I’m on v1.6.0.6)
