### ISSUE TITLE
Transformation proposal: Make Regular

### ISSUE THREAD

**Issue by fntagit** [bryceco/GoMap#145]
In mapping, one often encounters man-made objects with a regular polygonal shape. It is quite difficult to draw a good-looking regular polygon by hand...
In order to facilitate the drawing of regular polygons, a "Make Regular" transformation would be handy. This transformation, applicable to a closed way aka polygon, would, well, make it regular. It would probably make sense to keep the center in place while transforming.
Notes:
- applying this transformation to a four-sided polygon would always produce a square; this is not the same as "Make Rectangular";
- applying this transformation to a polygon with "many" sides would produce something ressembling a circle, but without changing the number of nodes/sides; this is not the same as "Make Circular".

**Comment by fntagit** [comment]
Coming back to this suggestion: arranging a set of points as a regular polygon is the same as arranging those points in a circle. So this transformation would be a variation of “Make circular”, simply NOT adding supplementary points in the process. And it would be a real boon when drawing those pesky hexagonal or octogonal towers, not speaking of those strange dodecagonal objects architects are throwing in the landscape 8-).

**Comment by bryceco** [comment]
Yes, this is easy and obvious. I'm not sure it's common enough to be worth cluttering up the interface
 with yet another option. If iD does it then I will too.

**Comment by fntagit** [comment]
You won’t believe how many polygonal historic structures we have on this side of the pond. I sure understand your concern about the inflation of the UI. Since what we are talking about is variation of "Make circular", would this be possible: Touch and hold "Make circular" to access the variation with no added nodes?
