### ISSUE TITLE
Object rotation: alternate UI proposal

### ISSUE THREAD

**Issue by fntagit** [bryceco/GoMap#146]
Go Map!! offers the option to rotate an object, either around its center or around one of its nodes. This is currently controlled by the two fingers gesture that is 'natural' on iOS.
In mapping, it is often necessary to perform a very precise rotation. This is not easy with the standard two fingers gesture, especially on the small screen of an iPhone.
Here is an idea for a competely different UI:
- after selecting "Rotate", the circular arrow appears to signal that the object rotation mode is active;
- the rotation is then performed by sweeping up and down, with a single finger, anywhere on the screen;
- the amount of rotation is controlled by the left-right positioning of the finger: near the left edge of the screen, the range is something like ±180° (or maybe even ±200° to be sure), near the right side something like, say, ±1°;
- so long as the finger stays on the screen, the object rotates according these rules;
- lifting the finger terminates the object rotation mode.
This is of course not original: there are already some applications that include such sliders or buttons.

**Comment by dieterdreist** [comment]
I like the idea but would invert left and right so that small increment is on the left

sent from a phone

**Comment by DerKarlos** [comment]
Controling in 2 dimentions may be to complicated and not intuitive. I would think of this:
Touch the screen and move left/right to rotate anti/clockwise. the more you swipe away from the start touch down, the faster the rotation. Below X picsles/% there souldn't be any move at all. An untouch may cause an unintended move to, so the last X ms chould be ignored/undone.

**Comment by fntagit** [comment]
Controlling in two dimensions is already very popular in media players, where it is the de facto standard for moving the playhead, aka "scrubbing". See for example VLC.
But it is true that in media players, the movement is controlled by the left/right sweep, while the resolution is controlled by moving vertically. Maybe that it would be wise to adopt the same convention, in order to capitalize on existing knowledge and muscle memory.
Media players also show a slider, showing the current position in the media. While not strictly necessary as an indicator when controlling the movement of an on-screen object - since one usually watches the object itself, it may be useful to include one as a hint and as a target for the finger.
I may not fully understand the details of your proposal, but can one, in a single pass, perform a large rotation and terminate with a fine adjustment?
Of course, preventing the untouch to trigger an unwanted movement is a good idea, regardless of the particular UI involved.

**Comment by bryceco** [comment]
See #147
