### ISSUE TITLE
prefer way over relation when selecting 

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#153]
Right now you can select a way that is also part of a relation by pressing long. For a single tap the relation is selected. It would be better to select the way or offer to select  one of the ways (if several overlapping ways are found) in the single tap case, and make the relation only selectable on long press. This makes adding nodes to ways much quicker in this context.

**Comment by bryceco** [comment]
You don’t need to long press: you tap the relation, then the way, then the node. Each tap is a refinement on the selection. Selecting the multipolygon first makes it obvious to the user that the way belongs to a relation, so they don’t accidentally move a building exterior without also moving its atrium for example, or add tags to a way when they should be tagging the relation.
