### ISSUE TITLE
Replace Tags Feature

### ISSUE THREAD

**Issue by zlavergne** [bryceco/GoMap#157]
The Copy/Paste functionality is useful for some cases and definitely safe but there is a large use case for being able to replace the tags of the paste object.

The main use case:
User changes a tag (name, lanes, surface type, etc.) of a highway way (new object or not) and needs to continue it onto the next segment of the way.

Current Copy/Paste behavior:
When a user pastes the tags, they are combined with the current tags of the object using semicolons.

Proposed Replace Tags behavior:
When a user pastes tags, all tags of the object will be removed and all the copied tags will be added to the object.

I was also considering there could be preferences for replacing tags. For instance, if you only want to copy/replace names and surface_type, you could select those in a checkbox list in the settings.

I'm working on this on the Kaart fork but I can make a PR if you want it on the main project.

**Comment by bryceco** [comment]
I’d prefer that if the target has existing tags that it ask if it should Merge or Replace. 
I sometimes want to move address tags from a node to a building and need the merge behavior. 

My concern with selective copying is that the user might forget that a subset is selected and accidentally lose data.

**Comment by zlavergne** [comment]
I wasn't thinking about getting rid of the paste(merge) functionality but adding another option in the Edit Actions Sheet.

> My concern with selective copying is that the user might forget that a subset is selected and accidentally lose data.
That's true. I was trying to think of a way around that but couldn't come up with anything. I'll leave that part out. 

Perhaps calling it "Replace All Tags" would be less ambiguous? I definitely want to keep the current Merge functionality.

**Comment by bryceco** [comment]
Oh, so you would put it under the More... menu? That seems confusing to have different pastes in different places, I’d rather have a prompt for clarification which will also remove the ambiguity with the current Paste button.

**Comment by tordans** [comment]
Another idea:

Removing tags by just swiping from right to left ist very easy and fast in the "Node tags"-UI.
Maybe a different workflow might help to prevent adding additional options in the menu or a new prompts.

Example/Idea:
- I copy a tag with "some=value"
- I select a different tag with "other=value"
- I click paste
- Now the UI shows the "Node tags" UI which now has both tags in it "some=value" and "other=value". 
- I now can understand what happened (solves one issue) … and review the tags … and easily remove those that are false (swiping) – or I can just click save at the top-right to close the view.

Both solutions (additional option in the menu or a prompt) dont really solve the understanding, as I might now really know all tags that are present. So I would need a comparison table to really know whats going on. 
Like a prompt 
>  Therare those tags right now <List>, you are pasting <OtherList>. 
  Do you want to … 
  {button}replace tags{/button} {button}merge the tags{/button}

This feels more complex than the idea above.

**Comment by zlavergne** [comment]
Sounds good. I will make an update to this (hopefully next week) to use a prompt instead and display the options: "Merge" and "Replace". I will play around with it and see if there is a useful way to show the changes before actually executing the paste.

**Comment by zlavergne** [comment]
![image](https://user-images.githubusercontent.com/9849118/47112353-58279200-d213-11e8-9131-ff05dcb923c1.png)
@bryceco Do you think the "Paste {from_name}'s tags?" message makes sense or should I scrap it?

**Comment by bryceco** [comment]
I'm usually pasting tags defining a tree, a trail+surface combination, a building=apartment, or something similar. So for my case I'm not sure it adds any value. But if you think it would help someone else I'm okay with it. Also think about the #129 situation, I don't know how the dialog adapts to long names.

**Comment by bryceco** [comment]
Thanks for adding this!
