### ISSUE TITLE
Associated Domains

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#164]
Is the "Associated Domains" feature working properly?

In the [documentation][1], Apple states:

> To associate a website with an app, you will need to have a file on your website [...].
> Place this file either in your site’s .well-known directory, or directly in its root directory. If you use the .well-known directory, the file’s URL should match the following format:
> `https://<fully qualified domain>/.well-known/apple-app-site-association`

The domain that is entered as an associated domain is _openstreetmap.org_. But neither [in the .well-known directory][2] nor [in the root directory][3] the `apple-app-site-association` file is available.

This leads me to believe that the feature does not work at the moment. Or am I missing something here?

[1]: https://developer.apple.com/documentation/security/password_autofill/setting_up_an_app_s_associated_domains
[2]: https://www.openstreetmap.org/.well-known/apple-app-site-association
[3]: https://www.openstreetmap.org/apple-app-site-association

**Comment by bryceco** [comment]
This relates to #98. I started looking into it but I felt I really need to have a test domain under my control to verify it works before asking Tom Hughs about putting the required file on the OSM website. If you own a domain and want to experiment with it that would be great.

**Comment by wtimme** [comment]
Can you provide the [team ID][1] that you use for the app?

With this information, we can then create the apple-app-association-file and submit a pull request for #98. After the pull request is merged, iOS users who have Go Map!! installed will be asked if they wanted to open it when choosing "Edit with Remote Control".

Furthermore, we need to write a parser that can handle URLs like this and e. g. focuses on the entity:
```
https://www.openstreetmap.org/edit?editor=remote&way=5013364#map=18/48.85826/2.29450
```

[1]: https://stackoverflow.com/a/18727947

**Comment by bryceco** [comment]
I'd like to test the app with the apple-app-association-file before submitting the pull request.

**Comment by bryceco** [comment]
The team ID is MKTTC6734C

**Comment by wtimme** [comment]
Thanks for the update!

Here's the `apple-app-site-association`:
```json
{
    "applinks": {
        "apps": [],
        "details": [{
            "appID": "MKTTC6734C.com.bryceco.GoMap",
            "paths": ["/edit"]
        }]
    }
}
```

### Testing

In order to test this, upload the JSON to the `.well-known` directory or in the root of your webspace:
- `https://example.com/.well-known/apple-app-site-association` or
- `https://example.com/apple-app-site-association`

You now need to add your domain to the list of *Associated Domains* in the *Capabilities* of the "Go Map!!" target.

Run the app and open Safari. In the address bar, type your domain plus the `/edit` path, e. g.:
`https://example.com/edit?editor=remote&node=663346172#map=19/52.52111/13.40837`. 

Instead of opening the website, iOS should switch to "Go Map!!".

#### Things to keep in mind while testing

- Make sure the file is available via HTTPS
- The response should have the header `application/json`

### Next steps

After successful testing, we'll need to
- request the file to be included in the OSM server (and therefore available on openstreetmap.org)
- write a parser that handles the URL when the app is opened

**Comment by bryceco** [comment]
This is fixed in eb539ac5e61d2c03c72cac4d0b4c7247a940a289

To test you can click on this link:
https://gomaposm.com/edit?center=47.679056,-122.212559&zoom=21&view=aerial%2Beditor

**Comment by wtimme** [comment]
Neat! Has this also been added to openstreetmap.org, so that mappers can open GoMap from the original OSM page?

**Comment by bryceco** [comment]
Not yet, not until it's in the App Store version.
