### ISSUE TITLE
 No autocomplete for number values

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#166]
For values like `capacity`, when typing numbers, the autocomplete makes it actually harder to add the value than without.

Instead of just typing my value and clicking in the next field I need to click the value from the list. Every time I click on save or cancel I either close the edit window (save) or even loose all my changes (cancel), since those actions don't apply to the autocomplete overlay but the edit window in general.

Interestingly, this behavior is only for editing, not for new nodes.

Eg: Create a new bicycle_stand => the capacity works great without autocomplete.
But edit an existing => the capacity behaves like described above.

<img src="https://user-images.githubusercontent.com/111561/47260730-731f2e00-d4c1-11e8-976f-cf317e250150.png" height=400>

**Comment by dieterdreist** [comment]
yes, this started recently, I am collecting a lot of building:levels these
days, and when I add the value like "5", autocompletion gets in my way
(even obscuring current key and value which I typed) and suggests 5 and 5.5
or something like that. For number values it would be better not to have it.

**Comment by bryceco** [comment]
I'm using a hard-coded list for keys, so if you see inappropriate behavior let me know and I'll adjust it.
