### ISSUE TITLE
Add Mapillary SDK to capture images in app

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#168]
Mapillary just announced a new SDK to allow image capturing from inside other apps.

Blogpost https://blog.mapillary.com/update/2018/11/06/capture-sdk.html
Git https://github.com/mapillary/mapillary-sdk-ios

I would love to see this feature in GoMap. Right now, whenever I go mapping I have both apps open and switch between them constantly.

Having image capturing in GoMap would help a lot to …
- capture images of areas that I dont have the time to map while  on the go
- capture images of areas that I just mapped as a proof of what I just saw

The way I use Mapillary when walking is more as a POI photo service. So I dont take a coherent set of pictures like you would when you mount your phone/camera to a bike/car. Instead I have the app open to take 360-photo-sets or capture sets of images from POI on the go (10 pics of a junction here, 3 pics of a ad-column there, …).

Does this sound interesting? Should we maybe try to add some wireframes to this issue to discover how this might work?

**Comment by bryceco** [comment]
This is something I’ve been wanting to do as well. Good to hear there is an API now.

**Comment by zlavergne** [comment]
We've been wanting to incorporate image capture too! There were ways to make it happen before but the SDK makes it much easier. And according to that blog post, they're migrating most of their operations to the SDK and it will become more robust over time.

**Comment by tordans** [comment]
Just for reference, this feature is par of the GSoC project idea list at https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2019/Project_Ideas#GoMap.21.21_editor

>|title=GoMap!! & Mapillary: Integrate Mapillary Image SDK into GoMap!! for mobile mapping
|suggestor=[[User:Tordans|Tordans]]
|summary=GoMap!! is the best mapping tool for OSM on iOS (iPhone and iPad). It it the best too for #MapWalking – improving OSM while on the go. Mapillary on the other hand is ideal to record information visually to map them later at home. Both use cases should be combined: Thinks that are too complex or time consuming to map right now in GoMap could be captured with an integrated Mapillary image capturing to map later. But also thinks that I just mapped in GoMap benefit from a few images as a form of visual proof and guideline for other mappers.
|skills=iOS
|difficulty=medium
|mentors=For UX and UI Feedback [[User:Tordans|Tordans]]
Development [[User:Zlavergne|Zlavergne]], [https://www.openstreetmap.org/user/bryceco bryceco]
|notes=GoMap Github Issue for this idea: https://github.com/bryceco/GoMap/issues/168
Mapillary SDK Blogpost https://blog.mapillary.com/update/2018/11/06/capture-sdk.html
Mapillary SDK Github https://github.com/mapillary/mapillary-sdk-ios

**Comment by bryceco** [comment]
I would love to have photo support in OSM in general. There are proposals for image=* and mapillary=* keys, but nothing that is standardized and handles issues like multiple photos. In addition there are confusing (to newcomers) issues like having to create/login to an additional account unrelated to OSM. And bandwidth issues requiring postponing uploads until WiFi is available. Until OSM has more clarity on this I don’t think it’s appropriate to break new ground in this area.

**Comment by dieterdreist** [comment]
Am Fr., 17. Apr. 2020 um 08:39 Uhr schrieb bryceco <notifications@github.com
>:

> I would love to have photo support in OSM in general. There are proposals
> for image=* and mapillary=* keys, but nothing that is standardized and
> handles issues like multiple photos. In addition there are confusing (to
> newcomers) issues like having to create/login to an additional account
> unrelated to OSM. And bandwidth issues requiring postponing uploads until
> WiFi is available. Until OSM has more clarity on this I don’t think it’s
> appropriate to break new ground in this area.
>


the "image" tags have been around for a very long time and are pretty
standard. Also images through wikidata would make a good complement. FWIW,
I would see these as additional data that is not so relevant for editing
software. People are expected to update objects based on their own
observation (and even more this seems the case for mobile editors). IMHO
you should not "fix" objects based on images you didn't take (if you do not
know the place), you don't know when they have been taken, from where they
have been taken.
