### ISSUE TITLE
Paste functionality (Again...)

### ISSUE THREAD

**Issue by zlavergne** [bryceco/GoMap#169]
After working on additional Copy functionality on the [Kaart Group Fork](https://github.com/KaartGroup/GoKaart/tree/kaart-dev), I revisited the paste functionalities. I think the original **Paste** feature should be modified to function more like JOSM's `Shift+R`. `Shift+R` adds all copied tags to the new object but keeps the tags that aren't replaced. It only replaces the  common tags between the objects:

Object A: 
``` 
name=Object A;
highway=residential;
surface=asphalt;
lanes=2;
```
Object B:
```
name=Object B;
highway=tertiary;
```
Object A (after pasting from Object B):
```
name=Object B;
highway=tertiary;
surface=asphalt;
lanes=2;
```

I think this is how the **Paste** feature should work and **Replace Tags** still works by replacing all tags.

**Comment by bryceco** [comment]
Yeah that seems reasonable.
