### ISSUE TITLE
Use presets from osmlab/name-suggestion-index

### ISSUE THREAD

**Issue by tas50** [bryceco/GoMap#171]
Hey there. I've been using this app for a long time and it's been a great help doing on the ground surveys so thanks for all the time you've put in. I was wondering if you'd ever consider using the presets from osmlab/name-suggestion-index project. That way when people were doing survey and they typed in a common store name they'd get a preset with all the correct tags. I think it would really help speed up local surveys and would increase the accuracy of data in OSM.

**Comment by bryceco** [comment]
Yes I agree that should be added.
