### ISSUE TITLE
Render "direction" for surveillance cameras

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#187]
> As a mapper, I want to see the FOV of surveillance cameras, so that I can check if those nodes are set up correctly.

## Background

I'm collecting data on surveillance cameras (for [Surveillance under Surveillance](https://kamba4.crux.uberspace.de/)). In order to make sure that the cameras are tagged correctly and can be rendered on the map, it would be helpful to see the field of view of the cameras.

## Example rendering

![camera-fov](https://user-images.githubusercontent.com/1681085/55686763-c5abb400-5954-11e9-868b-32f6550ba487.png)

## Open questions

- Do we need (or want to have) a setting/filter for this?

**Comment by bryceco** [comment]
Having a spotlight effect when the camera is selected would be great. I'm not sure about having displayed at all times. (The term FOV rather than direction is a little misleading since it implies knowing something about the camera optics doesn't it?)

**Comment by tordans** [comment]
Personally, I like **the design that iD uses** ([Example](http://preview.ideditor.com/master/#background=DigitalGlobe-Premium&disable_features=boundaries&map=19.84/52.51901/13.37613), Screenshot).

<img width="280" alt="Bildschirmfoto 2019-04-08 um 17 02 22" src="https://user-images.githubusercontent.com/111561/55734898-ab3f0c80-5a20-11e9-8184-0f883316bae7.png">


**My opinion on the setting/defaults:**
- On a selected node with `direction`: Always show the direction-indicator
- On all nodes with `direction`: Only show the direction-indicator, if a setting-flag is "on" (other than iD does it, which is always on)
  - This setting flag should be default:off
  - Since it is similar to "show unnamed roads errors" or "show Notes and Fixmes", the "Overlay"-Area of the Display settings seems a good place for it.
  - How about "Direction indicator (O__)"

**Comment by wtimme** [comment]
Thanks for the feedback!

## FOV

> The term FOV rather than direction is a little misleading since it implies knowing something about the camera optics doesn't it?

Yes, correct, I was using "FOV" for a lack of a better word.

If the tags
- `height`
- `camera:angle` and
- `direction`

are present, we could at least be able to roughly calculate the radius that the camera can see, and this is what I meant with "FOV". My idea is to roughly visualize which area the camera covers. Some are 360° cameras, while others are static and only surveil a fixed area. But when I think about it, we can also do this in a "V2". Let's MVP this!

## Introduce new setting

I like @tordans' idea with the setting. To be honest, I was a bit hesitant to create a new setting, since I fear that there's some effort involved in that, especially since they are "synced" across at least two view controllers.

## Appearance

Again, I like the suggestion from @tordans.

## Rendering

As for which elements to render this for, have a look at the [values for `direction`][1]. I suggest we render the direction if the value was either a **number** (0, 90, ...) or a **cardinal direction** (`NE`, `SW`, ...).

[1]: https://taginfo.openstreetmap.org/keys/direction#values

**Comment by bryceco** [comment]
As long as the spotlight icon is small and unobtrusive as it is in ID then I’d prefer to not have a setting at all. Just show it always.

**Comment by wtimme** [comment]
I've played around with the colors and tried to match those of the iD editor. Have a look:

![camera-direction-rendering](https://user-images.githubusercontent.com/1681085/55915205-a02edc80-5bd8-11e9-87f2-7b339a3b8bf7.png)

As you can see, some of the direction layers are covered. Is that the intended behaviour?

At the current state, the app renders the direction overlay if the data is available and if the tag `surveillance:type` was `camera`.

Should I go ahead and open a pull request?

**Comment by bryceco** [comment]
That looks great. Go ahead and create a pull.

**Comment by tordans** [comment]
> At the current state, the app renders the direction overlay if the data is available and if the tag surveillance:type was camera.

I don't see any harm in rendering any `direction` tag on any object. Eg I know mapper that map their benches with a direction. Or a swing. In both cases the direction-key is not part of the preset, but its a nice addition.

Also: It looks good, IMO. 
At some point nicer (and streamlined) icons where great, but not really important either :).

**Comment by wtimme** [comment]
I've changed it so that now for all nodes that have either the "direction" or the "camera:direction" tag set, the direction will be rendered. 👍  The PR is opened: #198
