### ISSUE TITLE
Set angle via compass

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#189]
This is more of a brainstorming based on https://github.com/bryceco/GoMap/pull/180 by @wtimme.

**The compass can also provide an angle. So how might we use this?**

- Taginfo shows only some cases for `*:angle` https://taginfo.openstreetmap.org/search?q=angle, mainly:
  - `roof:angle`, 10 288x
  - `camera:angle`, 4 020x
- `roof:angle=*`
  - Pro: Is used for numbers, as expected https://taginfo.openstreetmap.org/keys/roof%3Aangle#values
  - Con: Is only documented as a secondary solution beside `roof:height` https://wiki.openstreetmap.org/wiki/Simple_3D_buildings#Roof
  - Con: Most roofs are out of reach for a smartphone
- `camery:angle=*`
  - Pro: Is used for numbers, as expected https://taginfo.openstreetmap.org/keys/camera%3Aangle#values
  - Con: No wiki-page; not even a mention on the surveillance page https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurveillance
  - Con: Cameras are out of reach
- `incline=*`
  - Pro: Is used a lot – `incline`, 461 323x https://taginfo.openstreetmap.org/keys/incline#values
  - Pro: Until now, most only specified very roughly like "up" or "down", so this would help making the data more precise
  - Pro: Has a fairly good wiki doc https://wiki.openstreetmap.org/wiki/Key:incline
  - Pro: Other than the angle ideas above, I can actually reach a road with my smartphone :)
  - Con: Road are not perfectly straight, so the values need to be eyeballed to be an average
  - Con: Value is mostly used as %, not degree value, so some more code is required to transpose or add the °-sign
- ? other ideas

**Comment by wtimme** [comment]
Great write-up so far, thanks!

I did a little bit of technical research and found out that we can use [CoreMotion][1] to get the [pitch][2]. I've implemented a quick and dirty Swift class, and was able to get the values:

<img width="71" alt="screenshot-of-debug-log-output" src="https://user-images.githubusercontent.com/1681085/56612871-ee92a100-6604-11e9-96dc-d60ff776d5fe.png">

Most of the existing functionality that exists for the "direction" tag can be reused: the view controller, most parts of the view model, ... Maybe we can even refactor it a little bit to allow for an easier integration of device sensors, to make it easier to create new "measurement" screens.

As an MVP (and until #217 is sorted out), how do you suggest we integrate the new screen - only for `incline`?

> Value is mostly used as %, not degree value, so some more code is required to transpose or add the °-sign

The new screen could have a `UISwitch` or some similar control to toggle between `°` and `%`.

[1]: https://developer.apple.com/documentation/coremotion/getting_processed_device-motion_data
[2]: https://developer.apple.com/documentation/coremotion/getting_processed_device-motion_data/understanding_reference_frames_and_device_attitude#2875084
[3]:

**Comment by bryceco** [comment]
So far this feels like a solution in search of a problem. How many taginfo results are there with a numeric value?

Also the accuracy of measuring an incline is going to be a lot better if you use the camera to sight along the roof/road and then measure the angle.

**Comment by bryceco** [comment]
Won't fix
