### ISSUE TITLE
Fix address preset

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#195]
My understand is, that GoMap uses the presets by iD, involving a manual transformation to make them work with iOS.

To me it looks like the preset for address is broken.

Issue:
- I create a node
- Search for "address" as a preset
- Select "Address" (no icon)
- Bug: The "Type" field is empty, there are no special key/value pairs like with other presets

Expected:
The UI shows 
- Type "Address"
- And the address-block like it does with buildings=yes

This is the address preset in iD https://github.com/openstreetmap/iD/blob/master/data/presets/presets/address.json
(I don't quite get how this files plays into the setup https://github.com/openstreetmap/iD/blob/master/data/presets/fields/address.json.)

(Ping: https://github.com/bryceco/GoMap/issues/19)

**Comment by bryceco** [comment]
Yes, because selecting Address doesn’t create a key/value pair the way selecting other types does, so the machinery for populating the appropriate presets doesn’t get activated.

**Comment by tordans** [comment]
The way I read the last commit on the preset, what iD seems to do is: 
Whenever there is a node that does not match any preset but it has a "addr:*" part, the it is displayed as a preset address.
https://github.com/openstreetmap/iD/commit/7b9af48c4d42927620952548665d2f3bf57381f9

However, that only solves half the problem, right? I don't know enough about the code to help more :).
