### ISSUE TITLE
Cleanup default fields

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#196]
I suggest to cleanup the default fields that are available on the "common tags" panel all the time.

IMO they come from a time when the presets where not really that good. Now the presets do a better job.

My suggestion:
- `ele` > remove (would not know what to do with it …)
- `note` > keep (good default while on the go)
- `phone` > remove (part of the relevant presets)
- `website` > remove (part of the relevant presets)
- `wheelchair` > remove (part of the relevant presets)
- `wikipedia` > remove (nothing I can to while walking around)

**Comment by bryceco** [comment]
Yeah I agree

**Comment by wtimme** [comment]
So, to sum it up, the "Other" section should only consist of "Note". Correct?

Removing those other fields doesn't look difficult. In `CommonTagList.m`, there's an array:
```
NSArray * extras = @[ @"elevation", @"note", @"phone", @"website", @"wheelchair", @"wikipedia" ];
```

![remove-default-tags](https://user-images.githubusercontent.com/1681085/56037030-e6418880-5d1d-11e9-81c0-971d73b5625c.png)

**Comment by tordans** [comment]
I think, that is better than before, yes :-).
We could argue that the "other" section is now a UI smell, but IMO it's still the right next step.

**Comment by bryceco** [comment]
There is also the situation where the object isn’t a recognized feature: amenity=foo. In that case the existing list might be useful.

**Comment by bryceco** [comment]
After the latest iD presets pull I've deleted the "Other" section.
