### ISSUE TITLE
Automatic code formatter for Objective-C

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#201]
> As a developer, I want the Objective-C code to be automatically formatted, so that I don't have to care about it.

## Acceptance criterias
- The whole codebase should be formatted fully at least once (for a "clean slate")
- Developers who are changing the Objective-C files don't have do take any extra steps to have their new code automatically formatted

**Comment by wtimme** [comment]
On `wtimme/refactoring/201-Automatic-code-formatter-for-Objective-C`, I've added `clang-format` and manually executed the binary. You can see changes caused by the formatter in [commit `4e498f6`][1].

What are your thoughts, guys? @zlavergne, do you have input here?

If this is something that we want to integrate, the next step could be adding a "Run Script" build phase that automatically formats the Objective-C code during build.

[1]: https://github.com/wtimme/GoMap/commit/4e498f67f80dd2e632f7b67f1a03fa3530e2e790

**Comment by bryceco** [comment]
Obviously I’m a big fan of the way that it currently formatted :)

Is it possible for the formatter to more closely follow the existing style?

**Comment by wtimme** [comment]
Sure, there are a lot of [style options][1] available. All you need to do is put them in the `.clang-format` file on my branch, run the command (`./vendor/clang-format -i -style=file **/*.{h,m}`) and check the results.

Are there any formatting options that you are particular keen on keeping? That would help others and me to see if there were options to do so.

[1]: https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by bryceco** [comment]
Cool, at a minimum all the Align* options should be true, but I’ll play with the others when I get a chance.

**Comment by wtimme** [comment]
After playing around with the code a bit, I'd find it helpful if we used only a single space between a variable and the assignment.

```objc
_spatial = [QuadMap new];
```
instead of
```objc
_spatial        = [QuadMap new];
```

This would make it easier to search for assignments to the variable and helps when navigating around the code, as it can be found with the search term "_spatial =". With multiple spaces, I need to use a regular expression, which seems like a bit of an overhead.

What do you think?

**Comment by zlavergne** [comment]
> After playing around with the code a bit, I'd find it helpful if we used only a single space between a variable and the assignment.

I'm a fan of this type of formatting!

I think incorporating some standard formatter is a good idea in general for open sourced projects.

**Comment by wtimme** [comment]
Hey @bryceco, is there something I can do to further this? Were you able to play around with the options?

**Comment by bryceco** [comment]
6bcb1c6ec032e91fbf8d8112beafe1bc6e3f2464 adds a prototype format file

**Comment by bryceco** [comment]
Fixed via 85952f2a451c8a4d89435878e7f0efbb549e46f4
