### ISSUE TITLE
Add credit "© OpenStreetMap contributors"

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#204]
According to OpenStreetMap's [Copyright and License][1] page,

> We require that you use the credit “© OpenStreetMap contributors”.

They further suggest:

> For a browsable electronic map, the credit should appear in the corner of the map.

![Example of how to show the attribution](https://user-images.githubusercontent.com/1681085/56077502-91a91680-5dcc-11e9-81c2-9cafa16c0aa4.png)

[1]: https://www.openstreetmap.org/copyright

**Comment by bryceco** [comment]
Does any other editing software include this?

**Comment by tastrax** [comment]
Street Complete is a good example of an editing app that attributes correctly - https://play.google.com/store/apps/details?id=de.westnordost.streetcomplete&hl=en&gl=US
