### ISSUE TITLE
Tag releases with version and build number

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#214]
> As a developer without access to GoMap in iTunes Connect, I releases to be tagged, so that I can better identify issues or answer questions.

## Acceptance criterias

- "Version number" and "build number" are properly set up in the project's settings
- The build number that is incremented after the release was created
- Each release has a unique tag
- Tags are pushed to `bryceco/GoMap` so that they can be accessed by other developers

**Comment by bryceco** [comment]
iTunesconnect requires that the version number be incremented on every upload. Typically (unless I forget) I’ll push a commit just for the version increment. Is there a way to ensure a tag is created when the version changes?

**Comment by wtimme** [comment]
Yes, there are two: manually 😴 or using automation, e. g. [fastlane][1]. I could try to prepare a branch that you can test and add instructions on how to use it to the README for you to test. What do you think?

[1]: https://fastlane.tools/

**Comment by bryceco** [comment]
I went back and tagged the last year's releases. If I miss any going forward please ping me.
