### ISSUE TITLE
Create new setting "Show FPS label"

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#218]
> As a developer, I want to easily be able to enable the FPS label, so that I can debug performance issues with the rendering

## Acceptance criterias

- In the app's settings, under "Advanced", there is a new cell with the title "Show FPS label" and a UISwitch.
- The switch/setting is off (`false`) by default.
- When the setting is set to on (`true`), the map view displays a label that shows the current FPS of the map.
- The setting is stored in the `UserDefaults`, persisting across app restarts.

## Background

While discussing #205, @bryceco raised the topic of potential rendering issues that might be introduced with those changes. The code base already contains a mechanism to show a FPS label, but this "easer egg" was not known to everybody.

I suggest to add a proper new setting for this.

## Unhappy cases

The tech-unsavy user might not know what this setting does, or how to use it.

**Comment by bryceco** [comment]
I’d prefer to not add a feature with UI impact that is useful only to developers. Can we move this switch to the iOS Settings page or something where it’s essentially invisible?
