### ISSUE TITLE
"Check your surroundings"-Mode

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#222]
_As a mapper, I want to have my neighborhood mapped with detailed and up to date tagging. I want to easily review what is missing. I want to easily review if existing information is still up two date._

The idea: **A "check your surroundings"-mode.**

In general, this is the "this street is missing an name"-feature of GoMap, but for all kind of rules or attributes.

# I image scenarios like this

- In my hood, I want all the streets to have `width`-attributes (or `surface`, or `maxspeed`, …)
- In my hood, I want all the street-trees to have the right `ref`-attribute (this is where https://github.com/bryceco/GoMap/issues/124 comes from)
- In my hood, I want all the streets to have parking attributes (more at https://github.com/openstreetmap/iD/issues/6178 for details)

# What I do right now

I go for a walk with the app open, and click all kind of objects, go to the details, check the ref, surface, width – whatever I am focussing on – and review or add the data. This is very inefficient. Especially after you did this for a while. I always forget what place I already checked, so I re-check everything a lot. Or miss spots that I think I checked, but did not.

# Visualize + edit

In https://github.com/openstreetmap/iD/issues/6178 I show the example of the parking lane viewer which does something very simple, yet powerful: It has a dedicated visualization for a certain use case (different colors for streets show tagging values). Combined with a dedicated editing UI.

# Interface ideas

- There is a UI in the settings that allows me to activate what "check" I want to do
- There is/might be a UI on the map (at the top?) that allows me to change/toggle "checks" quickly
- There might be a UI to add new checks (future?)
- There might be dedicated editing UIs for the check (or just the presets at first)

Example for interface "Check `width`":
- Ways without a width are Red, indicate "todo"
- Ways with `width` show the with-values; as number; maybe as line-thickness?; …
- Other geometries might be softened; maybe non-editable?; …
- Tabbing a way directly show a dialogue with with values. Or the one edit tag-field with a keyboard.

**Comment by bryceco** [comment]
This sounds similar enough to #221 that they should be the same feature.

**Comment by tordans** [comment]
I think we can close this in favor of the other thread. See https://github.com/bryceco/GoMap/issues/221#issuecomment-487258622 for more.
