### ISSUE TITLE
Peek and Pop to quickly review object

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#223]
I wonder if it where easy to implement a "Peek and Pop" UI to "look into" object quickly, without opening the "all tags" view.

**UseCase:**
Basically, what I describe at https://github.com/bryceco/GoMap/issues/222. I go around my hood to check objects. Right now, that require a lot of tapping all over the screen (like "cancel" at the top-left of the screen, which is very hard to reach).

**Idea:**
1. I long-tab or 3d-tab an object.
2. A small UI shows up that shows all key-value-pairs.
3. From there I can flick to close or go into the edit-mode.

I think, this is the feature I am referring to https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/3d-touch/. However, it where great to have it for all devices (also non-3d-touch devices). Like instagram seems to have build it with a long-tab as replacement for 3d-tab https://www.reddit.com/r/apple/comments/40xc98/discussion_you_can_peek_and_pop_on_non3d_touch/?st=juqp4uaw&sh=1dda6b56.

Example: Instagram Peek-Window without 3D Touch
<img src="https://user-images.githubusercontent.com/111561/56470107-9744d300-6442-11e9-8d18-79452b0f99e1.jpg" width=200>

**Comment by tordans** [comment]
@wtimme this might be a nice UI for your review of surveillance cameras :).

**Comment by wtimme** [comment]
Sounds great, and should definitely be doable. My main concern with peek-pop is that it is a rather "hidden" feature that the user is only able to find through discovery, or by reading help/wiki articles.

As for the content that is being previewed, what would the user see? The list "all tags"? Or the "common tags"? Or a new "summary view" that we would need to create?

**Comment by tordans** [comment]
> As for the content that is being previewed, …

One cannot interact with those views, right / they are readonly? So it might be a new text-view. A table or a plain `key=value\n` list. Or the "all tags" panel.

In general, I think it should just show all tags for now. We will find out if other data (like changeset date" are important; right now I would say no.

**Comment by bryceco** [comment]
I think it should be similar to the hyperlink behavior in safari, where it initially shows a readonly view, but you can swipe up to switch to the editing view. 

The preview should show the feature type (e.g. Driveway) in bold, followed by the friendly formatted values (which is usually short, and will be localized) followed by the all-tags values.

**Comment by wtimme** [comment]
So what we need is to create a new view controller that displays the preview. When the gesture is being completed, that new view controller would be the one that was selected in the tab bar. This means that we'd have four view controllers in the tab bar:

- **Summary** _(title tbd)_
- Common Tags
- All tags
- Attributes

Do you guys have any idea on the layout of this new view controller, maybe screenshots from some existing app?

**Comment by bryceco** [comment]
I thought this would be a popover window, that was only displayed for as long as your finger was held down, and would disappear when you lifted your finger.

 We already have a long press gesture so I’m not sure how that fits in.

**Comment by wtimme** [comment]
Peek-and-pop displays a popover, yes, but then it allows the user to "commit" the gesture by 3D-(hard)-tapping again, presenting the view controller fullscreen. You can see this for yourself with your device in "Photos", in a photo stream.

**Comment by bryceco** [comment]
I was assuming that when you commit it would take you to the editing view. 

I don’t like having an extra tab just for a static display. If we must have a static tab I’d prefer it to be modal with an Edit button that would take you to the editing window.

**Comment by tordans** [comment]
I thought it would work like this. Similar to the screenshot from instagram above.

<img width="775" alt="Bildschirmfoto 2019-05-12 um 10 19 15" src="https://user-images.githubusercontent.com/111561/57579646-7d296e00-749f-11e9-8914-44a21f159ae1.png">

The arrows are a bit missleading, since the action is not the tab but the hard press (3d touch) or long press (non-3d-touch).

To edit this "wireframe": https://docs.google.com/presentation/d/1N0DOVANKTgVB7BLZgOEuGWdUHOch9sRxC_32PxBjqNs/edit#slide=id.g5a005b17c2_0_2

**Comment by wtimme** [comment]
I've implemented Peek and Pop in a feature branch. For now, it is limited to `OsmNode`s, and I haven't tested it on pre-iOS 13 devices.

![peek-pop-tags](https://user-images.githubusercontent.com/1681085/76571790-443b9a80-64b0-11ea-906c-7faf3a6f3a2f.PNG)

For the preview, it _always_ shows the "All tags" view, while hiding the tab bar and the navigation bar. When committing the preview (= 3D touch again), the `POITabBarController` is presented modally, as if the mapper had tapped "Tags", with "All tags" still selected.
When tapping "Cancel", the mapper lands back on the map with the object selected.

Is that an addition that it is already of use to you, @tordans? If so, I would go ahead and create a pull request, so that we have a V1 that is ready for feedback.

**Comment by tordans** [comment]
This sounds great and will help reviewing objects while walking a lot. 

ATM its only working with force touch, right? Did Apple build a native fallback, yet, for iPhone Xʀ and such? Or, is there a workaround?

**Comment by wtimme** [comment]
Thanks for the feedback! I‘ve only tested this on an iPhone X running iOS 13.3.1.

Is someone able to get their hands on a test device?

**Comment by tordans** [comment]
I checked it out on a ForceTouch iPhone.

Here is a video: https://www.dropbox.com/s/hf6lb1q4reywyxq/peek-gomap-RPReplay_Final1584118055.MP4?dl=0
At first, I try selecting the tree in the middle, later other elements.

After testing it a little bit, I am sorry to say, I am not sure this feature is a good idea. The interaction collides strongly with the "long press to choose layered or surrounding elements"-feature. ATM, I don't think both feature can coexist. At least I dont see how.
