### ISSUE TITLE
Direction Testcases

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#228]
I create this issue to have a place to collect a few testcases for the upcomming direction feature.  

My goal: Get a feeling for how accurate the iOS compass direction is compared to what I would add manually.

All test flight users: Please add your experience as well.

**Comment by tordans** [comment]
Case:
Billboard was manually set to direction=15. When I walked the street, the compass showed something quite higher (maybe 30?). I did not take a screenshot or check it in detail, it's just my first, rough observation.

<img width="640" alt="Bildschirmfoto 2019-04-27 um 07 11 01" src="https://user-images.githubusercontent.com/111561/56845080-d1d3c300-68bb-11e9-88fd-5f4c9b47d6bf.png">

https://www.openstreetmap.org/edit#map=19/52.47637/13.44767

**Comment by wtimme** [comment]
Thanks for the report!

Indeed, when collecting directions, I also noticed that the accuracy is not always optimal. I was even able to further degrade the measurement by shaking the device around randomly, very fast. The values would just increase, even if the device layed still on a flat surface.

My initial suspicion was that there's something wrong with the way we measure, but I was also able to reproduce these measurements in Apple's Compass.app.

Is someone able to verify my observations?

**Comment by tordans** [comment]
I tested it on the cameras near https://www.openstreetmap.org/changeset/69827549

The direction was good. Its not easy to really find the right direction of an object that is high up, like a camera. But its better than having no indication at all.

Right now, the testflight version does not have the direction indicator, yet. I am sure once that is in place, it will be easier to check on sight if the direction is off or not.

--- 

Thinking further on the last sentence: Should this feature really get used a lot, the "set direction" UI could be improved by showing a version of the map with the node in question and with the direction indicator on it. The compass becomes more of an "provide a number by moving your phone" UI, than a "take the realworld number and trust it blindly" UI.


--- 

I suggest to keep this issue open until the release in case we have new test cases.
