### ISSUE TITLE
Quest: Use Mapillary object recognition to add map data

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#229]
This is an idea for https://github.com/bryceco/GoMap/issues/221.

The Mapillary SDK allows to filter for object types (like `object--mailbox` or `object--cctv-camera` and such via the API.

**The idea:** 
Use this data for the quest feature. The user sees a "hotspot" of the type "mailbox" with the question: 
> Mapillary believes there is a mailbox here. {Add mailbox} {Don't see any}
Which leads to the tag-preset for mailbox.

The quest would also check if the map already has a mailbox nearby, to hide the questions if present.

**Some further reading**

- The app https://pic4review.pavie.info uses this setup AFAIK. You get to see pics of places where Mapillary believes to see bike parking. Once you approve/confirm, the app adds the bike parking tagging automatically.

- Mapillary API for object detection https://www.mapillary.com/developer/api-documentation/#object-detection-layers

- Detected "Segmentations" https://www.mapillary.com/developer/api-documentation/#segmentations
 This seems to be the data that is most feasible for this kind of quest since they are point objects. A few examples that I find interesting

> object--banner
object--bench
object--bike-rack
object--billboard
object--cctv-camera
object--fire-hydrant
object--mailbox
object--parking-meter
object--phone-booth
object--street-light
object--trash-can

- Detected Signs https://www.mapillary.com/developer/api-documentation/#warning and detected lines objects https://www.mapillary.com/developer/api-documentation/#lines
I dont think this those detections are really helpful for such quest, even though they are the longest list. Main reason is, they are hard to add to the OSM data. Most need to be interpreted and then applied to the street-ways in various ways. We could use the for street-sign-points, but those are IMO not very interesting OSM data.

**Comment by bryceco** [comment]
While this is an interesting idea, the quest feature itself still seems to be a long way off so I'm closing this for now.
