### ISSUE TITLE
Need GPX track option

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#23]
Need an option for creating/uploading GPX tracks

**Comment by bryceco** [comment]
My approach for GPX is going to be pretty simplistic: 
* Any time the GPS is active I'm recording a corresponding GPX track
* A GPX overlay toggle will display all GPXs on the map so they can be traced as ways. 
* A list of tracks sorted by creation date and duration will allow uploading to OSM (or other sharing). 
* Selecting a GPX in another app (Safari) will provide an "open in Go Map!!" option and save the track alongside the user generated tracks 
* GPX data will be deleted automatically after a certain amount of time (7 days?) so it doesn't grow indefinitely
* There is UI for deleting all tracks, or tracks individually

This eliminates the start/stop/name interaction at the cost of naming.

**Comment by DerKarlos** [comment]
Auto delete may be a bit unfriendly without an OK from the user.
You may ask for delete  when gomap!! is startet/once per day.
If the size of all tracks is below a limit, no delete is needed anyway

There some ideas (always):
If the track is next to a known way, it could "snap in"
A track (-part) with a lot of GPS-Points, could be "softened" and convertet do a new way.

**Comment by bryceco** [comment]
I've changed it to make the delete time configurable. The goal is for the GPX tracks to not bog down the app even for people who are unaware of the feature, so the default will still be 7 days.

**Comment by bryceco** [comment]
Now available
