### ISSUE TITLE
Compressed changeset upload

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#231]
Does this https://github.com/openstreetmap/iD/issues/6231 make sense for GoMap as well and does iOS have an easy way to support something like this?

Otherwise, please close again :-).

**Comment by bryceco** [comment]
My understanding for downloaded content is that iOS automatically requests gzipped data transparently. I assumed (but don’t know for certain) the same is true for uploading?

**Comment by mmd-osm** [comment]
Most frameworks won't automatically compress the payload of an HTTP POST requests, so this won't happen transparently (unlike the download case).

Also see: https://github.com/openstreetmap/operations/issues/193#issuecomment-359249157 re. fallback to uncompressed upload in case of 415 Unsupported Media Type.
