### ISSUE TITLE
Ongoing Dev

### ISSUE THREAD

**Issue by zlavergne** [bryceco/GoMap#234]
#178 & #165 both allow for Swift to be built and developed as part of the project.

Should new features be built in Swift or Obj-C or dealer's choice?

Just want to know before I start working on my next big features (issues coming soon).

cc: @wtimme @bryceco

**Comment by bryceco** [comment]
Either is fine.

**Comment by wtimme** [comment]
I recommend to use Swift, but technically, both is of course possible.

**Comment by zlavergne** [comment]
I know both are possible but I wanted to make sure that the whole project wasn't trying to move towards Swift. I don't really have a preference. Just want to be consistent and in line with everyone 😄
