### ISSUE TITLE
A proper logo for GoMap!! ?

### ISSUE THREAD

**Issue by Binnette** [bryceco/GoMap#236]
Hi,

On page https://apps.apple.com/app/id592990211, I saw that GoMap!! use the default OpenStreetMap logo.

Does it exist an "official" GoMap logo ?

If no, i can attempt to draw one in SVG format if you want 😉

**Comment by Binnette** [comment]
So, here is my first "Go Map!!" logo attempt ✏️
Let me know what do you think about it.
400px:
![GoMap](https://user-images.githubusercontent.com/6597721/72225242-63d34700-3583-11ea-9fb6-9e4b3d62f749.png)
100px:
![GoMap100](https://user-images.githubusercontent.com/6597721/72225267-a5fc8880-3583-11ea-91d7-e30ef29ac50c.png)
SVG File (must be renamed to svg): [GoMap.svg.txt](https://github.com/bryceco/GoMap/files/4051395/GoMap.svg.txt)

**Comment by bryceco** [comment]
This is pretty clever and interesting. What’s the thinking for the red parts? It takes a moment to recognize the !!, and once I do then it’s not clear what the second “grain silo” is. 

The one thing that I’m trying to encourage with the app (hence the name) is the outdoor, dynamic aspect of mapping. Go outside and map! I would love if the logo did something to reflect that emphasis. Any ideas?

**Comment by DerKarlos** [comment]
The !! as running legs?  :-)

**Comment by Binnette** [comment]
Hi @bryceco, thank for your answer. Do you have any requirements?

1. Prefered color? blue? green? red? yellow?
1. Prefered elements? a map? a runner? a magnifying glass?
1. Prefered icon shape? square? square with rounded corners? a circle? (i do not have an iPhone, so i'm not familiar with "iOS friendly" app icons)

All ideas and advices are very welcome 😉 (I'm a developper and not a logo designer 😋)

**Comment by Binnette** [comment]
Here is my 2nd "design":
![GoMap](https://user-images.githubusercontent.com/6597721/72478729-f4fc2500-37f2-11ea-835f-a32c63a3ca27.png)

100px:
![GoMap100](https://user-images.githubusercontent.com/6597721/72478743-fcbbc980-37f2-11ea-84b3-f161669d90c0.png)

My SVG: [Go.svg.txt](https://github.com/bryceco/GoMap/files/4067987/Go.svg.txt)

**Comment by Binnette** [comment]
A 3rd design:
![GoMap](https://user-images.githubusercontent.com/6597721/72554245-912d3700-389a-11ea-8578-4cffaf00ca1b.png)

100px:
![GoMap100](https://user-images.githubusercontent.com/6597721/72554261-98544500-389a-11ea-8858-edbeec824c1b.png)

SVG: [Go.svg.txt](https://github.com/bryceco/GoMap/files/4073206/Go.svg.txt)

**Comment by bryceco** [comment]
These are also interesting. Since the name of the app is below the icon anyhow it isn’t necessary for the icon to contain text if that makes it easier. I think #3 is my favorite so far.

**Comment by dieterdreist** [comment]
As a hint, you should also take account of the corner radius, because the
corners will be cut off.
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/

**Comment by patricks** [comment]
I also like the 3rd design. Maybe we can get rid of the Go text in the logo. I think it would scale better in the many different sizes and as mentioned the app name stands under the icon.

**Comment by Binnette** [comment]
This time, i tried to be more "iOS" friendly.

Design 4:
![GoMap-400px](https://user-images.githubusercontent.com/6597721/75584496-244bb600-5a70-11ea-814c-4ad716a8778d.png)

![GoMap-100px](https://user-images.githubusercontent.com/6597721/75584533-3e859400-5a70-11ea-9f49-e5984adc72c5.png)

SVG: [go.svg.txt](https://github.com/bryceco/GoMap/files/4268983/go.svg.txt)

**Comment by patricks** [comment]
That’s definitely the best one. 👏

**Comment by Binnette** [comment]
Let's add some colors:

![multi](https://user-images.githubusercontent.com/6597721/75605006-e6d24180-5ade-11ea-9451-91184161f863.png)


I put numbers 4.1, 4.2, 4.3, ... so you can vote for you fav one :+1:

**Comment by patricks** [comment]
My fav is 4.10 nice work!

**Comment by DerKarlos** [comment]
I like 4.5 and 4.10 too.

**Comment by tordans** [comment]
I like 4.5 best (4.10 good as well)

---

A few other thoughts – not that those should stop us from using one of the above, since they are already gerat compared to the status quo.

- how could the icon design be used inside the app, so the style gets picked up again somewhere?
- is there a way to use the last design and give it a bit more nudge towards the OSM logo? 
![image](https://user-images.githubusercontent.com/111561/75624553-94178900-5bb5-11ea-9793-13bbd00bac3e.png)
  - maybe by trying to abstract the green+blue areas + red line to the new design? maybe only the top left area of the osm-logo?
  - maybe the folding-style could be part of the nudge towards the osm logo; in an abstract form?

**Comment by Binnette** [comment]
Hi @tordans, I am open to any suggestions :+1: Let's add the OSM map logo then.

Design 5:
![design5](https://user-images.githubusercontent.com/6597721/75625935-18bcd400-5bc3-11ea-827e-645a0b8de903.png)

![design5-100px](https://user-images.githubusercontent.com/6597721/75625936-19556a80-5bc3-11ea-8ac6-bed7aee3505f.png)

I tried to put the magnifying glass but it is too messy for a tiny icon like that...

**Comment by patricks** [comment]
I like version 4.x more

**Comment by wtimme** [comment]
For updating the app icon for all sizes, [fastlane-plugin-appicon][1] works pretty well.

The app icon is based on the 1024x1024 PNG file in `fastlane/metadata/app_icon.png`. After changing this "master" app icon, we can re-generate the app icons using the fastlane plugin "appicon" like so:

    % bundle exec fastlane regenerate_app_icon

Should I prepare a branch and setup fastlane and the plugin? Then everybody could try icons in the Simulator.

[1]: https://github.com/fastlane-community/fastlane-plugin-appicon

**Comment by wtimme** [comment]
Can someone provide a 1024x1024 PNG file of the logo?

**Comment by TheAdventurer64** [comment]
..and we still don’t have a proper logo. Oof.

**Comment by wtimme** [comment]
@Binnette, could you provide the images as 1024x1024 px versions? Looks like 4.5 and 4.10 are the favorites so far.

Thanks a lot in advance! Good job on the app icon designs. 💪🏼

**Comment by TheAdventurer64** [comment]
With the new logo, will there be a color revamp to Go Map!!?

**Comment by TheAdventurer64** [comment]
> This time, i tried to be more "iOS" friendly.
> 
> Design 4:
> ![GoMap-100px](https://user-images.githubusercontent.com/6597721/75584533-3e859400-5a70-11ea-9f49-e5984adc72c5.png)
> 
> SVG: [go.svg.txt](https://github.com/bryceco/GoMap/files/4268983/go.svg.txt)

That looks like a logo that Go Map!! could’ve used when it first released back in 2012. Dislike.

**Comment by Binnette** [comment]
Hi @wtimme, sorry for the delay. Here are the asked 1024px logo :wink: 

- 4.5 
![1024px-logo4.5](https://user-images.githubusercontent.com/6597721/88900869-55fbbf80-d250-11ea-8315-a3488529d352.png)

- 4.10
![1024px-logo4.10](https://user-images.githubusercontent.com/6597721/88900874-572cec80-d250-11ea-805f-0cb05c70a509.png)

My SVG files:
[4.5.svg.txt](https://github.com/bryceco/GoMap/files/5000016/4.5.svg.txt)
[4.10.svg.txt](https://github.com/bryceco/GoMap/files/5000017/4.10.svg.txt)

BTW, feel free to publish those 4 joined files (2 png+2 svg) with any "open source" friendly license. If possible, write somewhere that i am the author and why not add a link to my [GitHub Profile](https://github.com/Binnette). That way if other people are interested by any of my icons, i can draw new icon for them or give them right to use any of it.

Thank you & have a nice day :wink:

**Comment by Binnette** [comment]
Oh! May be, you want it without the background?!? I do not know exactly how iOS works for icons. Here there are if needed:

- 4.5
![1024px-nobak-logo4 5](https://user-images.githubusercontent.com/6597721/88902385-6a40bc00-d252-11ea-973a-af03ea638749.png)

- 4.10
![1024px-nobak-logo4 10](https://user-images.githubusercontent.com/6597721/88902394-6e6cd980-d252-11ea-8871-dd91b4a4ff41.png)

**Comment by wtimme** [comment]
Awesome, thanks a lot! I'm not in reach of my MacBook right now, but I'll see to it once I am.

As described above, I suggest we use a fastlane plugin, since it'll make it very, _very_ easy to change the app icon once setup. If someone wants to go ahead in the meantime, feel free. 👍🏼

@bryceco, since you'll be having the final saying in this, do you have any objections, or are pull requests welcome?

We should probably update other places in which the (current) GoMap logo is being used, such as the wiki. Do you have ideas of where else we need to do so?

**Comment by dieterdreist** [comment]
sent from a phone

> On 30. Jul 2020, at 10:51, Binnette <notifications@github.com> wrote:
> 
> Oh! May be, you want it without the background?!?


the background is required, no transparency in app icons. 
My preference is for the 4.5

**Comment by Binnette** [comment]
Hi @dieterdreist TY for your remarks 👍 Do I need to "round" the edges of my icons myself ? Or should I provide a full square shape with plain background with "no transparency"? (as you said in your comment)

**Comment by dieterdreist** [comment]
Am Do., 30. Juli 2020 um 12:31 Uhr schrieb Binnette <
notifications@github.com>:

> Hi @dieterdreist <https://github.com/dieterdreist> TY for your remarks 👍
> Do I need to "round" the edges of my icons myself ? Or should I provide a
> full square shape with plain background with "no transparency"? (as you
> said in your comment)
>


you should not provide rounded corners. It is done automatically. The
biggest required size is 1024x1024, if you do not want to provide different
versions you can get all required images by downsizing this "original"
image. Maybe it could make sense to have all icons the same, but provide a
more detailed 1024x1024 image, as this is what is used on the app store to
promote the app (it is not a requirement, just an observation that some
publishers do it).

All sizes can be seen here:
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/

some sizes are the same, e.g. 60@2x (iPhone app icon) and 40@3x (iPhone
spotlight)

**Comment by wtimme** [comment]
> there are many (also free I believe) tools that do it for you

Not trying to push for it, but I've had good results with the [appicon](https://github.com/fastlane-community/fastlane-plugin-appicon) plugin for fastlane.

The plugin also puts the resized images in an asset catalog, making it a more-or-less one step process, once set up.

**Comment by wtimme** [comment]
I've created a new fastlane lane called `regenerate_app_icon`. That allows for an easy modification of the icon: Just replace the 1024x1024 px master file in `fastlane/metadata/app_icon.png` with any new icon, and run `bundle exec fastlane regenerate_app_icon` - that's it.

For my branch, I picked version 4.10. Take a look:
<img width="414" alt="go-map-logo-4 10" src="https://user-images.githubusercontent.com/1681085/89177599-202a4400-d58c-11ea-885c-0bd5e7a84402.png">

As for the attribution, I've added a new "Assets" section to the README.md, and also mentioned @Binnette in the commit message.

Let me know what you think. I'm happy to create a PR.

**Comment by dieterdreist** [comment]
btw: I know it is slightly offtopic, do you know if there is there a way to use this icon from another app without adding it there, provided the user has installed the app? I am working on a little OpenStreetMap based app where I offer an “open with GoMap!!” action, and for consistency it would be nice if the icon would update automatically when GoMap!! changes it.

**Comment by wtimme** [comment]
> is there a way to use this icon from another app without adding it there, provided the user has installed the app?

No, as far as I know, you can neither check whether another app is installed nor can you use its app icon in your own app.

**Comment by dieterdreist** [comment]
sent from a phone

> On 3. Aug 2020, at 14:06, wtimme <notifications@github.com> wrote:
> 
> No, as far as I know, you can neither check whether another app is installed nor can you use its app icon in your own app.


you can check „canOpenURL“ and give it a gomap url

**Comment by bryceco** [comment]
Your app can download and store the Go Map!! icon from this GitHub repository.

**Comment by bryceco** [comment]
I’m pretty happy with this icon, but I wonder if we couldn’t expand the overall size of the “map” to fill more of the dark area. I feel like we’re not full utilizing the (tiny) space we’re allocated.

**Comment by dieterdreist** [comment]
design is an area with no absolute rights and wrongs, and you can find arguments for any decision.
For me the current border spacing looks ok, also compared with other app icons.
As the map is fully contained (as opposed to partially visible and cut at the border/s), I believe there should be some margin to all borders

**Comment by bryceco** [comment]
That’s a reasonable point and you may be right. 

Looking at other icons that don’t “fill the space” and make use of a background color: Calculator and Contacts have a flat gray color, but lighter colored than what we have. Camera and Settings use a lighter gray plus gradient. 

The 3-D perspective in the icon is something I don’t see in any other app icon on my phone. It sets it apart (which is great) but it’s also responsible for the amount of empty space. Do you think adding a gradient would make it more interesting?

**Comment by pqhf5kd** [comment]
>Do you think adding a gradient would make it more interesting?

It also has a small gradient, see #404

**Comment by bryceco** [comment]
I'm happy with what was committed in bfcd13e6e77c0a404604ef762f325ec27729193f
