### ISSUE TITLE
Ability to set changeset source tag

### ISSUE THREAD

**Issue by AndrewKvalheim** [bryceco/GoMap#239]
I noticed that in [OSM Changeset Analyzer][osmcha] the changeset [`source`][source] tag is prominently displayed:

> <a href="https://osmcha.mapbox.com/changesets/76009606?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Go%20Map%21%21%22%2C%22value%22%3A%22Go%20Map%21%21%22%7D%5D%7D"><img src="https://user-images.githubusercontent.com/1844746/67232636-9c390e00-f3f6-11e9-8d5b-81858939662a.png" alt="OSM Changeset Analyzer - Editor: Go Map!! 1.6.1" width="416" height="188" /></a>

It would be useful to be able to set it to e.g. `survey` when submitting from Go Map!!.

  [osmcha]: https://osmcha.mapbox.com/
  [source]: https://wiki.openstreetmap.org/wiki/Key:source

**Comment by n76** [comment]
+1 to this issue. I think it is really important to be able to specify the sources used on edits.
