### ISSUE TITLE
Heads up: Maxar implementing new anti-scraping techniques

### ISSUE THREAD

**Issue by grischard** [bryceco/GoMap#242]
https://www.openstreetmap.org/user/@kevin_bullock/diary/391652

**Comment by LucasLarson** [comment]
Fortunately, GoMap uses @osmlab’s [editor-layer-index](https://github.com/osmlab/editor-layer-index), and automatically updates the “Additional Imagery Sources” [every 7 days](https://github.com/bryceco/GoMap/blob/3fc1e0d170a625416caf1290fbecd9d0ab8ac937/src/Shared/AerialList.m#L541-L544).

This issue should be closed.

**Comment by grischard** [comment]
I know, I'm one of the ELI maintainers :).

GoMap will probably need to implement new authentication mechanisms to access Maxar imagery, and should be involved in the conversation so that we have a solution that works for all editors.

**Comment by LucasLarson** [comment]
Oooh. Sorry. This issue should **not** be closed et je m’excuse.

Has Maxar described what their authentication will look like yet? If it’s unique keys, would the easiest, quickest implementation for GoMap be providing an incomplete layer URI and forcing the user to add their own key?

**Comment by grischard** [comment]
No description from Maxar, or any dialogue that I'm aware of.

I'd like to see something like https://github.com/osmlab/editor-layer-index/pull/548 where an anonymous user-specific api token can be transparently retrieved by the editor.

**Comment by zlavergne** [comment]
Maxar was just re-released in iD and JOSM. We will need similar AES encryption/decryption that iD used. We can use openstreetmap/iD#7355 as a template.

**Comment by bryceco** [comment]
It sounds like we will also need to get our own connect ID from Maxar?

**Comment by grischard** [comment]
@bryceco yes. Maxar also requests that this new API key isn't included in the source code or layer index. Are you on one of the OSM chat channels? Can you and @bhousel and/or @don-vip maybe talk?

**Comment by zlavergne** [comment]
My preference is to encrypt it in the source similar to to iD. Since there are a bunch of use cases where user of Go Map!! could have unreliable or spotty bandwidth (or none at all), I'm inclined to try and avoid additional requests. Being able to provide an offline solution is generally my preference for mobile design.

**Comment by grischard** [comment]
Would people still want to access Maxar imagery if they have no bandwidth?

**Comment by bryceco** [comment]
I'm in touch with Maxar and will add the appropriate code this week.

**Comment by bryceco** [comment]
Fixed in 1af2da2faf321dac739a1b2693b4d96261d6b3a3
