### ISSUE TITLE
Display wms

### ISSUE THREAD

**Issue by CaptainInler** [bryceco/GoMap#243]
Hi Everyone.
I'd like to load this WMS: "Kanton Zurich, Orthofoto ZH Sommer 2018 RGB 10cm" as my Background Areal-Image. This has worked in the past for quite some time but somehow the Tiles are not displayed anymore for some months now. Right now there are only white Tiles loaded.
Here is the [GetCapabilities](https://wms.zh.ch/OGDOrthoZH?SERVICE=WMS&Request=GetCapabilities) of this Service.

I tried to figure out what could cause the error but was not sucessfull..
This is what I've done so far:
1. I copied the URL
`https://wms.zh.ch/OGDOrthoZH?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=ortho&FORMAT=image/jpeg&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}`
and defined a "User-Defined Imagery". This did not display any Tiles but a message:
![2020-01-01 15-02-34-1](https://user-images.githubusercontent.com/16583617/71642404-c76b9380-2caa-11ea-98c1-d2312c6ce641.PNG)

2. I tried a GetMap-Request for the 2018 Images so figure out if the service is running:
[https://wms.zh.ch/OGDOrthoZH?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=ortho&FORMAT=image/jpeg&CRS=EPSG:2056&WIDTH=800&HEIGHT=600&BBOX=2680000,1243000,2696931,1255698](https://wms.zh.ch/OGDOrthoZH?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=ortho&FORMAT=image/jpeg&CRS=EPSG:2056&WIDTH=800&HEIGHT=600&BBOX=2680000,1243000,2696931,1255698)
So it is running.
I defined exactly this URL as a "User-Defined Imagery" to figure out if there is a problem with the parameters. This gets displayed:
![2020-01-01 15-02-34-1](https://user-images.githubusercontent.com/16583617/71642447-92137580-2cab-11ea-84c3-73811e81af85.png)
This lets me guess there might be a Problem with one or all of the variables of {proj}, {bbox}, {width} or {height}. But I was not able to tell if this is the case by replacing some with values. As soon as there is a variable present I get the xml-message from the first printscreen.

3. To figure out if other layers work well as "User-Defined Imagery" I defined "City of Zürich Orthophoto 2011" as a "User-Defined Imagery". This works without any problems. Here an Example of a GetMap-Request for this Layer: [Orthophoto 2011](https://www.gis.stadt-zuerich.ch/maps/services/wms/WMS-ZH-STZH-OGD/MapServer/WmsServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=Luftbild_2011&STYLES=&SRS=2056&WIDTH=800&HEIGHT=600&BBOX=2680000,1243000,2696931,1255698)
According to the [GetCapabilities](https://www.gis.stadt-zuerich.ch/maps/services/wms/WMS-ZH-STZH-OGD/MapServer/WmsServer?SERVICE=WMS&Request=GetCapabilities) there is also a Layer with Images from 2013 called "Luftbild_2013". Here a [GetMap-Request for the 2013-Images](https://www.gis.stadt-zuerich.ch/maps/services/wms/WMS-ZH-STZH-OGD/MapServer/WmsServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=Luftbild_2013&STYLES=&SRS=2056&WIDTH=800&HEIGHT=600&BBOX=2680000,1243000,2696931,1255698)
The difference between the 2011 and 2013 is only the Parameter `LAYERS=Luftbild_2011` or `LAYERS=Luftbild_2013` but Interestingly the 2013-Images won't be Display in Go Map. I only see a yellow wheel telling me somethings is being loaded but nothing happens further..

- Is there in generall a Problem with "User-Defined Imagery"?
- Can anybody help me to get  Orthofoto ZH Sommer 2018 running in Go Map?

Thanks

**Comment by bryceco** [comment]
For user defined URLs only the X, Y, Z and U (bing-style) placeholders are supported. You’ll have to find a URL in that format for it to work.

**Comment by CaptainInler** [comment]
Ah, good to know. thanks for your reply.
Is there any chance you can help me with the predefined Imagery of "CH / Kanton Zurich, Orthofoto ZH Sommer 2018 RGB 10cm"? Is there something wrong with the definition on [https://osmlab.github.io/editor-layer-index/](https://osmlab.github.io/editor-layer-index/)?
I can't see any differences e.g. in the parameters to "CH / City of Zürich Orthophoto 2011" which is working..

**Comment by tordans** [comment]
@CaptainInler the EditorLayerIndex supports WMS and TMS. But GoMap only supports TMS (iD Editor's external Data source as well). As far as I see it, https://github.com/osmlab/editor-layer-index/blob/12b5649ca1d72273964c7121889a3c284a48c6bd/sources/europe/ch/Kanton_Zurich_ortho_2018_wms.geojson?short_path=113e0fc uses WMS.

So it looks to me, that you will only be able to use the layer once the editor layer index is refreshed in GoMap. You cannot use it via the "user defined imagery".

But since https://github.com/bryceco/GoMap/issues/118#issuecomment-386091928 is in place, the app should download the new layer automatically.

**Comment by CaptainInler** [comment]
@tordans thanks for your clarification :+1:
you are right [CH / Kanton Zurich, Orthofoto ZH Sommer 2018 RGB 10cm](https://github.com/osmlab/editor-layer-index/blob/12b5649ca1d72273964c7121889a3c284a48c6bd/sources/europe/ch/Kanton_Zurich_ortho_2018_wms.geojson?short_path=113e0fc) is unfortunately only a WMS and not available as a TMS and therefore not useable as an "user defined imagery". But it is already listed at the editor layer index since April 2019. And I'm pretty sure this and all other Layer from Kanton Zurich e.g. [CH / Kanton Zurich, Orthofoto ZH Frühjahr 2015/16 RGB 10cm](https://github.com/osmlab/editor-layer-index/blob/12b5649ca1d72273964c7121889a3c284a48c6bd/sources/europe/ch/Kanton_Zurich_ortho_2015_wms.geojson) layer did work for some time in GoMap but for all of them I get now only empty tiles..
Can you please check if you get some tiles from this service with GoMap? Maybe there is something wrong with my device or app-installation.. :man_shrugging:

**Comment by bryceco** [comment]
You can also check the github history for the layer index and see if was changed recently.

**Comment by CaptainInler** [comment]
It did not change since May 2019.. @bryceco: is it working on your device?

**Comment by bryceco** [comment]
It doesn't work on my device, and I wouldn't expect it to.

**Comment by CaptainInler** [comment]
I‘m really sorry but I don‘t understand at all. Why don‘t you expect it to work? Because it is a wms rather then a tms?
If this is the case, why does following wms work?
https://github.com/osmlab/editor-layer-index/blob/12b5649ca1d72273964c7121889a3c284a48c6bd/sources/europe/ch/CityofZrichOrthophoto2011.geojson
Isn‘t the structure just the same?

Thank you for your patience 🙌

**Comment by tordans** [comment]
I @CaptainInler I don't see the layer with the name "City of Zürich Orthophoto 2011" either when looking at the area of Zürich. I think to understand whats going on, we need something like https://github.com/bryceco/GoMap/issues/249.

**Comment by CaptainInler** [comment]
@tordans: thats interessting. This is the list I see: 
<img width="500" alt="List Arealimages" src="https://user-images.githubusercontent.com/16583617/72224070-80b54d80-3576-11ea-82c6-4febe30234ed.png">

This is pretty much the list on Editor Layer Index
<img width="400" alt="Editor Layer Index List ZH" src="https://user-images.githubusercontent.com/16583617/72224198-cd4d5880-3577-11ea-9d65-76a0bed5d689.png">

I also see the 2011 Berlin WMS when moving the map there.

Question: Don't you think the tiles of "CH / Kanton Zurich, Orthofoto ZH Sommer 2018 RGB 10cm" get no requested right? I see white tiles get loaded. Isn't this a different case as when nothing is loaded. It would be interessting to debug this. Maybe the request url gets wrong concatinated and then the tiles wrong requested. Unfortunately I'm not a iOS-App developer (yet :smile: )

**Comment by bryceco** [comment]
I'm closing this for now. If we can get a side-by-side setup where a URL works in iD but doesn't work in Go Map!! then I'll reopen and investigate.

**Comment by CaptainInler** [comment]
I'm realy sorry to bother you. If you need a side-by-side check, I have one for you.
iD:
![grafik](https://user-images.githubusercontent.com/16583617/80141392-c6d47100-85a9-11ea-8914-73f6289f9612.png)

GoMap!!:
![grafik](https://user-images.githubusercontent.com/16583617/80143707-85de5b80-85ad-11ea-823c-ed970a98683e.png)

**Comment by bryceco** [comment]
Great, thanks!

**Comment by bryceco** [comment]
It turns out the bug isn't in Go Map!! in this instance. The layer index advertises that the server supports EPSG:4326 but that endpoint returns blank tiles. Simply by luck iD chooses the EPSG:3857 projection instead which does work. In a future version of ELI the EPSG:4326 projection will be removed and then it will begin working for us.

**Comment by bryceco** [comment]
Fixed in b15b14c840c7a43e6dd4898dbe557ed7d9031ff6
