### ISSUE TITLE
Show date of editor layer index in UI

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#249]
The editor layer index has a release date in the imagery-file ([raw](https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/imagery.geojson)):

```json
…,"meta":{"format_version":"1.0","generated":"2020-01-12 04:00:26"},"type":"FeatureCollection"}
```

It would be helpful for understanding issues like https://github.com/bryceco/GoMap/issues/243 if the app displays this date in the UI.

Possible UI:

Extend the sub-headline on the "Custom Areal" page.

> ADDITIONAL IMAGERY SOURCES (list version 2020-01-12)

**Comment by bryceco** [comment]
Fixed in c276594d15ba144bfa5ff47ae68a56629996df49

**Comment by bryceco** [comment]
Note that in practice almost none of the common tile sets include date information, unfortunately.

**Comment by tordans** [comment]
@bryceco I think we are talking about different date-data here.
My idea was, to have the release date of the image layer feed in the editor UI, for example at this place:
![IMG_5736](https://user-images.githubusercontent.com/111561/75835118-4883fb80-5dbe-11ea-891e-262f86255a6d.jpeg)
The idea was, to be able to see what editor layer index version the software is using.

As far as I understand you commit, what you build is to show the start/end-Date that is available per image source. Which is also great, but a different issue.

**Comment by bryceco** [comment]
Okay I see.

**Comment by bryceco** [comment]
Fixing, but I'm putting it in the footer at the end of the list
