### ISSUE TITLE
Show error message as html-page if error response is HTML

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#252]
From time to time I have connection errors that show up for a split second in this bray error message bar but the content is not a message but HTML.

The problem is, I cannot usually see whats going on since the message is not visible long and only shows the first line.

Maybe, there is a possibility to show the error message in something like a website, whenever the response is not plain text? 

Or maybe, the error message could be stored in some log, so I can look at them afterwards with more time at hand?

Example:

![IMG_5136](https://user-images.githubusercontent.com/111561/72916463-5ae03380-3d42-11ea-96a4-43d626a1904b.png)

In this case, the server was down and send a html 502 page.

**Comment by bryceco** [comment]
Does anyone know a repeatable way of getting an html error to appear?

**Comment by tordans** [comment]
> Does anyone know a repeatable way of getting an html error to appear?

I had the issue with …
- https://tiles.codefor.de/berlin-2019/16/35216/21507.png which is down again and again – it is down ATM (but might be up in 5 Min again)
```
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```



- an overpass query in completionist (I think)
