### ISSUE TITLE
Replace In-App help with web view for OpenStreetMap wiki page

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#264]
# Current situation

The text that is displayed when tapping the info button at the top-right corner of the map is part of the storyboard. Personally, I am not very comfortable with editing attributed strings in the Interface Builder.

# Proposed solution

When tapping the info button, we should instead show a `SFSafariViewController` that displays the [Mobile View](https://wiki.openstreetmap.org/w/index.php?title=Go_Map!!&mobileaction=toggle_view_mobile) of the OpenStreetMapWiki.

In my eyes, this has multiple benefits:
- We have one single source of truth, and no redundant/outdated information
- Adding to or improving the documentation does no longer require any tools - an account on the OpenStreetMap wiki allows everyone to improve it
- Less code to review and maintain

**Comment by bryceco** [comment]
This seems like a win overall. I wish it were possible to easily cache the web page for off-line use and to improve responsiveness in general, but that's not essential.

**Comment by tordans** [comment]
@wtimme sounds like a good idea. Alternatively, we could add a /docs folder in this repo and generate it as a GitHub Page. This would allow for more styling-control. And still everyone with a GitHub Account can contribute (but a bit more controlled).

In both cases I wonder: Is there a way to use the apps language to choose the wiki page? Personally, I am finde with EN only or making it the users task to change the lang once the wiki page loaded – I am just wondering.

**Comment by wtimme** [comment]
Good suggestion, @tordans! Yes, that also came to my mind. As far as I know, GitHub pages are stored as Markdown, so we would need to either render it inside the app _or_ render it during build and then put it into the app as HTML. To make it even easier, we could use the "Wiki" functionality of GitHub.

I don't know how we would handle things like screenshots, however. To my understanding, they need to be part of the repository as well, right?

**Comment by tordans** [comment]
GitHub Page / Markdown: I was still thinking about the solution that uses the webview; so the app still shows the HTML page, but the editing-ui is the .md-File in the /docs folder of this repo, which Github pushes to the public URL on every change.

Screenshots: Yes, its all part of the /docs folder. Which is ok IMO. It could also be a separate repo, but that makes thinks more complex IMO.

Github Wiki: In comparison the OSM-Wiki would be better. Both are Wikis with less nice styling, so there is not advantage to using GitHub here.

OSM Wiki Updates: It seems to have it's own live cycle which we would not touch; wich is fine IMO.

**Comment by bryceco** [comment]
I’m failing to see how moving it to GitHub helps things. Seems it only makes it more difficult for other people to contribute. 

I’m also concerned about the impact on people who maintain translations of the wiki (notifications and tracking edits).

**Comment by wtimme** [comment]
Yes, valid points. How about we just stick with the OSM wiki approach for now? Once we encounter issues or shortcomings, we can always improve and adapt.
