### ISSUE TITLE
contact:website (contact:*) compatibility

### ISSUE THREAD

**Issue by sun-geo** [bryceco/GoMap#274]
I saw recently edits from a user which did use Go Map!! 1.6.1 for uploading changes to the osm-db. One part of the changeset was to add the tag `website=https://abc.com` while a tag of `contact:website=https://abc.com` did already exist for the same object.

Question, was this a mistake from the user, or is it depending of the GUI/workflow of the Go Map!! application?

Do you think it is okay to have such double information stored in the osm-database?
If not (as i think), is there any way to tell this the user of the Go Map!! application, to prevent this?

https://wiki.openstreetmap.org/wiki/Key:contact

**Comment by bryceco** [comment]
The app uses the same presets that iD uses. Currently that means that website=xxx is the default key/value pair, but the user is free to override that. The editor doesn’t currently detect if “synonyms” or alternate tagging schemes are in use. I believe the iD preset database contains some hints for warning the user but we don’t include support for those yet.

**Comment by bryceco** [comment]
I was incorrect about the preset database providing help with this. If it ever does we can address it then.
