### ISSUE TITLE
Use Share-Control for Share-Button on Changeset-Webview

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#275]
The embedded browser that shows when I click on the changeset ID via the "node attribute" page shows two custom sharing options – "mail" and "open in safari". (Same for the "identifier".)

Instead, it would be great to have the default iOS sharing dialogue here, which also includes "copy" for the URL and other sharing options.

This is the current UI I am referring to:
![IMG_5626](https://user-images.githubusercontent.com/111561/75839027-0069d680-5dc8-11ea-9002-3a91123cdfd4.png)

**Comment by wtimme** [comment]
The same applies to the other attribures as well. How about we use the `SFSafariViewController`?

**Comment by tordans** [comment]
This UI would be great: 
![8FE1F5EF-6C24-462E-90EF-DC8B58DA18D8](https://user-images.githubusercontent.com/111561/75913042-7b77cf00-5e52-11ea-8f00-f5fed77e6405.jpeg)

**Comment by bryceco** [comment]
> The same applies to the other attributes as well. How about we use the `SFSafariViewController`?

Yes I agree.
