### ISSUE TITLE
Add "Extract" option for node on area/way

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#276]
The iD editor added a feature a few month back that allows to "extract" a node from a area/way into a single node. This is a great feature when someone glued a node with tags which you now want to be stand alone.

![image](https://user-images.githubusercontent.com/111561/75839356-f694a300-5dc8-11ea-810b-34c6a735c979.png)
[Editor](https://www.openstreetmap.org/edit?node=2095453480&locale=en#map=19/52.49858/13.44700)

GoMap has a similar option with "disconnect", which I can call on a node but which results in an error message.

My idea is, to allow "disconnecting" nodes in all cases / remove the error message/condition.

In the example of the screenshot (https://www.openstreetmap.org/node/2095453480), this would extract the node with all its tags an remove it from the way.

In other edge cases, it might result in two empty nodes instead of a way, which IMO is fine, since the user used this feature with intend and should have a plan how to further edit those – temporarily useless – nodes.

Current UI:
|   |   |
|---|---|
| ![IMG_5707 Kopie](https://user-images.githubusercontent.com/111561/75839553-5b4ffd80-5dc9-11ea-80e6-5abb7c78229d.jpg)   | ![IMG_5706 Kopie](https://user-images.githubusercontent.com/111561/75839554-5c812a80-5dc9-11ea-9ec3-444a72c67c6b.jpg)    |

**Comment by dieterdreist** [comment]
desired behavior should be keeping the id for the detached node (with the tags) and add a new one to the way.

**Comment by dieterdreist** [comment]
IMHO #385 is about a different thing, as it is not about detaching an existing node with its tags but about transferring tags from a polygon to a new node

**Comment by TheAdventurer64** [comment]
Yeah. That was another reason why I wanted the feature.

> IMHO #385 is about a different thing, as it is not about detaching an existing node with its tags but about transferring tags from a polygon to a new node

**Comment by tordans** [comment]
Ran into this again today. There are still a few areas (in Germany) where gluing stuff on areas/ways is way too common. In general GoMap is ideal to un-glue things (even easier than iD I think). It would be great to have it for nodes as well.
