### ISSUE TITLE
Temaki icons / Icon color

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#277]
Hi, I love the new - same looking - [temaki icons](https://github.com/ideditor/temaki) in the current master. Thanks – also to Bryan and Quincy [who are making them](https://github.com/ideditor/temaki/graphs/contributors).

# Color

Even though iD does not have colors for their icons, I fee like GoMap would benefit from it.
On the small screen, especially in icon-dense location, having colors will help to fokus on certain features.

Suggestion: Maybe we can re-use the color schema from the osmCarto Map stile? There colors seem to be at https://github.com/gravitystorm/openstreetmap-carto/blob/master/style/amenity-points.mss#L1-L25. However, mapping the colors to the features seems to be more complex (like https://github.com/gravitystorm/openstreetmap-carto/search?q=health-color&unscoped_q=health-color).

# White box

Looking at the Testflight, I am not sure the white box has the same good effect like it did before. Its invisible often. But I dont have an idea ATM about what to improve.

# Example Screenshots
![IMG_5805](https://user-images.githubusercontent.com/111561/76057519-128b7680-5f7a-11ea-88a6-a51b41ffef71.PNG)
Location: https://www.openstreetmap.org/#map=19/52.47151/13.43487

![IMG_5807](https://user-images.githubusercontent.com/111561/76057516-0ef7ef80-5f7a-11ea-8684-174e3bb8b149.PNG)
Location: https://www.openstreetmap.org/#map=19/52.47420/13.44707

**Comment by tordans** [comment]
Another argument for colors is, that the icons are re-used.
For example the bike-icon is used for bike-parking (in the screenshots above at the kerb/curb) as well as bike shops (in the following screenshot).

![IMG_5916 Kopie](https://user-images.githubusercontent.com/111561/76355942-6ea52080-6315-11ea-95bf-564069165c33.jpg)

**Comment by wtimme** [comment]
As for the white background, here's a screenshot of how the map would look like without it:

![icons-color-default-without-background](https://user-images.githubusercontent.com/1681085/76462879-50edbf00-63da-11ea-8ca7-deef228cd62f.png)

**Comment by bryceco** [comment]
For certain dark aerial imagery the white background is essential. It also helps prevent multiple icons from merging into a single blob when they overlap. 

The circles are cute, I’d like to try them.

**Comment by tordans** [comment]
Thanks for the update!

+1 for white background; when mapping in the city I dont have areal images active most of the time, that why I did not see it.

+1 for circle being nicer; I still have an issue with finding the exact lat/lng in the center of the object, but thats a different story :)

+1 for green trees (natural=* as green?) https://github.com/bryceco/GoMap/pull/287#issuecomment-597925828

+1 for looking into alternative "fallback" icons; but IMO that can be a separate issue as well; iD has a few good ideas IMO.

**Comment by wtimme** [comment]
Thanks for the positive feedback! 👍🏼

I've just uploaded another TestFlight build for "OSM Completionist" (1.7.0 (27)), in which I included a preview for the circles. Please have a look and let me know what you think.

As for the trees, I tested a bit with `natural=*`, and it seems to apply to all trees. Now all we need is a color value. Any suggestions?

**Comment by bryceco** [comment]
#127A38 for natural=tree

**Comment by wtimme** [comment]
Alright. 👍🏼 Have you taken a look at the circles yet? Should I create a PR so that you can take a look at the changes and compile it yourself?

**Comment by wtimme** [comment]
I've gone ahead and created a pull request (#293), adding screenshots for comparison. Let me know what you think.

**Comment by bryceco** [comment]
I like the circles. Can we close this?

**Comment by tordans** [comment]
This looks good, thank you!

As a side node, I wrote about searching for ways to pick up the new brand look from the icon inside the app in https://github.com/bryceco/GoMap/issues/236#issuecomment-593084624
> how could the icon design be used inside the app, so the style gets picked up again somewhere?

IMO once the app icon is decided, we could revisit those in app colors and see if we can use them to give the app "more brand" without looking on the clarity and usability front.

**Comment by wtimme** [comment]
@bryceco, I think this can be closed as well. 👍🏼
