### ISSUE TITLE
Show direction indicator for Forward/Backward, eg on traffic_signal

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#280]
Signs and traffic lights have a Tag to indicate the direction on the street with forward/backward.

In iD, those are rendered with the direction-indicator that is also used for direction-keys.

It would be great to have those for GoMap as well.
Other than for the direction-key, in those cases the indicator has to use the angle of the street that is mapped on.

|---|---|
| ![IMG_5816 Kopie](https://user-images.githubusercontent.com/111561/76119135-13122480-5fef-11ea-8ace-7e14fad3568c.jpg)  | ![IMG_5817 Kopie](https://user-images.githubusercontent.com/111561/76119145-186f6f00-5fef-11ea-9553-2453bb070ce9.jpg) |
|---|---|

**Comment by dieterdreist** [comment]
sent from a phone

> On 6. Mar 2020, at 21:10, Tobias <notifications@github.com> wrote:
> 
> Signs and traffic lights have a Tag to indicate the direction on the street with forward/backward.
> 

of which street? I am against supporting inheritance of way directions to nodes, the latter do not have directions. We should not encourage ambiguous mapping styles.

**Comment by tordans** [comment]
I am referring to to …
- https://wiki.openstreetmap.org/wiki/Key:traffic_signals:direction 
- https://wiki.openstreetmap.org/wiki/Key:traffic_sign#As_part_of_a_way

Which I consider valid, documented practise.
