### ISSUE TITLE
End of line does not snap to building which is part of a relation

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#281]
Szenario
- I draw a new line
- Grab the end to snap it to a building
- This works for regular buidlings, but not for those that are part of a relation (like this one for example) https://www.openstreetmap.org/relation/933526

Video: https://www.dropbox.com/s/o1gz6vep2obcqvw/temp-gomap-repo-snapping-RPReplay_Final1583426002.mp4?dl=0 (I will remove this in a few weeks)

**Comment by tordans** [comment]
Update: Video URL moved to Dropbox.

**Comment by bryceco** [comment]
Fixed in 3e24d761478e1bb1e44df33492c47242b1f04344

**Comment by tordans** [comment]
Thanks, works great again.
