### ISSUE TITLE
Support single-finger zoom

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#298]
Several people have requested a single-finger zoom gesture, similar to what Google maps support: double-tap followed by a vertical motion to zoom in/out. I prototyped this once and there might be an #ifdef in the code, but I don't know if it works correctly.

**Comment by tomasokol** [comment]
![0A4B27EF-6B05-4206-895D-B6FC3C97347F](https://user-images.githubusercontent.com/51287372/78193176-2e4f4300-747a-11ea-8a71-c2dcd7ce83b2.jpeg)
The Mapy.cz App uses a slider on the right side of the screen. Pull down = zoom in, up = zoom out. 

I think it’s more reliable as you won’t accidentaly tap a node.

**Comment by bryceco** [comment]
Added in cd52d20a69ac9806acf8ce77eabee7eadaeb7d1b
