### ISSUE TITLE
Copying lat/lon should copy both values, not just one

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#305]
When copying the lat/lon of a node it requires two separate copy/paste operations since they are separate fields. Either the fields should be combined or the code should be modified to copy both values at once.

**Comment by wtimme** [comment]
Thanks for the feedback!

Personally, I don't use the copy/paste operation. In order to know what an ideal solution could look like, is someone able to give us a use-case? (_Why_ do you want to copy these values, and _where_ do you paste them to?)

**Comment by bryceco** [comment]
Sometimes I want to walk/drive to the location of a node so I’ll copy the coordinates into Maps. Or if I see something I’d rather fix in iD I might want to paste the location in the OSM.org search box. Or if I’m emailing someone about an area I’ll send the  coordinates.
