### ISSUE TITLE
Use CLLocationManager to get altitude for elevation tags

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#306]
Similar to how me measure direction with the compass.

**Comment by 1ec5** [comment]
I wonder whether the [`CLLocation.altitude`](https://developer.apple.com/documentation/corelocation/cllocation/1423820-altitude) property is accurate enough for tagging purposes. As far as I know, turn-by-turn navigation applications sometimes use it to detect changes in elevation, but the absolute value isn’t taken too literally.

**Comment by bryceco** [comment]
That’s good to know. I got it as a feature request and wanted to document it. A little research suggests that 30 meters accuracy is the best one can hope for.

**Comment by dieterdreist** [comment]
sent from a phone

> On 15. Mar 2020, at 00:44, bryceco <notifications@github.com> wrote:
> 
> That’s good to know. I got it as a feature request and wanted to document it. A little research suggests that 30 meters accuracy is the best one can hope for.


more recent phones (I think since iPhone6) spot a barometric sensor which should give much better (relative) precision (but would require calibration for good absolute values)

I believe the measurement precision   of altimeters based on barometry should be in the submeter.
