### ISSUE TITLE
Need generic icon for amenity=yes

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#309]
iD shows these items with an empty pushpin. We show them as a colored rectangle. It would be nice to do a little better.

**Comment by dieterdreist** [comment]
sent from a phone

> On 14. Mar 2020, at 01:44, bryceco <notifications@github.com> wrote:
> 
> ﻿
> iD shows these items with an empty pushpin. We show them as a colored rectangle. It would be nice to do a little better.
> 


maybe with a triangle? Pointing down like a pin
