### ISSUE TITLE
Icon Color: Is the grey really better?

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#310]
As a follow up to https://github.com/bryceco/GoMap/issues/277 / FYI @wtimme.

The default icon color changed from black to grey.

After using it for a bit, do you think its better in grey?

Personally, I still associate it with being inactive / greyed out – even after using it fo a few times.

![IMG_5968 Kopie](https://user-images.githubusercontent.com/111561/76689709-ce166f80-6638-11ea-9377-fef982632254.jpg)

**Comment by bryceco** [comment]
I’ll fix it

**Comment by wtimme** [comment]
From the current state of `master`, this looks like it was resolved:

![icons-black](https://user-images.githubusercontent.com/1681085/77230953-d2d6a880-6b8f-11ea-9fff-2c2052d85f11.png)

For future reference, I believe the commit that fixed this is 2e5c012aab57266bd4ef1934618d9677fbebbf16.

@bryceco, looks much better now, thanks! Can this issue be closed?
