### ISSUE TITLE
(FYI) New areal image index at ideditor/imagery-index

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#311]
This is FYI (for now):
- https://github.com/openstreetmap/iD/issues/7425
- https://github.com/ideditor/imagery-index

**Comment by bryceco** [comment]
The latest build uses the JOSM list.

**Comment by tordans** [comment]
I don't know anything about the JOSM layer index. What is the best introduction / documentation to read to get to know it?

cc @grischard.

**Comment by bryceco** [comment]
Background is here: https://github.com/osmlab/editor-layer-index/issues/586

**Comment by grischard** [comment]
@tordans https://josm.openstreetmap.de/wiki/Maps is probably the best introduction.

Entries are xml entries like https://josm.openstreetmap.de/wiki/Maps/Germany#Berlinaerialphotograph2017 which should look familiar ;).

You hit 'Edit this page' at the bottom of country pages to add/edit/remove entries.
