### ISSUE TITLE
(?)Icon for "new node"

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#315]
Now that the new Icons make the app look even nicer, the old (?)-icon that is visible when placing a new node looks out dated.

![IMG_6125](https://user-images.githubusercontent.com/111561/78859374-6a147a80-7a2f-11ea-92b3-edefa6138bef.jpg)

---

Side note: The color of this icon could also be an opportunity to pick up brand colors, like I commented on at https://github.com/bryceco/GoMap/issues/236#issuecomment-593084624 
> how could the icon design be used inside the app, so the style gets picked up again somewhere?

**Comment by bryceco** [comment]
I agree that’s a great item to improve, suggestions welcome.

**Comment by tordans** [comment]
# Feedback to the Testflight

1. The "?" does not look as crisp as the rest of the UI.
@wtimme use some special iOS "dont make this a image, treat it as a vector"-param; maybe this is another one of those cases?

2. I like that the new-node-icon looked very differed.
Suggestion: Have it inverted: Black with white "?".
An maybe a shadow below the circle, to give it even more of a "I am not yet placed on the map"-Look.

![IMG_7632](https://user-images.githubusercontent.com/111561/83964641-9e30de00-a8ae-11ea-953e-1aa7a82a3ba9.PNG)

**Comment by tordans** [comment]
Look good to me! ![image](https://user-images.githubusercontent.com/111561/86492723-55fec180-bd6f-11ea-83b4-f86bac447fe3.jpeg)
