### ISSUE TITLE
Join when more than two ways end at a node

### ISSUE THREAD

**Issue by fntagit** [bryceco/GoMap#320]
When two ways end at a node, one can join them, if and only if the two ways share identical tags.

When more than two ways meet at a node, the join operation is currently impossible, since the target can not be determined, and since GoMap! does not currently have a mechanism to select a second way to indicate which way should be joined.

Now, if among the ways ending at the node, one and only one has exactly the same tags than the selected way, would it not make sense to perform the join with that compatible way?

**Comment by bryceco** [comment]
Yes that’s a great idea.
