### ISSUE TITLE
Version mismatch error

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#324]
When I try and save my edits, I get an error like this:
![A3D06872-C45B-45CB-B8A1-A75262F941B8](https://user-images.githubusercontent.com/50059322/81022248-d5702300-8e08-11ea-8716-25e8c169fb6b.png)
Now, I have located where the error is, and where it came from, but what I can’t figure out is how to fix it. 
Help?

**Comment by bryceco** [comment]
The app attempts to resolve those errors automatically, but if it can’t then your only options are to fix the error manually via editing the XML, or discarding the entire change that. 

You can use the Edit button to access the XML and modify the offending node, then Commit the new XML. Alternately you can mail the XML to yourself and then import it into JOSM and attempt to fix it there.

**Comment by TheAdventurer64** [comment]
Alright, so I fixed the issue, and I successfully saved my edits. However, when I try and save edits afterwards, I get the same error. I checked the xml and it looks like the node is gone. Help?

**Comment by bryceco** [comment]
After you've done the commit go to Cache Settings and clear the OSM Data.

**Comment by TheAdventurer64** [comment]
What about my unsaved edits?

**Comment by bryceco** [comment]
If you get the same error after editing the XML then there is probably another node that is also incorrect, and you'll have to repeat the process.

**Comment by TheAdventurer64** [comment]
Thank you.
