### ISSUE TITLE
Include OS version in changesets

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#326]
I’d like to know which versions of iOS are being used. In particular knowing that iOS 9 is rarely or never used would allow us to drop support for it and move to more modern APIs when available. This could be accomplished by adding a changeset tag os=iOS 13.4.1

Other information that is less important but still useful is:
* the device model (especially iPhone vs iPad)
* preferred language 
* which of various features within the app were utilized. Features that are never used could then be removed.

**Comment by tordans** [comment]
I don't think changeset tags would be the right place to store this information. Even though there are a convenient, quick way to solve this.
One reason is, that you cannot delete any information from changesets, so this data would be public forever but only needed for a very short time – for one decision mainly. Personally I would not feel great to have my iOS version exposed like this.

A few ideas

- add google analytics for app tracking – but this requires a privacy statement and explicit consent nowadays, so its not ideal

- add a survey that is shown to app users and ask them for feedback
> We plan to drop support for iOS 9 in the next release. Please take the following survey to let us know how you use GoMap (iPad? iPhone? Which? etc.) so we can optimize the app further. Thanks and happy mapping!

  - One way would be to use something like https://www.tinyfor.ms/, maybe in a webview
  - or a regular google form (the easiest an cheapest solution IMO)
  - or another form tool like survey monkey

- the quickest way is IMO: just drop support for one release and tell people in the release notes to email, if they still need it :)


Personally, I would go for the google form solution and make the answers public, so anyone can see what data is collected. With a big disclaimer that personal information does not belog in this form …

**Comment by bryceco** [comment]
I’m a fan of privacy and I won’t use Google products to collect information. Using a survey seems pretty annoying for end users, and there’s no way to know what the coverage is. If we just drop iOS 9 then those users will never know about the new version, they’ll just stop seeing updates. 

Another option is to have a one-time pop-up asking if information can be included in changesets, and then have a toggle on the login page if they change their mind? Or possibly have the information posted to some other private location. 

The nice thing about attaching it to the changeset is it gives an objective measure of what percentage of edits (not users) will be affected  if support is dropped.

**Comment by wtimme** [comment]
Great idea to get some numbers on this!

If I‘m not mistaken, it might be possible to get numbers from App Store Connect‘s Analytics section. I think that users can opt-out of these metrics, but they could be a starting point.

From the [App Store Connect help](https://help.apple.com/app-store-connect/#/dev5340bf481):

> App Analytics provides data on user engagement and marketing campaigns with metrics such as App Store Impressions, Product Page Views, Sales, Sessions, Deletions, and more. Keep in mind that App Analytics displays data from devices running macOS 10.14.1, iOS 8, ND tvOS 9, or later, and that data is displayed only when a certain number of data points are available.

I just had a look for an app that I maintain, and the „Sessions per Platform Version“ seems to be what we are after here.

**Comment by LucasLarson** [comment]
> get numbers from App Store Connect‘s Analytics section

I couldn’t immediately find that documentation — this is what’s needed!

**Comment by bryceco** [comment]
Great idea! 

Looks like 9.3 is pretty rare now. A few years ago I tried dropping it but there were some users who complained. Also I suspect a lot of those 9.3 sessions are from my own testing.

![IMG_0331](https://user-images.githubusercontent.com/279734/83299132-76ed5900-a1aa-11ea-89f8-cc88b0159462.jpeg)

![IMG_0332](https://user-images.githubusercontent.com/279734/83299160-7eacfd80-a1aa-11ea-8ace-58f2ecd6c353.jpeg)

**Comment by wtimme** [comment]
Thanks for sharing!

Looks like very, _very_ few sessions compared to other major versions.

What do you think - safe to drop?

If we were to drop, do you know which places in the code are specifically for iOS 9 compatibility and could potentially be removed?

**Comment by bryceco** [comment]
Probably safe to drop. The last couple weeks I made some performance improvements trying to get the frame rate on my really old 9.3 iPad Mini up to something reasonable. I’d like to do a public release making that available before dropping support. 

There are some deprecated API warnings in the Mac Catalyst build. I expect that fixing those warnings will force iOS 9 breaking changes. 

Unfortunately I don’t have an iOS 10 device to test with (my iOS 9 device can’t be upgraded), so that’s also a consideration.

**Comment by saper** [comment]
Too late to the party but I am using Go Map! on iPad Mini stuck on 9.3.6. Got burned a bit with the update to 2.1.2 - filed #517 about my experience with it...
