### ISSUE TITLE
Question about using the filter to hide borders

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#331]
I might still be using this feature the wrong way … but maybe it's a bug?

My goal is to hide the border.

This is my setup:

1: the border is visible
![1-border visible](https://user-images.githubusercontent.com/111561/83482624-ffb50f00-a4a0-11ea-98d6-79ff4ae96448.jpg)

1b: Those are the tags of the border
Its a part of https://www.openstreetmap.org/way/210889585#map=17/51.02220/12.83490
![1b-border tags](https://user-images.githubusercontent.com/111561/83482684-26734580-a4a1-11ea-9f7e-1922dc36084a.jpg)

2: The filter is "on"
![2-but filters on](https://user-images.githubusercontent.com/111561/83482690-2a06cc80-a4a1-11ea-9ad0-43c5e1ad2150.jpg)

3: And the borders are "show=false"
![3-and borders disabled](https://user-images.githubusercontent.com/111561/83482695-312dda80-a4a1-11ea-9787-d8a36a228452.jpg)

So my understanding is, those should be hidden?

-----

This might be an issue with the filter now working on relations? (This might still be an open ticket; need to check).

Or the filter-rules don't target this border? Could the filter rules be visible in a "hint" below the filter-label?

**Comment by bryceco** [comment]
This works for me, except that there is a redraw issue where the display doesn't update until you move the screen. Can you confirm?

**Comment by tordans** [comment]
I tried it again; still does not work.

This is the location I tested https://www.openstreetmap.org/way/210889570

Will link a video as soon as I have better internet :-).

**Comment by tordans** [comment]
Here is the Video: https://share.icloud.com/photos/0BZJezHKXQx4LOP78hXaJaX8w

**Comment by tordans** [comment]
Update to the current TestFlight: All works great now! Thanks!

This also fixed(?) the styling of the line when visible:

![image](https://user-images.githubusercontent.com/111561/84453786-0722a800-ac59-11ea-8dd1-daae3df56c10.jpeg)

And hidings works:

![image](https://user-images.githubusercontent.com/111561/84453827-228db300-ac59-11ea-9bf3-c56f8acc2848.jpeg)

**Comment by bryceco** [comment]
Great!
