### ISSUE TITLE
Preset selection for a building removes the building key

### ISSUE THREAD

**Issue by tohaklim** [bryceco/GoMap#332]
This is not something that I come across often since I mainly map pois as nodes, but the latest (1770) beta appears to remove the building key when applying an amenity/shop etc preset to the building polygon. 
This is similar to what iD does with eg the school preset, so not sure if that’s the same logic

**Comment by bryceco** [comment]
I see this behavior when the building is a node, but when the building is a polygon I see it keeping the building=yes tag. Can someone else verify this bug report?

**Comment by tohaklim** [comment]
I think it is only reproducible on buildings that don’t have an amenity/shop value already set. If I apply a preset to a building with supermarket tags, the building value remains

**Comment by bryceco** [comment]
I don't see it in that situation either.

**Comment by tohaklim** [comment]
![CBD2CD23-981C-4EAA-BC24-89BF4274AE91](https://user-images.githubusercontent.com/7071423/83749692-fde37b00-a65b-11ea-8d7e-3d9ba96d9476.gif)

Here is a recording

**Comment by bryceco** [comment]
Thanks, I’m able to replicate it now.
