### ISSUE TITLE
Empty value tag block vanished after closing OSM Wiki page

### ISSUE THREAD

**Issue by yellowsoar** [bryceco/GoMap#334]
# Reproducing:
tap any feature >  
tap "Tags" button >  
tap "Add New" >  
fill in "key" but leave "value" empty >  
tap any "Open in OSM Wiki arrow" >  
close page >  
the empty value tag block vanished!

[screen recording](https://i.imgur.com/x96k0o9.mp4)

**Comment by bryceco** [comment]
Fixed via 33a0a564b8a4c6b672f9706c37cd0aff4e904bb6
