### ISSUE TITLE
Testflight: Keyboard Tabs for new All Tags View

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#337]
Right now, I have to click from the key input to the value input manually.
I try to move my thumb as litte as possible, since mapping causes finger-pain :-).

Is it possible to add the Tab-keyboard-shortcuts to the keyboard, so I may use those to tab from the key to the value input? And maybe also tab from one line to the next?

I am referring to those:
![image](https://user-images.githubusercontent.com/111561/83964542-1ba81e80-a8ae-11ea-94a0-0c8872d7a5a1.png)
(Image source https://stackoverflow.com/questions/38385197/how-to-prevent-tab-action-triggered-by-ios-uikeyboard-arrows)

![IMG_7635 Kopie](https://user-images.githubusercontent.com/111561/83964622-8eb19500-a8ae-11ea-8746-0849b0d91d2c.jpg)

**Comment by bryceco** [comment]
That’s easy to add, and the placement of the buttons is configurable as well. (BTW I generally use a stylus when mapping which helps a lot with finger pain).
