### ISSUE TITLE
Show color next to 'colour' fields

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#338]
I guess, this is really low prio IMO and more of a gimmic.

Every time I see a color value, I wonder if its correct. But in order to check it, I need to copy and google it like https://www.google.de/search?q=%2335423E.

Possible solution: Show a preview of the color like on the OSM website https://www.openstreetmap.org/node/760002892

![IMG_7638 Kopie](https://user-images.githubusercontent.com/111561/83964861-f0263380-a8af-11ea-8eb8-0d46ac3228f2.jpg)

**Comment by bryceco** [comment]
Interesting idea, but who is adding colors in hex notation instead of by name? And are you then going to ask for a color wheel, and then camera-based color detection? 🤣

**Comment by tordans** [comment]
For the record, I think this is nice ![image](https://user-images.githubusercontent.com/111561/84453046-ca09e600-ac57-11ea-9001-865b95e90a79.jpeg)

—-

This makes me thinking, how about this camera based color detection? 🤣🤣
