### ISSUE TITLE
TestFlight: Redraw issue: Node not deleted

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#340]
I noticed with the last few testflights, that there is a redraw-issue where I delete a node which is still visible on the map afterwards.

Video: https://share.icloud.com/photos/04LPAxdY58GRgyWAFxo0RHJEA#Berlin

Snapshot: ![image](https://user-images.githubusercontent.com/111561/84452320-c83f2300-ac55-11ea-87d7-c861b9dc906b.jpeg)

**Comment by bryceco** [comment]
This is an unintended side-effect of a change I made where if you delete a way, it doesn't delete nodes in the way that have interesting tags. I'll fix this issue, but I'm wondering if the previous change should be reverted.

**Comment by tordans** [comment]
> where if you delete a way, it doesn't delete nodes in the way that have interesting tags. ... I'm wondering if the previous change should be reverted.

I did not know this changed and really like it. It lets me remove the non-needed tree_row without loosing  the trees at https://www.openstreetmap.org/way/432834334, for example; which I wanted to do forever :). 

My vote it to keep it (if feasible).

**Comment by bryceco** [comment]
iD also retains interesting nodes so I’m keeping it. The only unexpected side effect I saw is that if you delete a highway the crosswalk (etc) nodes remain, but I’m okay with that.
