### ISSUE TITLE
Fill color for landuse=forest

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#341]
I wanted to research this a bit more, but for now I will just document it here: 

Landuse=forest does not have a fill color. 

However, I remember seeing a color definition when looking at the code for https://github.com/bryceco/GoMap/issues/329, but it was quite different (more lime?) to the other forest-type (natural=wood(?), dark green).

So this has two parts
- add the fill color
- maybe make both forest-types look more similar (they are rendered the same AFAIK on the OSM-Carto-Style)

![image](https://user-images.githubusercontent.com/111561/84454046-d1ca8a00-ac59-11ea-9412-5c2352680768.jpeg)
![image](https://user-images.githubusercontent.com/111561/84454059-d7c06b00-ac59-11ea-8122-8a0e9c27a6ab.jpeg)

Test-Location: https://www.openstreetmap.org/way/108009356

**Comment by bryceco** [comment]
The fill colors were too similar to be discerned. Fixed in f6e44256a4c7ce100f187e24c64edfbc45f7640e
