### ISSUE TITLE
Add filter “no underground stuff”

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#342]
Some people mapped underground cables in Berlin, which are quite annoying when mapping, since I snap to them by accident.

They have `location=underground` as an identifying key.

https://wiki.openstreetmap.org/wiki/Tag:location%3Dunderground
It’s used 90k+ times.

Idea: a new filters “underground:on/off” which filters objects with this key.

However, I wonder if this filter should also include parking=underground, which is similar but does not have the location tag in the cases I know https://wiki.openstreetmap.org/wiki/Tag:parking%3Dunderground.

So maybe add this to the filter as well?

According to https://wiki.openstreetmap.org/wiki/Underground there is also railway features that are relevant, but IMO those get the location=underground tag, so they are handled.

![image](https://user-images.githubusercontent.com/111561/84454958-59b19380-ac5c-11ea-9281-9ff1ccf9b6e5.jpeg)

![image](https://user-images.githubusercontent.com/111561/84454970-60d8a180-ac5c-11ea-8c05-dfa20ebe0720.jpeg)

**Comment by bryceco** [comment]
This seems really close to layer < 0, and would also be confusing whether it applied to tunnels and culverts. Definitely low-priority to me.

**Comment by bryceco** [comment]
I'm going to stick to letting iD break new ground on this feature set. If they add it I'll add it.
