### ISSUE TITLE
TestFlight: artifacts on map on startup

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#344]
I get this weird artifacts on startup - but not every time. Sometime it resets to a good state after, like https://share.icloud.com/photos/0l827_UGS-jHrfEsQOUMB2nyQ but most of the time it shows those disconnected nodes on buildings and such afterwards.  

![image](https://user-images.githubusercontent.com/111561/85012957-2000f100-b164-11ea-882f-7af998c73183.png)

**Comment by bryceco** [comment]
Coordinates please?

**Comment by tordans** [comment]
Update: it happens all over Berlin where I map. I saw a glimpse of the same view in ID one time recently so I think it might be the zoomed out view of the custom background image I am using. Which is https://mapproxy.codefor.de/tiles/1.0.0/2019/mercator/{z}/{x}/{y}.png

**Comment by tordans** [comment]
I wanted to check if the max zoom level setting would prevent this error but I don't think I will gave the time so I will close this.

**Comment by bryceco** [comment]
Thanks! I never saw anything like this and couldn't reproduce. It's not clear where it came from but I think closing it is best as of now.
