### ISSUE TITLE
Immersive mode edition

### ISSUE THREAD

**Issue by JLZIMMERMANN** [bryceco/GoMap#346]
When checking if a shop is the same a year later, an immersive option is welcome. The idea: use the camera option and display the nearest POI that could be validated if still existing or edited with the new name and type of shop.

**Comment by bryceco** [comment]
Unfortunately I don't consider the compass to be accurate enough to be useful for an AR-type feature.

**Comment by TheAdventurer64** [comment]
Maybe @wtimme could work on this?

**Comment by wtimme** [comment]
I am sure AR will have a lot of use cases, and displaying OSM data in the camera feed sounds neat.

Right now, however, I would focus on getting the data models right before taking on such a seemingly big task. For example, I feel that a transition to Swift and the introduction of more unit tests has a bigger impact on the project right now.
