### ISSUE TITLE
Custom image background

### ISSUE THREAD

**Issue by bjornbostrom** [bryceco/GoMap#347]
Hi, 
I have added a custom background to a WMS-service that I use in JOSM. However, the background does not show up and a brief "<?xml version***** standalone=no>" text is showing on the screen. I suspect the WMS-service is returning some error message, is it possible to inspect data that WMS-service is returning? Doing so on my standalone computer works fine, so I suspect the error is that the priovided {bbox}, {height} or {width} are replaced with values that is not supported by WMS-serive. 

Any easy way to debug this? (i no not have x-code/emulators etc)

//björn

**Comment by bjornbostrom** [comment]
Found a way to tunnel the requests through a developer proxy. It seems that {bbox}, {height} and {witdh} does not translate at all.. The preset backgrounds have theese and working. Bug?

**Comment by bryceco** [comment]
Does the same URL work in iD? Can you post the URL here or send it to me privately by email via the in-app feedback?

**Comment by bjornbostrom** [comment]
Hi!
I've tested through iD editor now, and it does not work there. Inspecting it with Chrome DevTools revelas that {width}, {height} and {bbox} is not "translated". This is the parameters I pass in the URL:

?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=false&LAYERS=Ortofoto_0.5%2COrtofoto_0.4%2COrtofoto_0.25%2COrtofoto_0.16&TILED=true&STYLES=&WIDTH={width}&HEIGHT={height}&SRS={proj}&BBOX={bbox}

According to both Chrome Devtools and inspecting the traffic from GoMap!! through a proxy:

?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=false&LAYERS=Ortofoto_0.5,Ortofoto_0.4,Ortofoto_0.25,Ortofoto_0.16&TILED=true&STYLES=&WIDTH={width}&HEIGHT={height}&SRS={proj}&BBOX={bbox}

It seems that the parameters does not work. It may be as designed, but I thought it would work as some of the preset image backgrounds use them. (see screenshot from GoMap!!)

![IMG_0763](https://user-images.githubusercontent.com/67261371/85364631-d6c5ee00-b523-11ea-90d9-b722af1189b9.PNG)

**Comment by bryceco** [comment]
I see. Even if height and width are filled in {proj} is still an issue. I’ll have to rework that screen to allow selecting the projection as well. Once the app knows the projection it can fill in the other parameters automatically.

**Comment by tordans** [comment]
Isn’t the projection something that is the same for all GoMap mapping? So it just should not be a variable in the URL? With maybe a help text that explains what projection to use (which are supported by GoMap) in those cases?

**Comment by bryceco** [comment]
You would think, but some projections reverse the lat/lon when specifying the bbox.

**Comment by bryceco** [comment]
I just fixed a bug related to reversing a way containing nodes with direction=forward/backward. I think as long as we display the “facing” direction on the node it should make it clear to mappers that connecting new ways to it will cause problems.
