### ISSUE TITLE
Multilevel Parking garage should have same presets as Parking

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#349]

**Comment by bryceco** [comment]
I don’t see a difference between them. Can you be more specific?

**Comment by TheAdventurer64** [comment]
Comparison:
![CF6A6F6E-9925-4DCF-8D1E-188736EA80BF](https://user-images.githubusercontent.com/50059322/85659900-b5165500-b650-11ea-8bb3-cdbc94a15a7c.png)
![CB38FD88-A932-48D5-A77B-DB510842560C](https://user-images.githubusercontent.com/50059322/85659912-b778af00-b650-11ea-84c2-b5ed1a288af7.png)

**Comment by bryceco** [comment]
I think this must be on the release version. Can you confirm it on the TestFlight beta version?

**Comment by TheAdventurer64** [comment]
Yep. It’s only on the release version.
