### ISSUE TITLE
Consistently issue: E-mail should be Email

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#351]
Comparison:
![Uploading 4259E0E5-C3B1-4E9B-A265-
![4E86C269-8F9D-4807-B5ED-AAC3659BCA2E](https://user-images.githubusercontent.com/50059322/85808293-1e00da00-b6f0-11ea-9da2-68d32622f2db.png)
E175945DD6A7.png…]()

**Comment by bryceco** [comment]
Fixed in 90f95094e284dc6df11516489f660ee8ab6e0edb
