### ISSUE TITLE
TestFlight: Unknown nodes show up as „node“ (again)

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#360]
I remember a while back you added a feature that would show one of the tags of a node as name for a node.

This seems to be gone lost in the recent TestFlight.

Was this by design? – I still find this feature very useful :)

Update: This is where the feature was added https://github.com/bryceco/GoMap/issues/114

![image](https://user-images.githubusercontent.com/111561/86527839-0faa7f00-bea3-11ea-9f5b-0a874ba11994.jpeg)
![image](https://user-images.githubusercontent.com/111561/86527840-1507c980-bea3-11ea-936b-93b59f75cbbf.jpeg)

**Comment by bryceco** [comment]
You’re right, this is a regression.
