### ISSUE TITLE
Direction UI shows for cases where „forward/backward/both“ is meant to be used

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#361]
On a traffic_calming=chicane there is a direction=* preset field which will render the direction feature from https://github.com/bryceco/GoMap/issues/187.

However, in this case, only forward/backward/both makes sense.

I suggest to change the code that triggers the special direction UI in a way that is it not triggered when the direction-key is on a way of type highway.

This way it will still show up for a surveillance cam that is placed on the line of a building, but not for cases like above.

![image](https://user-images.githubusercontent.com/111561/86527938-f5bd6c00-bea3-11ea-8491-d63e0cfa2e2a.jpeg)
![image](https://user-images.githubusercontent.com/111561/86527943-fbb34d00-bea3-11ea-9b88-b9670e4656d0.jpeg)
![image](https://user-images.githubusercontent.com/111561/86527946-01a92e00-bea4-11ea-9122-4db9b71ae74b.jpeg)

CC @wtimme 
Ping to #228

**Comment by dieterdreist** [comment]
nodes do not have a direction, what could make sense are cardinal directions, but both, fwd bckwd do not seem reasonable

**Comment by tordans** [comment]
@dieterdreist didn’t we have this topic before with traffic lights?

The preset shows it as an option, see https://github.com/openstreetmap/iD/blob/72a99673a0328ba4f44c58dd110797cc733f7007/data/presets/presets/traffic_calming.json and https://github.com/openstreetmap/iD/blob/develop/data/presets/fields/direction_vertex.json

And the usage stats show, that the direction is used not his type of feature https://taginfo.openstreetmap.org/tags/traffic_calming=choker#combinations quite a lot.

And even though the wiki https://wiki.openstreetmap.org/wiki/Talk:Key:traffic_calming does not talk about it (except on the discussion page), it makes sense to have it since the information is valid.

**Comment by dieterdreist** [comment]
in theory you could inherit way directions on nodes, but it becomes complex when there are 2 ways on the same node (e.g. when splitting the way at the node or when you add it to an end node), and it means you must prevent connecting a third or more ways to the node.
It means you have to check the nodes as well when you change direction of a way. IMHO it is not a sane way of modeling direction depending properties on nodes.
