### ISSUE TITLE
integration with other iOS apps

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#363]
This is more a question than a bug, please excuse if this is the wrong place to ask. 
If someone wants to open a specific element with goMap!! from within a different iOS app, which is the format of the URL that she should use?

**Comment by dieterdreist** [comment]
I have found it here
https://github.com/bryceco/GoMap/blob/15e2e32332451605f4a3cd1fc0f26768b9327cfd/src/iOS/URLParsing/LocationURLParser.m

**Comment by bryceco** [comment]
There’s currently no way to open a specific node/way by its ID, but as you found you can specify the location/zoom.

**Comment by tordans** [comment]
This is related to https://github.com/bryceco/GoMap/issues/164 and #98, right? 

I had a new idea for those: The whole domain-validation-process could be simplified by registering osm-gomap.app and using this as the opening-point for URLs, so osm-gomap.app/node/123 would open the node. With a custom domain, we work around the need to use the osm.org-domain but osm.org could still link to GoMap for mobile-iOS.

**Comment by dieterdreist** [comment]
After implementing this and it apparently worked I have found now that there is an issue: somehow the position is cached. It works at first, but following calls bring me back to an older position. I am using the appspecific path like this:
@"gomaposm://?center=%f,%f&zoom=18"

**Comment by bryceco** [comment]
Are you using the TestFlight beta? There was an issue that sometimes caused the position to not get set when the app was freshly launched (not in the background).Specifically, the call to set the position was done before the app was ready to receive it.

**Comment by dieterdreist** [comment]
Yes, I use the beta, with latest it works now as expected. great!
