### ISSUE TITLE
orthopedics should be Orthopedics 

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#366]
![524E9BBE-BA43-472C-897F-ACA08FD92AE6](https://user-images.githubusercontent.com/50059322/87236228-185af380-c382-11ea-8b85-120c723fa810.png)
![FAC60D64-8980-41BC-B348-8C54CB643ED2](https://user-images.githubusercontent.com/50059322/87236229-1b55e400-c382-11ea-9eae-b6907c9979ed.jpeg

**Comment by bryceco** [comment]
Are you concerned about the spelling or the capitalization? For spelling British spelling is used since OSM is a British project. For capitalization the actual tag is almost always lowercased, but the Common Tags view capitalizes a few things when it can do so safely given context.

**Comment by TheAdventurer64** [comment]
It was about the capitalization. I appreciate the clarification, however, the tag selector for Orthopedics is capitalized. 
![19335068-7C0D-4B5A-99FC-550FBEDCE2D5](https://user-images.githubusercontent.com/50059322/87389175-f5773d80-c541-11ea-87ae-7092ba4abd6f.png)

**Comment by bryceco** [comment]
Won't Fix, because even thought its possible to fix the likelyhood of introducing subtle bugs in the process is too large

**Comment by TheAdventurer64** [comment]
#392

**Comment by bryceco** [comment]
Did it get fixed?

**Comment by bryceco** [comment]
Fixed in 8b33be12cdceaf0e7813580c8d7e1ec38ba2a01d
