### ISSUE TITLE
“(new object)” should be “Node”

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#368]
![7B6CE746-D7BE-4ABE-89AE-6ACF4C4A0596](https://user-images.githubusercontent.com/50059322/87389310-3bcc9c80-c542-11ea-9b0c-5d02e6fab06c.png)

**Comment by dieterdreist** [comment]
or “new node”?

**Comment by bryceco** [comment]
It could be a node, or the beginning of a way.

**Comment by TheAdventurer64** [comment]
“New Node”?

**Comment by bryceco** [comment]
This needs to be part of a larger discussion on terminology. iD uses the terms Point/Line/Area and in the Presets view those names leak into the interface, while node/way is used other places. 260189a79d1bacb90b40b68a2104396af57814ba moves things toward removing the Point/Line terminology (which was introduced more or less accidentally).
