### ISSUE TITLE
Join ways feature validation only works from one side

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#370]
I have https://www.openstreetmap.org/node/6796385933

Joining from one side shows the error as expected. But not from the other side. 

See **video** https://share.icloud.com/photos/0ZvpV5tHihlJzDn2C3vSAEemw

To reproduce you have to reset the tags if the middle section to what they where before my edit yesterday; like they are in the video. 
Curiously with the new tags the error is shown both times which is correct. 

Idea: does the validation maybe only check known preset tags?

Maybe related to https://github.com/bryceco/GoMap/issues/320

**Comment by bryceco** [comment]
Good catch! Not related to #320, in fact its a bug much older than that!
