### ISSUE TITLE
UI Improvements Idea

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#372]
So, I was thinking about an idea of how to improve the UI in Go Map!!

You could move the current location, 3D Button, and the Information button to the upper right, similar to what Apple Maps did. After this, you could replace the old current location slot with a search button.

**Comment by TheAdventurer64** [comment]
Will a 3D button be added in the feature?

**Comment by bryceco** [comment]
No, in fact I'm considering removing the 3-D support entirely.
