### ISSUE TITLE
wheelchair=Yes

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#374]
On vacation I mapped a [wheelchair-accessible shower on a camp-site](https://www.openstreetmap.org/node/7728227028/history) through the 'common tags' window.
GoMap added `wheelchair=Yes` to the shower, which [Osmose did not like](http://osmose.openstreetmap.fr/en/map/#zoom=16&lat=47.0023971&lon=5.6628808&item=3040&level=1).

I guess the tag added should be 'wheelchair=yes', in lowercase.

TestFlight Version 1.8.3 (1830) on an iPhone SE (Original) with iOS 13.5

**Comment by bryceco** [comment]
Seems to be another case of #365

**Comment by bryceco** [comment]
Thanks for noticing and reporting this! I wasn't able to reproduce it before but this allowed me to fix it.
