### ISSUE TITLE
Update UI for tagging

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#378]
So, as you can see here, the preset results  need to be updated, and the UI looks ancient. Could someone remove the lines and possibly change the font? That would help fix this greatly.
![783B66A1-6254-4E15-BEEA-DF487ACEDED2](https://user-images.githubusercontent.com/50059322/88708587-95d77100-d0af-11ea-89f1-854418c3c256.png)

**Comment by bryceco** [comment]
The tag values come from https://taginfo.openstreetmap.org/keys/building#values
and represent all values used at least 1% of the time. I suppose we could adjust the cutoff when the number of results is small?

**Comment by bryceco** [comment]
I’m using the default appearance and font, similar to the look used in the iOS Contacts app. Can you provide a pointer to a look you think would be better? I agree that a non-bold font would look nicer

**Comment by TheAdventurer64** [comment]
![B324039C-3175-4318-9A23-0CE142926168](https://user-images.githubusercontent.com/50059322/88725636-1f933880-d0c8-11ea-9a7a-9a95c5724177.png)
Maybe something like this?

**Comment by TheAdventurer64** [comment]
![F3D353E8-0CB7-466E-B49A-2089E6EC82D1](https://user-images.githubusercontent.com/50059322/88840323-ff22b700-d177-11ea-9686-4dcde19becc8.png)
Actually, I think this would look better.

**Comment by TheAdventurer64** [comment]
Could I see the new UI?
