### ISSUE TITLE
draggable buttons in latest

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#379]
Just wanted to let you know that 3 buttons aren’t draggable in latest testflight:
undo
redo
upload

**Comment by bryceco** [comment]
As stated in the initial window: they become draggable when they are no longer disabled (so just make a couple edits and then undo one of them).

**Comment by dieterdreist** [comment]
my bad, the feature distracted me and I started dragging buttons rather than mapping 😔
