### ISSUE TITLE
The app buttons need a UI update

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#381]
So, if you look at the new TestFlight version of Go Map!!,
it allows you to move the buttons around. I think that this is okay, as even though it is a temporary feature, it allows users to move their buttons around. The reason why I’m not a big fan is because it can be confusing to some people, and the buttons just don’t look modern. Bryce, if you are reading this, could you maybe do a complete overhaul of the button images?

Thanks,
TheAdventurer64

**Comment by bryceco** [comment]
Moving buttons is just to allow beta testers to explore and prototype different layouts, it won’t be present on the App Store. 

I’d love to revamp the look of the buttons. Please submit artwork!

**Comment by TheAdventurer64** [comment]
You could probably get them from here: https://icons8.com/icon/3059/undo

**Comment by bryceco** [comment]
Fixed in d1c13c1cec2caacd636a39296026980075f8f92a

**Comment by TheAdventurer64** [comment]
Could I see a screenshot of the new buttons?

**Comment by bryceco** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-07-31 at 16 58 26](https://user-images.githubusercontent.com/279734/89088849-4c0cb600-d34f-11ea-94c0-ca28a56665f4.png)
