### ISSUE TITLE
Add ability to AirDrop GPX Traces

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#383]
To share GPX tracks, you currently have only two options: You can either share them via mail, or you can upload them to OpenStreetMap. This is a problem, because as time changes, the app doesn’t support the latest features. So I propose that we overhaul this by replacing the share button with the new one, and add AirDrop support.

**Comment by bryceco** [comment]
If we replace the share button completely we lose the ability to upload directly to OSM don’t we? We can replace the email option with the modern share window though.

**Comment by TheAdventurer64** [comment]
Yeah.

**Comment by TheAdventurer64** [comment]
![1580EC23-61EA-468D-ABFE-AC5A964F05ED](https://user-images.githubusercontent.com/50059322/88858788-40c15b00-d194-11ea-9a93-6c92b316b967.jpeg)
Couldn’t you just add it here?

**Comment by bryceco** [comment]
That might be possible buts it's not a simple thing to do. I believe it requires writing a general purpose gpx upload extension that would be available system wide.

**Comment by TheAdventurer64** [comment]
Well, maybe you could do what you suggested first, and roll out the version I suggested in a later update.

**Comment by bryceco** [comment]
I prototyped this. It mostly works except that GPX files aren't a first-class citizen in the Apple ecosystem, so it transfers as a regular text file with .txt extension, or as just a long string inside an email message (and probably other apps I didn't test).
