### ISSUE TITLE
Add `Extract Node` to the More section of buildings

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#385]
So, if you go to the More section of a building (that has tags related to a POI), there should be a feature to extract those tags to a node, similar to the function of the same name in iD.

**Comment by bryceco** [comment]
While not as straightforward, this is pretty easily accomplished using Copy Tags, and Paste Tags. The iD Extract (#276) behaves differently I believe.

**Comment by TheAdventurer64** [comment]
You can do that with iD as well, but what Extract does is it centers the node within the building for you. Plus, it doesn’t copy the building tags, contrary to using Copy Tags.

**Comment by dieterdreist** [comment]
sent from a phone

> On 1. Aug 2020, at 04:02, TheAdventurer64 <notifications@github.com> wrote:
> 
> ﻿
> You can do that with iD as well, but what Extract does is it centers the node within the building for you. Plus, it doesn’t copy the building tags, contrary to using Copy Tags.
> 
> 
> 


IMHO this functionality would encourage bad mapping style. Can you explain when it would be useful?

**Comment by TheAdventurer64** [comment]
Easy. For example, if there is a retail building with a Safeway in the middle, but tenants in the front. You wouldn’t want to mark Safeway as leasing the entire building, you want to mark it as the main tenant with other shops in the front.

**Comment by dieterdreist** [comment]
sent from a phone

> On 1. Aug 2020, at 09:10, TheAdventurer64 <notifications@github.com> wrote:
> 
> Easy. For example, if there is a retail building with a Safeway in the middle, but tenants in the front. You wouldn’t want to mark Safeway as leasing the entire building, you want to mark it as the main tenant with other shops in the front.


why would a node in the geometric center of the building accomplish this? A polygon would be a better representation

**Comment by TheAdventurer64** [comment]
I think the extract node would would work well in these kinds of cases, where since the POI type doesn’t render as a area, you need to convert the tags into the node. Example here: 
![0694B14E-7396-43C2-B7DF-5152FC0804BE](https://user-images.githubusercontent.com/50059322/90161069-4d19ec00-dd2e-11ea-82c0-7ec550da5636.png)

**Comment by dieterdreist** [comment]
sent from a phone

> On 13. Aug 2020, at 18:29, TheAdventurer64 <notifications@github.com> wrote:
> 
> I think the extract node would would work well in these kinds of cases, where since the POI type doesn’t render as a area, you need to convert the tags into the node.


My suggestion would be to amend the renderer rather than fuzzing with the data in these cases. Generally a polygon is superior to a node as it conveys information about extent, shape and orientation

**Comment by bryceco** [comment]
I agree with @dieterdreist that converting areas to nodes isn't something we want to suggest as a typical action

**Comment by tordans** [comment]
> converting areas to nodes isn't something we want to suggest as a typical action

Just in case this was misunderstood. The way I understand the iD feature is: There are situations, when there are two presets applied to one form. The extract splits those presets. For example: You have a building that also has shop-related tags. Once you "extract", the shop becomes a node but the building stays a building. With this operation, some tags like address are duplicated since both objects can hold them. 

Update: I just see this [short definition by quincylvania](https://github.com/openstreetmap/iD/issues/7862#issuecomment-667173140): _"The intention has been for the Extract operation to easily separate out a POI from an area in one click."_

**Comment by dieterdreist** [comment]
sent from a phone

> On 21. Aug 2020, at 06:35, Tobias <notifications@github.com> wrote:
> 
> Update: I just see this short definition by quincylvania: "The intention has been for the Extract operation to easily separate out a POI from an area in one click."
> 


arguably it is still a loss of information. Separating buildings from POIs may have its benefit, but the POI could still remain an area.
