### ISSUE TITLE
Suggestion regarding buttons

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#386]
So today, the developer of Go Map!! released a screenshot of the new button layout for the app. It looks amazing, however, it could use some tweaks.

(https://user-images.githubusercontent.com/50059322/89089562-9f740980-d339-11ea-8726-3ae4e9dee36c.png)

1. The information button should be above the compass, making the layout look nicer and more professional.
2. The upload button image looks way too big. If possible, resize the button to look the same size as the other button images.
![651EE94D-90CE-415E-9D9B-C36E8FBE204F]

**Comment by bryceco** [comment]
That screenshot is just the layout of the moment. I'm still watching comments at #380. 
I'm still looking for an SVG graphic for cloud upload. The current image is a placeholder.
