### ISSUE TITLE
Information Button

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#388]
So, the current information button looks pixelated and unprofessional. The devs should make the button more HD to fit in with the UI revamp. I also that while this is happening, tapping the info button should redirect to a ”Contact Us” section, similar to the one found in settings, along with a “View this Page in Wiki” button.

**Comment by bryceco** [comment]
The help (i) button is the built-in system button, I'm not providing the image for it. It doesn’t look pixelated to me: 
![B2F320EB-4D74-41F9-9B0D-42CBBC03206C](https://user-images.githubusercontent.com/279734/89096814-42ef0980-d38e-11ea-9583-1bfc7c171cb2.jpeg)

**Comment by dieterdreist** [comment]
sent from a phone

> On 1. Aug 2020, at 09:25, TheAdventurer64 <notifications@github.com> wrote:
> 
> So, the current information button looks pixelated and unprofessional. The devs should make the button more HD to fit in with the UI revamp. I also that while this is happening, tapping the info button should bring up a “About Us” section, similar to the one found in settings, along with a “View this Page in Wiki” button.
> 


I would like to reiterate to remove it, and move the contents into the settings menu (cog wheel)

**Comment by bryceco** [comment]
I'm very likely to move Help under Settings in the near future.

**Comment by TheAdventurer64** [comment]
Oh. I thought it was pixelated. If you do keep the button, do you think you could get rid of the "white barrier" around it?

**Comment by dieterdreist** [comment]
sent from a phone

> On 1. Aug 2020, at 09:47, TheAdventurer64 <notifications@github.com> wrote:
> 
> Oh. I thought it was pixelated. If you do keep the button, do you think you could get rid of the "white barrier" around it?


I think it’s needed for the contrast, but it should be the same shape and size as the other “minor” buttons.

**Comment by bryceco** [comment]
There are 3 options here: Keep the button "as-is", replace it with a button that looks like the other buttons (size/shape), or delete it and put an entry under Settings. Please vote :)

**Comment by dieterdreist** [comment]
my order of preference:
move to settings
reformat button
keep

**Comment by tordans** [comment]
For the way I use the app, I vote to move to settings. We have actions that are used a lot more that could use the space. 

But I wonder, what was the intended usecase for the link in the first place? And if that would still be "solved" after the move? Or is something else like a welcome message needed to compensate?

**Comment by bryceco** [comment]
It would be great to have a tutorial mode on first run which would largely remove the need for the help button.

**Comment by TheAdventurer64** [comment]
Agreed. We could either integrate  a YouTube tutorial, or the devs could code something that would boot up for first time users.

**Comment by bryceco** [comment]
I did this video tutorial but of course it's obsolete now: https://m.youtube.com/watch?v=GUWg4d-jt5o
