### ISSUE TITLE
Cuisine not formatting correctly

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#392]
So, as you can see here, the cuisine is set to `Coffee Shop`.
![E6590993-A500-477D-8183-265F1C1336B4](https://user-images.githubusercontent.com/50059322/89110853-a9097a00-d3ea-11ea-997a-535f7546a743.png)
However, on the editor screen, the cuisine is marked as `coffee_shop`. 
![E12BEAD0-A5C3-483C-B0DC-981C7E0C12C3](https://user-images.githubusercontent.com/50059322/89110897-45338100-d3eb-11ea-8ba5-4c0fe2718b00.png)

I feel this doesn’t look very professional and should probably be fixed.

**Comment by bryceco** [comment]
This is a bit of an edge case. When we display the possible values in the picker view we take raw values like "coffee_shop" and programmatically remove the underscore and uppercase the value (to make it look pretty). When we display it later we display the raw value. Its possible we could do the same conversion later, but it's a bit counterintuitive, and possibly incorrect, because if you type in "Coffee Shop" we can't automatically do the opposite conversion to retrieve the original OSM value (there's no guarantee that the user intended for his typed text to be transformed).

**Comment by TheAdventurer64** [comment]
I’m wondering, there is a similar thing with
 `crossing=traffic_signals`, but the editor screen marks it as `Traffic Signals`. 
![8A696E5B-6202-452B-955E-A3CC499DD201](https://user-images.githubusercontent.com/50059322/89129074-060e3a00-d496-11ea-9187-a7b3a8f9b4a0.png)
![75D6E4EF-AE29-44D6-A01C-C35D5439E6D9](https://user-images.githubusercontent.com/50059322/89129110-54233d80-d496-11ea-92f3-3bf805f24701.png)

**Comment by bryceco** [comment]
The difference between the two cases is that for traffic_signals there is a built-in preset that establishes a bidirectional equivalence between the key/value and the "friendly" text. With cuisine there are no presets, instead the possible values are fetched from the TagInfo service, and the friendly text is essentially a best guess.

**Comment by bryceco** [comment]
If you switch your language to something non-English you'll notice that values from presets are shown in the selected language, while values from taginfo are still in English.

**Comment by dieterdreist** [comment]
sent from a phone

> On 2. Aug 2020, at 21:10, bryceco <notifications@github.com> wrote:
> 
> If you switch your language to something non-English you'll notice that values from presets are shown in the selected language, while values from taginfo are still in English


what I noticed with recycling containers (but likely with other tags it’s the same, in the preset tab, it shows translated keys and values, but when you select (for example in Italian “sì”=yes) it will show “yes” in the overview list

**Comment by bryceco** [comment]
> what I noticed with recycling containers (but likely with other tags it’s the same, in the preset tab, it shows translated keys and values, but when you select (for example in Italian “sì”=yes) it will show “yes” in the overview list

Sounds like a bug :)
