### ISSUE TITLE
Need ideas (pros, cons, recommendations) about combining Common Tags and All Tags

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#393]
I understand a lot of power mappers prefer to do things in All Tags, while Common Tags is oriented towards casual mappers and beginners. Personally I almost never use All Tags, except when I want to check if there are tags I should be concerned with that don't appear in Common Tags (because they don't have a preset). 

It would be great if Common Tags shows what it already shows, but also shows additional tags that had no Preset equivalent ("tiger:reviewed=no" etc), plus the ability to add arbitrary tags like All Tags supports. I'm looking for suggestions on how to combine these views in a way that is useful to experts while not being a burden to beginners. 

One possibility: Use current layout for Common Tags displaying all tags that are defined within the current sections (Address, etc). Then show all All Tags with key/value pairs that aren't defined by previous Common Tags. Then show Common Tags that aren't yet defined. Then display an empty All Tags key/value line that will move into position when a key/value is entered.

**Comment by batyrmastyr** [comment]
There is one issue with iD’s presets: some of them  intentionally violate community decisions therefore inadequate and we need some way to write correct tags.

**Comment by dieterdreist** [comment]
sent from a phone

> On 7. Sep 2020, at 20:03, Evgeny <notifications@github.com> wrote:
> 
> ﻿
> There is one issue with iD’s presets: some of them intentionally violate community decisions therefore inadequate and we need some way to write correct tags.
> 


maybe these aren’t set in stone, let’s see how things evolve now, as the iD maintainer has changed. It may be worth trying another time to fix these issues one by one in iD.

**Comment by bryceco** [comment]
The quality of the presets is an orthogonal issue. That discussion should take place on the iD GitHub. 

Since no feedback on the original proposal seems to be forthcoming I'm closing this for now.
