### ISSUE TITLE
Add share to the app icon context menu

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#395]
Today I was looking to share the app and noticed that the option is missing. If it's something that is added easily, this would be convenient. 

Example with share from Mapillary:
![image](https://user-images.githubusercontent.com/111561/89130520-ed3d6d00-d505-11ea-8748-78d245b5a00e.jpeg)

Go map without:
![image](https://user-images.githubusercontent.com/111561/89130540-f3334e00-d505-11ea-8db7-42a9d622027e.jpeg)

**Comment by bryceco** [comment]
The share button will display if you install the version in the App Store (not a beta).

**Comment by tordans** [comment]
That makes sense! Thanks.
