### ISSUE TITLE
delete node not working (always)

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#396]
Today I tried to remove some duplicate pois, but it didn’t work consistently. After a moment I remembered you had to remove all tags (?) which I did but even then it would not remove it. Only at the second or third try it did. 
This could be improved by showing some feedback (something like “the node has tags”) rather than simply unselecting.

**Comment by bryceco** [comment]
There’s no requirement to delete tags before deleting a node. What you describe might be a node that belonged to multiple ways, and it was deleted from one way but it remained in the other. Still a bug though.

**Comment by dieterdreist** [comment]
it was also the ruler interfering...

**Comment by bryceco** [comment]
Fixed by removing the ability to move the ruler.

**Comment by bryceco** [comment]
Unfortunately this is still broken

**Comment by bryceco** [comment]
Fixed in 1.9.5
