### ISSUE TITLE
more button not working for new node in way

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#397]
when you add a new node in a way and tap “more” the node gets unselected and nothing happens

**Comment by dieterdreist** [comment]
it happens also for existing nodes

**Comment by bryceco** [comment]
Looks like there is some interference introduced by the recent movement of the Ruler view (“x meters, y feet”) behind the More button. You can work around this bug by dragging the ruler to a new location. Or you can tap very carefully along the edge of the More button.

**Comment by dieterdreist** [comment]
thanks, that was it. I guess this could be closed then?

**Comment by TheAdventurer64** [comment]
#401

**Comment by bryceco** [comment]
Still broken in 1.9.2

**Comment by bryceco** [comment]
Fixed in 1.9.5
