### ISSUE TITLE
detach POI

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#398]
I’m finding frequently POI nodes that someone has made part of a way or polygon, although topologically they should not be part. There should be a detach POI function to detach these nodes while retaining their id (history/versions), i.e. the way should get a new node and the existing node should unconnect

**Comment by bryceco** [comment]
Is this a duplicate of #276?

**Comment by dieterdreist** [comment]
yes, sorry for the noise, I added a comment with what I thought to be important to #276.

**Comment by bryceco** [comment]
Thanks! I’ll try to prioritize this feature.
