### ISSUE TITLE
Provide Tag templates

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#40]
I would like to specify a given set of tags, name that set and when editing an object I want to be able to select one of those sets and the tags of the set are now added to the object. Maybe also the possibility to replace all tags of the object with the tags of the set. This would be very helpful for e.g. address mapping.

**Comment by dieterdreist** [comment]
yes, yes, yes, I also support this, it would be very helpful. I could imagine presets like the ones described here, but also editing the list of known tags (to add tags that are common in your area so they can be autocompleted) would be nice.

**Comment by dieterdreist** [comment]
maybe you could integrate support for JOSM presets? There is many of them, and its a well documented generic XML format.
These are the currently available presets: https://josm.openstreetmap.de/wiki/Presets
And this is documentation of the format: https://josm.openstreetmap.de/wiki/TaggingPresets

**Comment by bryceco** [comment]
Closing because discussion has moved to #323
