### ISSUE TITLE
Problem: Black Utility Bar is Too Low

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#401]
So, if you look at the new button layout, (Regardless if it changes or not, there will probably always be buttons on the bottom of the screen.) you’ll notice that the black utility bar is really close to the buttons.
![B5DCDD01-7CFB-4A41-8EB4-BBBE6CE0E62D](https://user-images.githubusercontent.com/50059322/89243737-6f7a6f80-d5a0-11ea-8c0b-af01de7d8d69.png)
Now this is a issue design wise as the bar (I feel) is too close to the buttons. This is also a problem as because the utilities bar is too low, I’ve had problems accessing the Tags and More section.

**Comment by bryceco** [comment]
I'll raise it a little in the next beta.
