### ISSUE TITLE
Go Map!!’s loading page hasn’t been updated 

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#404]
So, although the new logo is great, the logo for the loading screen hasn’t been updated. This is a uniformity issue. 
![8C37159F-A3A3-4120-A3F5-85B3C59EA1E9](https://user-images.githubusercontent.com/50059322/89363294-86d25f00-d66b-11ea-84ea-6626cad4b5e6.png)

**Comment by bryceco** [comment]
Good point!

**Comment by TheAdventurer64** [comment]
> Good point!

Thanks.

**Comment by pqhf5kd** [comment]
I looked at updating the Launch Screen with the new logo but the logo has a gradient so it's not as simple as using the same background colour. I tried the blue, green and yellow but they are all quite bright.
<img width="460" alt="image" src="https://user-images.githubusercontent.com/20027419/90309588-d02f7380-dee1-11ea-9091-b8bda72b95c8.png">

**Comment by dieterdreist** [comment]
sent from a phone

> On 15. Aug 2020, at 11:28, pqhf5kd <notifications@github.com> wrote:
> 
> I looked at updating the Launch Screen with the new logo but the logo has a gradient so it's not as simple as using the same background colour. I tried the blue, green and yellow but they are all quite bright.


we should probably use a version of the app icon here with transparent background and add a gradient to the background view instead.

**Comment by pqhf5kd** [comment]
I submitted a pull request with a transparent background logo and a flat background view because it can't set programatically. The gradient could be applied as an image but that would increase file size.

**Comment by tordans** [comment]
IMO the loading screen would be a good place to also show the OSM Logo. Maybe with a tagline like "Edit OpenStreetMap on the go". 
This would help new users to understand that this app is an editor for OSM.

**Comment by pqhf5kd** [comment]
> I submitted a pull request with a transparent background logo and a flat background view because it can't set programatically. The gradient could be applied as an image but that would increase file size.
> 
> #407

I messed up so I've tried again under #409

**Comment by pqhf5kd** [comment]
> IMO the loading screen would be a good place to also show the OSM Logo. Maybe with a tagline like "Edit OpenStreetMap on the go".
> This would help new users to understand that this app is an editor for OSM.

On my XS, the launch screen is shown so briefly that I'm not sure new users would have time to comprehend

**Comment by bryceco** [comment]
The screen will display longer if you download a bunch of OSM data.

**Comment by pqhf5kd** [comment]
I tried clearing the caches and force quitting but it still only appears briefly.
Of course I'm not doubting you, I'd just like to to recreate it :)

**Comment by bryceco** [comment]
Don’t clear the cache, load it up so you have 50,000+ objects. Then kill the app so it has to reload it all from disk.

**Comment by bryceco** [comment]
Fixed in bfcd13e6e77c0a404604ef762f325ec27729193f
