### ISSUE TITLE
Unable to connect to http server

### ISSUE THREAD

**Issue by harkle** [bryceco/GoMap#406]
Hello,

I need to connect to a local OSM server running on a VM with no HTTPS. It seems GoMap! always add "https" as a prefix to the adress.

**Comment by bryceco** [comment]
This is an effect of #202. Your connecting to 127.0.0.1?

**Comment by harkle** [comment]
Thank you for your answer. I'm trying to connect to http://192.168.0.95/api/ a VM machin on a local dedicated server. Is there anyway to avoid the HTTPS autoswitch?

Thank you.

**Comment by bryceco** [comment]
I looked into this and it appears that it isn’t switching http to https. It’s striping the http:// part (but not https) when displaying it in the Settings view but I believe it’s using http to make the request. I might be wrong so let me know if you have other evidence.

**Comment by harkle** [comment]
In my case it switch back to https.

1. I enter http://192.168.0.95/api/ and go back to general preferences;
2. I reopen the server settings its now set to 192.168.0.95/api/
3. I go set my username/password;
4. I reopen the server settings and it now set to **https://**192.168.0.95/api/

It seem the app get back to https when I set username/password.

**Comment by bryceco** [comment]
I'm not seeing that behavior myself but I'll look into it.

**Comment by bryceco** [comment]
Fixed (as an accidental side effect) in ca0424b2d4201a36801bb69b4dc70a09f9d9e4a4
