### ISSUE TITLE
Text version of the logo

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#408]
Now, that there is https://github.com/bryceco/GoMap/issues/236 and a new launch screen, I should it would be ideal, to also create an official SVG text-line-version (German: "Wortmarke") of the "Go Map!!" Name.

This way its consistent in terms of typo and spacing.

From a design point of view this should IMO look at: how italic is the italic, which type to use, how big is the space between Go and Map (less than a full space) and such.

We should then use this in #404 (Loading Screen).

Ping @Binnette since you created the new image-logo

**Comment by Binnette** [comment]
Hi @tordans, very good idea. When I have some time to spend. I will make some 'propositions' 👍

**Comment by bryceco** [comment]
Is this really something that's expected? Is OpenStreetMap, iPhone, Apple, FaceBook, etc localized? I don't believe so. These are all proper nouns and shouldn't be translated.
