### ISSUE TITLE
alt_name is a valid tag.

### ISSUE THREAD

**Issue by newnumber2** [bryceco/GoMap#413]
Please add the alt_name tag. It is a valid tag, used all the time in iD, Potlatch, etc., and is especially laborious to have to type each time.

Thanks

**Comment by wtimme** [comment]
Hey @newnumber2, did you know that you can add presets? A preset allows you to have a certain key always visible when editing an element that has a given key/value combination. You can customize your presets from the "Common tags" screen.

Does that help?

**Comment by bryceco** [comment]
I added the list provided by @dieterdreist. These will be available for autocompletion in All Tags. For Common Tags @wtimme's suggestion applies.
