### ISSUE TITLE
duplicate nodes created with make circular

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#414]
It just happened, duplicate nodes have been created: draw a closed way with 3 nodes, “make circular”:

![F85233AC-35CB-4512-A0F7-F6D2465D4549](https://user-images.githubusercontent.com/581288/91864800-f9395d80-ec70-11ea-926a-780423df110e.png)

**Comment by dieterdreist** [comment]
actually I cannot reproduce it now, something happened (maybe a gesture?) and it duplicated the nodes (in the description above), just the above steps works fine now

**Comment by bryceco** [comment]
I'm fairly certain this is a caching issue, not related to Circularize. Dup of #206.
