### ISSUE TITLE
Have a way of disabling the "Attention Testers!" dialog

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#417]
> As a tester, I do not want to be reminded constantly that the buttons on the map are movable.

![attention-testers](https://user-images.githubusercontent.com/1681085/92091219-babab480-edd0-11ea-8fad-99335192f170.png)

Especially during development, this dialog is very annoying.

## Suggested solution

The dialog could have a "Don't remind me again" button that, when tapped, sets a Boolean in the `UserDefaults`. Before displaying the dialog, the Boolean is being checked. If it was set, the dialog is not displayed.

![attention-testers-dont-remind-me-again](https://user-images.githubusercontent.com/1681085/92091429-08372180-edd1-11ea-842c-f0773dd3e989.png)

## Other solutions

- Only display the dialog once. (Set the Boolean in the `UserDefaults` when the user taps "Ok".)
- Add an "Advanced Setting" that allows users to control either the dialog, or the movable buttons themselves. (Having control over whether the buttons are made movable would be good for testing as well, given that we need to be able to test the "normal" button layout that is still existent and visible to end-users.)

**Comment by bryceco** [comment]
This will be removed in the next TestFlight release.
