### ISSUE TITLE
Setup CI to automatically release a nightly TestFlight Beta

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#426]
> As a TestFlight tester, I want to receive a nightly TestFlight Beta, so that I can start testing these changes as soon as possible.

## Acceptance criterias

- Once per day, a new build is created
- The build is unit-tested. In case the tests fail, the release is stopped.
- The new build is uploaded to TestFlight
- After processing, the build is automatically released in TestFlight
- This process runs automatically, without interaction needed from @bryceco 

## Ideas

Since the project is hosted on GitHub, we could make use of [GitHub Actions][github-actions].

[github-actions]: https://github.com/features/actions

**Comment by bryceco** [comment]
Builds still need to be reviewed by Apple before being released by TestFlight so there may be a 24-hour delay before you see the beta. I don't know if there's an issue with "spamming" the review process if several pull requests are applied on the same day.

**Comment by wtimme** [comment]
Thanks for the feedback!

>  I don't know if there's an issue with "spamming" the review process if several pull requests are applied on the same day.

That's a good point. "Whenever changes are pushed to `master" might happen multiple times per day.
A daily build (e. g. with a [scheduled action][schedule-action]) might be better.

The fastlane lane that is being run can be configured in a way that it only uploads a new version when there were any changes.

---

What do you think of the proposal to make use of GitHub actions? If that was an option for you, I could gone ahead and research what needs to be done, as well as help you with testing and the configuration.

[schedule-action]: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule

**Comment by bryceco** [comment]
I don't know anything about GitHub actions, so if you think that's the best approach that's fine.

**Comment by wtimme** [comment]
As a first step, I've configured _fastlane_ so that you, Bryce, can now run a lane which will test, build and sign the current branch.

**Please test the changes by releasing a new Beta, to make sure that everything is working on your end.** Once the testing is successful, I'll see to it that we configure the GitHub Actions.

If you need any assistance with testing, or have any questions/concerns, please don't hesitate to reach out.

**Comment by bryceco** [comment]
I'm excited to try this but haven't had a chance yet to try it out. Last time I tried using fastlane I got weird errors so I'll probably need help getting things configured.

**Comment by wtimme** [comment]
No worries, it should be fairly straight-forward. I've added [instructions][1] to the README to help with the setup.
If you do encounter errors, it might point us to a lack of documentation that we can resolve together.

[1]: https://github.com/bryceco/GoMap/pull/428/files#diff-04c6e90faac2675aa89e2176d2eec7d8R13

**Comment by bryceco** [comment]
For MATCH_REPO can that be a local git repo or does it have to be hosted? And what is the URL syntax for a local repo?

**Comment by wtimme** [comment]
Nice, I'm excited that you're trying it out.

To be honest, I haven't tried it with a local Git repository, but I don't know why it shouldn't work.

The fastlane docs recommend:

> First, enter the URL to your private (!) Git repo (You can create one for free on e.g. GitHub or BitBucket). The URL you enter can be either a https:// or a git URL.

**Comment by bryceco** [comment]
I'm getting this pop-up constantly now. I haven't yet started to create a MATCH_REPO yet or anything:
![Image 9-14-20 at 1 12 PM](https://user-images.githubusercontent.com/279734/93133441-1536f900-f68c-11ea-8d6f-5121e3359504.jpeg)

**Comment by wtimme** [comment]
My bad. I forgot to add an action that removes the Keychain again. I'll create a pull request that fixes the Fastfile.

In the meantime, you should be able to remove the Keychain by running

    % bundle exec fastlane run delete_keychain name:"fastlane_keychain"

from the `src/iOS` directory. Sorry about the inconvenience!

**Comment by TheAdventurer64** [comment]
How is this coming? Is it still being worked on?
