### ISSUE TITLE
Improve Wikilink

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#427]
I tested the MVP wikilink feature on the all-tags-view and I really like it. It helps a lot to be able to quickly check the wiki for details of eg. surface-values (the example pictures); or to check, if at tag like ramp=yes is the right way to map it.

I have two main issues with the current implementation

1. The click area is broken. One can click at the small area below an imput an still trigger the wiki-url-open.
Possible solution: The click area should only be the icon (arrow).

2. The arrows on AllTags + CommonTags look the same but behave very differently. Since I use both views a lot, this is confusing.
Possible solution: The icon should be something more descriptive than an arrow; and not be reuse for something else somewhere else.

3. It would be great to access the Wiki links on the CommonTags as well; but IMO not too important.

Ideas for a solution:

How about moving the wiki link to the drag action? 
![image](https://user-images.githubusercontent.com/111561/92357726-9caec600-f0e8-11ea-9ac6-58ee0bf1fdd7.jpeg)

The primary action would be to delete the value (continue drag or tab the option). The secondary action to open the wiki (tab the option).

I think such an option is better, than adding an icon to each row since this would clutter the UI.
Other ways to avoid the clutter could be to only show actions once the row is active (like cursor in the input), but that’s more complex from a UI point of view IMO.

**Comment by wtimme** [comment]
I agree that the current solution can be improved.

> How about moving the wiki link to the drag action?

I love it, but it [looks like][1] these actions have only been introduced with iOS 11. So if we were to use these actions, we would need to either drop iOS 11 support, or have two alternative ways of interacting with the wiki links.

[1]: https://useyourloaf.com/blog/table-swipe-actions/

**Comment by bryceco** [comment]
Here's my attempt to improve this. While putting the actions in the drag action saves space, I'm concerned about whether it's sufficiently discoverable? I personally rarely drag items:
![IMG_3684](https://user-images.githubusercontent.com/279734/99440055-dcedaa00-28ca-11eb-9cdf-a7f2a5edbee9.png)
