### ISSUE TITLE
Allow mappers to highlight map elements using customizable filters

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#429]
With the "quest" issue closed and OSM Completionist deprecated, I am missing the ability to highlight certain elemens on the map.

I do admit that the question-based "quest UI" was not quite thought through. More thinking must be done for such an UI.

How would you feel if we integrated Overpass (Wizard) queries as some sort of filters that mapper can enable?

For instance, say I found it fun to map benches and their "backrest" tag. What I would like to have is a way to tell whether a bench on the map is lacking that tag.

Right now, I need to tap every object and manually look at its tags.

Mappers would be able to add filters and enable/disable them, one by one.

Objects that match the enabled filter(s) cound have an indicator (e. g. a circular ring).

For taps, a highlighted element does not behave differently as a non-highlighted one.

Just like with _OSM Completionist_, no additional network traffic would be required, since the filters apply to the local data. That means the filters work offline as well.

**Does that sound like something that more people could want?** 
I'm certain it would help _me_. And yes, of course, it would be great to recycle some of the time I already spent for the project. ;)

Thanks in advance for your feedback and consideration!

**Comment by dieterdreist** [comment]
sent from a phone

> On 7. Sep 2020, at 22:56, wtimme <notifications@github.com> wrote:
> 
> Does that sound like something that more people could want?


Yes! I could use this as I am looking for fountains which haven’t got an image tag, and for fountains which haven’t got a fountain tag.

There are many tasks (missing properties) I could think of, and being able to highlight them would be great.

**Comment by bryceco** [comment]
I'm fine with the idea of something that allows highlighting. 

I'm wondering if this should be combined with the existing filter UI: for each object it could be shown, hidden or highlighted?

I'm not enthusiastic about using overpass wizard queries. While these are familiar to hardcore OSM users, most users will have no idea what the correct syntax is. A tabular filter system with columns for key, value, equal/not-equal is more user friendly IMO. Such a system allows us to support autocomplete on the key/value names, allows queries to be built up incrementally, and you can easily enable/disable different types of objects. I used such a system for a Windows app and it looked like this: 
![image](https://user-images.githubusercontent.com/279734/92420943-0cde3b80-f12b-11ea-944d-eb5ef7c16d16.png)
Our version would look more like All Tags with some additional columns.

**Comment by wtimme** [comment]
Here is a quick draft I threw together:

![edit-filter](https://user-images.githubusercontent.com/1681085/92639780-9a14c200-f2dc-11ea-9d1b-3895ca502ec2.png)

It only allows for "and" combinations, but it's a start.

**Comment by bryceco** [comment]
That's a good start. I'm not sure about the difference between "equals" and "matches". I'd prefer equals/begins-with/contains. 

As for AND/OR operations these can be inferred automatically. If a key appears multiple times the respective values are OR'd. All other combinations are AND.

**Comment by wtimme** [comment]
"matches" would allow for regular expressions.

**Comment by wtimme** [comment]
So in order to have a version that people can work with and give feedback for, I suggest the following:

1. The app will have a user-managed list of these new filters
2. The user can add/edit/remove filters using the UI pictured above
3. When an element matches the filter, it is highlighted

> you can easily enable/disable different types of objects

We can always add this later down the road. Personally, as pointed out in the original post above, I am looking for the highlighting more than for hiding/showing certain objects, so highlighting is my focus here. But since the filters are quite universal, we can later use them to hide/show objects as well.

Is this a feature that you would be willing to merge, @bryceco? I am asking this since I want to avoid investing time into a feature that benefits me (and, apparently, @dieterdreist as well), only to have its release delayed/objected. (I guess I'm still hurting from #221.) I do realize that there are a ton of other potential use cases for these filters, but we have to start somewhere.

**Comment by bryceco** [comment]
It would be sufficient to initially support highlighting a single type of object defined by a boolean expression with multiple conditions.￼￼ Once that is in place we can move on to having sets of those the user can enable individually. ￼What I'd like to avoid is having a feature that is only usable by a few expert/in-the-know people: if we can make the UI useful for novices I am happy to include it.￼

**Comment by bryceco** [comment]
Merging filtering and highlighting at a later date (or never) is fine.￼

**Comment by dieterdreist** [comment]
sent from a phone

> On 10. Sep 2020, at 07:46, bryceco <notifications@github.com> wrote:
> 
> It would be sufficient to initially support highlighting a single type of object defined by a boolean expression with multiple conditions.￼￼


I think it should support:

1. having a tag or a tag/value or combinations

2. not having a tag should be easy to express (most common case for the feature for me would be highlighting objects of some kind that miss a subtag)

3. maybe restricting to object types (node/open way/relation/closed way)

**Comment by wtimme** [comment]
So, the UI is getting to a point where one of the next steps would be

1. validation of the different conditions (e. g. field `key` must not be empty, etc.) and
2. allowing for conditions to be removed

Does someone have some suggestions on how the UI could look like for these scenarios?

As an MVP, for 2, we could add a button below every condition that reads something like, "Delete", with a red text. Tapping it would simply remove the condition (and its section).

For 1, we could show an `UIAlertView` with the different kinds of errors, e. g.

> Please make sure to enter a "Key" for every condition.
> Please make sure to provide a value for every condition that requires one.

An alternative would be to show the errors in-line, basically beneath every condition. This has the advantage that the user has context and knows where to fix the error.

**Comment by bryceco** [comment]
I'd like validation to be in-line. It could be as simple as a red outline around the incorrect field. If you want to add explanatory text somewhere that's optional (but would be nice). 

We could have an additional line for options which could include: enable/disable, exclude, trash can.

**Comment by wtimme** [comment]
> I'd like validation to be in-line.

What do you think of this?

![filter-validation-error](https://user-images.githubusercontent.com/1681085/93024801-5cc07500-f5f9-11ea-8dc6-85451b3c3bda.png)

**Comment by bryceco** [comment]
Looks great!

**Comment by dieterdreist** [comment]
would also be nice to filter for meta data:
username is/is not
version is 1 / is greater than 2
last modified : today/this week/month/more than 1 or 3 years ago...

**Comment by TheAdventurer64** [comment]
What are the `Equal` and `Do Not Equal` values for?

**Comment by wtimme** [comment]
> What are the `Equal` and `Do Not Equal` values for?

The operations that the mapper can select are the equivalent of the "Tag request clauses (or 'tag filters')" of the Overpass Query Language ([see the wiki](https://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide)).

Equal (and its negation "does not equal") compares a tag's value.

**Comment by bryceco** [comment]
I played with the WIP a bit and although I know its an early version I feel like using UIPicker might be a bit too large and clunky. Its difficult to make selection and then dismiss the picker, or to scroll to other parts of the UI. What do you think of making the query type be a button that pops up a UIAlertController instead? If we do stay with the picker would it be too difficult to have the picker replace the cell in-line rather than below it?

**Comment by wtimme** [comment]
Thanks for taking the WIP for a spin!

Yes, I agree. Even though the picker looks good, expanding and contracting it feels clunky.

For the MVP, we could go with the UIAlertController that you suggested. Good idea!

**Comment by bryceco** [comment]
Closing due to lack of progress.
