### ISSUE TITLE
Redirect Universal Link to OSM.org if Go Map!! is not installed.

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#430]
The [Universal Link support][3] is working great, thanks for adding that!

When visiting the link on my phone, Go Map!! opens and I can start working. If I opened the same link in my desktop browser, however, I am greeted with "Not found".

I did some research and it looks like one way to go is the [addition of some JavaScript][1] on the page. That seems to also be the behaviour that [Apple suggests][2]:

> Universal links work even when your app is not installed. When your app isn’t installed, tapping a link to your website opens the content in Safari, as users expect.

I propose we configure gomaposm.com so that it redirects to OSM.org, basically letting the user edit the map with iD.

[1]: https://stackoverflow.com/a/36046412
[2]: https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html
[3]: https://github.com/bryceco/GoMap/issues/98#issuecomment-663813960

**Comment by bryceco** [comment]
If they click a link on their phone and don't have the app installed we don't want them sent to OSM.com, we want to show them a download link.

**Comment by wtimme** [comment]
Good point!

Can you open-source the website? I would love to help.

**Comment by bryceco** [comment]
I have no website skills  so I used the site builder software the hosting service (hostgator.com) provides. 

Should I create a new directory in our current GitHub and FTP everything into it?

**Comment by wtimme** [comment]
> Should I create a new directory in our current GitHub and FTP everything into it?

I suggest to set up a dedicated repository. It makes it easier to understand the code base, and we have a dedicated issue tracker for website-related things.

**Comment by bryceco** [comment]
https://github.com/bryceco/gomaposm.com now exists. I'll give you commit rights once you accept my invite. Feel free to delete/modify anything except "public_html/.well-known" which is essential for the universal link.

**Comment by wtimme** [comment]
Thank you very much for your quick response, and for creating that repository!

I think we can continue this discussion in bryceco/gomaposm.com#1. I'll therefore close this issue here.
