### ISSUE TITLE
sets tags on way when node is selected 

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#431]
I guess it is a feature, when you select a node of an untagged way and go to the tags, gomap!! will automatically change the selection and select the way. Also happens when you select the node and paste tags (will nonetheless paste to the way).

I could imagine having a modal in between (“do you want to change tags for the way?”).

If this is deemed too intrusive, the thing should exclude untagged ways that are part of a multipolygon relation from this behavior (i.e. add the tags to the node when the node is selected).

**Comment by bryceco** [comment]
I agree, if the way is a multipolygon member it should notice that and not promote the selection.

**Comment by bryceco** [comment]
I just checked the code, and tested, and it should already by leaving the selection on the node when the way is a member of a multipolygon. Can you verify otherwise?
