### ISSUE TITLE
"Incorrect user or password" when uploading changes

### ISSUE THREAD

**Issue by spantaleev** [bryceco/GoMap#434]
I haven't fiddled with my login settings for years. It started doing that with the latest Appstore version (1.8.4). Not sure if it started doing it immediately or something happened later on.

I've also tried the TestFlight build (1.9.5 / 1950), hoping it would fix the issue, but it didn't.

Since them, I've tried going in an changing my credentials in the app's settings (basically entering the same credentials again). I got the "Login successful" message, but trying to upload my changeset still keeps giving me the same "Incorrect user or password" error.

I wonder if my changeset is somehow in conflict or something. Still, I'd expect a less misleading error, if so.

I haven't tried undoing my changes and uploading a different changeset. I was thinking it shouldn't go to waste, but.. I can start over, if necessary.

**Comment by dieterdreist** [comment]
try to delete the app completely. Then install it again. This will receive the internal app specific user settings database

**Comment by bryceco** [comment]
I received a private message reporting this same issue. I don't know if it's the same user. I'd like confirmation that the name/password succeeds when editing in iD.

**Comment by spantaleev** [comment]
It's not me who reported it in a private message.

I can log in at https://www.openstreetmap.org and edit in iD with my user.

By the way, my OSM name has a space in it, not sure if that's to blame somehow.

**Comment by bryceco** [comment]
The other person had a name with non-Roman characters but no space. I don't know if that's a factor. Maybe someone should create a new OSM account to test it?￼ ￼There haven't been any changes to that code path that I'm aware of.￼

**Comment by rossa75** [comment]
I’ve had the same issue. Can log into OSM with no problems. I have reset my credentials and it says that I’ve logged in successfully. Just unable to upload changeset.

**Comment by Demon-999** [comment]
I have the exact same problem. I changed phone and since then I can logon to the website. Also the app tells me the login is OK, but when uploading changes the bad PW/User notification comes up

**Comment by bryceco** [comment]
Can you try changing your password on the website and try again? 

Also, can you enter an incorrect password in the app and verify that the error message displayed is **exactly** the same as you currently see?

**Comment by Demon-999** [comment]
> Can you try changing your password on the website and try again?
> 
> Also, can you enter an incorrect password in the app and verify that the error message displayed is **exactly** the same as you currently see?

Hi, if I enter a wrong password I get the message “Bad Password”. It must be a problem with the authentication routine when uploading in my perception.

**Comment by Demon-999** [comment]
> Can you try changing your password on the website and try again?
> 
> Also, can you enter an incorrect password in the app and verify that the error message displayed is **exactly** the same as you currently see?

![6FA2E659-9EB6-41D1-AC10-592323F08CCF](https://user-images.githubusercontent.com/72313014/95001766-6bcd8e00-05cd-11eb-8d6e-079d0e673c69.png)
![F61B6492-EFE0-4272-9709-01D362826286](https://user-images.githubusercontent.com/72313014/95001769-6ec87e80-05cd-11eb-8912-48e7940fe5e2.png)

**Comment by Demon-999** [comment]
These are the pictures after changing the password.

**Comment by bryceco** [comment]
I really appreciate your help diagnosing this!

https://master.apis.dev.openstreetmap.org/ is a testing/development version of the OSM website. Can you create an account there (identical to your current account), then in the app go to Settings > Advanced > Server and change the URL to this one, and try to replicate the behavior? If you replicate it then maybe I could use that account/server to try to  replicate and debug the issue (you can use a throwaway password that I'll use temporarily).

**Comment by spantaleev** [comment]
I've tried deleting the app and starting from scratch, but it somehow seems to retain its settings. Weird! How does one fully uninstall an app and all its related settings on iOS? I've tried both removing it from the jiggly-icons screen and from somewhere in settings, but each time I reinstall it, it brings it back to the same state.

**Comment by bryceco** [comment]
There's no way to delete the username and password (although you can overwrite them) because those are stored in the keychain. That's an Apple "feature". All other settings should be removed when you delete the app.

**Comment by Demon-999** [comment]
Ok, i registered with the dev site and changed it in Go Map. The result is slightly different. Login successful, upload changes states „unable to upload changes“. So... I guess it is a problem with the API. Maybe they changed anything. 

![333E357F-E783-43DC-9812-4CA996CAFE7C](https://user-images.githubusercontent.com/72313014/95014397-d4a51c80-0646-11eb-83b2-02fbd6a7843d.png)

**Comment by Demon-999** [comment]
@bryceco , if you like to use my account for debugging, please let me know a private Channel where I can send it to you.

**Comment by bryceco** [comment]
If you send a message using Settings > Contact Us > Email it will go to my personal email account. 

I'm traveling for the next week or so but will debug it as soon as I'm back (unless someone else wants to debug it sooner).

**Comment by Demon-999** [comment]
Brilliant, mail with details is on its way. 

Greetings Tim

**Comment by bryceco** [comment]
I was never able to deermine the cause of this, but Demon reports that it's working again. Might be something server side.

**Comment by mmd-osm** [comment]
There was no change on the server side recently. Did this happen when creating a new changeset or uploading the changes (b/c that’s a huge difference where the respective endpoint is being handled)?

**Comment by Demon-999** [comment]
> There was no change on the server side recently. Did this happen when creating a new changeset or uploading the changes (b/c that’s a huge difference where the respective endpoint is being handled)?

Hi,

the problem occurred when I was trying to upload changes to footpaths in France (I am usually in Germany). However, I had changed my phone before and it was the first time trying to make changes with the then newly installed app. 

The problem then persisted for some time while bryceco and I were trying to test it out. Then we left it alone and roughly 3 weeks later I just tried it again and magically it worked. I did some changes already and I can do it all. 

Seems like my user was somehow blocked for a certain time.

**Comment by Demon-999** [comment]
... or my device... more likely my device..

As the device is a company device with Apple DEP... maybe that blocked it until an admin allowed the connection??

**Comment by bryceco** [comment]
@mmd-osm There were maybe a half-dozen people who reported similar issues simultaneously: password validation worked (by fetching api/0.6/user/details) but uploads failed. All of these users were able to upload previously. The app creates a new changeset and then immediately uploads, but I was never able to reproduce it so I don’t know which step failed.

**Comment by spantaleev** [comment]
I can confirm that the problem has disappeared for me as well (running on the new build 1970 now, but..). I'm guessing the API was faulty for a while. Glad to be able to contribute to OSM again!

**Comment by mmd-osm** [comment]
@bryceco : I don't know if it would make sense to add a bit of logging to get a clearer picture about the actual error condition. Creating changesets would be handled by the Rails port, while the upload itself is handled by CGImap. They use totally independent implementations for user authentication. Additional data would help tremendously to figure out which one triggered the issue.

**Comment by bryceco** [comment]
I didn’t realize there were multiple different components involved in validation. I’ll add some extra info to the error message to clarify which step is failing.

**Comment by mmd-osm** [comment]
I’ve seen a number of empty changesets around October 4th: https://www.openstreetmap.org/changeset/91907948

If those all have been created on the device in question, that would indicate an issue with the changeset upload itself. Unfortunately, all server log details have long gone by now.

**Comment by bryceco** [comment]
I went back though my e-mail bug reports and it does appear the empty changesets are due to this bug.
