### ISSUE TITLE
Allow selecting Feature in All Tags

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#440]
As I wrote in https://github.com/bryceco/GoMap/issues/339, I really like the new all tags view.

I would like to stay in the new view as much as possible. However, there are a few things that make me switch back again and again
1. I find myself going to common tags to access recommended values – this is https://github.com/bryceco/GoMap/issues/339,
2. I find myself going to the common tags to select a preset, and then switching back to the all tags view for details.

This tickets is about ideas for (2):

Idea A: Maybe make it easier to switch between all-tags and common-tags, eg. by adding a swipe gesture that change the form. Like the swipe gesture that allows to "go back to previous website" in the browser.

Idea B: Add a preset-selection-UI-element at the top of the all-tags view, similar to common tags.

**Comment by TheAdventurer64** [comment]
Could you share a concept art of Idea B?

**Comment by bryceco** [comment]
A: It should already be pretty easy. Press Done to dismiss the keyboard and then press Common Tags.
B: This isn't a bad idea. I'd like to prototype it.

**Comment by tordans** [comment]
> If the latter then I've already made changes so the suggestions update automatically when you set amenity=restaurant, etc.

Yes, that helps a lot – mainly for new nodes without any tags and when I really remember the primary key.

However, I cannot always remember the primary key. `natural=tree` is easy, but I have to look up the "leisure" in `leisure=playground` every time. That is the kind of mental load that gets lifted with the presets where I can just type "play" and click "Playground" and start adding details.

What was the primary key for `street_cabinet` again? (It's `man_made`…)

Unfortunately, the interaction between the two panels "Common tags" and "All attributes" is quite complex.

I have one idea:

|Screen1|Screen2|
|---|---|
| ![all-attributes](https://user-images.githubusercontent.com/111561/136796123-d84c6f96-8dea-4d9c-b296-05f831187eda.jpg) | ![preselection](https://user-images.githubusercontent.com/111561/136796140-4a6cc397-5bbb-4d8e-b01c-43fe74983479.PNG) |
|  Step 1 when I used the 'all attributes' panel before and just now created a new node. The UI opens with the keyboard open, which hides the "common tags" button and thereby my quick way to access the presets. — **Idea:** Add a "select preset" link in the blue marked box, which leads me to Screen2  | The "select presets" screen just as I see it when I open it from the "common tags" panel. On close, I should get back to the "all attributes" panel since I opened this search from there. |

**Comment by tordans** [comment]
> A: It should already be pretty easy. Press Done to dismiss the keyboard and then press Common Tags.

My issue with that is, that my muscle memory gets confused a lot: 

1. When I open Screen1, I know that I want to the presets with are on the common tags panel which is on the bottom left, so I click there like I do all the time. 
   * Another thing that leads to this miss-click is the fact, that the common-tags-button is visible when I first open the panel, so I see that it is not selected and start clicking it. But in the meantime, the keyboard opens …
1. But in this special case, the bottom left is the emojii-keyboard. 
1. And once I am in there, I remember that I needed to click "done" on the keyboard, so I click on the bottom right. 
1. But now this is the back-button of the emojii-keyboard, so nothing changes. 
1. So I have to click left again to switch to the regular keyboard, 
1. then "done" on the right", 
1. then finally "common tags", 
1. then finally the preset selection.

All the while I get completely pulled out of flow and have to remember what I was actually trying to do :-).

I tried taking a video, but that does not show it well either https://share.icloud.com/photos/0Vy-wlAmieX5iKu76nCDXJ7-Q

Is this just me? 🤔

**Comment by bryceco** [comment]
I've implemented this but I'll take feedback for the UI. Where previously the word Tags appeared it now displays the type of the current feature, and the arrow on the right takes you to the regular feature picker.￼

![image](https://user-images.githubusercontent.com/279734/137027487-db358fd4-e0a4-49d9-a16c-9509c1636e92.png)

**Comment by bryceco** [comment]
Added in c9e1f18a356be7d0e3d5521061755e5209f24f6a.
