### ISSUE TITLE
Change buttons back to original look

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#443]
So, as you can see here, the buttons got a big "overhaul".
However, I dislike this for many reasons.![image](https://user-images.githubusercontent.com/50059322/93111760-c5880b80-f652-11ea-8726-06daa1f5da66.png)
1. The button photos look too big. When you make the buttons look too big, it can make the pictures look old and outdated, and because of this, it's not very astetically pleasing to the user.

**Comment by bryceco** [comment]
Now that the images are vector based it's easy to adjust their size. Is there a preferred point size for button images?￼

**Comment by tordans** [comment]
IMO one goal would be to have all icons use the same line thickness. ATM the upload icon is different. 

@wtimme do you know - from the top of your head - if there is a recommendation in the apple interface guidelines?

**Comment by bryceco** [comment]
The upload button is the exception to my statement. SF Symbols has a similar upload button but it's only allowed to be used with iCloud services, so I had to scrounge up a similar looking image.

**Comment by dieterdreist** [comment]
sent from a phone

>> On 14. Sep 2020, at 19:58, Tobias <notifications@github.com> wrote:
> @wtimme do you know - from the top of your head - if there is a recommendation in the apple interface guidelines?


AFAIK apple leaves this to the designers, their symbols font provides 8 (or so) different line weights, so you can choose what you want, and potentially also adapt to accessibility settings 


I am also pro standardizing the line weights, it seems we are using several variations, not just the upload button icon, but also settings, search...

**Comment by bryceco** [comment]
I believe the other buttons are all identical weight.
