### ISSUE TITLE
OSM data download fails after upgrade

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#446]
Occasionally after upgrading the app (either via App Store or TestFligh), OSM data doesn't download and instead a "not found" error message is displayed. This has been reported by around a dozen people, but I haven't seen it myself and don't know the cause.

It's been reported that login information in Settings validates as correct.

You can fix the problem by deleting and reinstalling the app.

**Comment by TheAdventurer64** [comment]
#444

**Comment by bryceco** [comment]
How did you fix it?

**Comment by TheAdventurer64** [comment]
I cleared my cache, and restarted the app. I don't believe I got a Not Found error, but I could be wrong.

**Comment by rsalzer** [comment]
Hmm ... reinstalling the app should not be the solution ;)
But it worked

**Comment by bryceco** [comment]
I totally agree, and I’m desperate to know what the root cause is, but I’ve had no luck reproducing the bug.

**Comment by bryceco** [comment]
It appears this can be fixed by modifying the server URL in Advanced Settings, and then reverting it to the default

**Comment by bryceco** [comment]
I was able to reproduce the error message on an old device running release 1.6.2, which contained a bug where visiting the Server URL page under Advanced would append // instead of / to the end of the UR (fixed by @wtimme). Doing this gives the "not found" error, while other various changes to the URL cause a "page not found" error with some additional text. 

One possibility is that the extra slash didn't cause a problem server-side until recently, which made it look like an upgrade bug instead of a server configuration change? The latest 1.8.42 in the App Store contains a fix.

**Comment by bryceco** [comment]
Fixed in ca0424b2d4201a36801bb69b4dc70a09f9d9e4a4
