### ISSUE TITLE
When commenting on a note text is truncated at ampersand sign

### ISSUE THREAD

**Issue by saintamh** [bryceco/GoMap#447]
When I add a comment to a note, if my comment includes the `&` character, that character and everything after it are truncated from the comment.

For instance the 2020-09-17 12:08 comment at https://www.openstreetmap.org/note/2326722 was "Closed indeed. Surveyed & updated", but the "& updated" got chopped off.

POST body parameters not being escaped correctly maybe?

**Comment by bryceco** [comment]
Fixed in 8afb444c8d5edc93d7d90bb733222b9ce7c94e46
