### ISSUE TITLE
iOS 14 - „not found“

### ISSUE THREAD

**Issue by rsalzer** [bryceco/GoMap#449]
After upgrading to iOS 14 "not found" appears.

![image](https://user-images.githubusercontent.com/17248257/93673180-80793480-faab-11ea-90ab-5c0567114d06.png)

**Comment by bryceco** [comment]
Dup of #446

**Comment by TheAdventurer64** [comment]
^ This error happens on iOS 13 as well. It's not because of iOS 14.

**Comment by dieterdreist** [comment]
while I had the problem before (13) and solved by reinstalling, it now did not occur with ios 14
