### ISSUE TITLE
Display GPX tracks

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#45]
Should be able to display a GPX track:

    Accepting the file extension *.GPS form the iOS-API. That would also work with Dropbox.
    Downloading from the OSM-API What ever may be the simplest to code.

**Comment by bryceco** [comment]
GPX is coming. KML is too complex to be worth the effort.

**Comment by DerKarlos** [comment]
Hey, you are alive! Go on, I still love and use "go map!!"

**Comment by socketpair** [comment]
Just download public tracks and show! Very need that!

**Comment by bryceco** [comment]
Latest release has this.

**Comment by socketpair** [comment]
Can it download publick tracks in vector form ? Image layer with tracks stops upadting more than year ago, so new tracks are not shown.

**Comment by bryceco** [comment]
If you are in Safari (for example) and click on a gpx track there should be an option to open it in Go Map!!
