### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#458]
![Uploading 97816541...]

**Comment by bryceco** [comment]
Upload seems to be stuck

**Comment by TheAdventurer64** [comment]
![image](https://user-images.githubusercontent.com/50059322/98208123-5fa55b00-1f02-11eb-8d6f-2444316323b7.jpeg)

**Comment by TheAdventurer64** [comment]
![image](https://user-images.githubusercontent.com/50059322/98208257-a1360600-1f02-11eb-83ef-48e850d946b9.jpeg)

**Comment by bryceco** [comment]
Can you reproduce it?

**Comment by bryceco** [comment]
What's interesting about this bug is that the app contains only a single instance of the PushPinView, the object that displays the text, so there's no explanation for it appearing twice. Since it seems to be a one-off but and without steps to reproduce it I'm closing this.
