### ISSUE TITLE
Can’t log in with another service

### ISSUE THREAD

**Issue by lizzyd710** [bryceco/GoMap#459]
I registered for OSM through my Google account, and there’s no options to log-in using one of those third-party methods like Google or GitHub. Just to make sure, I tried using my OSM name and Google password in the log-in fields, but got hit with the Bad Login notification.

**Comment by bryceco** [comment]
Instead of entering your Google password you should go to the Settings page on the OSM website and create an OSM password there. If you need additional help please ask.
