### ISSUE TITLE
Problem: Button Size is Too Big

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#462]
#Rationale 

If you look at this photo, you'll notice that the two button sizes are inconsistent.![image](https://user-images.githubusercontent.com/50059322/99889528-bf4a7880-2c1b-11eb-8d9a-64590eec07dc.png)
This is problematic, as this looks unprofessional and is inconsistent.

**Comment by bryceco** [comment]
Actually I was hoping to make the rightmost button even smaller, to make it less obtrusive.

**Comment by bryceco** [comment]
What version of iOS do you have? Your's looks different than mine.

**Comment by TheAdventurer64** [comment]
iOS 14.1

**Comment by bryceco** [comment]
Updated in 5bbe15c7952a54ecf027fbc3174d0ed1be10a6ed

**Comment by TheAdventurer64** [comment]
![image](https://user-images.githubusercontent.com/50059322/104245349-2e687000-5408-11eb-88da-200bc67c2961.png)
The Link button is still the same size as before, after a few new versions. What happened?
