### ISSUE TITLE
Center button should be updated

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#463]
In this photo, the center button looks old and outdated.![image](https://user-images.githubusercontent.com/50059322/99889679-36ccd780-2c1d-11eb-8169-6cc80cef7978.png)
This is outdated, as the font is from a older OS, and the button looks like it hasn't been updated since iOS 7.

**Comment by TheAdventurer64** [comment]
May I see a picture of the new photo?

**Comment by bryceco** [comment]
![F44FBE93-72C0-4FFF-A9BA-6A9DC81F82D6](https://user-images.githubusercontent.com/279734/100280895-c45e3f00-2f1d-11eb-9d15-a34a868734d8.png)

**Comment by bryceco** [comment]
![7667F369-920B-4BCE-BB80-7DAFF7007F31](https://user-images.githubusercontent.com/279734/100281032-05565380-2f1e-11eb-9aee-e5d2db7bce40.png)
