### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by yellowsoar** [bryceco/GoMap#464]
I think this one might be a typo?
https://hosted.weblate.org/translate/go-map/app/en/?checksum=f5c6e5376697f118
Compare to another string:
https://hosted.weblate.org/translate/go-map/app/en/?checksum=ed6711f6eeebe19d

**Comment by bryceco** [comment]
Fixed in daf5f8e2683bd5a8c4fba994746bc2ee4f797ea0
