### ISSUE TITLE
Problem: Areas can be used to create lines

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#465]
So, one of the main issues with GoMap is the fact that "Area[s]" aren't really areas. ![image](https://user-images.githubusercontent.com/50059322/99916638-e9aa3d80-2cd0-11eb-8f60-b9127ed135b1.png)This is problematic, as users can get confused as of why they can create roads and such with "Area[s]" in GoMap, but not in iD. To solve this problem, I propose something like, where the user can choose between either a area, a line, or a point.

**Comment by dieterdreist** [comment]
that's because in OSM there aren't areas.

**Comment by bryceco** [comment]
iD doesn’t really have areas, instead it has a set of heuristics to decide whether to call any closed way an area. You can use area=yes or area=no to force a distinction.
