### ISSUE TITLE
Undo and Redo buttons aren’t showing

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#466]
![image](https://user-images.githubusercontent.com/50059322/100143897-9d3f3900-2e5b-11eb-849d-3e0b5b9a9a97.png)
Apparently, the buttons appeared after I edited something. Shouldn't the buttons be there by default?

**Comment by bryceco** [comment]
This is intentional, following a suggestion that controls be hidden unless they are enabled/useful. Therefore undo/redo and upload are hidden until you’ve modified data.
