### ISSUE TITLE
The survey date should be put in the changeset source tag, not on objects

### ISSUE THREAD

**Issue by gileri** [bryceco/GoMap#467]
Disclaimer : I can't test this application as I'm not an iOS user, so this is from an OSM contributor/consumer viewpoint.

As far as I know Go Map!! use `source=survey` on the changeset, and add `survey:date` on objects. Why not concatenate the date to the changeset's source tag ? That will be sufficient to indicate that the modification comes from a survey at this date.

The reason I see for using `survey:date` on objects is that allows to indicate currentness of an object's data, even if some or all data hasn't been modified. However there is a significant downside : This tag don't indicate which information has been surveyed. Was it its
* name ?
* position ?
* owner ?
* opening hours ?
* `ref=*` ?
* wheelchair accessibility to the restroom ?
* air conditioning ?

The first ones will usually be surveyed, while the latter will not. As it stands, other contributors or consumers can't know what has been surveyed with `survey:date`. I see two solutions in order to make this tag more meaningful :

* Either apply it on the changeset, so that only modified data is linked to a survey date.
* Or add a `survey:*:date` tag (e.g. `survey:opening_hours:date`) for each information validated by the Go Map!! contributor

Both will make this information reliable for other users to depend on. What do you think ?

**Comment by tordans** [comment]
Hi @gileri I will have to re-read your post cause I thing I did not yet fully understand your usecase and goal. But in the meantime, this sounds like it should be thought about in relation to the new StreetComplete Review-Feature which was build and discussed recently, since this is also working with survey_date dates. More about it at https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020/Proposal/Map_Maintenance_with_StreetComplete/Report (and the interem report and proposal) and on the mailing list and on the github issue(s). Westnordost did a lot of thinking for this one and its a new way of using the OSM-DB IMO.

**Comment by bryceco** [comment]
Changesets have a date associated with them already so I don’t understand why it would need a tag to redundantly provide that information.

The tag goes on the object because if the object is re-surveyed and nothing has changed then it won’t appear in a changeset, so survey:date fulfills that need. It indicates that all tags were verified on that date.  This tag isn’t added automatically, only if the user requests it.

**Comment by gileri** [comment]
@tordans Thank you for your those examples. I'll take the opening_hours one to illustrate, I hope that'll be clear enough :

A restaurant has the following tags :

name=Pizza buenissimo
cuisine=pizza;pasta
air_conditionning=yes
website=https://example.com
phone=555-555-555
wheelchair=yes
diet:halal=yes
organic=yes
opening_hours=Mo-Sa 11:00-22:00
etc.

A Streetcomplete or Go Map!! user verify that the opening hours are still the same. The restaurant's tags then become :

name=Pizza buenissimo
cuisine=pizza;pasta
air_conditionning=yes
website=https://example.com
phone=555-555-555
wheelchair=yes
organic=yes
opening_hours=Mo-Sa 11:00-22:00
**survey:date=2020-11-25**

What has been surveyed ? By applying a "blanket" survey date we can't know.

If storing this "check date" in OSM is indeed useful, it should be stored in a tag like `survey:opening_hours:date` or `check_date:opening_hours` to allow future contributors (and applications such as StreetComplete) to know what has been surveyed.

**Comment by bryceco** [comment]
It seems silly to me to envision a mapper would survey the opening hours without also verifying the name, cuisine, etc. I don’t think that’s how real-world users of the app do things. In a StreetComplete scenario I see it but not this app. 

It also seems crazy to think that essentially every tag of every object needs to have an associated survey:date tag, 99% of which would have the same date.

**Comment by gileri** [comment]
> It also seems crazy to think that essentially every tag of every object needs to have an associated survey:date tag, 99% of which would have the same date.

That's why I suggested putting the survey date in the changeset as an alternative.

> It seems silly to me to envision a mapper would survey the opening hours without also verifying the name, cuisine, etc. I don’t think that’s how real-world users of the app do things. In a StreetComplete scenario I see it but not this app.

Maybe I'm crazy and/or silly but I don't think that most mappers will check every tag. I don't think for example they will check the restroom accessibility for wheelchair users, or whether the restaurant has outdoor seating while it's winter and there are no signs of it outside.

If you are confident that most contributors using this feature will check all tags, feel free to close this.

**Comment by dieterdreist** [comment]
Am Mi., 25. Nov. 2020 um 19:00 Uhr schrieb bryceco <notifications@github.com
>:

> It seems silly to me to envision a mapper would survey the opening hours
> without also verifying the name, cuisine, etc. I don’t think that’s how
> real-world users of the app do things. In a StreetComplete scenario I see
> it but not this app.
>

probably not for name, but there is a lot of stuff people will not check
when they change something else, e.g. phone numbers, tax numbers, operating
company, etc. E.g. for petrol stations, people might only change the brand
but not the operator (these change frequently their operators around here).
or the mapper might change the name but be unsure about the opening hours
and keep them nonetheless.



> It also seems crazy to think that essentially every tag of every object
> needs to have an associated survey:date tag, 99% of which would have the
> same date.
>

mostly agree

**Comment by dieterdreist** [comment]
> Changesets have a date associated with them already so I don’t understand why it would need a tag to redundantly provide that information.
> 
> The tag goes on the object because if the object is re-surveyed and nothing has changed then it won’t appear in a changeset, so survey:date fulfills that need. It indicates that all tags were verified on that date. This tag isn’t added automatically, only if the user requests it.

I agree that in the context of GoMap!!, almost all edits will be made at survey time. In other editors, e.g. when mapping from gpx traces and photos, it may be quite some time between survey time and when you finally find the time to do it. Still, it would be more explicit with a dedicated tag

**Comment by dieterdreist** [comment]
on changeset tags, there is the idea to use hashtags for the type of edit:
https://wiki.openstreetmap.org/wiki/Changeset/Governance
E.g. this idea could be extended to mapping during a survey / in loco

```
#country-armchair | I don't know the place but I know the norms the country's community agreed on
-- | --
#local-armchair | I don't know the place but I know the norms the local's community  agreed on. Just use this hashtag in cases where a local community  established an own tagging norm because the place's norms are a little  bit different from the country's norm.
#aftersurvey | I have been at the place recently but I am mapping it after the  completion of my survey. I took notes, pictures I use for mapping etc.  or map from memory.


```

**Comment by bryceco** [comment]
> probably not for name, but there is a lot of stuff people will not check when they change something else, 

If you don’t check everything you shouldn’t press “update survey date” IMO, but maybe I’m too idealistic

**Comment by TheAdventurer64** [comment]
> Disclaimer : I can't test this application as I'm not an iOS user, so this is from an OSM contributor/consumer viewpoint.
> 
> 
> 
> As far as I know Go Map!! use `source=survey` on the changeset, and add `survey:date` on objects. Why not concatenate the date to the changeset's source tag ? That will be sufficient to indicate that the modification comes from a survey at this date.
> 
> 
> 
> The reason I see for using `survey:date` on objects is that allows to indicate currentness of an object's data, even if some or all data hasn't been modified. However there is a significant downside : This tag don't indicate which information has been surveyed. Was it its
> 
> * name ?
> 
> * position ?
> 
> * owner ?
> 
> * opening hours ?
> 
> * `ref=*` ?
> 
> * wheelchair accessibility to the restroom ?
> 
> * air conditioning ?
> 
> 
> 
> The first ones will usually be surveyed, while the latter will not. As it stands, other contributors or consumers can't know what has been surveyed with `survey:date`. I see two solutions in order to make this tag more meaningful :
> 
> 
> 
> * Either apply it on the changeset, so that only modified data is linked to a survey date.
> 
> * Or add a `survey:*:date` tag (e.g. `survey:opening_hours:date`) for each information validated by the Go Map!! contributor
> 
> 
> 
> Both will make this information reliable for other users to depend on. What do you think ?

I like the `survey:*:date`, as it is similar to `source:name`, as well as the fact that it makes good use of the : suffix.

**Comment by bryceco** [comment]
When I search taginfo for survey:name:date and survey:opening_hours:date I get zero results, so that idea is dead: I'm not interested in breaking new ground WRT tagging. If/when JOSM/iD provide first-class support for that tag scheme we can talk about it again.

**Comment by gileri** [comment]
You're right bryceco, I should have only suggested `check_date:*`, which [is alive](https://taginfo.openstreetmap.org/keys/check_date%3Aopening_hours).

**Comment by TheAdventurer64** [comment]
The `survey:*:date format isn't used, but there are similar tags;

  ![image](https://user-images.githubusercontent.com/50059322/100399899-2f8d3b80-301a-11eb-8df0-15e91ee36769.png)

**Comment by bryceco** [comment]
We already support survey:date, as well as a number of other synonyms. But as for dates attached to specific keys (https://taginfo.openstreetmap.org/search?q=check_date%3A) the numbers are too small for me to care about. If tag-specific dates become popular in the future we can revisit this.
