### ISSUE TITLE
New POI Icons Aren’t Appearing

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#469]
So, as you can see here, the Bubble Tea Cafe doesn't have an icon.![image](https://user-images.githubusercontent.com/50059322/100903749-df83fe00-348b-11eb-8e2d-cfe4bc450b78.png)
This is problematic, as the iD editor has one. Was there an issue with the import?![image](https://user-images.githubusercontent.com/50059322/100903860-fd516300-348b-11eb-994e-3565e59adc82.png)
Edit, it looks like the issue lies within the fact that the Tamaki icons haven't been updated. New presets like Mounted Binoculars use icons that have already been imported into GoMap.

**Comment by bryceco** [comment]
That's correct, icons haven't been updated yet. Should be fixed in a couple days.

**Comment by bryceco** [comment]
Fixed in 48d7e95e07216b17685f3d64d43c042edc8725d2
