### ISSUE TITLE
Presets are missing fields of type 'typeCombo'

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#473]
So if you look here, the phone and website fields are on the bottom.![image](https://user-images.githubusercontent.com/50059322/101267370-e87b0680-36fb-11eb-95c6-230295a64845.jpeg)
This is a problem, as the current iD presets have them here instead:![image](https://user-images.githubusercontent.com/50059322/101267374-f03aab00-36fb-11eb-9a29-0469d8e995d6.jpeg)

**Comment by bryceco** [comment]
I'm not sure what you think has changed. That's how it has always been.￼

**Comment by TheAdventurer64** [comment]
Ah, okay.

**Comment by bryceco** [comment]
iD has a similar breakdown where website is promoted and phone is not:
![Image 12-5-20 at 7 59 PM](https://user-images.githubusercontent.com/279734/101271073-796dd400-3734-11eb-9714-eaae47d492e3.jpeg)

**Comment by TheAdventurer64** [comment]
What about `office=government`? There's a Type (`government=*`) field that hasn't been added.

**Comment by bryceco** [comment]
That's a bug :)
