### ISSUE TITLE
Surface Tags are Broken

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#479]
![image](https://user-images.githubusercontent.com/50059322/102918450-039f8300-442b-11eb-8365-c9c3602cbc41.png)
As you can see here, you are not able to select a preset value of Surface, due to the fact that > is missing. The only way is by typing it in manually and letting the values automatically give options to fill it in. There is also no Unknown text, leaving users to assume that you cannot type in Surface.

**Comment by bryceco** [comment]
Good catch! Thanks!
