### ISSUE TITLE
Building not showing

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#480]
Building isn't rendering on GoMap![image](https://user-images.githubusercontent.com/50059322/103111513-026c8280-45f2-11eb-88f7-eea93520dc83.png)![image](https://user-images.githubusercontent.com/50059322/103111516-07313680-45f2-11eb-9a43-f6b7136a7f54.jpeg)
![image](https://user-images.githubusercontent.com/50059322/103111529-229c4180-45f2-11eb-997f-2c5223784794.png)

**Comment by bryceco** [comment]
Is it fixed by clearing the cache?

**Comment by TheAdventurer64** [comment]
> Is it fixed by clearing the cache?

Nope.

**Comment by tordans** [comment]
It shows up for me 

This is the location, btw. https://www.openstreetmap.org/way/461624038

![image](https://user-images.githubusercontent.com/111561/103141485-1d73eb00-46f5-11eb-99e8-43495227536e.png)

**Comment by tordans** [comment]
Just a debugging suggestion: Are there any active filters?

**Comment by bryceco** [comment]
It shows up for me too.
