### ISSUE TITLE
Accidentally creating new nodes when panning

### ISSUE THREAD

**Issue by rbirkby** [bryceco/GoMap#481]
With the new UI, if I’m following a feature such as a footpath, road, or pipeline, I will highlight that feature and pan along it. Unfortunately, the add node icon is where my finger goes to pan and consequently I hit the icon accidentally adding new nodes to the way. 

If I’m also making other edits at the same time, I don’t notice these phantom new nodes and commit them to osm. 

Can the add node icon be moved to a less dangerous position?

**Comment by bryceco** [comment]
You can move it to the opposite side of the screen (in Display settings), but that probably doesn't help your situation. In a future release I'll add support for placing it at the bottom of the screen.

**Comment by rbirkby** [comment]
A solution is only to record the “press” if the touch release is also on the icon.  The other buttons work in this way, so why doesn’t the ‘add node’ button?

**Comment by bryceco** [comment]
Yes it should work that way. I'll look into why it doesn't.
