### ISSUE TITLE
Version 2.0.7 crashes on iPad when selecting “Attribute”

### ISSUE THREAD

**Issue by wopfel** [bryceco/GoMap#484]
Hi,
Nice new icon :-) Thanks for the update!

When selecting an element (point, line, rectangle) and touching the left button (titled “Tags” before, now “Attribute” in DE language), the app closes suddenly, falling back to the iPad home screen.

Device: iPad8,12
iOS version: 14.3

I’ve cleared the cache, but same behavior.

Btw, on iPhone it just works.

Please let me know if you need additional information.

Happy new year! 😃 

Kind regards,
Bernd

**Comment by bryceco** [comment]
It's working on my iPad(s), so maybe there's something else going on? There was a report that seemed to imply that it crashes for some people who have a Custom Preset defined for a very old version, could that be it? Deleting and reinstalling might fix that particular case.

**Comment by wopfel** [comment]
Hello bryceco,
Thanks for your answer. I’ve worked with custom presets in the past. But I’m unsure if I’ve used them on the iPad. Unfortunately there’s no possibility to remove those presets without tapping on the tags button :) As you suggested I’ve deleted and reinstalled your app and now the tags button works just fine.

Thank you for your help!

Kind regards,
Bernd
