### ISSUE TITLE
Ruler is incorrect

### ISSUE THREAD

**Issue by rbirkby** [bryceco/GoMap#485]
I have used the Make Circular function to make a 25 foot circle. As I rotate the map, the circle according to the ruler can be as large as 100 foot. Why does the ruler get this wrong?

![48D7FE83-961E-4ED9-B650-84FFC76BC985](https://user-images.githubusercontent.com/203034/103436584-1bd68580-4c15-11eb-9264-d10b1ce68a51.jpeg)
![B3A60B85-ED54-4D17-A97C-1763AB672F77](https://user-images.githubusercontent.com/203034/103436585-1d07b280-4c15-11eb-961d-f2f67d029e60.jpeg)

**Comment by bryceco** [comment]
Thanks for reporting this. The code that computes meters/pixel wasn't properly dealing with rotation.
