### ISSUE TITLE
Crashing when clicking "Tags" button

### ISSUE THREAD

**Issue by aawiseman** [bryceco/GoMap#488]
I love Go Map!! and was trying out the new version. However it's crashing for me whenever I have something selected and then click "Tags". The other buttons and moving a feature works fine.

I have iOS 14.2 on an iPhone 11 Pro and I'm logged into OSM under my account. I’ve tried restarting the phone and made sure the app doesn't need to be updated, no luck.

**Comment by bryceco** [comment]
I'm pretty sure this is due to an old user-defined custom preset (based on crash reports I've encountered). The easiest fix is to simply delete and reinstall.

**Comment by aawiseman** [comment]
Yep that worked! Thanks!
