### ISSUE TITLE
Encoding of Umlauts in Note comments

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#492]
I just closed [a note](https://www.openstreetmap.org/note/2505085) with Go Map!!
The comment (in German) contains an Umlaut, which is input correctly in the UI, but gets pushed badly to OSM.

Here's a screenshot of how it's entered [1]

![IMG_1401](https://user-images.githubusercontent.com/1651235/105210273-22d52180-5b4b-11eb-875d-451338c0f3b0.jpeg)

You can check yourself how it shows up on OSM: https://www.openstreetmap.org/note/2505085 :)

I'm using the TestFlight version of Go Map!! (Version 2.0.7 (2070) on iPhone 12 mini with iOS 14.2.1.

[1]: Which is a superfluous test-comment after I closed the note with the 'real' comment.

**Comment by habi** [comment]
Don't know if this is important: My iOS is set to English, but I use both the English and German keyboard depending on the 'use case'.

**Comment by bryceco** [comment]
Thanks! I seem to have a lot of bugs related to encoding notes correctly :)

**Comment by 1ec5** [comment]
The percent encoding happens here:

https://github.com/bryceco/GoMap/blob/6287a27ff79bb358e3171296a7cfc5ced1d5237e/src/Shared/OsmNotesDatabase.m#L407

But that encoding step is probably unnecessary because the value is wrapped in an NSURLQueryItem, which does its own percent encoding.

https://github.com/bryceco/GoMap/blob/6287a27ff79bb358e3171296a7cfc5ced1d5237e/src/Shared/OsmNotesDatabase.m#L429

**Comment by bryceco** [comment]
NSURLQueryItem does it's own encoding, but it doesn't encode everything. See
http://www.openradar.me/24076063

I don't recall exactly but I think I saw the same issue with ";".

**Comment by habi** [comment]
> I don't recall exactly but I think I saw the same issue with ";".

That was also an issue I submitted: https://github.com/bryceco/GoMap/issues/321 :)

**Comment by R3gi** [comment]
I confirm this issue in v2.0.7. Notes written with Czech diacritics are corrupted.
Example of [corrupted note](https://www.openstreetmap.org/note/2507703#map=18/50.06949/14.48385&layers=N).

**Comment by bryceco** [comment]
Seems this is a bug in NSURLQueryItem + NSURLComponents. Each of them encodes the text independently resulting in a double encoding.
