### ISSUE TITLE
Remove code for 3D buildings

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#496]
As outlined by Bryce in #495,

> The code for 3D buildings could be removed as it never has worked great, and my efforts to move it to SceneKit ran into problems.

**Comment by wtimme** [comment]
@bryceco, does this include the code related to the `SHOW_3D` flag as well, or only the SceneKit-related stuff?

**Comment by bryceco** [comment]
We should create a "3D buildings" feature branch that includes all SceneKit and SHOW_3D stuff. Also the UI button needs to be removed as well as the 3-finger gesture recognizer. This code might be helpful in the future if AR becomes practical.

**Comment by bryceco** [comment]
- [ ] I guess I should also mention that if you had any plans to convert that class to Swift it would be better to do this work after converting.

**Comment by wtimme** [comment]
Thanks for your response! With Git, the code is not lost - it just not part of the _current commit_ anymore. Let's improve the code by removing things we do need right now (cp. for example [this text][1]).

> I guess I should also mention that if you had any plans to convert that class to Swift it would be better to do this work after converting.

Since Swift conversion takes time (like any software development), I strongly suggest to first remove dead/unused code and only then to start with the conversion.

I realize that this might sound harsh, but given that our resources (time and contributors) is limited, let's remove things we do not need.

For this GitHub issue, I suggest we add a couple of subtasks:

- Remove everything related to `SHOW_3D`
- Remove the button for 3D
- Remove the 3-finger gesture recognizer

Would you be fine with someone going ahead here and create pull requests?

[1]: https://www.oreilly.com/library/view/becoming-a-better/9781491905562/ch04.html

**Comment by bryceco** [comment]
I realize that deleted code isn't lost, but creating a feature branch for it ensures it stays easy to find and maintain if someone wants to work on it in the future. This is similar to what I did with the NetworkStatus and VoiceAnnouncement code. We can branch the code as it is and then delete from master.
