### ISSUE TITLE
Yes - No instead of No - Yes

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#501]
For the No-Yes value UI,I personally think that the UI should be Yes - No instead, for formality purposes.￼ [image](https://user-images.githubusercontent.com/50059322/107134082-e3207080-6892-11eb-895c-607a1149f4f9.png)

**Comment by bryceco** [comment]
On iOS yes/no (or on/off) switches place the "yes" on the right, so I'm following that precedent. The phrasing isn't relevant.
