### ISSUE TITLE
Remove Vehicle: from Service Tags

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#502]
The issue with Service tags at the moment, is that they have the 
```Vehicle:``` value on them. Personally, I don't think this is! good for cosmetic purposes. ![image](https://user-images.githubusercontent.com/50059322/107134153-9721fb80-6893-11eb-96f8-19852b544f86.jpeg)

**Comment by TheAdventurer64** [comment]
Also, US citizens don't call tires "tyres". Maybe this could be fixed as well?

**Comment by bryceco** [comment]
Yes, vehicle: shouldn't appear. Thanks!

**Comment by bryceco** [comment]
Unfortunately "tyres" comes from taginfo, so if you want to get rid of it you'll have to file a report against https://github.com/openstreetmap/id-tagging-schema

**Comment by dieterdreist** [comment]
sent from a phone

> On 7 Feb 2021, at 06:52, bryceco <notifications@github.com> wrote:
> 
> Unfortunately "tyres" comes from taginfo


is there a translation for US English, or are you using the same preset labels as the British?

**Comment by bryceco** [comment]
There is no preset for tyres. We query taginfo 
https://taginfo.openstreetmap.org/search?q=service%3Avehicle%3A
and tyres is one of the results.
