### ISSUE TITLE
Move Yes/No switches for user purposes

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#505]
![image](https://user-images.githubusercontent.com/50059322/107838540-684fcd80-6d4a-11eb-83f5-e266068d72e7.png)
The issue shown above is that the Yes/No switches collide with the scrolling bar. This is an issue, as one could easily accidentally press No while attempting to use the scrolling bar. To solve this issue, I propose that the Yes/No switch be moved to the middle:![image](https://user-images.githubusercontent.com/50059322/107838612-cda3be80-6d4a-11eb-84cb-990a13e4d961.jpeg)
This will make the user interface better, and the design nicer.

**Comment by bryceco** [comment]
I don't understand how moving the switches changes the situation. If you're tapping in the center of the screen you can still hit them accidentally. And placing them on the right is the most like how regular On/Off switches appear in iOS. Can you post a video showing the problem?
