### ISSUE TITLE
language issues

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#508]
Something strange happened: GoMap!! is speaking German with me. I have my osm user account set to this locale: "en-US en de-DE de it-IT" and the device language is set to "Italian", preferred languages in this order: "Italian, German, English, English(UK), Spanish, Russian, French, simple Chinese, Portuguese, Japanese".
I used to get the device language IIRR (although it might be worth considering to use the first supported language from the OSM user settings), but now the device language is ignored and the second preferred language is provided. 
A guess would be that you use the device languages and there is some issue with Italian currently, this would explain defaulting to the second priority.

**Comment by patricks** [comment]
Afaik there is no Italian localization available for GoMap!! so it uses your second preferred language (German). You also can switch the language per app (since iOS 14). Go into Settings.app -> Go Map!! -> Preferred Language

**Comment by dieterdreist** [comment]
indeed there isn't currently an Italian localization to choose from in the settings.app (thank you for the hint, I changed it to English now). But I could swear there was a few days or weeks ago, even the presets were Italian (I never liked it, because the translated tags are harder to understand than the original tags).

**Comment by bryceco** [comment]
The presets could be in Italian (but not the rest of the app) because they are localized separately and support more languages (look at Settings > Language in the app).
