### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by Boza22** [bryceco/GoMap#515]
I am happy to use GoMap for several years but now I got this error. I am not able to upload data. I don't know, how to get rid of it and continue to use it. I am not aware doing something in different way.  
![IMG_7308](https://user-images.githubusercontent.com/31953218/115839488-fe733480-a41a-11eb-93ff-82e74fbf21f0.PNG)

**Comment by dieterdreist** [comment]
interestingly it is yourself who uploaded version 5: https://www.openstreetmap.org/node/366846144
the message is a conflict report, you are uploading a new version for this node pretending to base your edit on version 4, while the server already has a version 5. To move on, you should remove the node from your commit. (edit xml from the upload window) or download the edit via email and modify it (e.g. in JOSM or a text-editor). You can also delete all your current edits by going to "Display" (map icon) and then "Clear Cache" and "Clear osm data".

**Comment by Boza22** [comment]
When I deleted first conflict and tried to upload it, other conflict appeared. When I deleted second node (which was quite easy) another conflict of Way edit popup. 
![IMG_7313](https://user-images.githubusercontent.com/31953218/115846724-7abd4600-a422-11eb-924a-938e2fa59b08.PNG)

![IMG_7314](https://user-images.githubusercontent.com/31953218/115846739-7db83680-a422-11eb-838a-1ee2c6b2b510.PNG)

And then I gave it up - editing XML on small mobile phone screen was hard. So I backed up data via mail, swiped cache and now everything works. It was probably some mistake during survey - or I do not have any reasonable explanation.
Thank you for swing and useful reply.

**Comment by Boza22** [comment]
Thank you for swing and useful reply.

**Comment by dieterdreist** [comment]
sent from a phone

> On 23 Apr 2021, at 10:58, Boza22 ***@***.***> wrote:
> 
> It was probably some mistake during survey - or I do not have any reasonable explanation.


a reasonable explanation would be you uploaded and the server accepted your edits, but somehow gomap didn’t get the confirmation, and next time you uploaded, these changes were tried to upload again, but this second time you got the conflict.
It seems probable because you were the creator of the current version of the OpenStreetMap objects on the server

**Comment by bryceco** [comment]
I agree that's the most likely explanation. ￼
