### ISSUE TITLE
iOS 9: unsupported, but the app still upgrades

### ISSUE THREAD

**Issue by saper** [bryceco/GoMap#517]
I was quite happy with Go Map! on the old iPad Mini stuck on the last 32-bit release (9.3.6).

Many apps I have stopped updating at some point since they require 10+ or newer. However, there are exceptions (Zoom and Telegram deliver updates frequently and work very well).

I missed the discussion on #326 and #454 - never thought to follow the project on Github :(

My problem is that I have carelessly updated 2.0.7 to 2.1.2 without reading the release notes that iOS 9 support is dropped.
I think it is a problem that the update is being offered to my device; with other apps I usually don't get the update at all or a message pops up that the app is no longer compatible (but then an annoying notification remains).

That's the bad news for me - any help here? How to roll this back?

The good news is - the app still mostly works! The map shows up great, the tags are displayed and are editable.

The only thing which is broken is that the menu text labels ("settings" menu lower-left) are empty - but I can still select them and pick up a language for example (the value is displayed fine). Should I file a more detailed bug report about this so that iOS 9 still works? Would be nice...

and thank you for building this app!

**Comment by bryceco** [comment]
I'm confused about why the App Store allowed you to upgrade since the app is marked with a 10.2 deployment target.  Have you tried deleting the app and redownloading it, maybe it will pick up the old version again?

**Comment by saper** [comment]
I don't know why.

The appstore description still says this to me in German:

> Kompatibilität: Erfordert iOS 9.0 oder neuer. Kompatibel mit iPhone, iPad und iPod touch.

_Compatibility: Requires iOS 9.0 or newer. Compatible with iPhone, iPad and iPad touch_

I'd rather not deinstall it now. I might lose it forever :( - seen apps advertising iOS 9 support but still not installing with "This app is not compatible with this iPad".

This can be seen on the web as well:

https://apps.apple.com/us/app/go-map/id592990211

**Comment by bryceco** [comment]
The App Store should allow iOS 9 devices to download the old version that is compatible. I have an old iPad mini like yours so I'll experiment with it and see I find.

**Comment by saper** [comment]
It never happened to me in practice. Once the app drops support, I can never install an older version.

**Comment by bryceco** [comment]
> The only thing which is broken is that the menu text labels ("settings" menu lower-left) are empty 

Is your device set to use English or another language? That doesn't sound like an iOS 9 problem but rather a localization that isn't working correctly.

**Comment by bryceco** [comment]
BTW I just downloaded 2.1.2 on my 32-bit iPad mini running iOS 9.3.5. I don't see the missing text.

**Comment by saper** [comment]
My default iOS language is Polish. I can also see that one as being selected in the menu (the value is there, label is not).

**Comment by bryceco** [comment]
Ah, in fact the Polish translation is broken on every iOS version unfortunately. If you install the TestFlight version it will work, or you can change your device language.

**Comment by saper** [comment]
Currently the app does not start anymore, I'll try to figure it out and try again. How to testflight Go Map? Do I need an invitation or something like this?

**Comment by bryceco** [comment]
iOS 9 support was dropped for the current release but for some reason that change didn’t reflect on the App Store. However it should still mostly work. 

https://testflight.apple.com/join/T96F9wYq

**Comment by dieterdreist** [comment]
maybe it would be worth adding the previous version a new app ( GoMap!! legacy), until it breaks with future API updates?

**Comment by bryceco** [comment]
I don't think there's anything actionable for this, and I haven't heard any other reports.
