### ISSUE TITLE
Help with custom tile layers

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#520]
Can someone point me to why I am getting a "no image data avaliable" for those custom tiles

* `https://supaplex.uber.space/micromap/tiles/parkingmap/{z}/{x}/{y}.jpg`
   Live example https://supaplexosm.github.io/strassenraumkarte-neukoelln/?map=parkingmap#15/52.4772/13.4393
* `https://supaplex.uber.space/micromap/tiles/micromap/{z}/{x}/{y}.jpg`
   Live example https://supaplexosm.github.io/strassenraumkarte-neukoelln/?map=micromap#15/52.4772/13.4393

Source https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/blob/main/index.html

You need visit 52.4772/13.4393 / "Berlin, Neukölln", eg https://www.openstreetmap.org/node/599873093 to see data (it's only available for one district.

**Comment by bryceco** [comment]
On a desktop browser can you open the Developer panel and locate the URL of an individual tile?

**Comment by bryceco** [comment]
This worked for me once I made sure to zoom to 52.48150,13.43571

![image](https://user-images.githubusercontent.com/279734/116747047-35fd5600-a9b2-11eb-9cc5-8a06bac22c38.png)

![image](https://user-images.githubusercontent.com/279734/116747066-3b5aa080-a9b2-11eb-8fe4-cb61a7fe679e.png)

**Comment by tordans** [comment]
Thanks for testing! Today it works for me as well. No idea what was going yesterday. The times where there in the browser but did not load in the app. Well, now they do :-).
