### ISSUE TITLE
OpeningHours localization

### ISSUE THREAD

**Issue by HERTZNo1** [bryceco/GoMap#522]
In opening hours module (https://github.com/bryceco/GoMap/tree/master/src/iOS/OpeningHours), strings that depend on a user chosen language should be encapsulated in a separate file. Doing so would make localization of the module easier.

**Comment by bryceco** [comment]
Closing this due to lack of demand. Until there's a large corpus of languages being supported I don't have any confidence that translating to a new language will "just work" without code tweaks as well, so refactoring the translations into a separate file seems premature.
