### ISSUE TITLE
Problem with X on top right corner of upload screen

### ISSUE THREAD

**Issue by TagaSanPedroAko** [bryceco/GoMap#524]
I've just finished an edit in the Philippines but have uploaded it with the wrong comment (from a previous edit elsewhere), something to do with the X on the top right corner of the upload screen that do often get accidentally pressed when trying to correct part of the comment that appears to the right of the screen (in portrait view). Should that button be removed?

**Comment by bryceco** [comment]
That button was added because of https://github.com/bryceco/GoMap/issues/130

I’m open to suggestions that would make everyone happy.
