### ISSUE TITLE
missing icon for traffic light controlled crossing 

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#525]
There is no icon for highway=crossing, crossing=traffic_signals but there is for crossing=zebra and also for highway=traffic_signals
JOSM shows the traffic signals icon for pedestrian crossings with 2 instead of 3 dots, and this seems reasonable. Do you want me to provide the icon?

**Comment by bryceco** [comment]
That would be great. Support for this needs to materialize upstream:
1. Add your new icon to https://ideditor.github.io/temaki/
2. Add a new entry for crossing=traffic_signals to https://github.com/openstreetmap/id-tagging-schema/

**Comment by dieterdreist** [comment]
it came out there is already an icon in temaki: please use this icon for nodes with the `crossing=traffic_signals` tag
https://github.com/ideditor/temaki/blob/main/icons/railway_signals.svg

**Comment by tordans** [comment]
This looks like the corresponding preset: https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/highway/traffic_signals.json

**Comment by dieterdreist** [comment]
sent from a phone

> On 6 Jul 2021, at 20:03, Tobias ***@***.***> wrote:
> 
> This looks like the corresponding preset: https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/highway/traffic_signals.json


thank you for pointing in the right direction, I’ll look tomorrow at it, seems it could be integrated here:

https://github.com/openstreetmap/id-tagging-schema/tree/main/data/presets/highway/crossing

**Comment by dieterdreist** [comment]
Let's see if it will be merged:
https://github.com/openstreetmap/id-tagging-schema/pull/192/commits/7c68925630e828872e1a1fb31a8112bf608e3f20
