### ISSUE TITLE
Beta: Custom Preset Link is gone

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#533]
The link to see and add custom presets seems to be gone in the new beta. Or I don't find it anymore :).

**Comment by tordans** [comment]
Re https://github.com/bryceco/GoMap/issues/531#issuecomment-864286044 – did not see this answer before writing this issue.

>> Btw, is it by design or is it just me: I cannot find the preset button in the new app anymore.
>It hasn't moved, it's at the bottom of Common Tags.

I am pretty sure it should be here, right?

![image](https://user-images.githubusercontent.com/111561/122653246-ba16c300-d143-11eb-8455-c544e3c82728.png)

**Comment by bryceco** [comment]
Yeah it's missing
