### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by mormahr** [bryceco/GoMap#535]
I've just checked out the new swift version and formatting is not according to swift format. (When I run it I have 112/129 changed files). I noticed, for example, mixed tabs / spaces usage.
Do you plan to run swiftformat once on everything so it's clean? Otherwise PRs are going to introduce a lot of noise..

You can even add the formatting commit to a [ignore-revs](https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame) file so it can be ignored with git blame.

**Comment by bryceco** [comment]
I'm not worried about churn at the moment since all the swift files are unconnected to their ObjC origins, so there's no history to lose. You're right that running swift format is a good idea. I'll take a look at the format options today.

**Comment by bryceco** [comment]
Fixed via 85952f2a451c8a4d89435878e7f0efbb549e46f4
