### ISSUE TITLE
TestFlight version does not imagery which is loaded in AppStore version

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#537]
I'm in Switzerland and like to use [swisstopo SWISSIMAGE](https://github.com/osmlab/editor-layer-index/blob/1891875b589149c9a14d181acbd45fb4d4d0f6aa/sources/europe/ch/swisstopo_swissimage.geojson) for editing.

The AppStore version of GoMap!! (2.2.1) loads this imagery just fine, while the TestFlight version (2.3.03) does *not*.
Both version load the Bing imagery as expected.

**Comment by bryceco** [comment]
Sorry about that! Next Beta will fix it.
