### ISSUE TITLE
Beta: object not rendered after commit

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#538]
Steps:
edit an existing area 
Commit
Area is hidden until I pan the map
Should: are is rendered again right away. 

Video: https://share.icloud.com/photos/0qovxefRrSnB0u_G3qp_NRZDw (only the very end is relevant)

**Comment by bryceco** [comment]
Fixed in 461df6e9cd9ae9d1fad55d35dd75bd2feebf1119
