### ISSUE TITLE
Untagged ways are not shown when a landuse filter is enabled

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#540]
Closing a way makes it disappear from the map, so no tags can be set.
Undo to open the way makes it appear again.

Version 2.3.05, iPhone 12 mini with iOS 14.6

https://user-images.githubusercontent.com/1651235/123551075-81dd3900-d770-11eb-8d92-482818a72dc4.MOV

**Comment by bryceco** [comment]
I can't reproduce this. Can someone else see it?

**Comment by habi** [comment]
> Any chance you have a filter set?

Yes, I'm filtering lands and boundaries, since I'm usually not mapping those on the go.
If I turn off filters, the newly added way shows up as expected.
Good catch!

If that's expected, then you can happily close this issue, otherwise I'm happy to provide more information :)

**Comment by habi** [comment]
Thanks for the quick fix, awesome!
