### ISSUE TITLE
add an icon for crossing=traffic_signals

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#541]
There is an icon for crossing=zebra (which btw. is ambiguously translated as “marked crossing”, while zebra crossings being only a subset of marked crossings), but there isn’t yet for crossing=traffic_signals yet. Josm shows the highway=traffic_signals icon with 2 instead of 3 dots for this. Should I provide an icon?

**Comment by bryceco** [comment]
Is it added based on #525? I haven't integrated iD presets in a while but if you added it there then I'll go ahead and pull them.

**Comment by dieterdreist** [comment]
This had somehow escaped my attention, thank you for the pointer. https://github.com/ideditor/temaki/pull/66
