### ISSUE TITLE
XML Error loading map data

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#543]
![image](https://user-images.githubusercontent.com/111561/123802628-cb9e5e80-d8eb-11eb-93e5-7df93f9669b9.png)

This video shows that there are in fact two error messages but one is only there for a quarter of a second: ￼ https://share.icloud.com/photos/0Zcye746Z_B6TIk-lzibcocww

**Comment by bryceco** [comment]
Did anything trigger this, and how did you resolve it?

Next update (I submitted it last night) has better error display.

**Comment by tordans** [comment]
I don't know that I did anything special, just panned around a lot in search for something. 

It started working again after a while. 

Did this with just now again and git the same message https://share.icloud.com/photos/0vujNaDlyjVjhnxmKFJzxbyvg

**Comment by bryceco** [comment]
Is that 2.3.5 or 2.3.6?

**Comment by bryceco** [comment]
At some point a bug was introduced that causes the app to reload data from the server extremely frequently. Another user ended up getting block messages from the server for too much data use ("HTTP status code 509 (Bandwidth Limit Exceeded)"). I'm wondering if this is something similar, even though the message is different? Your error is (probably) "EmptyDocumentError" based on https://ios.forums.wordpress.org/topic/understanding-nsxmlparsererrordomain-error-messages.

**Comment by bryceco** [comment]
Pushing out a fix for the data consumption tonight, BTW.

**Comment by tordans** [comment]
It looks like the latest beta solved the issue. Was not able to recreate it even with a lot of panning around.
