### ISSUE TITLE
Large area not rendered correctly

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#545]
Just checking if this is a new thing or something that was always this way...

The "Tempelhofer Feld" is a large area and it shows only half filled (background) until I pan around it's borders in a circle once. 

Video: https://share.icloud.com/photos/0hUySIEAo_XS8tZ-erAiVNTQg

![image](https://user-images.githubusercontent.com/111561/124022179-c2e18180-d9ec-11eb-97b8-25058890144e.png)

**Comment by bryceco** [comment]
If it's a multipolygon relation then it will not be filled until all of the member ways are downloaded.￼

**Comment by tordans** [comment]
Yes, it is https://www.openstreetmap.org/relation/7317281. So this is behaving like intended and I will close it.
