### ISSUE TITLE
Beta: changing languages does not work as expected

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#547]
Video: https://share.icloud.com/photos/0Cx1R-PT8rXa4sNBNwvp64Epg

The video shows that the click seems to be recorded internally but the check mark only changes after re-entering the panel.

**Comment by tordans** [comment]
It also looks like not all panels use the new Lang. And the new Lang is not always marked with a check mark. 

Video 2: https://share.icloud.com/photos/0jQlzk82KOt2n4Kxa6W2QXW5Q

**Comment by bryceco** [comment]
Keep in mind it only changes languages for presets (Common Tags stuff).
