### ISSUE TITLE
Help button as a circle

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#551]
I remember reading https://github.com/bryceco/GoMap/commit/23af58a5f601291a5024a9abcb24cc287d93d767 which reads like it would fix this, so maybe the refactoring re-introduced the styling error?

Help button not a full circle:
![image](https://user-images.githubusercontent.com/111561/124026776-63867000-d9f2-11eb-8b5e-26eb67673a1b.jpeg)

Also, while we are on the topic of styling details, a bit of margin right next to the attribution image and before the attribution text would be a great addition:
![image](https://user-images.githubusercontent.com/111561/124026801-6aad7e00-d9f2-11eb-98a8-c4d719dfc696.jpeg)

**Comment by bryceco** [comment]
The code to make it a circle is there, but for reasons I don't understand it doesn't work (and hasn't ever worked).
I agree about the spacing.

**Comment by bryceco** [comment]
Turns out the code for setting the corner radius was being run prior to layout calculations that changed the size of the button. Fixed a few weeks ago but I don't recall the commit.
