### ISSUE TITLE
Arabic translation 

### ISSUE THREAD

**Issue by abdullahO2** [bryceco/GoMap#554]
have updated all Arabic translation on **weblate** and **iD presets**.
Thank you and my regards
Abdullah

**Comment by bryceco** [comment]
I've been watching the Arabic translations coming in and wanted to contact you, but I don't know how to do that from weblate. Thanks for the effort! In the next week I'll push out a new beta with them, and at that time please let me know if there are right-to-left issues that you'd like fixed.

**Comment by abdullahO2** [comment]
Thank you for this great application and I will inform you about my comments and user feedback in Arabic and maybe there will be translation fixes based on that.

**Comment by bryceco** [comment]
I'm going to post some previews so you can provide feedback. 

![image](https://user-images.githubusercontent.com/279734/128242602-4c2feb4f-4a86-4514-9c71-7910bb63a68b.png)

**Comment by bryceco** [comment]
This doesn't look very pretty to me. Suggestions welcome. 

![image](https://user-images.githubusercontent.com/279734/128242912-42a9218d-ecbb-466b-96ae-a34505c3bcd1.png)

**Comment by bryceco** [comment]
![image](https://user-images.githubusercontent.com/279734/128243582-b4908f91-dbd2-4a30-9a3e-6e1206f124ce.png)

**Comment by bryceco** [comment]
![image](https://user-images.githubusercontent.com/279734/128246467-7578b7dc-9d44-49e8-bf16-f7490a622d8d.png)

**Comment by bryceco** [comment]
![image](https://user-images.githubusercontent.com/279734/128256769-6ef0fe8a-438d-4df6-8679-c4b43d7bdc64.png)

**Comment by bryceco** [comment]
![image](https://user-images.githubusercontent.com/279734/128256798-92b67882-4b0b-4727-8bb1-bbbf06afebd3.png)

**Comment by bryceco** [comment]
![image](https://user-images.githubusercontent.com/279734/128256827-6c8f33fe-b133-4685-af40-f1d524adb4ac.png)

**Comment by bryceco** [comment]
![image](https://user-images.githubusercontent.com/279734/128261589-35b2f5e3-4361-4e32-9b0c-ca9745a53c1b.png)

**Comment by bryceco** [comment]
One oddity is that UISegmentedControls have the order of buttons reversed. Notice that the action buttons are reversed which seems fine, but also the undo/redo buttons are reverse-order. Is that correct?
![image](https://user-images.githubusercontent.com/279734/128265826-46e8dceb-e784-4199-b1d8-756f2613c421.png)

**Comment by abdullahO2** [comment]
Thank you very much, I have modified some translations to be better, I am joining TestFlight and will test any version that comes out and give you feedback if any.
Accept my greetings and thank you
