### ISSUE TITLE
gomap!! suggesting adding building information to a shop

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#555]
It’s maybe not fixable here, but I just noticed that adding some shops tags made gomap!! suggest me adding some building related information, e.g. height and building:levels
These tags are completely unrelated to a shop, they are describing a building. By presenting these rows people might be misled to add building tags to businesses

**Comment by tordans** [comment]
I think those might be tags from the "moreFields" section of the presets. iD shows those only via a search and suggest feature below the main fields. But AFAIK GoMap shows both fieldsets in one list

https://github.com/openstreetmap/id-tagging-schema/search?q=building%3Alevels

As to why those presets like "Club" have or [Shop](https://github.com/openstreetmap/id-tagging-schema/blob/9fdecc983443ce75185c2923caae9f7703f2cae4/data/presets/shop.json#L18) habe the tag suggestion in the moreFields at all: I don't really see why; but it would be something to discuss upstream in https://github.com/openstreetmap/id-tagging-schema/ (which is not really maintained ATM, unfortunately).

**Comment by 1ec5** [comment]
Each field specifies the tags that are required to be applied before the field can be offered as an option either in the main inspector or under More Fields. In this case, `building:levels` [requires](https://github.com/openstreetmap/id-tagging-schema/blob/9fdecc983443ce75185c2923caae9f7703f2cae4/data/fields/building/levels_building.json#L8) `building` (and ignores `building=no`). Is Go Map!! considering that prerequisite?

**Comment by bryceco** [comment]
@1ec5 Good observation. I believe that's my bug.
