### ISSUE TITLE
select ways lie on top of each other

### ISSUE THREAD

**Issue by TheFive** [bryceco/GoMap#556]
hi,

go map has a nice feature selecting things using the same line by tapping several times on that line.

but if there are two line using the same points

https://www.openstreetmap.org/node/4469536504
(Here the landuse and the highway lines are different.)

i did not find a way to select the highway, i only manage to get the line that is part of the multipolygon.

(see https://www.openstreetmap.org/node/4469536504 to get both lines)

Christoph

**Comment by bryceco** [comment]
You can long-press to pick any specific object  near the press.

**Comment by TheFive** [comment]
Thanks, that is helpfull
