### ISSUE TITLE
Use english for values of changeset message-source-placeholder

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#557]
ATM, the placeholder values of the input field for the changeset message source are translated.
However, the values I put in there, always be english – eg 'survey' instead of 'Beobachtungen'.

I suggest to always use the english terms for the placeholder.

![1C01FDEE-7E85-44AA-9F9A-6632F7EA23A6_1_105_c](https://user-images.githubusercontent.com/111561/131238564-53b4a542-bdd1-46cf-b3f0-17f8d5d4929d.jpeg)

---

PS: I was looking for a way to see the most used source-values, but Taginfo does not show changeset tags according to https://github.com/taginfo/taginfo/issues/305

**Comment by bryceco** [comment]
Okay, I did some changeset analysis and I agree they should probably be English. Because these items get translated "automatically" via the normal translation work-flow the only way to enforce "English only" is to mark them as "Do Not Localize" on the translation website, and hope that the translators do the right thing.

**Comment by tordans** [comment]
This sounds like an improvement, yes.

Is it technically possible to hard code the placeholder term? I wonder, if maybe GoMap should just suggest 'survey' as hard coded placeholder term in this case. 
IMO for the GoMap, 'survey' is the most likely value and users will likely leave it blank otherwise. I only add 'aerial imagery' (probably miss typing it as 'areal images') in cases, where I do couch mapping to refine something in GoMap.
It would stille be a free text field, but just suggest one value via the placeholder.
