### ISSUE TITLE
Switching views between 'Node tags' and 'Attributes' discards edits

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#560]
I added the location of a defibrillator and then wanted to see who updated the defibrillator in the 'Attributes' view.
Loading the web-view of the history and going back looses the data I entered (before pressing 'Save').

A short screencast (with bogus data) is attached.

https://user-images.githubusercontent.com/1651235/134784216-23931e42-4531-41da-b0af-59c7f21890a1.mov

**Comment by bryceco** [comment]
Looks like a bug! Thanks for reporting.

**Comment by bryceco** [comment]
Fixed in 89603be89fc22048f082139994de22f8bf322290

**Comment by habi** [comment]
Thanks for fixing!
