### ISSUE TITLE
HTML in value preview

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#562]
![image](https://user-images.githubusercontent.com/111561/135747190-b8b22bdb-123b-4c73-a52f-1b4e415a40ac.jpeg)

Saw that only once today with current TestFlight. In case that is only in Edge cases I would need to investigate more.

**Comment by bryceco** [comment]
That's coming from the iD presets, and is a buggy German translation:

https://github.com/openstreetmap/id-tagging-schema/blob/bde8a416c80cbbb27a0ad36df3c6dcec3151ec8b/dist/translations/de.json#L60

I can fix it but it will return the next time I import the presets.

You can report it to id-tagging-schema (although the project is unmaintained), or fix it yourself at https://www.transifex.com/openstreetmap/id-editor/

**Comment by tordans** [comment]
Thanks, I fixed the translations and nudged to remove all HTML from the generated files to provide a clean output https://github.com/openstreetmap/id-tagging-schema/issues/246.

I wonder, though, why this only now came up; the translations was 3 years old according to Transiflex.
