### ISSUE TITLE
Request to be able downloaded on M1 Mac

### ISSUE THREAD

**Issue by fishsunsun** [bryceco/GoMap#563]
JOSM provides all functions to edit OSM. However, most likely, I prefer GoMap for making changes on the go. It would be great if we can edit the map on the iPad app on Apple Silicon M1 Mac. 

And, since Apple is blocking side-loading the iOS app on Mac, it would be great if the developer can make it download-able on Mac App Store.

**Comment by bryceco** [comment]
This is definitely something I intend to support. It would have been included in the 3.0.0 release except that iOS 15 broke some things on the Mac side that I haven't fixed yet.
