### ISSUE TITLE
Aerial images Berlin 2021 does not show up

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#565]
In GoMap (App Store Version), I see "last update 6.10.2021" below the "additional areal images" section.

But the "Berlin/Geoportal DOP20RGBI (2021)" from https://josm.openstreetmap.de/wiki/Maps does not show up.

Don't understand why.

**Comment by bryceco** [comment]
I assume it doesn't appear in iD either, because it uses EPSG:25833 which (AFAIK) isn't a web mercator compatible projection.

**Comment by tordans** [comment]
Thanks, I did not even consider checking this. To me this is a big `+1` for https://github.com/bryceco/GoMap/issues/569, since in ELI the format is checked to be compatible with iD https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/de/Berlinaerialphotograph2021.geojson

**Comment by bryceco** [comment]
Partially fixed by edbcd2b06ff9155553b20c712c33b2ea50f96013. The 2020 imagery is there but not 2021 because it is marked historic. I need to figure out how to handle the best/historicphoto attributes.
