### ISSUE TITLE
list for selection should show ways first

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#571]
currently when long pressing on a way you get the relations first in the select menu, and in case there are many relations there is a lot of scrolling required in order to select the street at the bottom, e.g. https://www.openstreetmap.org/way/125151692
At least for the case when the object is a street, the probability that you want to select the highway for modification is much higher than for each of the individual routes

**Comment by bryceco** [comment]
Currently it orders them relations, ways, nodes (and then for identical types oldest first). It sounds like you want the order reversed (except for age). I don't have an opinion myself so if nobody else disagrees I can change it.

**Comment by tordans** [comment]
A few images, for reference:

**Example with only a few results**

![IMG_8251](https://user-images.githubusercontent.com/111561/137639900-59fe61dd-5101-4f2b-a448-922ec85cb32d.jpg)

**[Example with many relations](https://www.openstreetmap.org/way/125151692)**

| a | b |
|---|---|
| ![IMG_8252](https://user-images.githubusercontent.com/111561/137639918-bf36a298-5402-4d98-92fc-46b922104220.jpg) | ![IMG_8253](https://user-images.githubusercontent.com/111561/137639922-a6a6c38c-823c-469a-af57-cf55747bf29c.jpg) |

**Relation screen in "way tags panel"**

![IMG_8254](https://user-images.githubusercontent.com/111561/137639944-5b3b87c9-26fb-402c-ae7d-141b78e71dfc.jpg)

**Comment by tordans** [comment]
I wonder: Why do we need the relations in the quick select for anyways? AFAIK I cannot edit them directly, I can just tab "Tags" next to edit the tags, right? If so, maybe it would be enough to have one line, whenever there are relations

> List relations (12)

Which then opens the panel from the [last screenshot](https://user-images.githubusercontent.com/111561/137639944-5b3b87c9-26fb-402c-ae7d-141b78e71dfc.jpg) on the "Way Tags" panel with the "Relations" headline visible.

**Comment by bryceco** [comment]
It will now put tagged objects before untagged objects, then sort ways > relations > nodes
