### ISSUE TITLE
Local brand presets don’t show

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#577]
When I try and use local brand presets in Hawaii (eg. KTA Super Stores, Longs Drugs), they do not show up.

**Comment by TheAdventurer64** [comment]
@bryceco

**Comment by bryceco** [comment]
This is due to the location being specified as us-hi, and I don't support the state-province syntax. I'll fix it to ignore the dash suffix, meaning it will ignore the state but at least it won't reject it entirely.
