### ISSUE TITLE
'Bug reports and suggestions' could link to GitHub list of issues

### ISSUE THREAD

**Issue by alexandreleroux** [bryceco/GoMap#58]
Currently, the 'Bug Reports & Suggestions' under 'Settings' creates an email to app author.

It could be enhanced to link to the this GitHub list of known bugs or even better, display the list directly in the app. 

The author would then get less dupe bugs reports by email.

**Comment by TheAdventurer64** [comment]
Well, here we are in 2020, where this exact suggestion that was closed is now an option.

**Comment by bryceco** [comment]
Yes, that's why it's closed.
