### ISSUE TITLE
duplicate keys while editing tags

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#581]
When you change a key to a new key name which is already present, the existing tag gets dropped silently.
It would be better if the duplicate key is kept temporarily (so that the user can change it), and only when the tag sheet is closed there could be a warning that a duplicate key is dropped (or a dialogue: continue editing / drop duplicate tag), or even it could refuse to finish tag editing until you resolve the duplicate key problem

**Comment by bryceco** [comment]
I understand where you're coming from, but this dialog already has a lot of assumptions and complexity built into it, and I'm loath to add to that by supporting duplicate keys for an edge case.
