### ISSUE TITLE
would be nice to be able to set direction on more kinds of things

### ISSUE THREAD

**Issue by fdr** [bryceco/GoMap#582]
the feature whereby Go Map makes it easy to set the direction an information board is quite convenient.

I wish I could do it with benches. Maybe it'd be good to have an out-of-the-way to attach a direction tag to any point and open the widget to allow workarounds as new tag combinations that can have direction are added.

**Comment by tordans** [comment]
You can, by adding the `direction` tag on the "Node Tags" (middle panel) and then using the `(+)` to access the direction feature.

GoMap pulls presets from https://github.com/openstreetmap/id-tagging-schema. So if you want a specific preset to have the direction right from the start, it needs to be added there. 

I would +1 to add it to benches, which is used in the Neukölln micromapping map, eg https://supaplexosm.github.io/strassenraumkarte-neukoelln/?map=micromap#20/52.47466/13.44323.

**Comment by fdr** [comment]
Thanks, I think you mean "All Tags". I have opened a pull request:
https://github.com/openstreetmap/id-tagging-schema/pull/342
