### ISSUE TITLE
Fuel presets (octane)

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#583]
At least in my vicinity, all `amenity=fuel` 'serve' different octane levels.
These are currently not 'exposed' in the "Common Tags" tab, but it would be nice if they were.

![image](https://user-images.githubusercontent.com/1651235/150001288-47695dc5-3daa-41d4-a42f-4cb09ee10e70.png)

![image](https://user-images.githubusercontent.com/1651235/150002089-68c5a516-8ea6-4df5-b8c9-81d1cbddfd3c.png)

**Comment by tordans** [comment]
The presets are managed in https://github.com/openstreetmap/id-tagging-schema (see https://github.com/bryceco/GoMap#source-code-structure). The Common Tags only shows, what is part of the recommended and secondary recommended tags in the id-tagging-schema repo (similar to iD having two sections in the sidebar, one for the presets and one for all tags).

Another way would be add a custom preset (common tags => link at the bottom) in your local app which would then show the tag on the common tags panel as well.

**Comment by habi** [comment]
Thanks for the information @tordans. Do I understand it correctly that this could be changed in the ID presets and would eventually migrate to Go Map!!?

**Comment by tordans** [comment]
> Do I understand it correctly that this could be changed in the ID presets and would eventually migrate to Go Map!!?

Yes. Bryce pulls the Presets from the id-tagging-schema repo every now and then for GoMap. There are AFAIK no GoMap-Specific presets (only user specific presets on device).

**Comment by habi** [comment]
I just looked at the gas station with iD.
iD does expose more the `fuel types` than are visible in Go Map!! as can be seen in the screenshot below.

<img width="400" alt="Screenshot 2022-01-21 at 12 38 26" src="https://user-images.githubusercontent.com/1651235/150520952-c8186d1e-6e17-47b6-b97f-82545ac30f1e.png">
.

**Comment by TheAdventurer64** [comment]
A similar problem occurs with `payment` tags. Certain tags like `payment:discover_card` and `payment:jcb` are not available via the GoMap preset, but is available through the iD editor. Maybe a possible fix is to add more slots for the `Payment` field?
