### ISSUE TITLE
take pictures with Gomap & add keywords from OSM [XML,XMP...]

### ISSUE THREAD

**Issue by JLZIMMERMANN** [bryceco/GoMap#587]
Something would be great : give abiliy to open the camera of the Iphone. Then while taking pictures be able to select the POI that are taken to push EXIF, XMP and IPTC datas.
In my idea it would be great to link some keywords selected from the map of the main objects that are taken. By this way, it would help to manage easily a huge number of pictures.

**Comment by bryceco** [comment]
I don't understand what information you want to add to EXIF. Can you give examples?

**Comment by JLZIMMERMANN** [comment]
Have you taken a look to the app named [DigiKam ](https://www.digikam.org/)it's a great app to improve the tagging system for pictures.
![image](https://user-images.githubusercontent.com/4929752/179002770-0e9ce336-d7c0-4929-882f-56df5640929a.png)

 In my idea it would be something like : 
- I select an object in Gomap
- I select picture option
- I take my picture and the app pushes the OSM tags in metadata of the picture

**Comment by bryceco** [comment]
If I understand this correctly you're using this approach to tag photos, not objects in OSM. So it really belongs as part of a photography app doesn't it? It doesn't seem like it does anything to contribute to OSM, which makes it out of scope.

**Comment by JLZIMMERMANN** [comment]
Some app let us take pictures (Streetcomplete, OSMand, Mapcomplete [web]) but there is still no common store to keep these to be seeked in a simpest way using K=V.
In your app GoMap we may use the camera to mesure.
It was an idea for something still missing.
