### ISSUE TITLE
Clarifying whether logged in or not

### ISSUE THREAD

**Issue by alexandreleroux** [bryceco/GoMap#59]
In the Settings panel, under 'Credentials', I suggest changing the current label 'OpenStreetMap Login' to 'Logged as OpenStreetMap user $username' when successfully logged in to make it obvious right in the main Settings panel whether or not we're logged in.

**Comment by bryceco** [comment]
Added.

**Comment by jwmh** [comment]
Update / bug:
This doesn’t display after tapping the actual login;
it should have “Sign Out” or “Switch Accounts”.

instead it still gives the Sign In or Register option.
