### ISSUE TITLE
pasting not on selection

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#591]
there is a regression (?), go map is again pasting tags to other objects than the selected. This behavior is so time consuming and one risks to upload wrong data.
I select a way, add a node to it and paste tags (doing this for house numbers in Italy, where entrances are the object that gets the number). GoMap!! rather than pasting the tags to the node, looses the selection and pastes them to the relation in which the way is.
There is not even a hint for the user that the editor is doing something different than requested. 
I end up with an arbitrary address on a building multi polygon and an entrance tag on it. Only way to work around it is doing twice the select node and paste option, then select the relation and delete the tags. For every single house number and there are many on every building.

I know this is meant as a feature, but it just doesn’t work for me. Maybe it could become an option switch “do what I ask to do” / “let the software decide where tags go”
in case the user chooses the latter, be smart and do not add node only tags to polygons (e.g. entrance=*)

**Comment by bryceco** [comment]
I'm not sure this is a regression but it might be a bug. This feature where it "promotes" the selection from a node to the parent way is only supposed to happen if neither the node nor the way contain any tags, and the way is not a member of a relation, so typically it triggers only on a freshly drawn way. You say that it pastes the tags to a relation so I'm wondering what exactly was and was not tagged when you saw this.

**Comment by dieterdreist** [comment]
It was always ways which were members of a multipolygon relation (parts of a building or landuse). It happens when surveying housenumbers, which either go on gates or entrances here, so I create a node on the way and paste the tags to it, before modifying the number.

**Comment by bryceco** [comment]
Yep, you're right there's definitely a bug.
