### ISSUE TITLE
Issue with 

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#595]
I recently added a [`amenity=charging_station`](https://www.openstreetmap.org/node/9705193077) with the newest TestFlight version of Go Map!!.
In older versions I was able to search for 'charging' in the 'Common tags' tab, this time it didn't work, I had to enter the tags manually.

When added, the charging station was missing it's icon (from a tagging preset?), being only labeled as 'Amenity', as seen in the screenshot below.

![IMG_9062](https://user-images.githubusercontent.com/1651235/166414327-3c3f400b-b319-489a-9fff-e5cdc88b097c.PNG)

I'm running GoMap!! Version 3.1.4 (3104) on an iPhone 12 mini with iOS 15.2 (19C56

**Comment by bryceco** [comment]
I believe this is because it’s part of a way. The presets categorize things as point/line/vertex/area, and charging stations should be point or area.

**Comment by habi** [comment]
The charging station is attached to the wall of the building, that's why I mapped it like so.
I just double-checked, if I add a charging station as a single node somewhere in the Pampas (figuratively) the search works as expected.
Thanks for the explanation/clarification!
