### ISSUE TITLE
Have to press + to enter next node in track

### ISSUE THREAD

**Issue by khelbley** [bryceco/GoMap#6]
After starting to enter a track I was expecting to tap a location on the map to add the next point.  maybe add a way to toggle between pressing plus to create the next node and tapping the location of the next point?

I intended to label this -enhancement- but can't figure out how labels work with my access.

**Comment by bryceco** [comment]
The 1.4 release allows you to directly draw ways: tapping the screen while holding down + will add nodes wherever you tap. You can quickly add a bunch of nodes along a curving road this way, for example.
