### ISSUE TITLE
Add unit dropdown for attributes containing number values

### ISSUE THREAD

**Issue by dudeuter** [bryceco/GoMap#600]
I was doing some analysis of `maxspeed` values in the US in OSM recently, and found some recent contributions from a GoMap user that did not have `mph` units.

OSM uses metric units as defaults, depending on the attribute, and the geography you are in it's not always intuitive what that unit should be.

It would be good to add a dropdown menu for units, this can help prevent contributors from making simple mistakes that they otherwise might not even know they're making.

**Comment by 1ec5** [comment]
The `maxspeed` and `maxspeed:advisory` fields [are of type `roadspeed`](https://github.com/openstreetmap/id-tagging-schema/blob/04c6691082c761a629bed574f9ebf93eb8167d27/data/fields/maxspeed.json#L3), which Go Map!! presents as a text field with a numeric keyboard by default:

https://github.com/bryceco/GoMap/blob/9a0c7ae65e2510dfbd2b0252d7a7df12936234ca/src/Shared/PresetsDatabase/PresetsDatabase%2BTableView.swift#L639-L640

It is possible to enter a correctly formatted value such as `25 mph`, but there’s no indication that a new value should follow that format.

[iD’s implementation of this field type](https://github.com/openstreetmap/iD/blob/develop/modules/ui/fields/roadspeed.js) includes a unit dropdown menu and defaults to the unit [appropriate to the current country](https://github.com/ideditor/country-coder#roadSpeedUnit).

**Comment by bryceco** [comment]
I added a tristate km/h or mph button that updates the value appropriately:
![IMG_0011](https://user-images.githubusercontent.com/279734/181656497-d363d931-699c-4630-b632-5dc68421b03f.PNG)
