### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by AntonM030481** [bryceco/GoMap#602]
Is it possible to clear cache to get updated data from OSM servers?
I hade to uninstall app with it's data and install it again.

**Comment by tordans** [comment]
Yes, that is possible:

On the map screen, hit the Map-Icon (above the "+" Icon)
-> There is "empty cache" as the second group (similar wording)
-> On that panel you have a selection of caches; to get fresh data, choose "clear OSM data" (first entry) (similar wording*)

---

*) my app is in German…

**Comment by AntonM030481** [comment]
Thank you!
