### ISSUE TITLE
Authentication failed 

### ISSUE THREAD

**Issue by oggioniale** [bryceco/GoMap#604]
I have an account OpenStreetMap but if I use the credentials into Go Map!! the response is “Bad login. Not found”.
How can solve this?

**Comment by bryceco** [comment]
What are you using for your user ID? You need to use your OSM ID, not an email address. If you signed up for OSM using OAuth and don't have an OSM user ID you can create one by setting a Display Name here: https://www.openstreetmap.org/account/edit

**Comment by oggioniale** [comment]
I use the user ID of OSM without email reference (xxx of xxx@pippo.com).
I don't use OAuth for signed up in the OSM.

**Comment by bryceco** [comment]
Can you post or email me (from within the app under Contact Us) your user ID?
