### ISSUE TITLE
Misspelled tag: "cabines"

### ISSUE THREAD

**Issue by mueschel** [bryceco/GoMap#605]
Users of this app add the wrong tag 'cabines' to camping places. The correct key would be 'cabins'.

**Comment by 1ec5** [comment]
“Cabines” doesn’t appear in this codebase, except as a substring of a message in the French and Dutch translations. Of [the instances you recently corrected](https://osmcha.org/?filters=%7B%22tag_changes%22%3A%5B%7B%22label%22%3A%22cabines%3Dyes%22%2C%22value%22%3A%22cabines%3Dyes%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%222022-06-01%22%2C%22value%22%3A%222022-06-01%22%7D%5D%7D), [only one](https://www.openstreetmap.org/changeset/122481375) was introduced by Go Map!!, using the German localization. (The others were saved in JOSM.) Presumably the mapper added `cabines=yes` manually using the All Tags tab.

**Comment by mueschel** [comment]
Sorry, it seems I messed this up in my memory.
