### ISSUE TITLE
Direction not working on yield sign

### ISSUE THREAD

**Issue by Coloradohusky** [bryceco/GoMap#610]
Currently, stop signs that use [forward and backward](https://wiki.openstreetmap.org/wiki/Key:direction#Forward_and_backward) render their direction on the map. However, yield signs (highway=give_way) don't appear to render their direction when given the same forward or backward tag.
![image](https://user-images.githubusercontent.com/45430066/181162602-8a825334-b11e-4032-9a65-c30da2b6fbc9.png)
![image](https://user-images.githubusercontent.com/45430066/181162606-ca9a652b-c09a-496a-ae81-079fbaec2e4b.png)

**Comment by bryceco** [comment]
Thanks! Any other related directional objects you can think of?

**Comment by TheAdventurer64** [comment]
> Thanks! Any other related directional objects you can think of?

I believe that traffic signals don't support `traffic_signals=both`.

**Comment by bryceco** [comment]
> > Thanks! Any other related directional objects you can think of?
> 
> I believe that traffic signals don't support `traffic_signals=both`. Same with stop signs.

If the node is part of a single way then "both" is supported. If it's at a 3-way or 4-way intersection then it needs to specify "all" instead of "both".

**Comment by TheAdventurer64** [comment]
> > > Thanks! Any other related directional objects you can think of?
> 
> > 
> 
> > I believe that traffic signals don't support `traffic_signals=both`. Same with stop signs.
> 
> 
> 
> If the node is part of a single way then "both" is supported. If it's at a 3-way or 4-way intersection then it needs to specify "all" instead of "both".

My bad - I meant to say `traffic_signals=all`.

**Comment by bryceco** [comment]
> > > > Thanks! Any other related directional objects you can think of?
> > 
> > 
> > > 
> > 
> > 
> > > I believe that traffic signals don't support `traffic_signals=both`. Same with stop signs.
> > 
> > 
> > If the node is part of a single way then "both" is supported. If it's at a 3-way or 4-way intersection then it needs to specify "all" instead of "both".
> 
> My bad - I meant to say ~`traffic_signals=all`~ `direction=both` on traffic signals and stop signs.

Yes, I understood what you meant, that should work correctly:
![IMG_0010](https://user-images.githubusercontent.com/279734/181637325-30cad3aa-4e15-492a-8c66-0f4b441b922e.PNG)
