### ISSUE TITLE
Use best aerial, not Bing

### ISSUE THREAD

**Issue by matkoniecz** [bryceco/GoMap#613]
I showed Go Map to a friend who has an iphone - and noticed that on new start, in Poland it was using Bing.

In Poland Geoportal is marked as preferable layer and it was even shown in imagery switcher (with a star).

I think it should be also selected by default.

Note that in Poland Bing is massively inferior, mostly due to massive imagery offsets while Geoportal is more accurate than high quality GPS and can be assumed to be ideally accurate.

**Comment by bryceco** [comment]
Yeah, it always defaults to Bing on first launch since we want to ensure it always has something reasonable to display at startup (and we may not have finished downloading ELI yet). I agree this could be improved, but there might be a weird jump when imagery switches from Bing to "best" an indeterminate time later.

**Comment by 1ec5** [comment]
iD bundles a snapshot of ELI with the application. Maybe would that be an option to make it more synchronous? The tradeoff would be that users wouldn’t get the absolute freshest layers until upgrading to the next Go Map!! release.

**Comment by matkoniecz** [comment]
ELI is updating quite rarely, while difference in quality between Bing and Geoportal is gigantic, and partially not obvious.
Update only on release would be likely good enough (how often default layer somewhere gets broken?).

here offset is tiny, but user "fixing" it using Bing aerial would be irritating. It used to be common problem when iD defaulted to Bing
![screen20](https://user-images.githubusercontent.com/899988/183823314-d6a323e4-5908-44e7-b9bb-f14056858e26.png)
![screen21](https://user-images.githubusercontent.com/899988/183823324-b763607f-2257-4160-9dea-7ea748187bb4.png)

here is more noticeable kind of difference. Geoportal.gov.pl is also often getting targeted updates after major infrastructure projects are completed, like opening motorway.
![screen23](https://user-images.githubusercontent.com/899988/183823356-a5c8d33d-6667-4bf9-8a2c-f23937d57389.png)
![screen22](https://user-images.githubusercontent.com/899988/183823339-1c018981-65e2-4a62-870e-51b7c326d89e.png)

Or maybe have bundled ELI + fetch updated one?

**Comment by matkoniecz** [comment]
Though it is nice that it updates later, that almost entirely fixes my worries.

**Comment by bryceco** [comment]
I've added code that checks for better imagery when the user moves to a new location or better ELI imagery downloaded. There's a chance that if the user is determined to use non-best imagery that it will seem like nagging, but it only prompts if the user moves at least 10 km from the previous prompt, so I think it's acceptable.

![IMG_0766](https://user-images.githubusercontent.com/279734/189250242-9a8c1730-84f6-4f4a-aaab-92bbff2cc2b3.jpeg)
