### ISSUE TITLE
Problem with the "Advanced Settings" dialog

### ISSUE THREAD

**Issue by csterritt** [bryceco/GoMap#616]
Hello,

First time using this -- looks pretty cool! However, I wanted to change the speed of zooming (I'll do another issue for that).

Hoping to find it under "Advanced Settings", but got the following dialog on an Intel iMac, running macOS 11.6.8.

<img width="552" alt="Screen Shot 2022-09-22 at 12 04 30 PM" src="https://user-images.githubusercontent.com/37917/191797534-0b457393-5825-493e-a2ee-23b0cc819431.png">

I didn't copy the whole dialog, the rest was blank.

Thanks!

**Comment by bryceco** [comment]
Fixed in 7fe5118675213611a311fc05dd465ef0d47e02d5, thanks for the report!
