### ISSUE TITLE
upcoming schema change in id-tagging-schema repository

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#618]
@bryceco, in https://github.com/Zverik/every_door/issues/452 @tyrasd informed about upcomming changes to the id-tagging-schema repo which will also require updates in GoMap.

Since pulling the data is a manual process in GoMap, this is just a FYI.

**Comment by bryceco** [comment]
Thanks for this!

**Comment by bryceco** [comment]
Improvements for this are now present in the 3.1.8 TestFlight.
