### ISSUE TITLE
Unable to build current version

### ISSUE THREAD

**Issue by patricks** [bryceco/GoMap#621]
Hi,

I tried to build the current master branch, but I get the error message:

`Missing package product 'CountryCoder'`

Do I need to get the package from somewhere else or did I miss some setup step(s)?

<img width="257" alt="Screenshot 2022-11-15 at 16 13 25" src="https://user-images.githubusercontent.com/132167/201955866-5b58ae0e-66bf-43b7-85ad-68a61e5762f2.png">

**Comment by bryceco** [comment]
It’s available here: https://github.com/bryceco/country-coder

and the package definition is at:
country-coder/src/CountryCoder/Package.swift

Sorry, I’d meant to fix up the reference to it so it would get pulled automatically. It’s a bit of a mess at the moment.

**Comment by bryceco** [comment]
I migrated the external package into the code base, so this should no longer be an issue.
