### ISSUE TITLE
Switch to kotlin in Version 4.0

### ISSUE THREAD

**Issue by MaestroGlanz** [bryceco/GoMap#623]
Hello Bryce Cogswell,

you might not like the suggestion at first, but it is a thing, which I would really like. With https://vinivendra.github.io/Gryphon/ there can be a translation of your code to kotlin. I don't know, how well this works, but if it works, it would open the possibility to deploy for Android and iOS. I never tried this translator, it might be garbage, might be good, I don't know.

Your editor is by far the most superior editor for phones and tablets. It is the only reason, why I would like to have an iPad. But unfortunately, there are other reasons against it. Mostly the price for just one single purpose.

**Comment by bryceco** [comment]
Automatic translation systems like this translate the code, but they don't translate the underlying APIs that the app uses to interface to the OS. That means that any code doing UI would have to be redesigned to be cross-platform, and that's a very big project, larger even than the conversion from Objective-C to Swift done a couple years ago.
