### ISSUE TITLE
Show "extra" tags when editing Common Tags

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#624]
Currently when an object contains tags that are not part of the set of predefined presets that get displayed in Common Tags it's necessary to switch to All Tags to see them. To resolve this I'd like to show those extra tags as another section within Common Tags.  A first try of that appears below. Currently I'm experimenting with this appearing at the bottom of the Common Tags page, but I'm looking for feedback on alternatives (possibly in the section just before the last section of presets).

![IMG_1975](https://user-images.githubusercontent.com/279734/208199927-beb93630-dc13-4a96-9fd6-07823331b75a.PNG)

**Comment by bryceco** [comment]
Completed in d2b2f274274324adaae26901147a28334931c588

**Comment by tordans** [comment]
Thanks, I am looking forward to "clicking" a lot less, now!
