### ISSUE TITLE
Testflight 2022-12: Change highlighting color of filled in tags

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#625]
The new "common tags" view (https://github.com/bryceco/GoMap/issues/624#issuecomment-1356623313) is great. It means I have no reason anymore to constantly switch back and forth with "node tags").

I also like the new highlighting color of filed that are filled in vs. missing!
**However, I suggest to change the color.**
The green suggest a validation – as in "this is correct in some way". I was expecting a red version of that line…
But the message is more like "this tag has some value".

Working with color for this kind of messages is super tricky in my experience. Any red-green-yellows will likely be interpreted as some kind of validation or call to action.

Would it maybe be enough to use some shade of white/black/gray?
Or maybe change the text color slightly for those keys that don't have a value yet (this should be applied to the "all tags" section below as well, I think).

<img width="387" alt="image" src="https://user-images.githubusercontent.com/111561/208858259-32a973eb-7faf-4665-a407-06d2a0738c30.png">

**Comment by bryceco** [comment]
Thanks for the feedback. I’m also not terribly happy with the color so this is just a first try. I initially was adding a tint to the entire table cell but that was too distracting. I wanted to change value text colors but that doesn’t work with yes/no values. I didn’t think of changing the color of the key text. 

I’ll try changing it to a blue shade. We can also narrow the line if you think it’s too distracting? Or we could have a blue dot?

**Comment by bryceco** [comment]
Fixed in 6ca67d8bb792b377bc7b4801c135d61909f3a450
