### ISSUE TITLE
Make it easier to remove a dropdown value

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#626]
This is about adding more ways to remove a value from a dropdown field.

## First off, there is a way now, which is:
1. click the value input
2. click the (x) icon
<img width="432" alt="image" src="https://user-images.githubusercontent.com/111561/208858844-8e408c53-bca4-4527-b225-c9080bcda7d5.png">

However, this is never the way I tend to work with those fields; I only find this option after some clicking around…

## Option: swipe "delete"

UseCase: Delete value without first focussing the value input.

Improvement: I would love to just swipe right on the field to get a "delete" or "empty" button which I can then click to null the field.

View:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/111561/208858772-37c1767c-485f-4293-bab0-49a0306344e3.png">

## Option: "remove value" as part of the dropdown

UseCase: I am in the dropdown, I want to select "no value" to get out of the dropdown.

Right now I have to click around to somehow get out of the dropdown. I get there… but never intuitively; often I select a value to remove afterwards. I wonder why the "Cancel" action is never convenient for me. It might be an issue of one-hand usage and the cancel being super far away, so I cannot reach it.

Improvement: Add an option "No value" or "Remove value" (if present) to the dropdown, which sets the value to null.

View:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/111561/208858800-33e50a77-de53-4fe8-b8e1-e7f65be5b6c7.png">

**Comment by bryceco** [comment]
I've added swipe to delete on arbitrary items in Common Tags.
