### ISSUE TITLE
Maxar Imagery issue

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#627]
I get the error message below when wanting to look at 'Maxar Premium Aerial'.

TestFlight Version 3.2.1 on iOS 16.3

![image](https://user-images.githubusercontent.com/1651235/219590241-363eb4ba-9521-49e4-978c-b6add6037954.jpeg)

**Comment by bryceco** [comment]
Maxar recently deactivated some of their server tokens (JOSM was also affected). I have a new token from them but it will require a new build to make it available to users.

**Comment by habi** [comment]
Great, thanks for the info!
Shall this issue be left open until the next build?

**Comment by bryceco** [comment]
I'll leave it open for visibility until the fix is released.

**Comment by tohaklim** [comment]
Works ok in 3.3.0

**Comment by habi** [comment]
Works fine in v3.3.3

**Comment by Kopterlove** [comment]
Around some weeks not work on 3.4.8 :(

**Comment by tohaklim** [comment]
Yep, broken for me again - shows login failed, Maxar probably swapped the creds again

**Comment by cicku** [comment]
@bryceco please disable that imagery, they no longer provide access.
