### ISSUE TITLE
Is there any way to change the bing imagine offset to match open street map data?

### ISSUE THREAD

**Issue by stephane-archer** [bryceco/GoMap#632]
Hi, there is a big difference of a few meters between bing map position and Open street map data in El Chalten Argentina.
Is there any way to change the bing imagine offset to match open street map data?

**Comment by dieterdreist** [comment]
on a side note you can check with strava heatmap which is the correct alignment, from experience where the terrain is not flat, simply moving the aerial imagery is typically not sufficient because it is distorted.

**Comment by bryceco** [comment]
We don't support imagery offsets. I'd like to add support for it but I don't know a good way to do it within the confines of the UI.  Maybe a 4-way button near the compass that bumps the imagery a few pixels at a time? And there needs to be a way to indicate that an offset is currently active. Also, closed as dup of #32.
