### ISSUE TITLE
Open custom OSM or geojson layer

### ISSUE THREAD

**Issue by Valenoern** [bryceco/GoMap#636]
I have been trying out an Android app called [Vespucci](https://github.com/MarcusWolschon/osmeditor4android), which allows you to load in a geojson layer it will show as generic points or shapes. (This app actually has a "layer stack" where you can arbitrarily add and arrange new imagery or data layers.)

But what I would really like to do is import and display an arbitrary **layer of OSM-formatted objects**.  
If you think about projects such as [OpenHistoricalMap](https://wiki.openstreetmap.org/wiki/Open_Historical_Map) which build on OpenStreetMap and its format but should not be combined with OSM, any OSM editor can be just as useful for prototyping map data for these projects. (In my case, I like to keep an informal game guide of [AR portals](https://en.wikipedia.org/wiki/Ingress_(video_game)) for Pokémon Go, and am experimenting with creating a "standard" set of tags to describe portals.)

The way I tend to use this custom layer is to create my own editor preset which uses the image and tags I want and associates them together. (here, the otherwise-bogus tag `tourism=portal` and the `fas-cube` icon.) Then I expect things tagged with my preset to show up as the new icon. [I messed with iD](https://github.com/openstreetmap/iD/issues/9514) and got it to do this by manually injecting a preset, and expect this is also about the way it works in [JOSM](https://wiki.openstreetmap.org/wiki/JOSM).

(If being able to specify an icon for a preset as a preset should be another issue, that's fine. That's just more context.)

**Comment by bryceco** [comment]
Both iD and Go Map!! are developed to enable people to contribute new data to the OpenStreetMap database. They are not meant to be used to display maps to end users for navigation etc. which seems to be your use case. Other frameworks are more appropriate for that.
