### ISSUE TITLE
Quest: Crash when selecting row

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#637]
Video:

https://share.icloud.com/photos/01dQcwhB7iK97nEF8YYOJ8W9w

1. custom quest natural=tree and ref missing
2. open quest
3. select row (light gray highlighting of area of input field)
=> crash

I submitted two reports as well on this, but those are the steps.

**Comment by bryceco** [comment]
I wasn't able to reproduce a crash on 3.3.7 but I went ahead and eliminated the ability to select a row when it's a text field.
