### ISSUE TITLE
Quest: Quest cannot be saved

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#638]
The save action is disabled.

Custom quest `natural=tree`, `ref` missing.

~~I think I already created an issue on this about the save button being disabled in the regular tagging view as well, in some situation.~~ => Now I did, see https://github.com/bryceco/GoMap/issues/645

 ![1A0B9243-C236-4C38-B3F1-5FA4FD83FDE1_1_201_a](https://user-images.githubusercontent.com/111561/222955432-d7d18b31-f7f2-4ebb-a657-5d078e932883.jpeg)

**Comment by bryceco** [comment]
Fixed in 3.3.7
