### ISSUE TITLE
Quests: Open Tag Editor should preserve value

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#639]
1. I start here with a value given
   ![1A0B9243-C236-4C38-B3F1-5FA4FD83FDE1_1_201_a](https://user-images.githubusercontent.com/111561/222955432-d7d18b31-f7f2-4ebb-a657-5d078e932883.jpeg)
   (Ignore the highlighting on the top right, that is for https://github.com/bryceco/GoMap/issues/638)
2. "Open Tag Editor" to add details
3. SHOULD: Preserve the value "9"
    IS: Value is lost
    ![1D9C77F4-0CF6-4D56-9254-C85B0FF810C8_1_201_a](https://user-images.githubusercontent.com/111561/222955529-d82893a5-0dfd-4f8c-96be-9a8e7c7c98b7.jpeg)

**Comment by tohaklim** [comment]
I think this is fixed (or alleviated) in 3.3.6, where opening the tag editor from the quest menu now prompts the user to save/discard values previously entered

**Comment by bryceco** [comment]
Yep, should be fixed in 3.3.6 and later. If not please reopen.
