### ISSUE TITLE
Quest: (Feature) Filter by geometry type (line, point, area)

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#641]
I want to create a quest "all highways (lines) that do not have a surface tags".
Unfortunately, OSM uses the `highway` key for various point geometries like `street_lamps`.

It would be great to be able to filter for "only match on line|point|area".

![7BFD702E-F904-4657-B453-BD6FC3044E69_1_105_c](https://user-images.githubusercontent.com/111561/222955672-e5f51f1d-1c5f-4b3a-ae52-cf903b662cd9.jpeg)

---

This screenshot shows that currently the quest is applied to `highway=street_lamp` and such:

![A3568265-D3CA-47C8-9689-8C838FAE1AB1_1_105_c](https://user-images.githubusercontent.com/111561/222955714-0785f4c7-218d-4126-b08e-8872cb7d9623.jpeg)

**Comment by bryceco** [comment]
When I first prototyped quests I included a geometry field, then removed it later because it seemed redundant. I guess I'll put it back in!
