### ISSUE TITLE
Quest: Highlight quest when geometry selected

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#642]
I dense areas, its hard to see which geometry belongs to a quest.

This is especially hard since the quest don't use the centroid, yet. (Btw, this might be a good read on that topic https://blog.jochentopf.com/2022-11-10-finding-representative-points-for-polygons.html)
But even if this where fixed…

It would be great to highlight the quest icon when I select the geometry that belongs to it.

Eg change the dark blue to the light blue of the selected outline.

Example: In this case, the quest does not belong to the selected area but I thought it did…
![5019E7F4-B9FB-42DB-9EDC-3289288FB889_1_102_o](https://user-images.githubusercontent.com/111561/222955801-7f2c01c6-432d-40de-8a29-d5f8909cbb9d.jpeg)

**Comment by bryceco** [comment]
Keep those suggestions coming! 👍
