### ISSUE TITLE
Quest: Prevent auto correct to capitalize letters

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#643]
With my German keyboard, the inputs are auto corrected to use capitalized letters. This is quit annoying, since we use lower case keys and values in OSM.

Is there a Way to tell iOS to not do this on those inputs?

![76E8EBF3-D4A4-4BF5-91F7-EDA19AF2E80C_1_105_c](https://user-images.githubusercontent.com/111561/222955910-dda36305-c5f8-4617-b5b8-121d31adb567.jpeg)

**Comment by bryceco** [comment]
This regression should be fixed in 3.3.7

**Comment by bryceco** [comment]
3.3.7 fixes a different capitalization issue. This issue is fixed in 373028fad4d9e7f721c41c20b5b5b8d7b37b6926 and will be in the release after 3.3.7
