### ISSUE TITLE
[Regression] Notes are not 'Resolve'd

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#648]
I wanted to close [a note](https://www.openstreetmap.org/note/3587731) with Go Map!! Version 3.3.6.
The note is resolved on OSM when clicking 'Resolve', but not in Go Map!!, where it can be resolved several more times.
I *think* I noted that already in an earlier TestFlight build, but didn't file an issue then.

**Comment by habi** [comment]
Here's a link to a little screen recording: https://share.icloud.com/photos/02624mZcleVr9Nmxn7tTDdTgg

**Comment by bryceco** [comment]
Thanks! I'll check it out.
