### ISSUE TITLE
Use iCloud to store app data

### ISSUE THREAD

**Issue by euf** [bryceco/GoMap#654]
As mentioned in #653, 

> When you delete the app it deletes all presets/settings/data

Maybe GPX traces and custom presets could be stored in iCloud Documents? I was rather disappointed by losing several hours of GPX recordings while updating from App Store to Testflight version. Moreover, it would become easier to export and import GPX files or to share presets among users. 

Storage usage also should not be an issue: utilizing several hundred kilobytes (or even a couple megabytes) wouldn't be too much even for those who stick with a free 5 Gb plan.

**Comment by fntagit** [comment]
If this would be implemented, would it be possible to also save the definitions of the user defined imagery? I have about 35 such definitions, and I already have lost them several times.

**Comment by bryceco** [comment]
I'd like to have many settings stored in iCloud, which would have two effects:
* They'd be preserved if you buy a new device, or delete the app and reinstall.
* They will be shared between devices if you use both iPhone and iPad, etc.

My initial list of settings to save is:
* preferred language 
* customization of POI presets and other settings
* custom quests
* which quests are enabled
* custom imagery
* nominatim search history
* upload comment/source text and history

If you're mapping in a particular area on your phone and then start using your iPad, should we assume the user wants to continue mapping the same area? Or is it more likely that the two tasks are unrelated? My first instinct is two treat them as separate editing sessions, which means that these settings are NOT stored:
* current lat/lon 
* display settings and overlays
* when gpx tracks expire
* current imagery selected
* which object filters are enabled

Does that seem reasonable?

**Comment by bryceco** [comment]
> Does this also implicate user-defined imagery? It seems like every time the app updates, I have to re-add some custom tile servers. 

Yes, it will include user-defined imagery

> In fact for some reason today I only see two options. There used to be many more defaults.

The list of aerial imagery is downloaded when the app first launches, and stored in the cache directory. It's possible for the system to decide to delete cached items, in which case the app will download it again on the next launch. If for some reason it isn't able to connect to the server then you only get the few imagery providers that are built-in.

> Edit: The Default list somehow returned to normal, but my user-defined servers still did not carry over.

You shouldn't be losing user-defined imagery. I'll look into it.

**Comment by bryceco** [comment]
> > Edit: The Default list somehow returned to normal, but my user-defined servers still did not carry over.
> 
> You shouldn't be losing user-defined imagery. I'll look into it.

To clarify, if you delete the app and reinstall then you should expect to lose user-aerial imagery, but that problem should be fixed when this change happens.

**Comment by bryceco** [comment]
This was added in 1a58879, except for the part about GPX files which are still stored locally. Forgot to update this issue.
