### ISSUE TITLE
Quest menu shows only after drag & drop on the map

### ISSUE THREAD

**Issue by yellowsoar** [bryceco/GoMap#655]
## Reproduce
1. tap on any quest
2. no quest menu
3. drag & drop on the map
4. here comes the quest menu
5. check the screen recording

https://user-images.githubusercontent.com/4775704/229775240-156deef5-3fc0-4f8f-8e7d-933a8cd0bd1e.mov

## Environment
Model: iPhone SE MXD22TA/A
iOS: 16.3.1
Go Mapp!!: 3.4.5 (3405)

**Comment by bryceco** [comment]
Weirdly enough this regression was caused by https://github.com/bryceco/GoMap/issues/652.
