### ISSUE TITLE
Location marker is drawn incorrectly sometimes

### ISSUE THREAD

**Issue by euf** [bryceco/GoMap#658]
When location button was switched off and then turned on, the location marker is often misplaced: it is drawn somewhere relative to the cursor. Then it's fixed by an instant jump to an actual location only when the map is moved. 

I recorded two examples of thisbehavior. First is more common, the marker appears under the cursor in the center of the screen. Second happens not so often, the marker has a repeating offset to the cursor. 

To reproduce this, one could try tapping location button on and off while dragging the map between these events. 

https://user-images.githubusercontent.com/11754264/230793704-bcf3d9a7-2e28-474b-908a-d570290f90ce.MOV

https://user-images.githubusercontent.com/11754264/230793728-d9125301-0387-47a9-aef3-1cba4b1ac332.MOV

**Comment by bryceco** [comment]
Is anyone able to replicate this? I don't see the behavior myself.

**Comment by euf** [comment]
Since the report, I was not able to reproduce it myself. Must have been some random glitch. Closing the issue now, will update in case it happens again

**Comment by bryceco** [comment]
Thanks for the update!
