### ISSUE TITLE
Background GPX recording seems broken

### ISSUE THREAD

**Issue by euf** [bryceco/GoMap#661]
Previously I used App Store version a lot to record GPX tracks while driving (app was in background and another navigation app was active) or while hiking (screen was off and phone was in the pocket). 

Testflight version doesn't work in both scenarios, GPX recording stops at the moment app goes background or screen turns off.

In the system settings I noticed that the app didn't request a permission for "Always" accessing location. It was only for "When active". Unfortunately when I manually change it to "Always" the problem remains.

**Comment by bryceco** [comment]
It sounds a lot like you don't have the "Collect in background" switch turned on. 
When the app is in the background do you see iOS Location indicator in upper left corner of the screen?

**Comment by euf** [comment]
My bad, I completely missed the "Collect in background" switch. Now it works correctly. Sorry for that
