### ISSUE TITLE
[3.8.4] Save Button not working after use of direction tool

### ISSUE THREAD

**Issue by Icebird2000** [bryceco/GoMap#663]
If you use the direction Tool:
![IMG_1858](https://user-images.githubusercontent.com/1193280/233722570-076c7bfe-ac20-4c29-ba30-70df0bdbd46d.jpeg)
and save the new value could not saved directly. If i change other fields it is possible. 
![IMG_1859](https://user-images.githubusercontent.com/1193280/233722679-8ade4e53-866e-457c-9b45-0b6be341fbf1.jpeg)

By the way: is it possible to make a picture in the background of the direction tool which indicate the correct usage. 

It will shows differently values in portrait or landscape mode. 

Portrait screen:
![IMG_1857](https://user-images.githubusercontent.com/1193280/233723776-88d2de16-0e49-4cf2-8a3a-dacc19fe213c.png)
now i turn the phone to left by 90 degrees:
![IMG_1856](https://user-images.githubusercontent.com/1193280/233723903-99a93a45-1ff7-4b6b-ae9f-ac375aa26527.png)

or isn’t it easyer to use a direction arrow on the map to set the value?

**Comment by bryceco** [comment]
> It will shows differently values in portrait or landscape mode.
The phrasing is somewhat ambiguous, it should probably say something more like "the top of your phone"

> or isn’t it easier to use a direction arrow on the map to set the value?

That's not a bad idea, except: 1) sometime's you don't know which direction you're facing, such as when hiking in woods, and 2) it's possible to turn off screen rotation in Display settings.
