### ISSUE TITLE
Quests - sort building types

### ISSUE THREAD

**Issue by arkhandir** [bryceco/GoMap#664]
Thank you for implenting Quests in the latest version. In my localisation (German), the building types are not ordered according to any recognisable characteristic, which makes it very time-consuming to pick out a specific type. A sorting option and/or a small favourites icon that can be used to pin frequently used menu items at the top would be good.

**Comment by bryceco** [comment]
This bug also appears in the regular non-quest Building Type field, and by extension probably a bunch of other fields where the values are pre-sorted for English. I'm kinda disappointed that nobody has reported this before now, so thank you!
