### ISSUE TITLE
Broken login causes hang when uploading GPX

### ISSUE THREAD

**Issue by vectro** [bryceco/GoMap#668]
Go Map!! hangs for me when I try to upload a GPX track to OSM.

Observed on:
* iPhone SE (Gen 1) with Go Map!! 3.4.8 (3408) and iOs 15.7.5
* iPhone 14 with Go Map!! 3.4.8 (3408) and iOs 16.4.1

What I observe:
* OpenStreetMap Login is displayed as `<unknown>`
* Trying to upload a GPX track causes the app to hang.
* The situation can be resolved by signing in to an OpenStreetMap account.

I don't know how I got into this state, but I did recently upgrade from the SE to the 14.

**Comment by bryceco** [comment]
I tried to reproduce this and didn't see the same behavior. What I did:
* Went to openstreetmap.org and revoked authorization to Go Map!! in my Settings.
* In Go Map!! under Settings my username shows as <uknown>
* Tried to upload a GPX.
* Result was a pop-up saying error 401, could't authorize.

**Comment by jwmh** [comment]
I added a comment/question to this closed issue here:
https://github.com/bryceco/GoMap/issues/76#issuecomment-1627116002
