### ISSUE TITLE
Indonesia address format

### ISSUE THREAD

**Issue by TagaSanPedroAko** [bryceco/GoMap#669]
Please add address format for Indonesia, which is as follows:

unit no., building name, street, house number, neighborhood, subdistrict, district, 
city, province, postal code

example address (in Indonesian):

Jalan Surya [No.] 10, RT.05/RW.02, 
Cempaka Putih, Cempaka Baru
Jakarta Pusat 10640

equivalent tags
- unit number (addr:unit)
- building name (addr:housename)
- street (addr:street)
- house number (addr:housenumber)
- neighborhood (addr:neighbourhood)
- subdistrict (addr:subdistrict)
- district (addr:district)
- city (addr:city)
- province (addr:province)
- postal code (addr:postcode)

neighborhood in this case can either be _rukun tetangga/rukun warga_ (RT/RW: community unit/neighborhood unit, the subdivisions of _kelurahan_), hamlets (_dusun_), housing complex, private commercial developments or industrial parks, and tagged as addr:neighbourhood. subdistrict can refer to _kelurahan_ in urban areas or villages (_desa_) in rural areas, and tagged as addr:subdistrict. district will refer to _kecamatan_, and tagged as addr:district. city will refer to both cities (_kota_) and regencies (_kabupaten_). province is not generally used in Indonesian addresses, but added here in cases where they are used.

Indonesia currently supports only default:

![IMG_1474](https://github.com/bryceco/GoMap/assets/27714833/7988632d-0a85-4ef7-8a45-04b5a6d9d9ad)

**Comment by tordans** [comment]
@TagaSanPedroAko did you check if the answer to this issue is the same as in https://github.com/bryceco/GoMap/issues/666#issuecomment-1536925357? Meaning, the change needs to happen in https://github.com/openstreetmap/iD/issues, where you already opened other issues.

**Comment by TagaSanPedroAko** [comment]
Ah ok, transferring this to iD.
