### ISSUE TITLE
Toggle Buttons don't work for translated values

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#672]
The key "Außenbestuhlung" (outdoor seating) shows the values "Nein" (No) and "Ja" (Yes) for the toggle button and does not recognize the "yes" as the selected value.

![IMG_7365](https://github.com/bryceco/GoMap/assets/111561/0793f951-9c9c-443e-8a03-163ca6b44dd1)

**Comment by Icebird2000** [comment]
This is fixed in commit https://github.com/bryceco/GoMap/commit/0d1c5a9d20f60ad857809c3cacae474ab9dc225a
