### ISSUE TITLE
Changes to `check_date` are not saved in Tags view

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#677]
Changing the `check_date` inn the 'Node Tags' sheet with the plus button and not changing anything else does not activate 'Save' on top right.
It's only activated when switching to the 'Common Tags' or 'Attributes' sheet.

https://github.com/bryceco/GoMap/assets/1651235/0d0e8966-2fed-4150-9359-719f69a280c9

**Comment by bryceco** [comment]
Just tested with the yet-to-be-released beta and it's working correctly there, so you'll see the fix in the next beta release.
