### ISSUE TITLE
provide 1. “Sign Out” option / 2. “Switch Accounts” option

### ISSUE THREAD

**Issue by jwmh** [bryceco/GoMap#679]
Update / bug:
[Showing the currently-signed-in-user] displays in the main Settings;
however it doesn’t additionally display in the Login sub-menu (after tapping the actual login)].

i’d like to see:
1. “Currently logged in as [username]”
2.  “Sign Out” 
3. or “Switch Accounts”.

— and if tapping either Sign Out or Switch Accounts,
provide:
“NOTE:  This will/will not (???) de-authorize this application on this device from signing in in the future— You will/won’t (???) need to re-authorize it again.
{If it doesnt de-authorize from OSM then give a statement saying the user will need to go to the OSM page to deauthorize it; offer to do so w option to decline or not.}

_Originally via
https://github.com/bryceco/GoMap/issues/59#issuecomment-1627119598_

**Comment by jwmh** [comment]
P.S.
Sorry— this turned into a longer issue than I anticipated .

**Comment by bryceco** [comment]
Fixed in 0b022c70f854f9f67d1d6fe4e161cc7809af2a18. Thanks Patrick!
