### ISSUE TITLE
Texts and icons are so blur on iOS device

### ISSUE THREAD

**Issue by nonPointer** [bryceco/GoMap#681]
![IMG_1388](https://github.com/bryceco/GoMap/assets/10243554/07384329-f798-4b15-a94c-be61a20d8955)

**Comment by patricks** [comment]
Hello @nonPointer,

there is still a green loading indicator visible on your screen. This normally means, that the app is still loading data from the internet. So in your case it could be that the correct background tile isn't fully loaded yet. Did the green loading indicator go away after a few seconds?

**Comment by nonPointer** [comment]
> Hello @nonPointer,
> 
> there is still a green loading indicator visible on your screen. This normally means, that the app is still loading data from the internet. So in your case it could be that the correct background tile isn't fully loaded yet. Did the green loading indicator go away after a few seconds?

Hi Patricks,

The loading indicator disappears after a few seconds, but the labels still seem blurry, like bitmap instead of vectorgraph (font).

**Comment by patricks** [comment]
The background layer (which you are seeing) is just a bitmap tile layer and it looks like you are zoomed in very deep.

You can change the background layer by tapping the map icon, but afaik the only vector based layer is the one where you can also change the data.

**Comment by nonPointer** [comment]
Thanks for your explanation!

**Comment by bryceco** [comment]
This is an interesting topic. As @patricks says these are bitmap tiles. At a given non-integer zoom level (like z=16.5) there's a choice of showing lower-zoom tiles that will have larger text that is blurry, or higher-zoom tiles that is crisp but with smaller text.  When displaying aerial imagery we prefer displaying higher-zoom imagery. But with the Mapnik tiles we prefer the lower-zoom tiles to prevent text from being too small to easily read, at the cost of them being fuzzy.
