### ISSUE TITLE
attributes show wrong date

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#684]
It seams the attributes are maybe showing the date of the former version, see this screenshot, version 2 is correct but the date is from version 1

![08C26ED2-B9AB-42AF-BD19-F69658630C5E](https://github.com/bryceco/GoMap/assets/581288/e135f854-b2e0-4c06-9a84-c6aad81bd4cd)

https://www.openstreetmap.org/node/11202843519/history

**Comment by bryceco** [comment]
Was this an object you created, and then updated to version 2?

**Comment by dieterdreist** [comment]
yes, I created it and updated it some hours later. Then I closed the app,
reopened and checked and noticed the date was wrong.

**Comment by bryceco** [comment]
Finally got around to looking into this. When you upload an object the server returns the new version number, and a new identifier if it changed. It doesn't return any metadata like the timestamp. We could query the server for the timestamp but I don't think it's worth the effort. Instead I'm going to update the timestamp to the current time, which should be accurate within a few seconds but will not exactly match what the server reports.
