### ISSUE TITLE
Possible to use with umap?

### ISSUE THREAD

**Issue by emanuil-tolev** [bryceco/GoMap#687]
Heya! Sorry for the usage question in the issue tracker, I couldn't find a more appropriate place to ask!

I need a native app to edit custom OSM maps. http://umap.openstreetmap.fr/en/about/ supports creating such maps. I can see an API server setting under the advanced app settings, but not really a setting to load a specific map. Is GoMap designed only with editing the default/main OSM map on a given OSM instance? Or might there be a way to get it to edit a map I've created in umap.

**Comment by bryceco** [comment]
We support OSM server instances that implement https://wiki.openstreetmap.org/wiki/API_v0.6 (such as OpenHistoricalMap). 

uMap is in a different category, it's not using that API.

**Comment by emanuil-tolev** [comment]
Damn, thanks. I guess I should host an OSM instance and point GoMap at it so I and my volunteers can ensure our changes are totally separate, that'll make a custom map. It's mapping street animals so it's not appropriate to suggest or make those edits to the default OSM map of the city.
