### ISSUE TITLE
Editor occasionally zooms out fully and switches to Bing imagery

### ISSUE THREAD

**Issue by fizwidget** [bryceco/GoMap#688]
Occasionally when I open GoMap!!, it’ll zoom out to show the whole planet and will switch to the default Bing imagery. Here’s a screenshot of what I see when this happens:

![IMG_1572](https://github.com/bryceco/GoMap/assets/1172012/deccc583-4c14-4041-84dd-2e3afe87b3db)

I think an error message briefly flashes on the screen too, but I don’t remember what it says. 

This isn’t a showstopping bug, just a mild annoyance 🙂. All I need to do when it happens is hit the “zoom to me” button and manually switch back to my preferred imagery. Figured it might still be worth reporting though. 

Thanks for the awesome editor!

**Comment by bryceco** [comment]
I suspect that when this happens you're using a local imagery source, so when it zooms out the imagery source is no longer valid and it switches to the default Bing imagery automatically. 

But the zoom-out behavior is definitely a bug!

**Comment by bryceco** [comment]
Need the zoom-out behavior to be reproducible to address it.
