### ISSUE TITLE
Draw lower side of retaining walls

### ISSUE THREAD

**Issue by Robot8A** [bryceco/GoMap#689]
According to https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dretaining_wall there is an upper and lower side of a retaining wall.
When mapping on the field, it is very useful to see visually which side is the correct one for an accurate mapping.

**Comment by bryceco** [comment]
barrier=retain_wall now gets the same treatment as natural=cliff, meaning you'll see direction arrows on it and can follow the "right-side is lower" rule when mapping.
