### ISSUE TITLE
Apple Watch companion app?

### ISSUE THREAD

**Issue by upintheairsheep** [bryceco/GoMap#690]
Can you create a small Apple Watch GoMap companion app? Some people prefer the watch to quickly survey an area, but a Go Map!! companion app wouldn't be as the iOS and macOS versions due to complexity of programming it, but a GoMap Watch app should have these things:

- It's existence
- The ability to display the map
- The ability to show the current location
- The ability to add a normal point to the map, and designate it as something, say for instance a restroom.
- The ability to edit the tags you usually would on an iPhone, it might be a list that you can edit, or it might be a wizard of sorts
- The ability to upload GPX tracks that are from the watch's recent locations API to OSM.
- The ability to work offline, without a phone currently online (ex: a hiking trip where one does not bring their phone with them due to problematic social media use or work stress)
- The ability to sync search history with the iPhone, if it is nearby.
- Due to being an iOS distro, the most of the rest of GoMap functionality may be easy to implement

I currently own an Apple watch and can say for certain that surveying may be easier with the brighter and smaller screen of the watch. I'm not blindly issuing this just because it could exist, in that case I'd suggest an Apple TV version with it.

**Comment by bryceco** [comment]
I admire your enthusiasm and confidence that such an app is feasible and useful on Apple Watch (which I own as well), but I think the payoff is not worth the effort that would be required.
