### ISSUE TITLE
Collect GPX data from Apple Health Workouts.

### ISSUE THREAD

**Issue by upintheairsheep** [bryceco/GoMap#691]
Add the ability to upload GPX data from Apple Workouts. Many people unknowingly map out trails while doing a Workout, and others knowingly do it. The only way to do it now is via exporting all data which could take a long time or be large, extract it, and upload it, and delete it for every workout. 

See https://developer.apple.com/documentation/healthkit/workouts_and_activity_rings/reading_route_data

Google Fit is a good example of an app that reads this data.

**Comment by harrija0** [comment]
I second this request. I was just lamenting that I didn’t record my trail run last night and trying to figure out if I could import the route to Go Map!!

**Comment by upintheairsheep** [comment]
https://apps.apple.com/us/app/gpx-workouts/id6463001431 works if you don’t
want to export everything but only works for the last few weeks while
exporting gets everything out

**Comment by bryceco** [comment]
Can someone tell me how to view these routes without downloading a 3rd party app?

**Comment by harrija0** [comment]
Not sure on that. I use HealthFit on my apple device to export my tracks and then put them into JOSM if I want to map them. Would be nice to import and view gpx tracks in Go Map!!  
https://apps.apple.com/us/app/healthfit/id1202650514 
but these are just apps that facilitate exporting of the apple gps tracks in a .fit (Garmin) or .fox format.

**Comment by bryceco** [comment]
Added in 41d1654

**Comment by tordans** [comment]
> Added in [41d1654](https://github.com/bryceco/GoMap/commit/41d1654c3d24806b6dd7f913c581386c98c581e5)

@bryceco just a nudge that this sounds like a nice feature to communicate in a release blog post later on.

**Comment by upintheairsheep** [comment]
Paid.
