### ISSUE TITLE
Presets for points

### ISSUE THREAD

**Issue by upintheairsheep** [bryceco/GoMap#692]
Hello, as a micro-mapper, I would like to create presets for points that show up in the amenity list. Please add the ability to create presets for the amenity list. Example, since there is no option to map out a fire alarm, so you need to have a Siren set to electronic speaker, purpose is fire, and named _Fire Alarm_. Another use case is a flag pole waving the flag that is not supported in OSM, so you need to manually the flag type and type out the flag name, and say whether it's lit, it's material, and the height in meters.

**Comment by bryceco** [comment]
We use the presets provided by https://github.com/openstreetmap/id-tagging-schema

I encourage you to make requests like this in that repository. They are very happy to add features like this, and they'll also appear in iD.
