### ISSUE TITLE
Mail button broken when not using built in Mail app

### ISSUE THREAD

**Issue by andrewtwelch** [bryceco/GoMap#693]
I have the built in Mail app uninstalled due to using other Mail apps, however this breaks the ability for me to email myself my change files if there’s a conflict or I want to continue mapping in JOSM. Can the Mail button be changed to work with other Mail apps if possible, or a button be provided to just export the .osc file to another app?

**Comment by bryceco** [comment]
Have you seen other apps that are able to launch your preferred mail app? I don't know if it's possible. 

As a workaround you can select the Edit button, Select All and Copy the OSC to your mail app.

**Comment by bryceco** [comment]
I think changing the behavior to a general Share button is the best option.
