### ISSUE TITLE
Support indoor floor filtering

### ISSUE THREAD

**Issue by upintheairsheep** [bryceco/GoMap#700]
Add an option that should only show objects on a certain floor level when in an indoor place with multiple floors. A great example of a place that is like this is Wichita State University in Kansas. Having two floors in one building without this filter is extremely difficult to map or even view what’s going on.

**Comment by bryceco** [comment]
This is already supported:

Display > Enable Filters > Building Level

**Comment by upintheairsheep** [comment]
> This is already supported:
> 
> Display > Enable Filters > Building Level

There should be an optional UI that has the list of floors of the current space you are in and a list of the floors you can select, as basically all other OSM and non-OSM sites have this dealing with indoor, including editors.
