### ISSUE TITLE
Add group of non-aerial imagery to the background selection

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#701]
It looks like, right now GoMap filters ELI data with a category of "other", like [this ALKIS data](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/de/BerlinAlkis.geojson?short_path=b7406a2).

It would be very helpful for me to be able to access this kind of data in ELI in GoMap as well. The iD Editor does show this data (but also filters some less relevant layers, like the map style layers).

Current view: 
![4DAAE0A6-B3D4-4E44-9466-239CC44DD787_1_102_o](https://github.com/bryceco/GoMap/assets/111561/6da7bf1f-501b-4077-8fb2-6152dd97acca)

**Comment by bryceco** [comment]
Fixed! I added layers in the "other" category and added Rapid's blacklist to filter out undesirable imagery. If you need layers that aren't "other" let me know.
