### ISSUE TITLE
Add Strava heatmap layer

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#702]
This Chrome extension is the best for mapping trails in woods

https://github.com/cmoffroad/id-strava-heatmap-extension

Strava is an app people use to track hikes and bike rides they do and the data is aggregated and provided for OSM mapping use for free (because Strava uses OSM for its maps)

https://wiki.openstreetmap.org/wiki/Strava

It would be great if you added an option to log in with Strava and then have this as an overlay.

**Comment by bryceco** [comment]
Asking users to create an account on a non-OSM website seems too tangential to include in what aspires to be a simple app.

**Comment by verhovsky** [comment]
A Strava account is not necessary, it just gives you the heatmap with a lower resolution. You can try yourself by installing the extension and not logging in or going to https://www.strava.com/heatmap and not logging in.
