### ISSUE TITLE
Clearing OSM Data cache deletes unsubmitted changes to existing nodes

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#703]
To reproduce:

- Move around some existing nodes
- Press the map button
- Clear cache
- Clear OSM Data

The nodes will be back on their original places.

I wanted to clear the cache because due to intermittent internet is seems to have cached a bit of broken data where some nodes think they don't continue (they're marked with a square in a white circle, when I cleared the cache those circled squares went away) to check I'm not drawing in nodes that already exist and it ended up deleting a bunch of the changes I drew that I had to re-draw.

At a minimum the app should refuse to clear the OSM Data cache when there are unsubmitted changes. Better would be to detect this specific situation when clearing the cache would clear changes and refuse it in that specific situation. Another thing to fix is to be better at refreshing nodes when internet comes back.

**Comment by verhovsky** [comment]
I see now that there's a warning about this specific situation but I don't have time to read warnings. I guess I assumed it was a "you're about to clear the cache, are you sure?" warning.

**Comment by bryceco** [comment]
Often people clear the cache because of edit conflicts or some other data issue, in which case it's necessary to delete unsubmitted changes in order to fix the problem. Sorry you lost data, but there's no 100% safe solution.

**Comment by dieterdreist** [comment]
sent from a phone

> On 31 Dec 2023, at 06:46, Boris Verkhovskiy ***@***.***> wrote:
> 
> At a minimum the app should refuse to clear the OSM Data cache when there are unsubmitted changes.


no, please not, it is convenient to just clear the cache when something went wrong. A warning might be appropriate, but refusing not.
