### ISSUE TITLE
Add "continue" as a node type

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#706]
Not being able to draw out an entire road is pretty common. I had to google how to set a node as a "needs continuing" node. It would be better if "Continue" was a dedicated type which would just leave node type as-is and add a "fixme: continue" tag so I don't have to google.

I understand that it's not a node type but adding it to this menu still makes sense.

**Comment by bryceco** [comment]
This would need to be a preset, and presets are handled by a different project which we consume. You can make a request here: https://github.com/openstreetmap/id-tagging-schema

**Comment by verhovsky** [comment]
https://github.com/openstreetmap/id-tagging-schema/issues/558 is the upstream issue.

Could you please at least remove this tag when continuing a way? So if I select a node with `fixme=continue` and then press the + to add a node it should clear that label from the selected node before adding the new node.

You could even make it two separate things in the undo history, so if I wanted to keep the continue tag on the node, I could press undo once after pressing + and keep the new node and have the tag re-appear on the old node. But that could be confusing.
