### ISSUE TITLE
Don't capitalize path access values

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#707]
When I edit the `access` property of a path, in the UI the values are capitalized but when I select it it's not capitalized

![IMG_2835](https://github.com/bryceco/GoMap/assets/5687998/213492a8-47f0-4366-acc7-8c9f8c7ecc0a)
![IMG_2836](https://github.com/bryceco/GoMap/assets/5687998/518a225c-8d83-4e6f-ae66-72f01ad10d63)

This is confusing, and makes me wonder if I'm accidentally adding capitalized values to the data or if it matters, etc. It should just be lowercase.

**Comment by bryceco** [comment]
It's not just access values: lots of other things also get capitalized for presentation. Values are (usually) displayed in a user's preferred language, so users generally don't see the underlying value (e.g. "private", etc) but instead the equivalent term used in their language (e.g. "Privado"). As a user you just have to trust that the mapping is being done the correct way.
