### ISSUE TITLE
Add node type documentation button

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#708]
The iD editor lets you view documentation of different node types and press for even more documentation, for example what a "Foot Path" is. Go Map!! should as well.

![IMG_2837](https://github.com/bryceco/GoMap/assets/5687998/7b06cf7c-384f-4187-8eb2-9ad7a7a9f622)

**Comment by bryceco** [comment]
I don't disagree, but the question is where to put it, and how to display it. A button could be placed next to the item on the "Common Tags" screen after you've selected the type. Or there could be buttons next to all items on the "POI Type" screen.

The information itself could be displayed on a new screen, or as a popup.

**Comment by bryceco** [comment]
Not fixed exactly how you wanted, but should accomplish the same purpose. It shows the description when you're selecting the feature, instead of waiting until after you've selected it.
