### ISSUE TITLE
High number of changesets with no edits created

### ISSUE THREAD

**Issue by simonpoole** [bryceco/GoMap#71]
While doing the research for https://www.openstreetmap.org/user/SimonPoole/diary/23352 I noticed the GoMap produces a high number of changesets which are empty. Currently roughly 70 per month for users first edits (of a total which is around 170-180), this seems to be extraordinarily high.

Since I don't have an iOS device I can't test myself, assuming however that GoMap does not allow a changeset to be created if nothing has been changed, this would seem to either to be conflicts (seems unlikely given we are looking at first time users here), or app crashes.

Sorry that I can only give a heads up and not directly help.

**Comment by Luzandro** [comment]
I just noticed via OSMCha, that a user created a lot of empty changesets the last days using Go Map!! 5.2.0?

https://www.openstreetmap.org/changeset/173232338
https://www.openstreetmap.org/changeset/173232293
https://www.openstreetmap.org/changeset/173232233
https://www.openstreetmap.org/changeset/173232208
https://www.openstreetmap.org/changeset/173232179
https://www.openstreetmap.org/changeset/173232167
https://www.openstreetmap.org/changeset/173232152
https://www.openstreetmap.org/changeset/173231975
https://www.openstreetmap.org/changeset/173231942
https://www.openstreetmap.org/changeset/173231875
https://www.openstreetmap.org/changeset/173294412
https://www.openstreetmap.org/changeset/173294426
https://www.openstreetmap.org/changeset/173294444
https://www.openstreetmap.org/changeset/173294459
https://www.openstreetmap.org/changeset/173294499

**Comment by simonpoole** [comment]
@Luzandro did you point this out to the user in question? In any case I would suggest creating a new issue for this as it clearly doesn't have anything to do with what was the cause of the empty changesets 11 years ago.

**Comment by bryceco** [comment]
That user is pretty active, and it looks like the failures are mixed in with successful uploads, so it could just be connectivity issues where they are. 

If an upload fails and they retry later the app doesn't reuse the changeset ID, so the result is an empty changeset.
