### ISSUE TITLE
Double tap Way to add a Node

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#712]
The [iD editor](https://www.openstreetmap.org/edit) works this way. If you double click on a way somewhere it adds a Node there. On touch surfaces it requires a triple tap. I like this more than Go Map!!'s "+" button because I don't have to move my hand/thumb as much/as precisely and it's faster. I think Go Map!! should have both ways of adding a node.

You could make it

- just a double tap to add a node any time
- the way has to be selected first for a double tap to add a node (and by extension, if you triple tap a way that's not selected it would add a node)
- always a triple tap to add a node (that's how iD editor works)

I think the second option would probably be best.

I think the macOS app should work like iD too (just double click) instead of right-clicking and also on iOS with an Apple Pencil tap (#529 #534) it should just be a double tap because it's more precise than a finger. Most importantly this allows drawing a Way starting from another way instead of currently with Go Map!! you always have to draw a disconnected way and then remember to go back to the start and connect it.

**Comment by bryceco** [comment]
I'm loath to add a double-tap gesture that adds nodes. People already complain that it's too easy to accidentally modify things, and this seems like it would make that problem worse.

>  this allows drawing a Way starting from another way 

Can you explain what you mean here? There are only a few situations where you're not allowed to extend or add to an existing way.
