### ISSUE TITLE
Zooming on macOS app is too fast and jerk-y

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#713]
Away from the equator zoom (by pinching on the touchpad) is way too sensitive and it seems like it lags the application so it zooms a bit, and then continues to process zoom events after I've stopped zooming in. It's also not sensitive enough before it starts zooming, so I have to move my fingers quite a bit before it starts zooming and then it zooms a huge amount.

It makes the Mac app basically unusable for me. Does the logic take into account how far from the equator you are? Because it feels like the zoom physics might be a bit better (but still not great honestly) in San Francisco than in Canada, but I'm not sure.

It also flashes white where a tile is loaded within a few frames after a lot, instead of only removing the old tile when the new tile can be replaced on the next frame.

M1 Macbook Air with macOS 14.2.1, which has a 13.3-inch (2560 × 1600) display. Go Map!! version 3.1.2

**Comment by bryceco** [comment]
This got fixed a long time ago, but the fix never got pushed to the Mac App Store. But I released it today and should be available as soon as Version 3.5.5 shows up in your region (might be up to 24 hours).

If you still see Mac behavior you're not happy about please file a new bug. It's not perfect by any stretch but it's getting better.
