### ISSUE TITLE
Icon Thai restaurant is wrong

### ISSUE THREAD

**Issue by louwers** [bryceco/GoMap#715]
The icon for a Thai restaurant is a bowl with chopsticks, but the Thai don’t use chopsticks.

**Comment by bryceco** [comment]
I agree with you, but to fix it you'll need to file a bug over at https://github.com/openstreetmap/id-tagging-schema, since that is where icon associations are defined.

**Comment by louwers** [comment]
Thanks for the link!

**Comment by louwers** [comment]
I created an issue here: https://github.com/openstreetmap/id-tagging-schema/issues/1089
