### ISSUE TITLE
Foot Path Surface Quest

### ISSUE THREAD

**Issue by pqhf5kd** [bryceco/GoMap#716]
I'm getting Surface quests for foot paths that already have the surface tag set. Am I missing something?
![Image](https://github.com/bryceco/GoMap/assets/20027419/bfe37ffa-1512-46e7-b13b-a443e87ada0b)

**Comment by bryceco** [comment]
This follows the logic that StreetComplete uses for its sidewalk quest: "paved" and "unpaved" aren't very specific as a surface value, so we ignore them when deciding to present the quest. 

But it's a bug that we suggest those values as valid answers!
