### ISSUE TITLE
Where Are The Quests Defined?

### ISSUE THREAD

**Issue by pqhf5kd** [bryceco/GoMap#717]
I wanted to take a look at the how the quests are defined but I can't find them. 
I can see quests.json in peterneman's branch but nothing in master.

**Comment by bryceco** [comment]
Currently they're defined in code rather than a configuration file. The sidewalk quest is defined at https://github.com/bryceco/GoMap/blob/5fc56bead2cc8c74289faf76c96cdbc61bd492ff/src/iOS/Quests/QuestList.swift#L142
