### ISSUE TITLE
custom tiles: special characters in query string

### ISSUE THREAD

**Issue by bloerwald** [bryceco/GoMap#718]
My local government provides a WMS tile server, and their inputs are really picky. One of them includes `&FORMAT=xxx` where `xxx` has to be *exactly* `image%2Fpng%3B%20mode%3D8bit`.

iD can produce that as it copies verbatim.

GoMap escapes the `%` sign though, producing `image%252Fpng%253B%2520mode%253D8bit`. Funnily, it doesn't escape much else, so `image=png; mode=8bit` produces `image/png;%20mode=8bit`. It seems to be impossible to produce an input that's escaped correctly.

As I guess this isn't a common issue and the escaping is likely done with some library, easiest might be providing a "use verbatim" checkbox.

**Comment by bryceco** [comment]
Yes, we're percent-encoding the string before sending it to the server. Does it work if you enter the URL using "FORMAT=image/png; mode=8bit", which is the equivalent non-encoded string?

**Comment by bryceco** [comment]
Ah, sorry I missed that part of your post. Let me look into it a little further.

**Comment by bryceco** [comment]
It looks like the URLs we're getting from ELI are correctly percent-encoded already, with the exception of a couple that contain spaces, so the percent-encoding we're doing is redundant and can be removed.

**Comment by bloerwald** [comment]
Perfect, deleted code is the best code!

If I read the diff right both `image%2Fpng%3B%20mode%3D8bit` and `image%2Fpng%3B mode%3D8bit` should work now, with everything else being untouched, right?

**Comment by bryceco** [comment]
Yes, both of those should work, once a new beta goes out.
