### ISSUE TITLE
Backup and restore histories, login, and settings

### ISSUE THREAD

**Issue by upintheairsheep** [bryceco/GoMap#719]
Can you create an option to backup and restore the app’s data, exporting point, area, and line history, search history, logins, GPX traces, and settings into a file that can be restored? iTunes backups work, but iTunes backups have one key flaw: they back up everything, with no way to deselect certain items like the photos album. Third party software cannot solve this flaw either.

**Comment by bryceco** [comment]
This is a more general issue with backing up state and sharing it between devices. There was some work that began using the NSUbiquitousKeyValueStore API which should solve this problem. I'll try to work on that some more.

**Comment by bryceco** [comment]
The next 3.6.2 beta will include iCloud storage for some, but not all of these settings. In particular it won't include login info (on general principle) and it won't include GPX traces. The proper solution for GPX files is to move the storage for them to iCloud Drive or iCloud Documents.
