### ISSUE TITLE
Trimming ends of GPX tracks

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#721]
Leaving location recording on for a long time creates laggy areas on the map. To reproduce, turn on location tracking overnight. You will wake up to a large cloud of lines around your house. After that, whenever you pan the map past that area, Go Map!! will drop frames.

One way to solve this is a UI to trim GPX tracks. Under the map you would have a slider with two dots at each end, and as I move the sliders (dots) it would jump to show me the new last pink/red point on the map (and possibly color the points to be deleted in a dim, transparent pink) so I could move the slider around and see immediately which points I would be deleting. A way to split tracks would also be nice, that way I can upload just sections that make sense to upload.

Another way would be to set up home points where GPS tracks aren't recorded if I get within 30m or whatever. That would be preferable because then I could just record my location non-stop instead of having to enable it whenever I decide to start mapping.

**Comment by verhovsky** [comment]
Basically dupe of #714

**Comment by bryceco** [comment]
I forget the exact cutoff but I believe that GPX tracks restart every hour, or maybe every 3600 points. So you should never have a trace that is ridiculously long, meaning you could delete most of those tracks when you're asleep while keeping the waking tracks.
