### ISSUE TITLE
Stash changesets

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#725]
I want to work on multiple changesets in parallel and easily switch between them, sort of like branches/stashes in git.

For example when working on mapping some type of way in my area in a single changeset I would like to be able to contribute a minor fix to a road when visiting a far away place without having to submit my unfinished changeset or put a far away minor edit that won't match the changeset description in my large changeset when I finish it.

You don't need perfect conflict resolution. If I make conflicting changes to the same node in two different changesets you can blame any data loss on me, the user, if that makes implementing this easier.

**Comment by bryceco** [comment]
This isn't going to happen - It's too complicated and too confusing. 

What might eventually be implemented is a mechanism to split changesets into multiple pieces, probably geographically, and allow uploading those pieces as separate changesets. This should accomplish the same goal for you.

**Comment by verhovsky** [comment]
Doing it properly is complicated, but a first pass would be to "just" turn the undo history into a tree instead of a linear data structure. When I stash you rewind the history of my edits and save that history with a label. When I want to look at a stash you rewind my current changes then replay the the stashed history. Having just two history branches to flip between would be fine as well.
