### ISSUE TITLE
Search does not work anymore

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#729]
I was using the search in the latest beta right now and it looks like it does not work anymore.
I don't get any visible error message.

Clicking the pre-suggested (or recently used?) items in the list does not work either. New searches are not added to this list either.

Screencast: https://share.icloud.com/photos/0dbzTP6PhrdomgxRlRjnhNXkw

**Comment by bryceco** [comment]
Nice catch! 
Fixed in 93a8337f62e993c57116715a9bd710d488f55500

**Comment by bryceco** [comment]
Fixed in 93a8337f62e993c57116715a9bd710d488f55500
