### ISSUE TITLE
`surface=dirt`

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#732]
To reproduce:

With Go Map!! 3.5.5, create a line and set it as "Surface: dirt"

What I expect: a line with `surface=dirt` is created.

Actual: a line with `tracktype=dirt` is created, which is incorrect and not how `tracktype` is supposed to be used. Seems like the presets need to be updated?

**Comment by tordans** [comment]
I cannot reproduce. Can you share screenshots of the steps please.

**Comment by verhovsky** [comment]
Sorry, I just mis-tapped.
