### ISSUE TITLE
Update user location bubble icon

### ISSUE THREAD

**Issue by patricks** [bryceco/GoMap#739]
The current user location bubble (BlueBall asset) looks a little bit outdated (imho). 

![IMG_8982](https://github.com/bryceco/GoMap/assets/132167/29603611-dd33-4feb-91f9-4783bd5285ef)

I have looked at other apps that use such an indicator, maybe they can be an inspiration:

![IMG_8983](https://github.com/bryceco/GoMap/assets/132167/25573c8c-c6ee-436a-b627-6dcde682e322)
![IMG_8984](https://github.com/bryceco/GoMap/assets/132167/8bef54c6-6119-4886-b48a-0c4f4c09634d)

**Comment by bryceco** [comment]
This is one of those things I'm so accustomed to looking at that I never consider changing it 😂. Updating this would be a nice addition to the work that @verhovsky is doing on feature styling. 

Note that we currently indicate the accuracy of the GPS with the radius of the circle, and the accuracy of the compass with the width of the cone. It would be nice to retain those properties.

**Comment by bryceco** [comment]
Here's the Apple Maps style:

![image](https://github.com/bryceco/GoMap/assets/279734/9329f494-7320-408b-aa6e-a8e92b01bfb0)

**Comment by bryceco** [comment]
Here's what I've got so far. I'm open to suggestions for improvements.
![IMG_1741](https://github.com/bryceco/GoMap/assets/279734/fad3858f-a8ba-4ef4-a30f-3faeee47aa3e)

**Comment by verhovsky** [comment]
looks nice.

on google maps and apple maps the little blue circle inside the white circle expands and contracts. I'm guessing it's doing the same thing as the big circle in your implementation just more subtly or it's just hinting that there's an active GPS connection.

**Comment by tordans** [comment]
> I'm open to suggestions for improvements.

Minor styling suggestions:
- Make the white border a bit smaller, more like the relation of the dot<>circle in the apple and (green) "other apps" screenshot
- Make the "view direction" gradient wider, more like apple screenshot
- Move the gradient center a bit more to the circle, more like the apple screenshot
- Maybe the blue outer circle should be a tiny bit thinner?
- Two other examples use a shadow to make the circle "fly" over the map, can that be added?

**Comment by bryceco** [comment]
I noticed the pulsing that appears on Apple Maps. I don't see a reason to replicate it.

**Comment by bryceco** [comment]
> * Make the white border a bit smaller, more like the relation of the dot<>circle in the apple and (green) "other apps" screenshot

Done

> * Make the "view direction" gradient wider, more like apple screenshot

The gradient is computed by the accuracy value that the compass API returns, so it's providing useful information. However I was thinking of putting a minimum width on it.

> * Move the gradient center a bit more to the circle, more like the apple screenshot

I don't understand what you mean. Note that the gradient is already kind of hard to see against a dark background so I intentionally decreased the amount of fade that it has compared to Apple's.

> * Maybe the blue outer circle should be a tiny bit thinner?

It looks thick in the screenshot, but when it's in motion it's harder to see and you don't see the thickness.

> * Two other examples use a shadow to make the circle "fly" over the map, can that be added?

That's a good idea.

**Comment by verhovsky** [comment]
![Simulator Screenshot - iPhone 15 Plus - 2024-04-14 at 21 52 11 2](https://github.com/bryceco/GoMap/assets/5687998/ba23427c-d75e-4a8b-a440-c4fae3d9593c)

**Comment by dieterdreist** [comment]
I am not sure how the bigger circle is calculated (static or dynamic
radius), but on Garmin the circle radius is indicating the precision of the
position and it is really useful and intuitive.

**Comment by bryceco** [comment]
Fixed in 8e0f0db2ce4b61bab09576f82b1d284ea533d4f5 and 6f36485ec118ea6f77a21b59a7fb0feac9202faa
