### ISSUE TITLE
option for overpass api link and download method

### ISSUE THREAD

**Issue by JustSomeGitHubAccount** [bryceco/GoMap#744]
I’m requesting that an option be added to the app (would make the most sense if it was in the advanced options tab) for a url for the overpass server, and for different methods of downloading, similar to what JOSM has. I ask this because it would be nice to be able to edit the maps of other programs using the OSM api (for example OpenHistoricalMap or OpenGeofiction) on mobile. Currently, it is not possible to download data from either of the aforementioned apps. Attached is a screenshot of what it looks like when you zoom in and try to download data from OpenGeofiction.
![IMG_4965](https://github.com/bryceco/GoMap/assets/65677497/e857b7cc-5194-401e-a2d2-0adc6ff7580a)

**Comment by bryceco** [comment]
Supporting Overpass would not allow you to upload your changes, so it's not a useful feature in general. 

You can edit OHM using the server URL:
https://www.openhistoricalmap.org/

You can edit OGF using the server URL:
https://opengeofiction.net/ 

The /api path component is added by us so you don't need to include it as you do in JOSM.

**Comment by JustSomeGitHubAccount** [comment]
how do you download the data from OGF on go map then? that is what i was requesting since i couldnt find a way to do that in the app

**Comment by bryceco** [comment]
Under Settings (gear in lower left) > Advanced Settings you can enter the URL I gave for the OSM Server.

**Comment by JustSomeGitHubAccount** [comment]
it must have been a problem on my end, i was able to get the app to download data off of OGF. although, i encountered another issue. An OpenStreetMap login is required to upload the changeset, but there are two issues with this. The most obvious is that, i’m not uploding to OSM, i am instead uploading to OGF. the second issue, which is not as obvious, is that when you login to the osm account on go map, it sends you to the oauth2 page to confirm that gomap can edit for you. the issue here is that i believe OGF doesnt use oauth2, and there is no confirmation page like with openstreetmap. also, should i open a separate issue on this page for that or just continue using this thread?

**Comment by bryceco** [comment]
I need to look into this more. I forgot that I need to register Go Map!! on OGF in order for it to use OAuth. But if OGF is using an older software stack then it may be necessary to open an issue there.

**Comment by bryceco** [comment]
31fc788f5ec9f152d50a062d7a15b172b929bce1 adds full support for selecting OGF and OHM servers, and I've verified they work with our OAuth implementation.
