### ISSUE TITLE
Name of object should become transparent when hovering over it

### ISSUE THREAD

**Issue by ooosssay** [bryceco/GoMap#747]
The name of an object should become somewhat transparent when the users pointer is hovering over it. When it’s transparent it should become visible when the user interacts with it or the pointer moves away from it.
![IMG_6395](https://github.com/bryceco/GoMap/assets/129241633/ed5eef44-2a49-43a6-9ea3-932d49f6bdf9)

The reason why I am suggesting this is because sometimes when I’m mapping, for example, a building, the node name covers the corner of the building making it hard for me to determine where to add a node. While I could simply just zoom in, you need to consider things where objects are really small where you can’t zoom into the map to see where you’re placing the node. Thanks.

**Comment by bryceco** [comment]
You want it to become transparent when it is covering the crosshairs in the center, correct?

**Comment by ooosssay** [comment]
Yes

**Comment by bryceco** [comment]
Nice suggestion!
