### ISSUE TITLE
v3.8.0 Aerial imagery alignment feedback - longer descriptions can cause alignment buttons to be obscured

### ISSUE THREAD

**Issue by leighghunt** [bryceco/GoMap#749]
Great work getting #32 sorted - I just tried the Beta and noticed that for some aerial imagery sources where the description may be longer than others, this can cause the alignment control to be partially obscured by the locate control.

Can be mitigated by turning to Landscape mode.

Level of obscuring can vary depending on alignment, but default of (0,0) ends up with worse case.
![IMG_8874](https://github.com/bryceco/GoMap/assets/349153/a2e5542b-9c2f-4aad-ab69-49fa2daedb1d)

![IMG_8875](https://github.com/bryceco/GoMap/assets/349153/cf57175e-c6fe-4f1f-a680-4671233c9489)

Aerial imagery source I used: LINZ NZ Aerial Imagery.
Description on screen: Sourced from LINZ CC-BY 4.0

Also happens with OpenAerialMap, Stamen Terrain.

**Comment by bryceco** [comment]
Thanks for reporting! I'd verified the (0,0) button wouldn't overlap but forgot to check the D-pad. 

There's also the question of whether the D-pad should be above or below the control for moving nodes. I'd like to hear opinions.

**Comment by leighghunt** [comment]
> There's also the question of whether the D-pad should be above or below the control for moving nodes. I'd like to hear opinions.

How about left justifying the D-pad, and placing the attribution text to the right - that way if it's truncated, it doesn't affect placement of controls?

Or maybe place the (0, 0) immediately to the right of the information button? Would mean no issues left justifying the D-pad and it not being centered with the (0, 0)?

Given image realignment is sort of a semi-modal operation, that control should probably be at the top of the z-order when it's visible?

**Comment by bryceco** [comment]
I want the (0,0) next to the imagery attribution since it applies to that specific imagery (it resets to (0,0) if you change imagery), and I want the (0,0) button tied to the D-pad visually so it's intuitive they work together. I'm just going to move the (0,0) button and the D-pad a bit to the left, which will solve the issue. 

> Given image realignment is sort of a semi-modal operation, that control should probably be at the top of the z-order when it's visible?

That's a good point, but leads me to the opposite conclusion: If you leave the D-pad open and then edit a node then the node handle should be above the D-pad (since its more transient than the D-pad).

**Comment by tordans** [comment]
@bryceco I was looking at the initial testflight that introduced this feature and hope, there is a way to make this feature less visible.

In the version I saw, it was visible always but I think the screen real estate on the main map is really valuable and should not be cluttered by something that is only used sometimes.

My thinking is, that this is a feature that is related to the imagery source, which has it's own settings UI. Can we move this adjustment somewhere there? 

Maybe by adding a "adjust this imagery" flag to a layer which then shows the UI?

Or maybe hide it behind a long press on the imagery source text? And hint at this in the imagery settings screen?

**Comment by bryceco** [comment]
If you tap the (0,0) button again the D-pad disappears. Is that sufficient?

**Comment by tordans** [comment]
My thinking is this: This is a feature that some but not a lot / all people have asked for. So making it something that all people see seems not ideal.

I suggest making it an optional thing for those people who need it…
OR, to make it something that one has to look for, not something that is there always.

**Idea A**

Add a toggle to the map layer and maybe use that place to also show the settings n/w/s/e offset.

<img width="372" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/0ccb2e51-6c18-4a39-8fb0-53bc2e44951f">


**Idea B**

Use the long press on the arial imagery to show the additional control. Hint hat this feature from the UI from Idea A in text form.

<img width="212" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/8bcfe06b-63e7-49bd-a768-6e9db1907495"> <img width="164" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/68786246-ffdc-4d42-9e4c-2e80d3192690">

Screenshot: It looks like there is some long press state for this text already, but I think it does nothing? (Second Image has white text while pressing.)

**Idea C**

If this UI element absolutely must be there, lets align it with the UI more, so it is less visually noisy.

- Move the icon to the left aligned with the `(i)` icon, same UI look
- Make the icon a settings Icon or something, not show the numbers
- Move the text next to the icon, aligned vertically centered to the icon
- Give the icon a different icon color or something to indicate that is was "used" / is active.

<img width="406" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/e651e198-a9d5-4937-96b8-bf9ac12f60f7">

**Idea D**

Given Idea C kind of creates a place to open a UI that relates to the layer … which we already have when long pressing the map icon.
Can we move the setting over there?

- Add an option "Adjust current image position" at the bottom of the list
- When pressed, the panel closes and the current adjust-UI shows with some "DONE" button next to it.
- When "DONE", the same panel shows "Adjust current image position (2,4,-2,-3)"

<img width="381" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/e35468f7-e5e9-4ce7-8b68-db236c0fb582">

**Comment by bryceco** [comment]
I agree that the button is too obvious in your screenshots. I gave the button a 60% alpha to reduce that, but it doesn't have the correct effect in Dark Mode:

![image](https://github.com/bryceco/GoMap/assets/279734/4e9b7b7f-cd8e-4cbc-afbd-c486903d28af)
