### ISSUE TITLE
How to handle Error 409?

### ISSUE THREAD

**Issue by Megachip** [bryceco/GoMap#750]
Is there any way to update a way manually?

**Comment by bryceco** [comment]
On the upload screen there are buttons to Edit/Mail/Export (depending on your version) the .osc file which you can edit manually and upload.

**Comment by Megachip** [comment]
> On the upload screen there are buttons to Edit/Mail/Export (depending on your version) the .osc file which you can edit manually and upload. 

So no option to update the way or everything visible on screen? 

Atm, if there wasnt too much work, I just clear the cache

**Comment by bryceco** [comment]
The code does some automatic conflict resolution on its own, but if that fails your only option is to undo, clear the cache, or manually edit the .osc
