### ISSUE TITLE
Map should stay visible in quests

### ISSUE THREAD

**Issue by Discostu36** [bryceco/GoMap#755]
At the moment, when selecting a quest, the quest dialogue covers the whole screen. When doing quests about ways, e.g. streets, this makes it hard to know which part of the way the quest is about without manually dragging the dialogue out of the way. The feature should be altered so that, like in StreetComplete, the screen is split and the map is still visible.

**Comment by bryceco** [comment]
We can easily support dragging the modal sheet halfway down and having it stick there. I'd rather not make it the default behavior though.

**Comment by bryceco** [comment]
You'll now be able to drag the quest sheet halfway down, and the selected object will center itself in the upper half of the screen.
