### ISSUE TITLE
Region subtag for zh-Hant

### ISSUE THREAD

**Issue by yellowsoar** [bryceco/GoMap#756]
# Requests
Divide language `zh-Hant` into `zh-Hant-TW` and `zh-Hant-HK`

# Reason
We have a new `Chinese (Traditional)` contributor @hugoalh joined on weblate. And @hugoalh seems not from Taiwan, but from Hong Kong perhaps? I guess the glossary of geospatial and OpenStreetMap in Taiwan might be different from Hong Kong. So, before we start fighting on the wording stuff and to make Go Map!! better, I think it's time to do so.

**Comment by yellowsoar** [comment]
cc @Supaplextw @bdon

**Comment by bryceco** [comment]
I don't see a zh-Hant-TW option in Weblate, but there is a "Chinese (Traditional, Hong Kong) (zh_Hant_HK)" entry. Is should be sufficient to create it and copy the zh-Hant over, correct?

**Comment by bryceco** [comment]
Fixed in Weblate.

**Comment by yellowsoar** [comment]
> I don't see a zh-Hant-TW option in Weblate, but there is a "Chinese (Traditional, Hong Kong) (zh_Hant_HK)" entry. Is should be sufficient to create it and copy the zh-Hant over, correct?

Seems so. [zh-Hant represents zh-Hant-TW in Weblate.](https://github.com/WeblateOrg/weblate/blob/6889ee3cf95526cfaeefb069270d28e684240490/weblate/formats/base.py#L40-L45)
But will that work in iOS app? Anyway let's wait for the next release as usual. XD

**Comment by bryceco** [comment]
Some of the translations by @hugoalh broke things in the build (placeholder names like `@meters@` were translated instead of being left as-is). I fixed them on my end, and then tried to fix them in Weblate as well but I'm worried I might have messed things up a bit. Basically the strings referencing meters/nodes with plurals support. You should probably review those strings for zh-Hant. I didn't touch the ones in zh-Hant-HK. Apologies!

**Comment by hugoalh** [comment]
I did sure I haven't translated anything related to `@xxxx@`... 😶

Viewed the history, it is translated by @yellowsoar.

![Screenshot_20240516-124247.png](https://github.com/bryceco/GoMap/assets/32359235/1c9d9b6e-16a1-42b9-8f7d-d1fa92ecb027)

**Comment by bryceco** [comment]
> Viewed the history, it is translated by @yellowsoar.

Oh, okay! Thanks for clarifying and apologies for the misattribution. I didn't look carefully, but I'd seen a notification that you'd edited zh-Hant-HK and the issue appeared there as well so I figured it was yours.

**Comment by bryceco** [comment]
I now realize that I copied the bad translation into HK myself when I duplicated everything in zh-Hant into HK 😅

**Comment by yellowsoar** [comment]
@bryceco @hugoalh So sorry, that's my bad. 🙇‍♂️ TBH I haven't done the translation for a long time. XDDDDD Didn't notice that we now support singular/plural forms. I think the unchanged warning from Weblate drives me to do that. But, I checked both `zh-Hant` and `zh-Hant-HK`, it's now ready to go. Let's keep it up!
