### ISSUE TITLE
highway/track color is often hard to see

### ISSUE THREAD

**Issue by pLoskutov** [bryceco/GoMap#757]
I haven't used GoMap for the last month, but today I installed 3.9.0 in the test and saw the new color of the highway/track road. Beige color on top of beige dirt roads!? How to use it?

**Comment by bryceco** [comment]
Thanks for the report. We're trying to more closely follow the color scheme used by iD. I agree that particular style needs to be fixed.

**Comment by pLoskutov** [comment]
> follow the color scheme used by iD.

Thank you. In general, there is a great lack of personal style settings so that each editor can customize the style he is familiar with. 

There is also no difference between residential - servise highway
The difference between tertiary and secondary is slightly noticeable

**Comment by bryceco** [comment]
> There is also no difference between residential - service highway
Residential is wider, just as in iD

> The difference between tertiary and secondary is slightly noticeable.
Different colors.

I hope that these issues are just a matter of adjusting to the new color scheme, and after a while differentiating them will be second nature. If that doesn't happen, please let me know.

**Comment by bryceco** [comment]
https://github.com/bryceco/GoMap/commit/1bff720572c55fbdefe030ca0a5eb0e511a9c4c3 makes the dashed lines bordering tracks much wider, so hopefully that makes them sufficiently easy to see.
