### ISSUE TITLE
Two notes enhancements

### ISSUE THREAD

**Issue by ooosssay** [bryceco/GoMap#761]
When commenting on a note the note screen closes but when you close a note the screen stays open. Shouldn’t this be switched? 

Also I’d love to be able to tap on a persons name to view their profile while in the note screen.

**Comment by bryceco** [comment]
> When commenting on a note the note screen closes but when you close a note the screen stays open. 

We close the window in both casees, unless it encounters an error uploading the note.

> Also I’d love to be able to tap on a persons name to view their profile while in the note screen.

Good idea!

**Comment by bryceco** [comment]
Second request fixed in 1638bf74ef888b94531c75122ce02b0b31d257c4
