### ISSUE TITLE
Lock screen UI has weird edge cases

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#762]
I was not able to pin this down exactly, but wanted to share it now so others can help find the issue (if there is any).

I was experimenting with the lock screen UI and I thing there are edge cases where the UIs don't match

One case is…
1. start recording traces
2. lock phone > lock screen
3. unlock > close app with task manager which stops the recording
4. lock phone > still there is a UI showing a recording, but the buttons don't work (some they open the app, but none handle the tracing anymore); the numbers on the lock screen UI don't change anymore, I think

There might be other edge cases that are similar …

**Comment by bryceco** [comment]
I'll try to fix these edge cases as best I can. The commit I just did will remove any widgets when the app terminates.

**Comment by bryceco** [comment]
Since there aren't any other cases being reported I'm closing this.
