### ISSUE TITLE
Invalid Token for U.S. Forest Roads Overlay / Adding name over errors 

### ISSUE THREAD

**Issue by ooosssay** [bryceco/GoMap#763]
Currently the U.S. Forest Roads Overlay gives an error when turned on

Additionally since Data Overlays are going to be implemented id suggest adding the overlay name over the error so if the user has a lot of data overlays and the user receives an error on one of them they will know which one to fix

**Comment by bryceco** [comment]
This is an issue with https://github.com/osmlab/editor-layer-index where we pull the data, and which I've been low-key working to help fix. 

Good idea about adding the imagery source to the error message, though!

**Comment by ooosssay** [comment]
Closing since the token is a separate matter that isn’t related to the app and the warning suggestion has been implemented.
