### ISSUE TITLE
What is the definition of `vertex`

### ISSUE THREAD

**Issue by bickelmeister** [bryceco/GoMap#765]
Recently I scrolled a bit through the QuestBuilder and I wondering about the` vertex: boolean`. 
Is this like the "Relation" or is it about a waypoint in a line?

Thanks for helping out.

**Comment by bryceco** [comment]
Correct, a vertex is a node in a way. This follows the iD terminology.

**Comment by bickelmeister** [comment]
Ok thanks :)
