### ISSUE TITLE
JSON Import for custom Quests

### ISSUE THREAD

**Issue by bickelmeister** [bryceco/GoMap#767]
**Current situation** 
If I want to add custom quests by using a JSON string, I need to paste the well formatted JSON string into a small text input. 

**Enhancement**
May add a possibility to import a JSON file. 

**Why I think it is a good idea**
I made a repository, which contains some quests I implemented for me. My script afterwards creates a big JSON file. 
This file I then upload manually into my iCloud and download it on the iPhone. Then I need to open the file and copy the content of the file to import it. But it will be more usable, if I could just import the JSON file into the app.

The repo I am talking about: https://github.com/bickelmeister/GoMapQuestTemplates

**Comment by bryceco** [comment]
If you are using a Mac then you can use [Continuity](https://support.apple.com/guide/mac-help/aside/glose229df1e/14.0/mac/14.0) to directly copy the text on your Mac and paste it into Go Map!!, right?

**Comment by bickelmeister** [comment]
That it possible, you are right.
