### ISSUE TITLE
Use Mirror Server to download data faster

### ISSUE THREAD

**Issue by TheFive** [bryceco/GoMap#77]
JOSM uses Mirror Server do load the data faster. I knew two sources of server, (both based on Overpass API) to support this.

a) French API Server
The French Community offers a mirror Server for Download 
api.openstreetmap.fr/api
For download it is compatible to the *.org download, and for upload it just reroutes the calls to the *.org server.
This information comes from this presentation on SOTM EU:
https://www.sotm-eu.org/en/slots/51

b) Mirror Download Overpass
There is a plugin in JOSM, that supports mirror download
http://wiki.openstreetmap.org/wiki/JOSM/Plugins/mirrored_download

The API call server are listed here:
http://josm.openstreetmap.de/wiki/MirroredDownloadInfo

**Comment by bryceco** [comment]
I don't see the benefits of doing this being worth the added complexity.
