### ISSUE TITLE
Darking “Add Note” button when  “Notes and Fixmes” is off 

### ISSUE THREAD

**Issue by ooosssay** [bryceco/GoMap#770]
For first timers, they might want to add a note on the map but when they do that it can disappear due to the “Notes and Fixmes” being off, they might think someone already completed it or a bug so I’m suggesting to darken and make the “Add note” unpressable unless the “Notes and Fixmes” overlay is on. 
Also possibly add a little alert saying “Enable the Notes and Fixmes Overlay” (preferably above the button) and not a big, middle of the screen notice.

**Comment by bryceco** [comment]
Great suggestion!

**Comment by bryceco** [comment]
We now automatically enable Notes & Fixmes option when user adds a note.
