### ISSUE TITLE
Filter Objects Being Downloaded/Cached

### ISSUE THREAD

**Issue by Alex-Vasile** [bryceco/GoMap#774]
If I only wish to work on certain objects (e.g. adding opening hours to stores) I filter everything out to make it easier to see. However the other objects are still being downloaded and cached. Would it be possible to limit the downloading and/or caching to only the objects that meet the enabled filter?

**Comment by bryceco** [comment]
That really complicates things. If you only download POI nodes (for example) but those objects are connected to ways without your knowledge it’s easy to break things. 

There are various apps that are more targeted and might be a better fit for specialized mapping. Check out EveryDoor, MapComplete etc.
