### ISSUE TITLE
Style: border missing after node

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#776]
This way has a border due to the surface but it stops at the gate note but the way is not split. 

https://www.openstreetmap.org/way/796860364

![image](https://github.com/bryceco/GoMap/assets/111561/d83b0670-f007-45e4-9a47-32716b0a38cd)

![image](https://github.com/bryceco/GoMap/assets/111561/a875faa4-572d-474e-99d0-7375c6ca29f0)

**Comment by bryceco** [comment]
The border is on both sides of the gate, but it is hard to see with the background color (zoom in on your screenshot). Switch to Bing imagery and the contrast is better.

**Comment by tordans** [comment]
Oh, you are right. When I move the gate the line "disappears" somewhere else, so the background image and line seem to be a perfect match…
