### ISSUE TITLE
App bricht zusammen

### ISSUE THREAD

**Issue by Feedback1000** [bryceco/GoMap#779]
Hallo.

Seit einigen Versionen kann ich Go Map ++ nicht mehr nutzen: sobald ich die auf meinem IPhone 11 Pro versuche zu öffnen, stürzt die App ab.
 
 Was kann ich tun?
 
 Mit Grüßen
Fabian

**Comment by tordans** [comment]
_Translation:_

> Hello.
> 
> I haven't been able to use Go Map ++ for a few versions: as soon as I try to open it on my iPhone 11 Pro, the app crashes.
> 
> What can I do?
> 
> Best regards,
> Fabian

**Comment by tordans** [comment]
@Feedback1000 did you try to remove the app and reinstall?

Hast du versucht die App einmal zu löschen und neu zu installieren?
