### ISSUE TITLE
request to open source this

### ISSUE THREAD

**Issue by jmarca** [bryceco/GoMap#78]
Hi,

Please do not be offended by this, but I would like to respectfully suggest that you release the code under an open source license.  I just browsed your issues, and it seems some things have been languishing (specifically, creating tracks, and importing tracks).

Your readme says this is not a commercial endeavor, so if you open the source code people may start contributing patches.

Feel free to close if this has already been hashed out.  And again, I don't mean to rub the wrong way, I just want to help out too.

**Comment by hallahan** [comment]
Yes, why isn't this open? OpenStreetMap's philosophy highly encourages open source code. I'd love to learn from you app, it is brilliant!

**Comment by patricks** [comment]
+1

**Comment by davidak** [comment]
i also would like to see this published as free software but the developer said here https://github.com/bryceco/GoMap/issues/53

>Go Map!! is currently closed source because it is a personal preference of mine.

i hope it remains free and respect his choice. maybe he feels comfortable in the future to do it.

**Comment by socketpair** [comment]
+1

**Comment by wtimme** [comment]
I just came across this app and noticed that on the App Store some users were asking for translations. I came here happy to contribute some of my spare time to this project just to find out that I am not able to go right ahead with it. Other users have already raised this issue a couple of months ago (#103).

Why are you not open sourcing this app, @bryceco?

**Comment by socketpair** [comment]
Some time ago, I tested beta-version (with object rotation!) but after that, @bryceco disappeared...

**Comment by tordans** [comment]
@bryceco any update on this? Any plans to OpenSource the app?

**Comment by tordans** [comment]
@bryceco did you just OpenSource the app? That is awesome! <3

**Comment by hallahan** [comment]
Wohoo!!!!!

**Comment by bryceco** [comment]
Fixed :)
