### ISSUE TITLE
App translation unclear

### ISSUE THREAD

**Issue by Icebird2000** [bryceco/GoMap#780]
While looking for the last error, I noticed that the labeling was a bit unclear. 

![image](https://github.com/bryceco/GoMap/assets/1193280/bef86fd7-0968-4207-a650-38e051f76595)

Localizable.xcstrings///Language selection affects only Presets and only for those presets that are translated for iD. The main interface is still English.

This mentioned that the main interface is still english, but this is not true. The main interface is the selected language under the Systemsettings. 

I think we should change the text a little bit to make it clear. 
„Language selection affects only Presets and only for those presets that are translated for iD. The main interface language is the one selected under IOS Settings -> Go Maps!!“

**Comment by bryceco** [comment]
Agreed. That text is left over from long ago, when we supported non-English presets but hadn’t translated the rest of the app.
