### ISSUE TITLE
App crash on [m|ft]

### ISSUE THREAD

**Issue by Icebird2000** [bryceco/GoMap#782]
On a highway=track use the editor and add a width=56,6
![image](https://github.com/bryceco/GoMap/assets/1193280/e03eed7e-8509-42c8-b814-f109aa76ad6f)
Press done
![image](https://github.com/bryceco/GoMap/assets/1193280/09188874-dc78-40df-997f-935a1df367ae)
No extension is now selected
Detect your error select the width field and remove the 6 and the , and write . and 6
Press done -> App Crash

By the way - Is it possible to automatically change a comma to a dot in such fields?

You can also take the width=16'3" from the wiki and remove '3" and press done -> App crash

**Comment by bryceco** [comment]
Thanks for the report!
