### ISSUE TITLE
Add "Translate this" to "fixme" tags

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#790]
I am at the SOTM EU in Poland at the moment and notice `fixme` notes that look like this…
> <img width="394" alt="image" src="https://github.com/user-attachments/assets/7621c32a-d9e7-46b6-a5cc-0ff25c80d3bf">

… which I cannot read.
I wonder, if there is an easy way to add on demand / optional inline translations to GoMap.
Something like a small button next to the `(i)` that will show the translated text below the input field.

It looks like there is an API in iOS for this https://developer.apple.com/documentation/translation/translating-text-within-your-app

---

Which tags would be relevant here? Maybe all tags that use the `textarea` field type?

**Comment by bryceco** [comment]
You can currently highlight the text and select Translate from list of options, right?

**Comment by tordans** [comment]
> You can currently highlight the text and select Translate from the list of built-in options, right?

You are right. I have to click the `>` twice but then there is this translation option:
> <img width="393" alt="image" src="https://github.com/user-attachments/assets/c4423f22-395b-422e-8ebe-7bc88321c5d4">
> <img width="415" alt="image" src="https://github.com/user-attachments/assets/64e2639f-70a6-4225-94ba-f5f2aea73b55">
