### ISSUE TITLE
Ability to redirect to the wiki with keys that has a namespace

### ISSUE THREAD

**Issue by ooosssay** [bryceco/GoMap#792]
When pressing the i button in the tags page, rather than just have no redirect when the key has a namespace it should show a list of keys that the user is able to search for. 
Now from what I understand that this implementation would be difficult as something as simple as `a:b` would create a big list of
* `a`
* `a:`
* `:b`
* `b`

And this does not include tags that are like `parking:both:orientation` 
So I fully understand if you decide to not implement this.

**Comment by bryceco** [comment]
I feel like this is something that should be addressed server-side by the wiki search code, not something clients should have to deal with.
