### ISSUE TITLE
Swiping down on Upload view resets changeset comment

### ISSUE THREAD

**Issue by nicolas17** [bryceco/GoMap#800]
If I tap Upload, and then swipe all the way down on the upload screen, this screen gets dismissed just like if I tap Cancel; this is standard iOS behavior. If instead I swipe down only partially, the upload screen bounces back up into place and it doesn't get dismissed. However, in either case, the changeset comment **gets reset to the previous value**, losing the text I may have already typed.

https://github.com/user-attachments/assets/41317bb8-8a4e-4c7c-b685-a97f32caf375

I wrote a changeset comment that made sense for my change, I accidentally swiped down slightly when trying to scroll the list of changes, it reset my comment to the one I used in the previous upload, and I tapped the Commit button before realizing what had happened. This made my changeset have the same comment as my previous upload from last week, which is completely unrelated to the change I made today.

**Comment by bryceco** [comment]
Thanks for the report!

**Comment by nicolas17** [comment]
Thanks, that was fast! FOSS wins again :smile:
