### ISSUE TITLE
Quests still appearing even after saving

### ISSUE THREAD

**Issue by ooosssay** [bryceco/GoMap#801]
After filling out a quest the emoji of the quest still appears on objects.

https://github.com/user-attachments/assets/8b9da3e4-2d2c-41f9-99fe-013d9b1ae680

**Comment by bryceco** [comment]
Can you post the quest definition?

**Comment by ooosssay** [comment]
My bad I realized that I should have excluded the tag that has values. I was using Advanced Quest Builder. 🙃
