### ISSUE TITLE
Modifying an object with a Fixme icon triggers display of quests, even when quests are disabled

### ISSUE THREAD

**Issue by jmapb** [bryceco/GoMap#806]
- iPhone SE (2nd generation)
- iOS 17.5.1 (21F90)
- GoMap!! 4.3.0

Steps to reproduce:

1. Toggle off **Quests** overlay (but leave individual quests toggled on)
2. Toggle on **Notes and Fixmes** overlay
3. Locate and select an object with a Fixme icon
4. Make any change that leaves the `fixme`-tagged object in a state that would trigger a quest, eg:
- Add a business tag like `shop=convenience` or `amenity=fast_food` (common when changing eg `constuction:amenity=fast_food` to `amenity=fast_food`) and leave off phone, website, or opening_hours https://github.com/user-attachments/assets/aa36d98c-0933-4da6-adb7-4c5f7259d7d4 ([node 2573047736](https://www.openstreetmap.org/node/2573047736))
- Rename a business that lacks phone, website, or opening hours https://github.com/user-attachments/assets/6dc98b64-ac95-42bb-aea3-744afa485725 ([node 7902998065](https://www.openstreetmap.org/node/7902998065))
- Remove the `fixme` (or `fixme:atp`) tag from a business that lacks phone, website, or opening hours https://github.com/user-attachments/assets/61d54fbd-1dbb-4b8a-96dd-5d26f1ce4ae7 ([node 4157284291](https://www.openstreetmap.org/node/4157284291))
- Remove the `phone`, `website`, or `opening_hours` tag from a business https://github.com/user-attachments/assets/f78261f3-aaba-41a5-ba73-4432b2e68317 ([node 5506774614](https://www.openstreetmap.org/node/5506774614))
- Remove `surface` from a highway https://github.com/user-attachments/assets/9702dbdb-f317-4e28-9537-1296e286fa0e ([way 1230660127](https://www.openstreetmap.org/way/1230660127))
- Paste address tags onto a building tagged `building=yes` (does not require opening the tag editor) https://github.com/user-attachments/assets/64f95c99-0c1f-4f7a-b8a8-4db9d602c379 ([way 248238792](https://www.openstreetmap.org/way/248238792))

One noteworthy quirk is that this behavior happens even if the blue **"F"** Fixme icon is not _currently_ showing. The `fixme` tag can be removed or the **Notes and Fixmes** overlay can be toggled off, and the unwelcome quest mode can still be triggered -- as long as the object in question had a Fixme icon earlier in the editing session.

**Comment by bryceco** [comment]
This behavior isn't actually related to FixMe's. Any edit to the object would cause it to rerun the Quest evaluation code on the object, ignoring that quests were disabled globally. Thanks for the report!
