### ISSUE TITLE
Add option for changing the OSM Server API URL

### ISSUE THREAD

**Issue by homme** [bryceco/GoMap#81]
The settings menu in the app allows users to enter their login credentials but does not allow them to connect to an OSM server other than the default.  It would be very useful to add an advance setting which allows the user to specify the server they want the app to connect to.  

This is needed for a variety of reasons such as testing as well as adding domain specific data that should not reside on the central server.

The Vespucci app on Android provides this functionality but obviously this is not available for iOS.

**Comment by bryceco** [comment]
Added.
