### ISSUE TITLE
Use RoomPlan to generate indoor maps

### ISSUE THREAD

**Issue by upintheairsheep** [bryceco/GoMap#811]
Hello, can you add the ability to generate floor plans (without having to contact the architects or building owners or deal with any legal issues) with RoomPlan API?

**Comment by bryceco** [comment]
That would be pretty cool. I think the output should be a GeoJSON file, not something where it would directly create nodes and ways, but it could be used as a background image that you trace over in iD or JOSM. It's not something that would fit well into a workflow for Go Map!!, but it would be a nice standalone app.

**Comment by upintheairsheep** [comment]
> That would be pretty cool. I think the output should be a GeoJSON file, not something where it would directly create nodes and ways, but it could be used as a background image that you trace over in iD or JOSM. It's not something that would fit well into a workflow for Go Map!!, but it would be a nice standalone app.

For the case of size-reduction, yes it would be better I believe if it's standalone, but it would still be amazing due to architectural copyright being iffy, everyone recommends LiDAR. See https://totheroot.io/article/create-a-2-d-floor-plan-with-room-plan-and-sprite-kit-part-ii

**Comment by upintheairsheep** [comment]
> That would be pretty cool. I think the output should be a GeoJSON file, not something where it would directly create nodes and ways, but it could be used as a background image that you trace over in iD or JOSM. It's not something that would fit well into a workflow for Go Map!!, but it would be a nice standalone app.

Any update? This feature seems extremely promising

**Comment by bryceco** [comment]
There are several iOS apps that let you scan rooms and export the result. For those that don't export to PNG you can screenshot the result and then trace it. It would be great to hear how well that works as a sanity check that such an app is useful.

**Comment by upintheairsheep** [comment]
well... go map does not support importing plans in order to trace them, see
#699.

**Comment by bryceco** [comment]
But other editors do?

**Comment by upintheairsheep** [comment]
No mobile editor. Tried JOSM and I much prefer mobile/touch for that rather
than mouse.

**Comment by bryceco** [comment]
That's fine, but I want to know whether the room scans are accurate enough to be usable. If the professional scanners that have been developed for a couple years don't do a good enough job then there is no reason to invest effort into making a new one with the same limitations.
