### ISSUE TITLE
Icons aren’t being rendered in Americana

### ISSUE THREAD

**Issue by ooosssay** [bryceco/GoMap#820]
Road signs and poi icons aren’t being shown on the Americana basemap

**Comment by 1ec5** [comment]
On the Web, OSM Americana uses an NPM library to draw route shields and some POI icons. osm-americana/openstreetmap-americana#1164 tracks porting this library to Swift and Core Graphics so that Go Map!! can use it.

**Comment by bryceco** [comment]
As @1ec5 says this is out of our control.
