### ISSUE TITLE
Dark-mode App icon for iOS18

### ISSUE THREAD

**Issue by Axlmln** [bryceco/GoMap#823]
Hello,

Thanks a lot for your app ! I’m using it everyday and it’s really powerful !

Are you planning on making a dark-mode icon for iOS18 ? If you want, I can design some icons to gain you some time, but I don’t know the needed format for the image file.

Thanks again for yout work !

**Comment by bryceco** [comment]
@Binnette made the current icon and you can see the process [in this issue](https://github.com/bryceco/GoMap/issues/236). 

A dark mode version of it would be great!

**Comment by Binnette** [comment]
Here are some attempts on my side:

Original : ![AppIcon](https://github.com/user-attachments/assets/28ac3a75-6f8b-459b-94ef-22d45fbf07e0)

|v1.1|v1.2|v1.3|v1.4|v1.5|v1.6|
|-|-|-|-|-|-|
|![AppIconDark1](https://github.com/user-attachments/assets/10a24286-7f21-4d52-990e-fc13dd3ffb72)|![AppIconDark2](https://github.com/user-attachments/assets/8d8a9a8a-7fc1-4c0a-a796-d599649f30c6)|![AppIconDark3](https://github.com/user-attachments/assets/975f30d8-5354-4263-b721-15bdb9512b21)|![AppIconDark4](https://github.com/user-attachments/assets/56a5275b-c186-4b52-ae22-b9b18ec7c6ca)|![AppIconDark5](https://github.com/user-attachments/assets/bd26da23-f342-43f1-8c6b-b51ab75bb942)|![AppIconDark6](https://github.com/user-attachments/assets/c1939bf7-b74f-46f2-b97f-61a9b4a1701f)|

**Comment by Axlmln** [comment]
Hi @Binnette!

Thank you very much for your work! I think version 1.3 is the best. It follows the black gradient of the other applications' icons, and I don't think it's necessary to tint it a little darker like on 1.4 because many applications still have white or very saturated colours.

Do you think it might be interesting to lighten the blue of the icon background for light mode to differenciate a bit more the two icons?

 Thanks again !

**Comment by bryceco** [comment]
I'm going to pull v1.3 unless there's any other feedback soon. I'd prefer not to change the existing light-mode icon.

**Comment by Binnette** [comment]
Hello @bryceco, here is SVG of logo v1.3 😊
[AppIconDark.svg.txt](https://github.com/user-attachments/files/17738964/AppIconDark.svg.txt)

As previous time, just remove ".txt" to get the SVG file

**Comment by bryceco** [comment]
Cool, thanks!
