### ISSUE TITLE
User can lose pending changeset comments when moving Upload sheet

### ISSUE THREAD

**Issue by nender** [bryceco/GoMap#827]
When swiping down slightly on the "Upload" dialog sheet, the description reverts to the previous value. This can cause users to lose pending changeset comments.

I suspect this is due to `viewWillAppear`/`disappear` firing even though the view controller isn't really leaving the view.

Reproduced on iOS 16.1, Go Map 4.3.0.

Example screen recording

https://github.com/user-attachments/assets/3444551e-e823-4b7d-8a1d-95f35a7c6073

**Comment by nender** [comment]
I plan on submitting a PR to fix this, but wanted to get an issue filed first.

**Comment by nender** [comment]
Actually this looks like it's already been fixed via 9523332a8f2a! Eagerly awaiting it getting released.

**Comment by bryceco** [comment]
Thanks for the report! New version being released in a day or two.
