### ISSUE TITLE
Add iPhone6 iPhone6 Plus support

### ISSUE THREAD

**Issue by patricks** [bryceco/GoMap#83]
Please add support for the iPhone 6 and iPhone 6 Plus.

**Comment by bryceco** [comment]
Can you be more specific?

**Comment by patricks** [comment]
iPhone 6 und 6 Plus have a Zoom and Standard Mode. I think it would be ok, if you adjust your storyboards and rebuild the app.

**Comment by bryceco** [comment]
I've run it on 6/6+ and didn't see anything that looked incorrect, so if there is something you dislike you have to be specific.

**Comment by patricks** [comment]
Maybe you tried a rebuild, not the app store version?

I have attached 3 screenshots

This one shows the display settings of my iPhone 6S:
View: Standard setting is important one.
![thumb_img_0052_1024](https://cloud.githubusercontent.com/assets/132167/10436050/45ce24a0-7124-11e5-965b-7e129f566d86.jpg)

This one show the app store version of the go map app. Take a look at the statusbar (top).
Compare it with the next screenshot, you will see, that this one is bigger (zoomed)
![thumb_img_0050_1024](https://cloud.githubusercontent.com/assets/132167/10436086/79b5b044-7124-11e5-9fa9-7acd5880c455.jpg)
![thumb_img_0051_1024](https://cloud.githubusercontent.com/assets/132167/10436104/a2e3609c-7124-11e5-8117-92bc98a2d2ef.jpg)


This is the default behavior if the app doesn't support the iPhone 6/6 plus screen size.

**Comment by bryceco** [comment]
I'm pretty sure I would never noticed that if you hadn't pointed it out. Yes I believe the problem was fixed automatically in my beta builds when I added a Launch Storyboard.
If you are interested in trying the beta send me an email via the in-app feedback.
