### ISSUE TITLE
GPS does not always initialize correctly

### ISSUE THREAD

**Issue by RayOnTheFarm** [bryceco/GoMap#85]
Condition occurs when Wifi is off and Airplane mode is on, where Go Map is unable to access GPS hardware (displays an error message). The GPS still works, as I go to compass, get GPS to display, then back to Go Map, and then it works. This is somewhat random, on iOS 8.3, iPhone 5C.

**Comment by Skippern** [comment]
I think this is more a hardware/iOS condition than a bug. According to FCC and other similar authorities, GPS receivers are not to be used, so Aviation Mode on telefones **should** disable this function. If it randomly activates the GPS on iOS 8.3/iPhone5C than this is an issue in breach with FCC approval of the telefone and a future update should fix this (meaning no more GPS in aviation mode).

**Comment by RayOnTheFarm** [comment]
Now I have a bit more information. When using Compass, rarely it asks me to roll the ball around the circle. Occasionally it shows the compass, but the display of lat/long is delayed by 5-10-15 seconds, then it (magically) appears.

After using Go Map for several hours this morning, I now believe that what I am seeing is that the GPS hardware is taking longer to initialize than Go Map is waiting for data. This is likely because I have no AGPS (Airplane mode being on) and because there is no skyhook-style AP lookup/approximation (because wifi is off). So it's left with only the GPS receiver hardware. Depending on how long I've had it in sleep (screen off), some of the GPS data (ephemeris ?) may have gone stale and needs to be reloaded. I saw one instance where Go Map displayed the error message, I tapped it away, then tried GPS again, and it worked the second time. I think it may be a timing issue, where GPS (in my configuration) is taking longer to initialize. Of course in some situations (e.g. inside a building with a metal roof) real GPS may not be able to initialize. The error being displayed is not so much an error, as it's a "I'm not ready yet" message.

**Comment by RayOnTheFarm** [comment]
The error is "KCLErrorDomain error 0". I think what's happening, is the error will be returned until GPS has been able to calculate a First Fix. Sometimes this happens quickly, and sometimes I have to tap thru several iterations of the error msg. Probably related to how many satellites are in view, etc.

**Comment by bryceco** [comment]
There isn't any specific timing code in the app. If location manager returns an error then we give up, without retrying. Perhaps the compass app continues trying multiple times.
