### ISSUE TITLE
Cache Update

### ISSUE THREAD

**Issue by Mesgary** [bryceco/GoMap#86]
Sometimes you need to refresh and update a small part of the map from the server to have the most updated data. At this time, you can only clear the whole cache and reload the map again. in this situation you will lost all the offline data which was stored in your cache, while you wanted to update a small part of the map. I think there should be a button to reload the viewing area data, specially for the OSM data which is so useful for mappers.

**Comment by bryceco** [comment]
You need to refresh the area because you're working with other mappers who are changing things? Or some other reason?

**Comment by Mesgary** [comment]
Yes. When some part of map downloaded to my phone, all changes of the other mappers in that area will not be transferred to my phone.

**Comment by tohaklim** [comment]
Was looking through the issues list looking for this. 
Indeed, would it be possible to disable/control the aggressive caching behavior? Sometimes I can't see edits made some days ago in an area

**Comment by bryceco** [comment]
In the 1.6 release my goal is to remove most of the need to manually manage the cache. It will use a combination of:
* how long since the data was downloaded 
* how long since the data was viewed
* network connectivity (WiFi/cel/none)
There will also be an option to keep the manual behavior.

**Comment by dieterdreist** [comment]
sent from a phone

> On 8. May 2018, at 01:45, bryceco <notifications@github.com> wrote:
> 
> There will also be an option to keep the manual behavior.


great, especially in a mapping party setting you find yourself deleting the osm cache every few minutes.

**Comment by bryceco** [comment]
Reloading only parts of the data is pretty complicated, and I don't believe worth the effort.
