### ISSUE TITLE
Rendering Persian

### ISSUE THREAD

**Issue by Mesgary** [bryceco/GoMap#87]
When a road is not a direct line and has some breaks in it, the name of the road is splitted while showing the name of the road. For example if a road name is "Fayyazi" (which is a road name in Tehran, IRAN), for showing the name over the breaking part of the road, it is divided to two part "Fayy" and "azi" and they are shown near each other over the node which cause the break for road.
This doesn't work probably in Persian. For example there is another road near the last example named "بهاران". It should be divided in two part "ن" and "بهارا" and concat them in the order they show the original name. But because the Persian language is and RTL language and these two part was acted like English, they become together in wrong order and I see "ن‌بهارا" in the app in that situation.

**Comment by bryceco** [comment]
Can you post a screenshot and/or a link to the way in question?

**Comment by Mesgary** [comment]
You can check this issue in attached screenshot. The original name and correct name is "صفا" which is rendered correctly in one screenshot and incorrect in another screenshot as "فاص".
The link to this road is
http://www.openstreetmap.org/#map=18/35.79116/51.44738
![correct](https://cloud.githubusercontent.com/assets/15173479/10585510/70aa43c2-76a4-11e5-988c-7f2835831091.jpg)
![incorrect](https://cloud.githubusercontent.com/assets/15173479/10585521/7d370a44-76a4-11e5-8d81-3a6561649cf5.jpg)

**Comment by bryceco** [comment]
I believe what's happening is that the text segments are being split and ordered as they would if they were being rendered on separate lines. Do you agree?

**Comment by Mesgary** [comment]
*Sorry to reply late. It is hard to connect to GitHub via Iranian IP address!*
If I want to be more descriptive in term of programming for a string with the length of 10, you have:
###English (any Latin or LTR language) character string:
- you put the `left(str,4)` on *left* side line of the road and `right(str,6)` on the *right* side.
###Persian (any RTL language) character string:
- you should put the `right(str,4)` on the **left** side line of the road and `left(str,6)` on the **right** side.
because in any RTL language, the characters are written from the right to the left so the first characters (which can be find using `left(str,n)` function) should be rendered in the right side.

**Comment by bryceco** [comment]
I have an issue with correctly detecting when a name is RTL. I'm using the built-in iOS functions and they usually work, but for example for the string "خط ١" it doesn't mark it as RTL. Any ideas?

Also depending on where I break the work it sometimes will change the glyph for the first character. I'm breaking words where line-break suggestions are. "خط 2 مترو" becomes "ط 2 مترو" "خ". Is this acceptable?

**Comment by Mesgary** [comment]
For your first question, I have no idea.
For your second question:
It is not acceptable. It is will result the same as now. You should split the string only over the white spaces and then don't forget to reverse the places I have talked in #issuecomment-152243645 .

**Comment by bryceco** [comment]
Fixed.
