### ISSUE TITLE
Merging Ways Feature

### ISSUE THREAD

**Issue by Mesgary** [bryceco/GoMap#88]
I think you should add "Merge" two (or more) ways together to the features of the application. These days while I am mapping and improving the Tehran map, I find this feature a requirement for mapping. Now, I write the situation in my notes and then fix it on my PC. But I think it can be handled in my phone with your "Go Map!" application.

**Comment by bryceco** [comment]
There is a basic Join feature: select a node that is shared by two ways (must be an endpoint for both) and then select More...Join. Or do you mean something different?

**Comment by Mesgary** [comment]
I mean this, but I couldn't do this. Especially when the node is for 3 or more ways and you want to merge 2 of them, it doesn't allow me. Do u want me to take an screenshot of it also?

**Comment by bryceco** [comment]
If there are more than two ways involved then merging doesn't work (since there is no multiple selection feature it isn't possible to know which two to merge). There is a workaround by disconnecting the unwanted way, joining the remaining two, and then reconnecting the first.

**Comment by Mesgary** [comment]
Also another solution is that: in this situation ask for the second way after clicking "Join". Am I clear with my suggestion or I should provide more details?

**Comment by tordans** [comment]
Hi, is this the same as https://github.com/bryceco/GoMap/issues/320 and therefore could be closed?

**Comment by bryceco** [comment]
It's similar. Since you can copy/paste tags to ensure the two ways to join are identical means this is largely satisfied.
