### ISSUE TITLE
Adding a way

### ISSUE THREAD

**Issue by Mesgary** [bryceco/GoMap#89]
Adding a way feature is now only for the ways that are not connected to any other ways. I wanted to add a dead end alley in the map and I couldn't do this. Finally I did it with my PC.
name = کاج
name:en = Kaj Dead End
link the map = http://www.openstreetmap.org/#map=19/35.75714/51.40028

**Comment by bryceco** [comment]
You can simply drag the endpoint of the way to connect it to another way.

**Comment by Mesgary** [comment]
Sorry, u r right.

**Comment by Mesgary** [comment]
Sometimes we need to connect a node in the middle of a way to another node in the middle of other way (working on crossroads). It doesn't work. Of course we can split the ways, but it is not a appropriate resolution. Should I open another issue or continue it here in this issue?

**Comment by bryceco** [comment]
This has already been added in the beta version so it is coming.
