### ISSUE TITLE
Not loading iPhone5 + iOS9.1

### ISSUE THREAD

**Issue by Skippern** [bryceco/GoMap#90]
The app is not loading and terminates without error message on my iPhone5 running iOS9.1.

The app remains in background but no display visible. Currently have no access to other devices to check.

Are display/story board for iPhone5 still supported?

**Comment by bryceco** [comment]
Can you try deleting it and downloading again?

**Comment by Skippern** [comment]
That seemed to solve it, thanks

**Comment by nickel715** [comment]
Duplicate to #95?

**Comment by bryceco** [comment]
Hopefully everyone has moved on from iOS 9 by now...
