### ISSUE TITLE
Don't zoom for locating

### ISSUE THREAD

**Issue by Mesgary** [bryceco/GoMap#91]
When I am in a place of the map and click on the "Locate Me", it shows my location and also zoom the screen to a default specific level. I think the zooming part is not useful. I always prefer the map remains at the same zoom level that it was before locating me.

**Comment by bryceco** [comment]
I added the "Center" button in part to address this. If you are leaving GPS on then it will restore your position without changing the zoom level. Have you tried it?

**Comment by Mesgary** [comment]
Yes I saw it. It is so great. But in some cases when the GPS is not active and needs to be activated (as seen in screenshot), there is no "Center" button. And it is when the "Locate Me" button is useful and it will zoom to default level!

![photo_2015-11-12_21-50-05](https://cloud.githubusercontent.com/assets/15173479/11127068/6c10744e-8987-11e5-9772-565c75b089c3.jpg)
