### ISSUE TITLE
Can't add tags on iOS 9.3

### ISSUE THREAD

**Issue by Nerakade** [bryceco/GoMap#95]
I have found with the latest version of iOS, I am unable to add tags to nodes or ways.  I can select feature, open the tags window, add a tag, but when the Save button is pressed, the app crashes. 

Running iOS

**Comment by Nerakade** [comment]
Hit submit too soon,

I am running iOS 9.3 public beta 2(?) (13E5200d) on an iPhone 6S.

**Comment by bryceco** [comment]
I'd recommend deleting and reinstalling the app.

**Comment by Nerakade** [comment]
That fixed the issue. Good thinking. Thanks!

**Comment by nickel715** [comment]
I had the same issue, reinstall solved it for me too. But it takes a long time to figure it out and I didn't used the app in this time :(

**Comment by Nerakade** [comment]
It is a bit of a tricky fix. After I leaned about this and fixed GoMap, I was able to get another app or two working properly again. They were having similar problems where they crashed every time after a certain command. It seems like this bug/fix is not just limited to GoMap.

**Comment by bryceco** [comment]
Hopefully everyone has moved on from iOS 9 by now...
