### ISSUE TITLE
Display of errors during "service unavailable"

### ISSUE THREAD

**Issue by harry-wood** [bryceco/GoMap#97]
I took this screenshot on some occasion back in May, presumably when the OSM server was temporarily struggling.

![img_0653 copy](https://cloud.githubusercontent.com/assets/227525/16536578/61ce55e4-3feb-11e6-87fc-1c76be393083.PNG)

Whenever that's happening I guess ideally the app would display just "Service unavailable" or some other message without the HTML mess.

I guess it would be clumsy to try to parse this HTML error in the app. No doubt it's arguably better tackled at the server end, but I think it only happens if apache is throwing a major hissy fit (hopefully not too often anyway!)

**Comment by bryceco** [comment]
Fixed in 19f73681f46fff85d743359f0c21c3209acad761
