### ISSUE TITLE
Deeper Integration with osm.org (edit in GoMap!!)

### ISSUE THREAD

**Issue by TheFive** [bryceco/GoMap#98]
i just put a marker to an osm.org request, that will not be solvable without your support.
https://github.com/openstreetmap/openstreetmap-website/issues/985

**Comment by bryceco** [comment]
I already support the geo: URI allowing you to open Go Map from the share menu. 
However if you install another app later it can get overridden requiring a reinstall to override it back. (If I'm understanding you correctly).

Bryce

**Comment by Skippern** [comment]
I don't see why the issue remains open on OpenStreetMap since it only requires the external editor to handle the given URI correctly, and would therefor only be an issue for each App not handling this correctly. 

Now, if other apps can hi-jack this binding, maybe a configuration option to regain the binding?

**Comment by bryceco** [comment]
It is a deficiency of iOS that it loses then binding. There's nothing the app can do about it.

**Comment by TheFive** [comment]
I did not get it runnung.

What did i do ?

a) removed and installed GoMap on my ipad.
b) open www.openstreetmap.org
c) zoom to an editable size of map
d) called edit with external editor

that results in an error message that josm or merkartor could nor be found.

e) try to use the iOS Export freature out of safari, here i cant fond go map as a receipient, nor can i configure it.

**Comment by bryceco** [comment]
On the OSM site: 
a) click the Share button
b) click the Geo URI link. It should launch Go Map!!

**Comment by TheFive** [comment]
thanks, i have deinstalled maps.me (first) and reinstalled GoMap(second).  maps.me is reacting on the geo link, gomap not :-(.

I am using GoMap 1.4 (installed from appstore) and iOS 9.3.2.



But the referred issue is asking for a special edit support instead of try to call merkartor or josm with IPC based on TCP on Desktops.
This could be done by a special uri e.g. osmedit: which can not be overwrittern by other apps (I am pretty sure every mapper has more apps on his device reacting on a geo: url) and that can e.g. react on selected objects, so an osm id can be handled in such an uri definition.

**Comment by TheFive** [comment]
just the referring link where my question started. https://github.com/openstreetmap/openstreetmap-website/issues/985

**Comment by TheFive** [comment]
Just for information, on OSM Side now something is done. Simon has put information short together.
See:
https://github.com/openstreetmap/openstreetmap-website/pull/1478#issuecomment-284968861

**Comment by bryceco** [comment]
Associated domains are now supported via eb539ac5e61d2c03c72cac4d0b4c7247a940a289

To test you can click on this link:
https://gomaposm.com/edit?center=47.679056,-122.212559&zoom=21&view=aerial%2Beditor

**Comment by habi** [comment]
I'm resurfacing this issue, as I cannot get [the link]( 
https://gomaposm.com/edit?center=47.679056,-122.212559&zoom=21&view=aerial%2Beditor) to open Go Map!! on my iPhone 12 mini with iOS 15.2.

(The reason being the mentioned issue some days ago).

**Comment by bryceco** [comment]
Looks like an entitlement got lost during the conversion to Swift. This will be fixed in the next update. Thanks!

**Comment by bryceco** [comment]
Fixed in 333112152f6d524d09345b37ffb4a58f0136e4b6

**Comment by habi** [comment]
Awesome, thanks for the quick fix.
